### ISSUE TITLE
Import APO for split channel applies to both channels

### ISSUE THREAD

**Issue by justinriddiough** [wwmm/easyeffects#1003] opened 2021-07-08 12:12 UTC
I did a room calibration with REW and was delighted that the EQ presets could be imported into with "Apply APO Preset"  I did a calibration of my left and right speaker, each had a slightly different profile.

When I went to apply the preset, I turned on split channel, and selected left channel and applied the preset, and unfortunately it applied the preset to both left and right channels. I ended up importing into one channel, and manually configuring the other.

I wonder if there is something in the exported file I get from REW I can use to apply the settings, or on the other hand, if there is something in the formatting of the import document that can specify the channel to apply?

```
Filter Settings file

Room EQ V5.19
Dated: Jul 7, 2021 6:58:16 PM

Notes:left

Equaliser: Generic
Jul 7 18:48:15
Filter  1: ON  PK       Fc     209 Hz  Gain -33.9 dB  Q 3.943
Filter  2: ON  PK       Fc     196 Hz  Gain   9.0 dB  Q 2.141
Filter  3: ON  PK       Fc    77.5 Hz  Gain -15.7 dB  Q 7.064
Filter  4: ON  PK       Fc    71.6 Hz  Gain   5.4 dB  Q 3.599
Filter  5: ON  PK       Fc     203 Hz  Gain   8.8 dB  Q 2.213
Filter  6: ON  PK       Fc     201 Hz  Gain   9.0 dB  Q 4.912
Filter  7: ON  PK       Fc    1607 Hz  Gain  -6.5 dB  Q 1.864
Filter  8: ON  PK       Fc     115 Hz  Gain  -3.0 dB  Q 6.530
Filter  9: ON  PK       Fc     104 Hz  Gain   4.7 dB  Q 14.332
Filter 10: ON  PK       Fc     174 Hz  Gain -10.8 dB  Q 11.012
Filter 11: ON  PK       Fc     146 Hz  Gain  -7.2 dB  Q 11.851
Filter 12: ON  PK       Fc    2394 Hz  Gain  -3.8 dB  Q 5.000
Filter 13: ON  PK       Fc    3686 Hz  Gain  -2.4 dB  Q 4.965
Filter 14: ON  PK       Fc    2951 Hz  Gain  -3.2 dB  Q 4.998
Filter 15: ON  PK       Fc     268 Hz  Gain  -3.0 dB  Q 4.999
Filter 16: ON  PK       Fc    96.6 Hz  Gain  -3.7 dB  Q 15.092
Filter 17: ON  PK       Fc    4831 Hz  Gain  -2.8 dB  Q 3.652
Filter 18: ON  PK       Fc    42.8 Hz  Gain  -6.1 dB  Q 20.787
Filter 19: ON  PK       Fc     164 Hz  Gain  -5.5 dB  Q 39.662

``` 

```

Filter Settings file

Room EQ V5.19
Dated: Jul 7, 2021 7:01:32 PM

Notes:

Equaliser: Generic
Jul 7 18:49:27
Filter  1: ON  PK       Fc     343 Hz  Gain  -8.2 dB  Q 5.000
Filter  2: ON  PK       Fc    2150 Hz  Gain  -8.0 dB  Q 4.941
Filter  3: ON  PK       Fc    1266 Hz  Gain  -6.7 dB  Q 5.000
Filter  4: ON  PK       Fc     161 Hz  Gain -11.4 dB  Q 8.602
Filter  5: ON  PK       Fc    1524 Hz  Gain  -5.9 dB  Q 5.000
Filter  6: ON  PK       Fc    1014 Hz  Gain  -4.8 dB  Q 5.000
Filter  7: ON  PK       Fc    2874 Hz  Gain  -3.6 dB  Q 5.000
Filter  8: ON  PK       Fc    5606 Hz  Gain  -3.2 dB  Q 5.000
Filter  9: ON  PK       Fc     704 Hz  Gain  -4.1 dB  Q 5.000
Filter 10: ON  PK       Fc    8307 Hz  Gain  -3.3 dB  Q 5.000
Filter 11: ON  PK       Fc    42.8 Hz  Gain  -7.3 dB  Q 16.276
Filter 12: ON  PK       Fc     105 Hz  Gain  -6.6 dB  Q 17.932
Filter 13: ON  PK       Fc    65.3 Hz  Gain  -4.5 dB  Q 32.609

```

**Comment by wwmm** [comment] 2021-07-08 14:10
At this moment our "import APO preset" function is very limited. And the fact I have never used APO and that I do not use Windows to not help me in improving this situation. Our current import code only exists because someone else contributed to it. But I do not even understand the regex strings that were used in the code implementation. 

I have also never used REW but I wonder if it uses other kinds of preset formats that could be more friendly than APO to support.

**Comment by justinriddiough** [comment] 2021-07-08 14:43
Yeah, I don't know either what is different with the APO and REW, I didn't even expect that it would map the REW frequencies, but when it did it was a nice suprise. It parsed the REW file fine, so perhaps the formats are similar, or it is actually an REW importer rather than APO.

REW allows you to set up a calibration mic and do a sweep and it will provide an EQ file that you can get for a flat response. In windows, people would then import EQ into APO. 

Could be a nice enhancement some day. I think if it worked a bit more easily, many people would put up tutorials in youtube on how to do this (as there are years olds discussions across the web asking how to do it, and many tutorials for REW & APO for windows)  

Thanks for the response

**Comment by wwmm** [comment] 2021-07-08 14:54
>When I went to apply the preset, I turned on split channel, and selected left channel and applied the preset, and unfortunately it applied the preset to both left and right channels. I ended up importing into one channel, and manually configuring the other.

Maybe I can improve this without having to touch on the APO parsers itself.  I think I can check if the `split-channels` is enabled and if yes I can force the output to go only to the channel that is currently being viewed in the window. I will take a look at this.

**Comment by wwmm** [comment] 2021-07-08 14:56
If I understood correctly each channel profile is saved in a different file. Is that it?

**Comment by justinriddiough** [comment] 2021-07-09 09:28
Yes, that is correct. 

Channel selection: 
![Screenshot from 2021-07-09 04-11-18](https://user-images.githubusercontent.com/654993/125056011-6e35aa80-e06d-11eb-9c1d-372ace1dc2d6.png)

Then it does a frequency sweep which is recorded by the microphone. (photo shows results of 2 sweeps, left and right) 

![Screenshot from 2021-07-09 04-11-32](https://user-images.githubusercontent.com/654993/125056099-8279a780-e06d-11eb-862b-99cdf5a2c2ed.png)

The next step is the EQ, which provides the calibration based off the 'house curve', i.e. predefined desired curve. 'Match response to target'

![Screenshot from 2021-07-09 04-12-08](https://user-images.githubusercontent.com/654993/125056032-74c42200-e06d-11eb-944e-fe01ba54c735.png)

When the response is matched:

![Screenshot from 2021-07-09 04-26-38](https://user-images.githubusercontent.com/654993/125056509-eac88900-e06d-11eb-9f3a-f9cbc831a10c.png)

Lastly there is an option 'export filter settings as text' - the output of this is what I used to import the APO and included in my first post (the left and right)

**Comment by wwmm** [comment] 2021-07-09 14:42
>eta: I was browsing the code and noticed you added some code for the channel eq. If I get some free time I'll try to build it!

Yes. I think it will be enough. At least it seemed to be when I was testing it.

I have to install REM someday. It seems interesting. The problem is getting an usb calibration mic here in Brazil. They are super hard to find. Which microphone are you using?

**Comment by justinriddiough** [comment] 2021-07-09 21:20
I don't actually have a calibration mic yet, I've been using an Antlion modmic which isn't the most ideal but it has worked well enough for experimenting (and correcting overly bassy speakers). They recommend a mic called Umik-1, and I've also seen a few options made by Dayton audio. I'm in Colombia currently so I'd probably have to order one from Amazon or something one day.

**Comment by polygonalenippel** [comment] 2021-07-13 22:12
I wrote the original APO import functionality for the equalizer a while ago. I kept it simple enough to *just work*, as the APO spec is a bit odd to parse, as discussed in the issue where we implemented it: https://github.com/wwmm/easyeffects/issues/588

@wwmm are you looking into it?

**Comment by polygonalenippel** [comment] 2021-07-13 22:17
By the way, I don't run Windows or APO. My only sources of APO presets are the ones created by AutoEQ.

**Comment by wwmm** [comment] 2021-07-13 22:28
>@wwmm are you looking into it?

Not really. As I do not use any APO preset whatever support we have is already good enough for me :smile:. In any case I think that this issue is solved. Or at least seems to be on my computer after some quick tests. I am just waiting for more people to confirm that it is now possible to import different APO presets for each channel.

**Comment by wwmm** [comment] 2021-08-11 15:03
I think we can close this.

**Closed by wwmm** 2021-08-11 15:03 UTC
Labels: enhancement
