### ISSUE TITLE
Popping noise when seeking

### ISSUE THREAD

**Issue by Miosame** [wwmm/easyeffects#1267] opened 2021-11-24 18:38 UTC
### EasyEffects Version

6.1.5

### What package are you using?

Arch Official (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I hear a (sometimes very loud) popping noise when seeking inside mpv or youtube videos in firefox - not inside chrome however during seeks, only if I close out the browser while audio is playng - if I bypass the bass-enhancer the noise goes away.

I can also trigger those loud pop noises by spamming the bypass of the limiter while any audio is playing, however removing the limiter does not remove the issue, it's only gone if the bass-enhancer is off or removed.

I first thought it may be an upstream issue of pipewire, since there's a few issues that describe quite literally this (however their suggested fixes are already done out of the box for months, e.g. no idle) - but pipewire alone never produces such sound and bypassing the bass-enhancer removes it too.

Possibly related issues I've found but as I said, seem irrelevant now that all the suggested config options are default and bypassing fixes it, regardless they might be useful to figure out if this is a pipewire or easyeffects issue:

- https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/576
- https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1569

Even worse very rarely, but sometimes the issue disappears or is very quiet when popping (making it more a crackle than an eardrum destroying pop), but most of the time the issue is present.

I've been able to replicate this issue on a brand new install of:

- arch
- cinnamon
- pipewire
- easyeffects

My specific plugin setup below:

```
{
    "output": {
        "bass_enhancer": {
            "amount": 16.49999999999997,
            "blend": 0.0,
            "floor": 20.0,
            "floor-active": false,
            "harmonics": 8.5,
            "input-gain": 0.0,
            "output-gain": 2.0,
            "scope": 100.0
        },
        "blocklist": [],
        "limiter": {
            "alr": false,
            "alr-attack": 5.0,
            "alr-knee": 0.0,
            "alr-release": 50.0,
            "attack": 5.0,
            "dithering": "None",
            "external-sidechain": false,
            "gain-boost": true,
            "input-gain": 0.0,
            "lookahead": 5.3999999999999915,
            "mode": "Herm Thin",
            "output-gain": 0.0,
            "oversampling": "None",
            "release": 5.0,
            "sidechain-preamp": 0.0,
            "stereo-link": 100.0,
            "threshold": 0.0
        },
        "plugins_order": [
            "bass_enhancer",
            "limiter"
        ]
    }
}
```

If there's anything I could do to help, please tell me, I'd love to provide some kind of logs, but I'm not sure if this is caused by some kind of reset visible in logs, or if it's an issue that needs e.g. a bisect.

Thanks!

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment] 2021-11-24 19:08
I think that what you are hearing has the same cause as #1023 and #1175. Try the workaround discussed at the end of #1023. But have in mind the using a fixed latency has its disadvantages.

**Comment by Miosame** [comment] 2021-11-24 23:25
@wwmm 

I didn't have /etc/pipewire initially, but copied out of /usr/share/pipewire into there, further the default values commented out inside pipewire.conf are:

```
    #default.clock.min-quantum   = 32
    #default.clock.max-quantum   = 8192
```

are those better/worse than suggested fix in #1023 ?

though even after applying the same values from the fix to both the pipewire.conf in /etc/ and /usr/share the issue still happens, granted I haven't rebooted yet, but only manually killed easyeffects and pipewire and restarted both, will try later today if reboot makes this better.

The linked issue also apparently saw it in the logs, so I might try to run it with the debug env variable too and see if it does anything.

**Comment by Miosame** [comment] 2021-11-24 23:29
It seems to remove firefox and re-add it while seeking:

```
(process:27976): easyeffects-DEBUG: 00:26:52.293: main: locale directory: /usr/share/locale
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.347: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.347: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.347: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.347: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.347: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.347: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/input
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.347: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/output
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.347: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/autoload/input
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.347: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/autoload/output
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.361: application: easyeffects version: 6.1.5
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.361: pipe_manager: compiled with PipeWire: 0.3.40
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.361: pipe_manager: linked to PipeWire: 0.3.40
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: core version: 0.3.40
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: core name: pipewire-0
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: found metadata: settings
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: found metadata: default
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: found metadata: route-settings
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: Audio/Sink 41 alsa_output.pci-0000_25_00.1.hdmi-stereo with timestamp 1637796412363796555 was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: Audio/Sink 42 alsa_output.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH130201N4L1MQAX-00.analog-stereo with timestamp 1637796412363819725 was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: Stream/Output/Audio 90 Firefox with timestamp 1637796412363865745 was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: Firefox port 85 is connected to alsa_output.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH130201N4L1MQAX-00.analog-stereo port 47
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: Firefox port 87 is connected to alsa_output.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH130201N4L1MQAX-00.analog-stereo port 49
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: Audio/Sink 113 easyeffects_sink with timestamp 1637796412363911866 was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.363: pipe_manager: Audio/Source/Virtual 101 easyeffects_source with timestamp 1637796412363920376 was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.364: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "easyeffects_sink" }
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.364: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "alsa_output.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH130201N4L1MQAX-00.analog-stereo" }
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.364: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "Firefox" }
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.364: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "easyeffects_sink" }
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.364: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "easyeffects_source" }
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.365: pipe_manager: easyeffects_sink node successfully retrieved with id 113 and timestamp 1637796412363911866
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.365: pipe_manager: easyeffects_source node successfully retrieved with id 101 and timestamp 1637796412363920376
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.365: pipe_manager: Firefox port 85 is connected to easyeffects_sink port 112
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.365: pipe_manager: Firefox port 87 is connected to easyeffects_sink port 95
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.386: soe: http://drobilla.net/plugins/mda/Loudness is not installed
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.398: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.421: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.455: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.503: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.514: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.524: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.524: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.542: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.580: pipe_manager: Filter ee_soe_output_level, id = 79, was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.582: soe: output_level successfully connected to PipeWire graph
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.583: pipe_manager: Filter ee_soe_spectrum, id = 81, was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.585: soe: spectrum successfully connected to PipeWire graph
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.585: pipe_manager: Filter ee_soe_bass_enhancer, id = 74, was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.587: soe: bass_enhancer successfully connected to PipeWire graph
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.589: pipe_manager: Filter ee_soe_limiter, id = 71, was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.591: soe: limiter successfully connected to PipeWire graph
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.614: sie: http://drobilla.net/plugins/mda/Loudness is not installed
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.626: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.649: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.683: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.731: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.742: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.752: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.752: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.770: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.806: pipe_manager: Filter ee_sie_output_level, id = 78, was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.808: sie: output_level successfully connected to PipeWire graph
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.809: pipe_manager: Filter ee_sie_spectrum, id = 66, was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.811: sie: spectrum successfully connected to PipeWire graph
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.811: sie: Input device id is invalid. Aborting the link between filters in the microphone pipeline
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.815: sie: Input device id is invalid. Aborting the link between filters in the microphone pipeline
easyeffects-INFO: 00:26:52.815: application: disabling global bypass
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.827: application_ui: Icon Theme Qogir-ubuntu-dark detected
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.951: new default output device: alsa_output.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH130201N4L1MQAX-00.analog-stereo
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.954: application: device alsa_card.pci-0000_25_00.1 has changed its output route to: hdmi-output-0
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.954: application: output autoloading: the target node name does not match the output device name
(easyeffects:27976): easyeffects-DEBUG: 00:26:52.954: application: device alsa_card.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH130201N4L1MQAX-00 has changed its output route to: analog-output-headphones
(easyeffects:27976): easyeffects-DEBUG: 00:26:57.292: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:27976): easyeffects-DEBUG: 00:26:57.356: pipe_manager: Stream/Output/Audio 90 Firefox with timestamp 1637796417356902314 was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:57.357: pipe_manager: Firefox port 87 is connected to easyeffects_sink port 112
(easyeffects:27976): easyeffects-DEBUG: 00:26:57.357: pipe_manager: Firefox port 100 is connected to easyeffects_sink port 95
(easyeffects:27976): easyeffects-DEBUG: 00:26:57.557: soe: limiter latency: 0.005396 s
(easyeffects:27976): easyeffects-DEBUG: 00:26:57.557: soe: output_level: new PipeWire blocksize: 1024
(easyeffects:27976): easyeffects-DEBUG: 00:26:57.561: soe: pipeline latency: 5.395833 ms
(easyeffects:27976): easyeffects-DEBUG: 00:26:57.746: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:27976): easyeffects-DEBUG: 00:26:57.934: pipe_manager: Stream/Output/Audio 90 Firefox with timestamp 1637796417934768958 was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:57.935: pipe_manager: Firefox port 100 is connected to easyeffects_sink port 112
(easyeffects:27976): easyeffects-DEBUG: 00:26:57.935: pipe_manager: Firefox port 51 is connected to easyeffects_sink port 95
(easyeffects:27976): easyeffects-DEBUG: 00:26:58.088: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:27976): easyeffects-DEBUG: 00:26:58.569: pipe_manager: Stream/Output/Audio 90 Firefox with timestamp 1637796418569564962 was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:58.570: pipe_manager: Firefox port 51 is connected to easyeffects_sink port 112
(easyeffects:27976): easyeffects-DEBUG: 00:26:58.570: pipe_manager: Firefox port 85 is connected to easyeffects_sink port 95
(easyeffects:27976): easyeffects-DEBUG: 00:26:58.655: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:27976): easyeffects-DEBUG: 00:26:59.384: pipe_manager: Stream/Output/Audio 90 Firefox with timestamp 1637796419384734668 was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:59.385: pipe_manager: Firefox port 85 is connected to easyeffects_sink port 112
(easyeffects:27976): easyeffects-DEBUG: 00:26:59.385: pipe_manager: Firefox port 87 is connected to easyeffects_sink port 95
(easyeffects:27976): easyeffects-DEBUG: 00:26:59.631: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:27976): easyeffects-DEBUG: 00:26:59.666: pipe_manager: Stream/Output/Audio 90 Firefox with timestamp 1637796419666822122 was added
(easyeffects:27976): easyeffects-DEBUG: 00:26:59.667: pipe_manager: Firefox port 87 is connected to easyeffects_sink port 112
(easyeffects:27976): easyeffects-DEBUG: 00:26:59.667: pipe_manager: Firefox port 100 is connected to easyeffects_sink port 95
(easyeffects:27976): easyeffects-DEBUG: 00:26:59.988: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:27976): easyeffects-DEBUG: 00:27:00.438: pipe_manager: Stream/Output/Audio 90 Firefox with timestamp 1637796420438329699 was added
(easyeffects:27976): easyeffects-DEBUG: 00:27:00.439: pipe_manager: Firefox port 100 is connected to easyeffects_sink port 112
(easyeffects:27976): easyeffects-DEBUG: 00:27:00.439: pipe_manager: Firefox port 51 is connected to easyeffects_sink port 95
(easyeffects:27976): easyeffects-DEBUG: 00:27:00.819: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:27976): easyeffects-DEBUG: 00:27:00.877: pipe_manager: Stream/Output/Audio 90 Firefox with timestamp 1637796420877012205 was added
(easyeffects:27976): easyeffects-DEBUG: 00:27:00.878: pipe_manager: Firefox port 51 is connected to easyeffects_sink port 112
(easyeffects:27976): easyeffects-DEBUG: 00:27:00.878: pipe_manager: Firefox port 85 is connected to easyeffects_sink port 95
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.728: application:  destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.729: presets_manager: destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.729: sie: destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.729: effects_base: destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.729: sie: stereo_tools destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.730: sie: rnnoise destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.730: sie: reverb destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.732: sie: pitch destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.732: sie: multiband_gate destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.733: sie: multiband_compressor destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.735: sie: maximizer destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.737: sie: loudness destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.738: sie: limiter destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.739: sie: gate destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.741: sie: filter destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.742: sie: exciter destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.743: sie: equalizer destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.747: sie: echo_canceller destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.747: sie: delay destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.748: sie: deesser destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.750: sie: crystalizer destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.750: sie: crossfeed destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.750: sie: convolver destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.750: sie: compressor destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.751: sie: bass_loudness destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.752: sie: bass_enhancer destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.754: sie: autogain destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.755: sie: spectrum destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.755: sie: output_level destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.755: soe: destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.755: effects_base: destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.755: soe: stereo_tools destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.756: soe: rnnoise destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.756: soe: reverb destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.758: soe: pitch destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.758: soe: multiband_gate destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.759: soe: multiband_compressor destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.761: soe: maximizer destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.763: soe: loudness destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.765: soe: limiter destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.767: soe: gate destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.768: soe: filter destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.769: soe: exciter destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.771: soe: equalizer destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.774: soe: echo_canceller destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.774: soe: delay destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.775: soe: deesser destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.777: soe: crystalizer destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.777: soe: crossfeed destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.777: soe: convolver destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.777: soe: compressor destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.778: soe: bass_loudness destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.780: soe: bass_enhancer destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.782: soe: autogain destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.782: soe: spectrum destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.783: soe: output_level destroyed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.783: pipe_manager: Destroying PipeWire registry...
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.783: pipe_manager: Disconnecting PipeWire core...
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.783: pipe_manager: Audio/Sink alsa_output.pci-0000_25_00.1.hdmi-stereo was removed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.783: pipe_manager: Audio/Sink alsa_output.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH130201N4L1MQAX-00.analog-stereo was removed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.783: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.783: pipe_manager: Audio/Sink easyeffects_sink was removed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.783: pipe_manager: Audio/Source/Virtual easyeffects_source was removed
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.814: pipe_manager: Destroying PipeWire context...
(easyeffects:27976): easyeffects-DEBUG: 00:27:03.814: pipe_manager: Destroying PipeWire loop...
```

**Comment by wwmm** [comment] 2021-11-28 14:08
>are those better/worse than suggested fix in #1023 ?

With these latency ranges PipeWire still has a lot of room to make lots of latency changes. The better way to disable it is doing something like https://github.com/wwmm/easyeffects/issues/1023#issuecomment-969125660

**Comment by bhack** [comment] 2021-12-07 01:29
We could have a potential solution to test at https://github.com/wwmm/easyeffects/issues/1023#issuecomment-987453003

**Comment by Miosame** [comment] 2021-12-07 02:35
@bhack awesome thanks! though I might wait for the upstream package, as I'm not too familiar how to package it up for arch, or rather how I'd modify the pkgbuild to point towards the branch instead: https://github.com/archlinux/svntogit-community/blob/packages/easyeffects/trunk/PKGBUILD (if you have any pointers, I'd be very glad to try it out!) - I did compile it inside my arch VM and it didn't seem to produce a single binary I could copy over.

**Comment by bhack** [comment] 2021-12-07 15:54
@Miosame you can quickly test it with https://github.com/wwmm/easyeffects/issues/1023#issuecomment-987663054

**Comment by Miosame** [comment] 2021-12-20 20:12
@bhack @wwmm
I noticed if I switch SPDIF => regular => easyeffects the popping goes away too

![image](https://user-images.githubusercontent.com/8201077/146826726-e2facca9-900b-4e5a-ad2e-0bb6036d2c49.png)
![image](https://user-images.githubusercontent.com/8201077/146826736-cfccd7ec-07c2-4f7a-94e7-d12e33a42dce.png)

is easyeffects possibly having issues initially binding to SPDIF?

**Comment by wwmm** [comment] 2021-12-20 21:11
>is easyeffects possibly having issues initially binding to SPDIF?

I use the digital port of my soundcard everyday and I did not notice pops when seeking on players.

**Comment by bhack** [comment] 2021-12-20 23:45
@Miosame Are you testing this with nightly/beta?

**Comment by Miosame** [comment] 2021-12-21 00:47
@bhack that fix I noticed in 6.1.5, but I can try out the flatpak linked - or is that too outdated by now?

**Comment by bhack** [comment] 2021-12-21 00:49
You can install the flatpack nightly/beta with https://github.com/wwmm/easyeffects#nightly-flatpak

**Comment by Miosame** [comment] 2022-01-01 19:04
@bhack with latest flatpak beta it sadly still happens

**Comment by wwmm** [comment] 2022-01-01 20:13
>with latest flatpak beta it sadly still happens

With which plugins enabled and which with audio applications? As we do not reinitialize the LV2 plugins on latency changes anymore in this case the problems is fixed. But we still have to reinitialize them on sampling rate changes. 

If possible try to record a video showing the problem. Sometimes listening to the noise make it easier to find out what could be causing it.

**Comment by Miosame** [comment] 2022-01-01 23:11
> With which plugins enabled and with which audio applications?

The same plugins as in my original post, with the same values.

It does not happen with chromium at all - it does happen with firefox and mpv for example, each time I seek it does the loud ear-piercing pop.

Sometimes it goes away, but I have no idea what causes it to disappear.

> If possible try to record a video showing the problem. Sometimes listening to the noise make it easier to find out what could be causing it.

[popping.wav.zip](https://github.com/wwmm/easyeffects/files/7798333/popping.wav.zip)

I've directly recorded off of the output and then skipped back and forth in this: https://www.youtube.com/watch?v=Qd9H1oP8YXQ

I noticed this effect only happens if there is any bass in the audio (or maybe it's just too quiet for me to hear when there isn't any to amplify?..) - so skipping from and to bass will cause that pop to happen.

**Comment by wwmm** [comment] 2022-01-02 02:55
I am doing some tests on Firefox and Chromium but so far I could not reproduce the same noise in your recording. But I had an idea about another test you can try to do. Keep 2 audio players running at the same time but mute the sound in one of them. Do you still notice the problem in this case?

The reason why I am thinking about this is that Firefox and MPV have a very odd behavior when doing seeks in a video. They literally destroy and reconstruct the audio stream each time a seek operation is done. And at least MPV can destroy and recreate the stream several times per second when the user is dragging the video progress bar with the mouse. You can see that if you keep EasyEffects window opened. The Firefox entry actually disappears and comes back almost instantly when a seek is done. That is because Firefox is recreating its stream.

What may be happening is that this bizarre way Firefox and MPV implement seeks is making EasyEffects link and unlink its filters every time you do a seek in the video. In order to save cpu power we unlink our filters when none of the players connected to our virtual devices are playing. And once there is activity in our virtual devices we link the filters again. Maybe we will have to put a timeout on that like we had to do in the past =/

**Comment by Miosame** [comment] 2022-01-02 20:49
> Keep 2 audio players running at the same time but mute the sound in one of them. Do you still notice the problem in this case?

Yep that solves it, the pop goes away!

**Comment by vchernin** [comment] 2022-01-02 20:59
> Maybe we will have to put a timeout on that like we had to do in the past 

That or you could hardcode quirky apps like Firefox or mpv. Or maybe dynamically detect apps that often recreate streams, perhaps by keeping track of their connections.

**Comment by Miosame** [comment] 2022-01-02 21:02
Having a list of applications would introduce infinite maintenance, and I imagine adding some sort of detection would be a lot more difficult to get right too, just a simple config toggle I think is the easiest and quickest fix or some kind of placeholder audio stream one can trigger (though that's a hack, compared to just disabling the unload of filters)

**Comment by wwmm** [comment] 2022-01-03 15:36
I am taking a look at the code and I will have to be careful with the "timeout approach". The code handling this on PipeWire is quite different from the one we used to have in Pulseaudio.

**Comment by wwmm** [comment] 2022-01-03 15:54
I have updated the master branch with some changes that will reduce considerably the frequency with which our filters are unlinked/linked. Not really a solution but it should help a bit.

**Comment by bhack** [comment] 2022-01-03 16:35
I suppose also that high frequent linking/unlinking could go to consume more power than saving.

**Comment by wwmm** [comment] 2022-01-03 16:56
>I suppose also that high frequent linking/unlinking could go to consume more power than saving.

It will depend on the amount of time our pipeline will keep playing silence. That is what is going to happen if we do not unlink ours filters when no audio player connected to our virtual devices are active. EasyEffects will continually play silence without stopping. How much CPU power would be wasted on this depends on the plugins inserted in the pipeline and on the runtime.

**Comment by wwmm** [comment] 2022-02-21 15:37
I finally had time to add an inactivity timeout control
![Screenshot from 2022-02-21 12-22-58](https://user-images.githubusercontent.com/16225172/154985438-571ecca6-385e-4818-92c7-5388bf8040e7.png)
It is already in our master branch @Miosame if possible try to do some tests. The default timeout value is `10 seconds` but it can be anywhere between `1 s` and `3600 s`.

@Digitalone1 As you can see there is a new string that will need translation.

After doing some tests I realized things have improved on PipeWire's side. In some cases when no client is playing to our virtual sink it automatically puts the filters to sleep even if they are linked. But unfortunately there are still situations where we have to unlink them. Using the microphone pipeline is one example.  So we still need the timeout. But it is good to see things like this improving on the server side.

I hope that with the reduced linking/unlinking frequency some kind of improvement comes to https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1733. I still do not have any idea about how to even debug it.

**Comment by Miosame** [comment] 2022-02-21 18:38
appreciate it a lot, thanks for the continuous effort! I've switched to the git version and so far the problem is gone, even if firefox or mpv disappear temporarily from the audio streams list!

**Comment by bhack** [comment] 2022-02-21 19:08
Really interested in the upstream ticket.

**Comment by wwmm** [comment] 2022-04-19 14:17
I think we can close this issue

**Closed by wwmm** 2022-04-19 14:17 UTC
