### ISSUE TITLE
Unable to open the native UI

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2414] opened 2023-06-20 19:02 UTC
Is the native UI supposed to be shown or the work is still in progress?

I click on the button inside the Limiter effect, but nothing is shown. Should I install additional packages in order to see the native UI?

Besides, wouldn't it be better if we put the native UI button in the footer alongside the reset button and the plugin credit?

```
|_Show Native UI_______________Reset_______________Using Linux Studio Plugins_|
```

**Comment by wwmm** [comment] 2023-06-20 20:22
>Is the native UI supposed to be shown or the work is still in progress?

It is working as intended on my desktop. I did not have time to test on my laptop yet.

>I click on the button inside the Limiter effect, but nothing is shown. Should I install additional packages in order to see the native UI?

Any warning in the terminal? It is totally possible there is an unknown dependency I did not notice.  

>Besides, wouldn't it be better if we put the native UI button in the footer alongside the reset button and the plugin credit?

I thought about it. It could be. I've chosen the other location just because it was super easy to put it there.

**Comment by Digitalone1** [comment] 2023-06-20 20:26
> Any warning in the terminal? It is totally possible there is an unknown dependency I did not notice.

No, nothing. Except the gtk_css critical warning already pointed out in another topic.

**Comment by wwmm** [comment] 2023-06-20 20:33
>No, nothing. Except the gtk_css critical warning already pointed out in another topic.

Humm... Was EE playing something? It is only possible to show the ui once the plugins instance is initialized. And we only do this when we start to receive audio frames. 

When things are working a debug message like this one should be shown for the limiter 
```
lv2_wrapper.cpp:554	found ui handle forhttp://lsp-plug.in/ui/lv2/sc_limiter_stereo
```

**Comment by Digitalone1** [comment] 2023-06-20 20:48
No, it wasn't playing. But when I started playing something and clicked the button, the first time I got a black window (no useful warnings). Then I closed and reopened the native window and finally got it working as expected.

So you have to play something to see the native window, it's a bit misleading. And, as far as I understood, the controls in the native UI aren't working, right? When I try to modify them, they return to the previous state. Is it supposed to only look at the plot? Anyway, also this could be misleading to the average user...

**Comment by wwmm** [comment] 2023-06-20 20:57
>So you have to play something to see the native window, it's a bit misleading

The process to load the ui requires the plugin instance. But create the plugin instance you have to know the sampling rate and block size that is going to be used. We could obviously create an useless instance with a default rate and block size just for the sake of being able to show this window. But if the values do not match the ones Pipewire are actually using at the moment the instance has to be recreated. So most of the times it will be just a waste of resources. But it is what DAW like Carla or Ardour do.

>And, as far as I understood, the controls in the native UI aren't working, right?

No. The amount of effort required for this is not small. The LV2 ui is totally independent of the plugins instance. So we have to bind each of the ui controls to the corresponding port in the plugin instance. In the end we will have double the amount of bindings as we are not going to replace the current custom ui by the native ui. First because we cannot embed them in our window. Second because they east a lot of CPU power.

>Is it supposed to only look at the plot? Anyway, also this could be misleading to the average user...

Seeing the plots is the only reason. It is impossible to view them otherwise. And it is something that only more advanced users will really benefit. It crossed my mind to hide the button behind an option but it seemed annoying to do this

**Comment by Digitalone1** [comment] 2023-06-20 21:45
> It crossed my mind to hide the button behind an option but it seemed annoying to do this

I think it's the way to do it. At the moment the behavior is misleading and after the release many people could come here asking "why controls do not work", "the close button on the native window does not work", "the window opens only when the music is playing"...

At least inside the settings you can explain in an additional label near the option that this is an experimental feature and it's useful only to see the plot.

**Comment by wwmm** [comment] 2023-06-20 21:58
>At the moment the behavior is misleading and after the release many users could come here asking "why controls do not work", "the close button on the native window does not work", "the window opens only when the music is playing"...

True. But on the other hand with the feature hidden we will probably still have people coming here asking for the frequency response curves because they did not notice the option in the preferences menu.

**Comment by wwmm** [comment] 2023-06-20 22:02
In any case it is not the end of the world to have the preferences option. But for now I will keep focusing on adding the feature to more plugins as well as trying to fix some of the rough edges.

**Comment by Digitalone1** [comment] 2023-06-21 09:34
Anyway I wonder how to hide a button behind an option. The UI is constructed when a plugin is added to the pipeline, but if the option is modified, we can't show/hide the button accordingly.

Maybe that option would need to restart the whole application (or just the window)...

**Comment by wwmm** [comment] 2023-06-21 14:50
>Maybe that option would need to restart the whole application (or just the window)...

>Update: Or maybe a gsettings bind to the option to hide/show the button? Maybe in ui_helper to not repeat it every time in the specific plugin source...

Although adding this setting will be annoying it is not going to require something so radical. We could handle it in a similar way to how we handle this https://github.com/wwmm/easyeffects/blob/f05e1a101d1174d2887dfd3c90812d089dc78876/src/effects_base.cpp#L72. The plugin_base class could have a bool flag named like `lv2_plugin_wants_to_show_ui`. Just like it happens for `lv2ui-update-frequency` this would be set for all plugins inside `effects_base`. Once this is set the plugin box in the gtk side can read this property inside its `setup` function and use this information to set the visibility of the button.

It is still annoying to implement. But EE worflow is not going to change because of it.

**Comment by wwmm** [comment] 2023-06-21 14:57
>Or maybe a gsettings bind to the option to hide/show the button? 

This would work well if each plugin had its own `show native ui` setting. But in this case we want one global setting that is applied to all lv2 plugins. So in order to do this binding it would be necessary to create an instance of the global gsettings path for each lv2 plugin. It is something to consider. But in the end it may be just as annoying to do as the approach I talked above.

**Comment by wwmm** [comment] 2023-06-21 15:06
>Maybe in ui_helper to not repeat it every time in the specific plugin source...

It may work if we create a gsettings object to the global path in a similar way we handle https://github.com/wwmm/easyeffects/blob/f05e1a101d1174d2887dfd3c90812d089dc78876/src/ui_helpers.cpp#L26. Its initialization could even be done in the same location as https://github.com/wwmm/easyeffects/blob/f05e1a101d1174d2887dfd3c90812d089dc78876/src/application_ui.cpp#L267.

**Comment by Digitalone1** [comment] 2023-06-21 15:37
Anyway, suppose you have the setting enabled and can see the button. You open the native UI, but then disable the setting. You can't close the native window anymore (because the close button on that windows does not work). Unless you reenable the setting to show the button. I don't know, it's not optimal.

**Comment by Digitalone1** [comment] 2023-06-21 15:42
Also, if the reason for this is to take a look at the plot for the frequency response, (because the native UI is not fully functional), isn't it better to change the label of the button in `Show Frequency Response`?

**Comment by wwmm** [comment] 2023-06-21 16:08
>isn't it better to change the label of the button in Show Frequency Response?

Maybe something like `Show Response Curves` would be generic enough for all cases. But I still think that people that would be confused in one case would still be on the other.

**Comment by wwmm** [comment] 2023-06-24 15:27
I have found a way to make most of the native ui controls to work. Now I have to find a clever way to propagate the changes they do to the gsettings database.

**Comment by Digitalone1** [comment] 2023-06-24 15:30
> I have found a way to make most of the native ui controls to work. Now I have to find a clever way to propagate the changes they do to the gsettings database.

Another bind? You said this would be overkill.

**Comment by wwmm** [comment] 2023-06-24 15:34
>Another bind? You said this would be overkill.

That is where the "clever way" will have to come in :smile: 

Jokes aside to make the native ui setting to affect the processing it took not much more than one line of code. So it feels a little wrong to not let them work. The synchronization with gsetting that may not be so easy to put in place.

A little off topic but while looking at the native limiter ui now I realized it has a `knee` control we are not exposing in our custom ui.

**Comment by wwmm** [comment] 2023-06-24 15:36
>A little off topic but while looking at the native limiter ui now I realized it has a knee control we are not exposing in our custom ui.

Actually we are. IT is just that the native ui suggests it is not tied to the ALR control... Strange...

**Comment by wwmm** [comment] 2023-06-24 15:42
>So it feels a little wrong to not let them work

For example some of the ui controls allows us to pause and clear the graphs. Or in the case of the equalizer to plot over the response curse the FFT calculated after or before the processing. That is really useful and does not require synchronization with gsettings. THat is why I feel that disabling all the native controls feels wrong. At least some of them we should let functional.

**Comment by Digitalone1** [comment] 2023-06-24 15:50
> Jokes aside to make the native ui setting to affect the processing it took not much more than one line of code. So it feels a little wrong to not let them work. The synchronization with gsetting that may not be so easy to put in place.

The problem is that the controls inside the native UI are automatically reset.

If they are effective, the first thing that comes to my mind: when the native UI is closed, loop through gsettings key (only ones related to the current effect) and update the value. There should be a way to get the value from the lv2 port bound.

> A little off topic but while looking at the native limiter ui now I realized it has a `knee` control we are not exposing in our custom ui.

That's weird, it should be added later. I would never miss it when the porting from Calf to LSP was made.

> Actually we are. IT is just that the native ui suggests it is not tied to the ALR control... Strange...

If I don't remember wrong, the LSP documentation was saying it was for the ALR mode.

**Comment by Digitalone1** [comment] 2023-06-24 15:54
Knee is for ALR section (at least the documentation says so): https://lsp-plug.in/?page=manuals&section=sc_limiter_stereo

But to bee 100% sure we should ask on LSP Github.

**Comment by wwmm** [comment] 2023-06-24 15:55
>The problem is that the controls inside the native UI are automatically reset.

I have just updated our master branch removing this forced reset. Now for example In the multiband compressor we can use that `split control` in the native ui to see each compressor band compression curve. Another thing that does not have to be synchronized with gsettings. We probably will still have to hide the native ui functionality behind an experimental option. I do not think I will be able ot make all the control work. But I think the native ui is more useful now.

>The problem is that the controls inside the native UI are automatically reset.

I was just confused by the fact it lets us control the alr parameters even without enabling the alr bool. We for example disable the controls if the alr bool is off. For some reason the native ui does not do this. Probably an oversight.

>If they are effective, the first thing that comes to my mind: when the native UI is closed, loop through gsettings key (only ones related to the current effect) and update the value. There should be a way to get the value from the lv2 port bound.

It is something to consider.

**Comment by wwmm** [comment] 2023-06-24 16:06
>There should be a way to get the value from the lv2 port bound.

We already have a function that does it https://github.com/wwmm/easyeffects/blob/33fc358cd24597736cd35f1190988172474b96a8/src/lv2_wrapper.cpp#L372. I think I would only have to add some kind of flag to the port struct that would allow us to know if some kind of conversion is needed. For example in the cases where a linear value is converted to decibel and vice versa. Most of the other values can be copied directly.

**Comment by Digitalone1** [comment] 2023-06-24 17:23
> I think I would only have to add some kind of flag to the port struct that would allow us to know if some kind of conversion is needed. For example in the cases where a linear value is converted to decibel and vice versa. Most of the other values can be copied directly.

You say an array of struct?

Wouldn't be easier a `std::tuple`? Defined as a container of two strings and an enum (lv2 port name, gsettings key and enum type of conversion).

Look at this: https://github.com/wwmm/easyeffects/blob/master/src/limiter.cpp#L51-L79

|lv2_port|gsettings_key|conversion_type|
|---|-----|---|
|mode|mode|enum|
|ovs|oversampling|enum|
|dith|dithering|enum|
|lk|lookahead|double|
|at|attack|double|
|rt|release|double|
|th|threshold|double_db|
|boost|gain-boost|bool|
|scp|sidechain-preamp|double_db|
|slink|stereo-link|double|
|alr|alr|bool|
|alr_at|alr-attack|double
|alr_rt|alr-release|double|
|knee|alr-knee|double_db|
|extsc|external-sidechain|bool|

**Comment by wwmm** [comment] 2023-06-24 19:25
>You say an array of struct?

Initially I though about just having a boolean that would tell if conversion between decibel and linear values was needed. But as gsettings uses a different function for each type maybe something more elaborated will be needed. I will think more about this.

**Comment by Digitalone1** [comment] 2023-06-24 23:37
I was thinking that with a tuple like the one above mentioned you can loop it to bind gsettings key and update values from native UI. The enum would suggest the type of bound and the conversion type.

**Comment by wwmm** [comment] 2023-06-24 23:42
>I was thinking that with a tuple like the one above mentioned you can loop it to bind gsettings key and update values from native UI. The enum would suggest the type of bound and the conversion type.

Do you mean to change the value in database as soon as we change it in the native ui? Technically we can only make bindings to `gobjects`. Without a custom gobject we have to manually call the setters.

In any case there is definitely room for improvement. For example I am not checking yet if there is really the need to write to the database like we do for our presets. But things are working in a very decent way here on my computer. The native ui is now almost fully functional. What remains to be tested are all those things LSP plugins have in their menus.

**Comment by Digitalone1** [comment] 2023-06-25 02:16
> Do you mean to change the value in database as soon as we change it in the native ui?

No, when the native UI is closed.

**Comment by Digitalone1** [comment] 2023-06-25 12:31
@wwmm I saw your implementation with callbacks. Practically you add functions in a vector to update every settings after the native UI is closed, but are those functions removed when the bind does not exist anymore (when the effects is removed from the pipeline).

I tried with the tuples but failed because I faced the same error that I got when I was trying to bind the settings with the Dropdown widgets a few months ago. I was passing key strings, but the bind templates want literals and I can't pass captured variables to the g_callback. If you want I can push this attempt to my repository to give it a look, but don't know if it can be of any help.

Besides I saw that we need also the `lower_bound` bool for `double_db` conversion which it seems missing because it defaults to true, but it should be considered when an update to g_settings is performed.

**Comment by Digitalone1** [comment] 2023-06-25 13:05
@wwmm we use `lower_bound` flag to show `-inf` on our widgets when the linear value is 0.

So I suppose that if, in the native UI, we change the linear value to 0, while updating to gsettings we got a big negative number from the conversion (near to - infinite). This could cause an overflow?

I think we should do:

```c++
gsettings_sync_funcs.emplace_back([=, this, lower_bound]() {
  const auto linear_v = get_control_port_value(key_wrapper.msg.data());

  const auto db_v = (!lower_bound & linear_v == 0.0F) ? util::minimum_db_d_level : util::linear_to_db(linear_v);

  g_settings_set_double(
    settings, 
    gkey_wrapper.msg.data(),
    static_cast<gdouble>(db_v)
  );
});
``` 

In place of https://github.com/wwmm/easyeffects/blob/master/include/lv2_wrapper.hpp#L231-L233

**Comment by wwmm** [comment] 2023-06-25 14:22
>So I suppose that if, in the native UI, we change the linear value to 0, while updating to gsettings we got a big negative number from the conversion (near to - infinite). Could this cause an overflow?

Somehow nothing bad happened when testing with the dry/wet controls that are among the ones LSP show the `-Inf`. Things just worked. In any case I have updated the master branch with the `lower_bound` code.

>I saw your implementation with callbacks. Practically you add functions in a vector to update every settings after the native UI is closed, but are those functions removed when the bind does not exist anymore (when the effects is removed from the pipeline).

At this moment both the bindings and the sync function vector are only destroyed when the plugin class is destroyed. But at this moment we do not destroy the plugin class. Last time I tried to do this I saw some crashes. So the plugin class lives and is reused while EE is alive. In any case there is no need to worry. As far as I remember the bindings between gsettings and the lv2_wrapper are done only when the plugin class is constructed. So the same will happen to the sync functions. There is no risk of having them being called when they should not.

**Comment by Digitalone1** [comment] 2023-06-25 14:35
So now remains to add the option to show the native UI button.

And maybe moving the button in the footer (as pointed out in the first post). Or do you like it at the top of the plugin UI?

**Comment by wwmm** [comment] 2023-06-25 14:37
>And maybe moving the button in the footer (as pointed out in the first post). Or do you like it at the top of the plugin UI?

I did a quick test and it may require some work to handle the alignment with the reset button for both when the native ui button is visible and hidden. So it is probably better to first add the preferences option and thinking about the native ui button location later.

**Comment by wwmm** [comment] 2023-06-25 14:46
>Or do you like it at the top of the plugin UI?

Although I prefer at the top it does not make sense to do this in the equalizer and other plugins. So from a design point of view it would be more consistent next to the reset button because it would be the same for all plugins. The question is how annoying the alignment there would be.

**Comment by Digitalone1** [comment] 2023-06-25 14:55
> Although I prefer at the top it does not make sense to do this in the equalizer and other plugins. So from a design point of view it would be more consistent next to the reset button because it would be the same for all plugins. The question is how annoying the alignment there will be.

The footer is a box with `center` as vertical alignment.

**Comment by wwmm** [comment] 2023-06-25 15:04
>The footer is a box with center as vertical alignment.

Maybe now that there will be 3 widgets there we should use a `GtkCenterBox` with the reset button as the center widget and the native ui button as the first. This way the reset button will probably be still centered when the native ui button is hidden.

**Comment by Digitalone1** [comment] 2023-06-25 15:19
The footer box is homogeneous width. There's already a placeholder box to show the reset at the center. It's enough to align the first placeholder box as horizontally left and you can place the button inside. The credit label is aligned right.

**Comment by wwmm** [comment] 2023-07-25 15:32
Now that the experimental features section is in place and the native ui buttons are hidden behind an option I think we can close this issue. The button layout can be changed in the future.

**Closed by wwmm** 2023-07-25 15:32 UTC
