### ISSUE TITLE
No sound after adding a Delay effect, sound comes back with "Invert Phase" on right channel

### ISSUE THREAD

**Issue by carolfs** [wwmm/easyeffects#3194] opened 2024-06-20 12:56 UTC
### EasyEffects Version

7.1.6

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 40

### Describe the bug

The sound stops when I add a Delay effect, with default settings or the same settings I was using before, even if this is the only enabled effect or along with other effects. The sound comes back when I enable "Invert Phase" for the *right* channel on the Delay settings. Enabling this for the *left* channel makes no difference (??). This is for headphones or speakers.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by Digitalone1** [comment] 2024-06-20 14:16
Yes, I can reproduce it. It's very weird. Maybe something new introduced in the latest LSP release.

**Comment by Digitalone1** [comment] 2024-06-20 14:29
Duplicate of #3153

The new LSP version with the fix is not out yet. The best thing you can do is to downgrade the LSP flatpak package to `1.2.16`.

**Comment by wwmm** [comment] 2024-06-20 22:04
As explained by @Digitalone1 it will be fixed in the next LSP release.

**Closed by wwmm** 2024-06-20 22:04 UTC
