### ISSUE TITLE
Bypass state in each effect isn't saved between sessions and in presets

### ISSUE THREAD

**Issue by AlexFolland** [wwmm/easyeffects#1039] opened 2021-07-22 06:00 UTC
**To reproduce:**

1. Add an effect.
2. Make it do something cool that you want to be able to enable whenever you want, but usually leave disabled with "Bypass".
3. Save it in an input or output preset, depending on what it is.
4. Restart the computer.

**Observed behavior:**

- The "Bypass" state in each effect is not saved between sessions and in presets.
    - It resets to disabled, meaning the effect is enabled.
- This is a new regression as of EasyEffects.
    - In PulseEffects, a disabled effect stayed disabled between sessions and could be saved as disabled in presets.

**Expected behavior:**

A disabled effect ("Bypass" enabled) is expected to stay that way between sessions and be saved that way in presets.

**Additional commentary:**

- As one example, I like using the pitch effect for certain music to make it sound hilariously demonic, and being able to toggle it on whenever I want.  With this issue, every time I restart the computer, the pitch effect is enabled when I want it to be disabled by default.
- I personally prefer the previous system where all effects were readily visible to be toggled with a quite-obvious switch in the main list instead of hidden in an effect selection context menu and then only togglable with a "Bypass" button that's only visible when visiting each effect's settings.
- Otherwise, EasyEffects is awesome and I love the new name, especially as the person who suggested it in my brainstorming list!  I'm so excited that you adopted it and did all the hard work it took to rebrand.  I have insane amounts of respect.

**Comment by wwmm** [comment] 2021-07-22 14:52
>This is a new regression as of EasyEffects. 

Not a regression in the usual sense. It was intentional. The reason is that in this context a bypass is typically used just to temporarily listen to the difference the effect is making and not as a way to disable the plugin permanently. The idea is doing that by removing the plugin from the list.

>I personally prefer the previous system where all effects were readily visible to be toggled

It was that way because dealing with GStreamer pipeline is hard. Totally removing the plugin from the pipeline was a pain. So I had a super complex structure where each plugin had a container that was always in the pipeline and the "bypass" was adding or removing a child bin from that one. That is why that list had all plugins. The corresponding "top level bins" were never removed from the pipeline.

The other side effect of the previous design is that all our gtk widgets are loaded all the time. For people that only wanted to use 1 or 2 plugins it was a waste of system memory. It is not that an additional 100 to 150 MB is big by today standards. But it is not nice to waste memory. 

All that being said making the bypass being saved to the preset is not a big problem. Most of the work would be creating the corresponding keys in the gsettings database. But as usually audio plugins do not use the bypass as a permanent setting this may make users of other hosts like Ardour or Carla confused. Let's keep this open for a while and see what other people think about this.

**Comment by AlexFolland** [comment] 2021-07-23 02:22
What if there was a setting, even hidden away in a config file or command line parameter, that was disabled by default that said "Save bypass state between sessions"?  I could enable it and users who aren't expecting it would leave it disabled.  Being able to quickly enable effects that are disabled on startup makes things like quickly switching between different voices possible.

**Comment by maplepy** [comment] 2022-02-09 05:40
> This is a new regression as of EasyEffects.

I agree that this is super annoying and should stay in whatever state you put it into before closing easyeffect, just like it did in pulseeffect.

If people want to make temporary, they can just disable the bypass manually? If you want to load a module with your settings but have it in a disabled state (with bypass) how are you supposed to do that? Recreate the settings everytime?

**Comment by wwmm** [comment] 2022-02-09 12:44
>Would that possible to make it a choice?

Maybe. I will take a look at it. But is definitely not going to be the default. I still see the bypass as a temporary action. It was different in pulseeffects because with gstreamer things were handled in a very different way.

**Comment by AlexFolland** [comment] 2022-02-09 21:56
It doesn't necessarily need to use the same "bypass" button.  A separate enabled/disabled state could be used for permanent changes with a checkbox like before, while the "bypass" button could remain a solution for temporarily bypassing the effect.

The ultimate goal is just some way to store configured-but-disabled effects like PulseEffects could do intuitively, so however that can happen would work just fine.

**Comment by wwmm** [comment] 2022-02-09 22:56
>A separate enabled/disabled state could be used for permanent changes

That would require more work. It is easier to use the bypass variable because it is already in all filters code. It is just a matter of adjusting the other places like the code handling the graphical interface such that the bypass is only permanent if an option is enabling this.

>with a checkbox like before

That checkbox was in PulseEffects only because fully removing the filter from the GStreamer pipeline was a pain. That is why that side panel plugins list had all the filters all the time. Now that we can actually completely removing the filter from the pipeline and as a result also from the plugins panel having an additional `enable/disable` checkbox feels weird.

**Comment by AlexFolland** [comment] 2022-02-09 23:08
> Now that we can actually completely remove the filter from the pipeline and as a result also from the plugins panel having an additional `enable/disable` checkbox feels weird.

I respectfully disagree.  Not having it feels weird.  Having a "bypass" button somewhere in the individual effect's interface which does not have a consistent on-screen position instead of a checkbox in the list of effects feels counterintuitive.  Other software like EqualizerAPO lets the user add an unlimited number of filters, remove them, and toggle them at will, while saving that toggle state.  There are many similar interfaces where one can add items to a list and remove them entirely which also have toggle switches right in the list view.  It feels quite natural across a wide range of similar software.

**Comment by wwmm** [comment] 2022-02-09 23:23
>I respectfully disagree.

No problems. I understand what you are saying. But you think that way because you have an use case for "the permanent bypass". In my case when I do not want a filter in the pipeline I just remove it from there and that is it. In this situation there is absolutely no need for that checkbox and it feels redundant.

All that being said there is no problem in trying to cover both cases if it does not make the code harder to maintain. What I really do not want is having to double check if I have "disabled plugins" when saving a preset. It would be super annoying. When I save filters to a preset I expect them to be active. So that "permanent bypass" has to be an option and not forced on everybody like it was before.

**Comment by AlexFolland** [comment] 2022-02-09 23:57
For context about my arguments, here's an image of the intuitive EqualizerAPO editor interface, which I used in Windows before making the switch to Linux in 2019.

![image](https://user-images.githubusercontent.com/601517/153310258-ef7ccad5-c016-42a0-bfbe-22dbade7905a.png)

Each filter in the chain can be dragged around, has its own interface, and has a giant toggle button in a consistent horizontal position on the left.  The toggle state is saved between sessions and saved in presets.  I expect this is what most users expect, especially considering one filter may be complicated to configure, and having to reconfigure one it if it was ever removed could feel tragic.

By the way, I only posted this for context about my position about the toggle switches, not to assert that the EqualizerAPO interface is overall superior or anything like that.

> What I really do not want is having to double check if I have "disabled plugins" when saving a preset. It would be super annoying.

That's a good point.  I've changed my mind to agree with you there.

**Comment by wwmm** [comment] 2022-02-10 00:11
@Digitalone1 this may be one more thing to have in mind when working on multiple filters instance.

**Comment by maplepy** [comment] 2022-02-11 02:31
> > Now that we can actually completely remove the filter from the pipeline and as a result also from the plugins panel having an additional `enable/disable` checkbox feels weird.
> 
> I respectfully disagree. Not having it feels weird. Having a "bypass" button somewhere in the individual effect's interface which does not have a consistent on-screen position instead of a checkbox in the list of effects feels counterintuitive. 

I agree that having to look for the bypass toggle at different places for each module feels a bit weird and counter intuitive. I'm not saying that it's hard or that it takes too much time but having to find it in modules where there are sometimes a few buttons is a bit annoying and its inconsistency makes it odd in my opinion.

I think having an option to save the bypass state in the app preferences would be nice or (I don't know if people would use that) having a way to use both the current bypass state and the permanent state with like a right click (for the permanent toggle for instance) and the standard left click for the current bypass would be something to consider?

Anyway, thank you very much @wwmm for listening to our feedback by the way! 

Hope you guys are having a great day :)

**Comment by wwmm** [comment] 2022-02-11 02:48
>having a way to use both the current bypass state and the permanent state with like a right click (for the permanent toggle for instance) and the standard left click for the current bypass would be something to consider?

That would over complicate things (and the code). Having an option to make the bypass state permanent should be enough. Or maybe it will be easier to make the bypass a setting just like any other and what the option would do is ignoring it when saving the preset. At the end of the day what is really annoying is having to check bypass state before saving presets.

In any case it may take some time until I take a look at this because at this moment I am working on another personal project I have neglected for some time. And there is also the "multiple filter instances" that also has to be done.

**Comment by maplepy** [comment] 2022-02-11 08:10
>In any case it may take some time until I take a look at this because at this moment I am working on another personal project I have neglected for some time. And there is also the "multiple filter instances" that also has to be done.

Yeah no problem, take the time you need and have fun with your project, I guess you're talking about _fastgame_ ?

**Comment by wwmm** [comment] 2022-02-11 13:59
>I guess you're talking about fastgame ?

Yes. It is another software I use frequently and I feel it is time to move it from gtk3 to `gtk4 + libadwaita` and reuse some of the ideas implemented in EasyEffects. But as fastgame code base is a lot smaller it should not take too long. But as usual there are also the things I have to do at my work.

**Comment by wwmm** [comment] 2022-06-25 16:31
I think I totally forgot about this issue. It is implemented in the master branch
![Screenshot from 2022-06-25 13-26-20](https://user-images.githubusercontent.com/16225172/175782469-e614ee6f-763b-48a3-8379-175cc5767fbc.png)
Although I still have the same opinion as before in the end I implemented without adding an  option to change the behavior. The reason was that moving the bypass button to the list in the left panel has already required way more changes than I was expecting. So I decided to not complicate things even more...

Now this has to be tested.

**Comment by AlexFolland** [comment] 2022-06-26 06:41
I have tested this with the `easyeffects-git` AUR package on Manjaro.  Here is my test report.

### Test executed

1. Install `aur/easyeffects-git`, removing `easyeffects`.
2. Reboot.
3. Open the EasyEffects GUI.
4. Navigate to the input menu.
5. Save an input preset.
6. Add a pitch effect with -4 semitones and disable it.
7. Save an input preset with a different name.
8. Reboot.
9. Open the EasyEffects GUI.
10. Navigate to the input menu.
11. Verify that the Pitch effect is still disabled.
12. Load the input preset which has no Pitch effect.
13. Load the input preset which has a Pitch effect.
14. Verify that the Pitch effect is still disabled.

### Result

Observed behavior matched expected behavior, so this test passed.

### Additional commentary:

There's nothing clearly showing that the effect is disabled in the list.  The only way to see whether it's disabled is to hover over the effect's row in the list and be aware that the icon that looks like streams swapping is highlighted slightly.  I have some suggestions which, either combined all together or chosen individually, might improve this situation.

1. Change the "Bypass" theming to "Enabled", with a 1/0 power button icon like EqualizerAPO uses.
    - This would also imply inverting the state of the button, so that when enabled, the button is in a visually "pressed" state, also like EqualizerAPO.
2. Make the Enabled icon always visible and left-aligned.
    - To make room for an Enabled button on the left, numbers could be used instead of the arrow icon, to clearly show the order in which the effects will be applied, also like EqualizerAPO.
3. Desaturate and/or darken/brighten the row or the text on the row if the effect is disabled to clearly show that the effect is disabled, also like EqualizerAPO.

I expect that these suggestions would help UI clarity and prevent issues like not knowing why an effect isn't working in case of loading a preset made by somebody else or accidentally disabling an effect without intending to.  It would also help discoverability of the ability to disable an effect, since currently the icon looks confusingly like a channel-swapping icon and not something related to disabling the effect.

As for my personal use case, I already know what the icon means and it works perfectly.  My suggestions are only for other new users of the software at this point.  The feature requested in the original post is implemented satisfactorily for my personal usage.

Thank you very much for reading and thank you even more for implementing this!  It's helpful to be able to have funny effects that I can toggle at will while voice chatting.

**Comment by Digitalone1** [comment] 2022-06-26 07:00
I don't think adding new always visible icons would help. And also introducing numbered icons will complicate things on the code side.

I think just setting the opacity to 0.5 to the arrow and the effect label would be enough when the bypass is enabled.

**Comment by AlexFolland** [comment] 2022-06-26 07:03
I agree that opacity would help, but discoverability of the ability to disable an effect is very useful for new users.

**Comment by Digitalone1** [comment] 2022-06-26 07:13
If it's for discoverability, we could just make the current icons always visible. That would also simplify the code.

**Comment by wwmm** [comment] 2022-06-26 15:10
>There's nothing clearly showing that the effect is disabled in the list. The only way to see whether it's disabled is to hover over the effect's row in the list and be aware that the icon that looks like streams swapping is highlighted slightly.

I did not mention it in my last post but I am concerned about this too. But I did not have a good idea about how to solve it...

>If it's for discoverability, we could just make the current icons always visible. That would also simplify the code.

I tried. It did not look right from a style point of view... It is hard to describe the feeling in words... Let's say "it looked too heavy to the eyes" having all the bypass buttons always visible... Maybe it is just me...

>And also introducing numbered icons will complicate things on the code side.

Besides this there is another problem. I tried to use numbers in the past. It is another feeling that is hard to describe but they felt "out of place". A number in a label does not have the distinct look an icon has. And when I tried to create an icon with a number size and resolution became a problem. In the end it did not look as good as the arrows. It was functional. But it did not look good.

>Desaturate and/or darken/brighten the row or the text on the row if the effect is disabled to clearly show that the effect is disabled

That is something I did not consider and that may actually work and be easy to do just with gtk xml code. I will investigate.

> since currently the icon looks confusingly like a channel-swapping icon and not something related to disabling the effect.

Being honest I was never happy with this icon. But as I am not good at making icons I have chosen the Adwaita icon that was close to the idea "of a path being ignored". But now I wonder how "power on" icon would look in this position. I will investigate.

In any case this is a problem that already exists in the global bypass button. If the user does not understands what this one does it is not going to understand it in the plugins name row too...

**Comment by wwmm** [comment] 2022-06-26 15:42
Guys this is what I've got with `1 line` of xml code
![Screenshot from 2022-06-26 12-39-33](https://user-images.githubusercontent.com/16225172/175822156-e217c404-5fc5-4438-9a23-090d78eb6efc.png)
And this is how it looks in a dark theme
![Screenshot from 2022-06-26 12-39-20](https://user-images.githubusercontent.com/16225172/175822174-ef7ca028-0fad-42c7-b67a-568220a5f995.png)
It is always hard to judge how new users will react but at least to the person that implemented it (me) :smile: it is clear that "something different" is happening to the `Bass Enhchancer` and `Crystalizer` entries in this list.

**Comment by wwmm** [comment] 2022-06-26 15:53
I think now I remember why I used the `media-playlist-shuffle` icon as bypass button. It does not seem the Adwaita icon theme has some kind of `power on/off` icon. Or at least I could not find it yet...

**Comment by Digitalone1** [comment] 2022-06-26 16:10
Did something change to left margin of effects name label? I have more space (but I'm still on the commit before the bypass changes).

![Schermata del 2022-06-26 18-08-52](https://user-images.githubusercontent.com/25790525/175823366-0838a14d-fe23-4be1-a5c2-d4d9b0f98b6e.png)

**Comment by wwmm** [comment] 2022-06-26 16:11
>Did something change to left margin of effects name label?

It must have happened when I was applying the `linked` style class to the buttons. I will fix this.

**Comment by wwmm** [comment] 2022-06-26 16:17
Fixed
![Screenshot from 2022-06-26 13-14-59](https://user-images.githubusercontent.com/16225172/175823697-1c33b78b-09ff-44ef-8ca0-e3b135636a63.png)

**Comment by Digitalone1** [comment] 2022-06-26 16:19
Can you also apply the same opacity value on the arrow with another line of xml or it's more tricky?

**Comment by wwmm** [comment] 2022-06-26 16:21
>Can you also apply the same opacity value on the arrow with another line of xml or it's more tricky?

I tried. Gtk ignored the `sensitivity` property in the icon. Maybe if I try to actually set the opacity property it will work. But in this case I doubt it can be done with only one line of xml code.

**Comment by wwmm** [comment] 2022-06-26 16:23
>Maybe if I try to actually set the opacity property it will work

It obviously has to. We can see in the image other icons with the sensitivity set. I will check again to see how we did it on them.

**Comment by Digitalone1** [comment] 2022-06-26 16:37
> Gtk ignored the `sensitivity` property in the icon. 

Oh, I remember that. For that reason I set opacity on both endpoint label and icon.

**Comment by wwmm** [comment] 2022-06-26 16:39
>Oh, I remember that. For that reason I set opacity on both endpoint label and icon.

Yes. It would have to be through the opacity. What will require some level of complication. I don't know... It seems fine to me to change only the label.

**Comment by wwmm** [comment] 2022-06-26 16:54
This is how the bypass buttons look with the `system-shutdown-symbolic` icon
![Screenshot from 2022-06-26 13-51-58](https://user-images.githubusercontent.com/16225172/175825171-94537a2a-c915-4348-a116-0565a4d84dcd.png)
What do you think @AlexFolland and @Digitalone1? Is it an improvement over the media shuffle icon? There is also the question about how it is going to look on other icon themes. This isn't an icon we hardcode in our sources... But we could if necessary...

**Comment by wwmm** [comment] 2022-06-26 16:58
Maybe the `system-shutdown-symbolic` icon gives the inverted idea. That it should be pressed for effects to work and unpressed to bypass...Humm...

**Comment by Digitalone1** [comment] 2022-06-26 17:00
I don't like it and in the header bar it might be confused to shutdown the whole app.

I could try in the next days to find some switch icons on those free icons website with license that permits to use the icon and modify it.

If one is good for us, we can try to adapt it as symbolic and hardcode it.

**Comment by AlexFolland** [comment] 2022-06-26 17:07
That's the perfect icon!  Nice find!

> That it should be pressed for effects to work and unpressed to bypass...

This is still the mindset of "bypass", when really, it's being enabled or disabled.  When something is enabled, its state is on.

**Comment by AlexFolland** [comment] 2022-06-26 17:12
> I don't like it

This surprises me.  It looks crystal clear in its functionality to me.

**Comment by Digitalone1** [comment] 2022-06-26 17:21
> This surprises me. It looks crystal clear in its functionality to me.

In the effect row could be good, but in the headerbar I would confuse it with close the application. I don't know if I'm the only one with this impression. If it's okay for you and @wwmm, no problem, add it. :)

**Comment by AlexFolland** [comment] 2022-06-26 17:28
> in the headerbar I would confuse it with close the application

Oh, I hadn't seen it there in the header bar.  I agree that it's not good for it to be there and it would be better to only be in the list of effects.

**Comment by wwmm** [comment] 2022-06-26 17:36
>I don't like it
>That's the perfect icon! Nice find!

I have to say it was hilarious to read totally different opinions so close to each other :smile:

>This is still the mindset of "bypass", when really, it's being enabled or disabled. When something is enabled, its state is on.

I see no problems in changing the meaning that is being passed to the user. We just have too adjust the text in the tooltips. It won't make sense for them to still use the word `bypass`

>Oh, I hadn't seen it there in the header bar. I agree that it's not good for it to be there and it would be better to only be in the list of effects.

I used the same icon in both places because the global bypass in the headerbar is essentially doing the same thing but on the pipeline level. Maybe there we should keep the shuffle media icon and used the system shutdown icon only in the list. This way we would pass the information that the global bypass is on another level. I will do this now.

**Comment by wwmm** [comment] 2022-06-26 17:50
I updated the master branch again. The global bypass button uses the `shuffle-media` icon and in the user interface each plugin has now a `enable` button instead of a bypass button and the icon is the `system-shutdown`. In the presets file what is saved is the bypass state. I have just inverted the binding in the window. People editing the json file directly will have to invert the boolean mentally.

**Comment by wwmm** [comment] 2022-06-26 17:50
With this this issue can be closed.

**Closed by wwmm** 2022-06-26 17:50 UTC
Labels: enhancement

**Comment by AlexFolland** [comment] 2022-06-26 17:53
> I have to say it was hilarious to read totally different opinions so close to each other

This difference was a misunderstanding on my part.  I was only looking at the effects list.  Ultimately, I agreed about the header bar icon, which I hadn't seen at the time of my opinion.  The icon itself is perfect in the context where it fits.

**Comment by Digitalone1** [comment] 2022-06-26 18:41
What do you think of these ones?

https://www.svgrepo.com/svg/240175/on-switch

![image](https://user-images.githubusercontent.com/25790525/175829168-13e3130d-bdca-48f2-8194-41860af258a2.png)

https://www.svgrepo.com/svg/240177/off-switch

![image](https://user-images.githubusercontent.com/25790525/175829199-fabfd7e5-896b-4b62-b33a-a2ef3ac279a7.png)

https://www.svgrepo.com/svg/294669/off-switch

![image](https://user-images.githubusercontent.com/25790525/175829206-ec1827c2-2c12-47dd-9c71-6647cc276f6f.png)

**Comment by wwmm** [comment] 2022-06-26 18:45
>What do you think of these ones?

I think that when it comes to the "enable meaning" in each plugin row the one from Adwaita is better. But in the global bypass button the third icon may be good. We would have to test.

**Comment by Digitalone1** [comment] 2022-06-26 18:47
In the next days I could try to adapt it as a symbolic icon and test it inside the UI.

**Comment by AlexFolland** [comment] 2022-06-26 18:48
If it toggled between the second icon there when enabled and the third icon there when disabled, that would seem intuitive to me.

**Comment by Digitalone1** [comment] 2022-06-26 18:56
@AlexFolland The toggling is difficult to do and requires extra work. Anyway the first thing to do is find a way to adapt the svg code to be like symbolic icons as they have the ability to switch color according to light/dark theme. As they are now, they are only suitable for light theme.

**Comment by wwmm** [comment] 2022-06-26 19:03
>The toggling is difficult to do and requires extra work.

It has the annoyance of requiring some C code so we can change the icon property inside a callback but differently from each plugin `enable` button the one for the global bypass isn't inside a dynamic listview where signal connections have to be bind/unbinded ondemand. I am more concerned about how alternating icons would interact with the dynamic color switching GTK has to do depending on whether the theme is light or dark. I think that the second icon has to much black path in it. Things may look weird  when using a dark theme.

**Comment by Digitalone1** [comment] 2022-06-26 21:29
I was thinking, we want a switch icon for the global bypass. But we could use the switchbutton directly. What do you think?

**Comment by wwmm** [comment] 2022-06-26 21:43
>I was thinking, we want a switch icon for the global bypass. But we could use the switchbutton directly. What do you think?

I am not sure we really want a switch icon. The main problem with the bypass operation is that, in my opinion, its icon has to give the idea that a "default path" where something is flowing will be avoided if you enable the button. It is super hard to pass all this information in an icon. And as much as I like how the GtkSwitch looks it doesn't do all of this too. I think that the crossed paths from the shuffle icon we currently use are closer to this idea than the GtkSwitch shape.

**Comment by AlexFolland** [comment] 2022-06-27 02:10
The end user doesn't have to know anything about it being a pathway of any kind.  To them, it's an on-off switch, and it's useful to present it that way for clarity, since that's exactly how it acts in the user's experience.

**Comment by Digitalone1** [comment] 2022-06-27 06:18
> its icon has to give the idea that a "default path" where something is flowing will be avoided if you enable the button.

For this we can only use the icons with the x inside. Or something like this: https://www.svgrepo.com/svg/159099/switch

**Comment by Digitalone1** [comment] 2022-06-27 07:12
These also give the idea:

https://www.svgrepo.com/svg/103608/plug-in

![image](https://user-images.githubusercontent.com/25790525/175878907-fa9da9a4-3f84-4e64-ab4d-dea38cb00c28.png)

https://www.svgrepo.com/svg/33738/plug-and-plug-connection

![image](https://user-images.githubusercontent.com/25790525/175879066-c787678c-11e2-4255-ae37-c16c4e914d29.png)

> The end user doesn't have to know anything about it being a pathway of any kind. To them, it's an on-off switch, and it's useful to present it that way for clarity, since that's exactly how it acts in the user's experience.

He's right because the bypass is not meant to be an enabled/disabled permanent parameter. It's temporary only for testing purpose. 

At least the global one, because the other on the plugins can be used to disable the effect permanently since it's also stored in the presets now. It's now acting as "load the pipewire filter anyway, even if you don't use it".

But that is not the way the global bypass is working since it's not stored across sessions and if you change the preset it reverts automatically to the disabled state.

The switchbutton might give the idea of something to store until you switch it back, while one of the icons above might be more suitable for a temporary testing purpose.

**Comment by Digitalone1** [comment] 2022-06-27 10:48
I tried some of those icons, but even if I follow the svg style of symbolics icons, they are not visible in the dark theme. Besides In the light theme they seem too little and not quite clear because of the downscaling needed since they are bigger then 16x16 px.

I don't know, until we find a better symbolic icon, the current one might seem the only remaining valid option.

**Comment by Digitalone1** [comment] 2022-06-27 11:09
What do you think of the system log out icon?

![Schermata del 2022-06-27 13-03-50](https://user-images.githubusercontent.com/25790525/175927440-583bcbc8-668d-42e6-8a50-f99e339088cc.png)

![Schermata del 2022-06-27 13-04-27](https://user-images.githubusercontent.com/25790525/175927456-06993763-6370-442d-bbba-702661bff35d.png)

It seems better to me because it cannot be confused with the shutdown and I think it's more appropriate since the shuffle icon is more related to the casual order rather than "bypassing" something.

@wwmm if you want to test, just change the name of the icon to `system-log-out-symbolic`

**Comment by wwmm** [comment] 2022-06-27 11:36
>What do you think of the system log out icon?

It seems fine to me. I think we can use it for a while and see how the public is going to react. As it is just a matter of replacing a string it is easy to make things go back to how they were before if necessary.

**Comment by Digitalone1** [comment] 2022-06-28 07:17
@AlexFolland we are testing the logout icon in place of global bypass now in the master branch.

**Comment by AlexFolland** [comment] 2022-06-28 08:40
Thanks for the mention.  I checked it and while I do see the new icon, it doesn't make much intuitive sense to me for representing a bypass or a toggle switch for enabling or disabling something.  I have a few thoughts about this, which I've written as nested bullet points to elaborate on each.

- If there is an intended analogy the icon's trying to portray, it's not obvious to me.
  - I have some guesses, but they may not match your expectations, and I'm already biased by knowing what the button is meant to do.
- No other GUI elements are affected while the global bypass is disabling the effects.
  - An intuitive way to clarify that might be covering the spectrum visualization region with a crosshatch or something like that and a large centered message saying that EasyEffects is temporarily disabled.
  - Another addition which might be useful would be some red status text somewhere like the bottom-right explaining that EasyEffects is temporarily disabled; just something that draws the eye if the spectrum visualization is disabled.
- The icon doesn't change when it's toggled.
  - Currently I guess it looks like the arrow is going "through", so if the arrow represents the effects being applied or something, the icon turning into an opaque circle (white on a dark theme or black on a light theme) with no arrow would show the arrow being cut off or something like that.
    - With the ability to change an icon, though, a switch element would be better.
- I've come to change my mind and think that the power icon we previously both agreed didn't fit there isn't bad for this case.
  - At least a power icon represents whether the whole program is on or off, since that's the universal meaning of that icon.
  - It would be clearer than this circle with an arrow, at least to me.

**Comment by Digitalone1** [comment] 2022-06-28 12:10
> Thanks for the mention. I checked it and while I do see the new icon, it doesn't make much intuitive sense to me for representing a bypass or a toggle switch for enabling or disabling something. I have a few thoughts about this, which I've written as nested bullet points to elaborate on each.
> 
> * If there is an intended analogy the icon's trying to portray, it's not obvious to me.
>   
>   * I have some guesses, but they may not match your expectations, and I'm already biased by knowing what the button is meant to do.
> * No other GUI elements are affected while the global bypass is disabling the effects.
>   
>   * An intuitive way to clarify that might be covering the spectrum visualization region with a crosshatch or something like that and a large centered message saying that EasyEffects is temporarily disabled.
>   * Another addition which might be useful would be some red status text somewhere like the bottom-right explaining that EasyEffects is temporarily disabled; just something that draws the eye if the spectrum visualization is disabled.
> * The icon doesn't change when it's toggled.
>   
>   * Currently I guess it looks like the arrow is going "through", so if the arrow represents the effects being applied or something, the icon turning into an opaque circle (white on a dark theme or black on a light theme) with no arrow would effectively mean the arrow is blocked, like the effects are not able to come out of the hole and apply to the system.
>     
>     * With the ability to change an icon, though, a switch element would be better.
> * I've come to change my mind and think that the power icon we previously both agreed didn't fit there isn't bad for this case.
>   
>   * At least a power icon represents whether the whole program is on or off, since that's the universal meaning of that icon.
>   * It would be clearer than this circle with an arrow, at least to me.

**Comment by wwmm** [comment] 2022-06-28 12:39
>At least a power icon represents whether the whole program is on or off, since that's the universal meaning of that icon.

What if we changed the global bypass button meaning just like it was done for each plugin button? This way it would be pressed by default and should indicate to new users to that "something is enabled" and that they should pay attention to what it is before changing it's state.

One advantage is that this way we would have the same icon in both places. What should help users to understand what the button does.

**Comment by Digitalone1** [comment] 2022-06-28 12:41
>   * If there is an intended analogy the icon's trying to portray, it's not obvious to me.

Because there's no appropriate icon for it and also the shutdown one is not totally appropriate in my opinion. Anyway there's always the tooltip to suggest the meaning of the control.

> * No other GUI elements are affected while the global bypass is disabling the effects.

This is another problem and might be resolved in a different issue. It's not related only to the global bypass, but also to the preset loading. I tried to show a massage to the user in the case the loading was failed, but there are some limitations in the code that makes this tricky to do. 

It's the same for the global bypass. It would be better to signal it in some other ways to the user, not only hovering the button in the headerbar, but we should discuss how to do it because it's not easy since the window is not always visible. 

>   * Currently I guess it looks like the arrow is going "through", so if the arrow represents the effects being applied or something, the icon turning into an opaque circle (white on a dark theme or black on a light theme) with no arrow would effectively mean the arrow is blocked, like the effects are not able to come out of the hole and apply to the system.

Changing the icon by pressing the button is tricky to do and it's not worth to complicate the code only for the bypass which is a temporary feature. 

I suppose (correct me if I'm wrong) that your point comes from the fact that you think EasyEffects could be disabled. In reality if you want to disable it, just quit its service. The global bypass is meant only for a temporary testing purpose. As I said before, if you apply a preset, it will turn off automatically and its state cannot be saved across sessions. Something like that it's not a real enabled/disabled state.

The bypass/enable control for single effects is different because its state can now be saved across sessions. 

> * I've come to change my mind and think that the power icon we previously both agreed didn't fit there isn't bad for this case.

>   * At least a power icon represents whether the whole program is on or off, since that's the universal meaning of that icon.

The shutdown icon could be confused with the button for quitting the service while the close button means to hide the window only, while the service is still running. 

Already in the past we had some users complaining of the meaning of the close button and they couldn't understand if it was only hiding the window or quitting the service.

**Comment by wwmm** [comment] 2022-06-28 12:59
>The shutdown icon could be confused with the button for quitting the service

I can see some users doing that... EasyEffects just pretends to be a service but that is obviously not easy to know. In my opinion we should keep this button as it is for some time. If people start t ogive a negative feedback we can always go back to the shuffle icon or trying something else. I would not put too much energy at this at this moment.
