### ISSUE TITLE
Permanent hardware damage

### ISSUE THREAD

**Issue by agoodm88** [wwmm/easyeffects#1075] opened 2021-08-06 20:18 UTC
I have a ThinkPad X1 Carbon Gen 9. I installed pulse effects from apt along with presets from here https://github.com/JackHack96/PulseEffects-Presets

I selected convolva and then chose the Dolby Atmos preset. I started playing music on Spotify and turned up the volume a bit. I heard a slight bit of distortion and then one of the speakers on the bottom of the laptop stopped working.  It appears that I pretty much instantly caused permanent damage to my laptop. I've tested the speakers using a live boot disk and they don't work there either.

I didn't see any warnings about hardware damage and honestly thought I'd hear sounds if distress long before anything broke.  So user beware I guess?!

**Comment by wwmm** [comment] 2021-08-06 20:47
Unless the volume has gotten really loud and suddenly I do not see how any audio app could damage the speakers. And even in this case it is hard to do that. In the past both Pulseaudio and PipeWire put my volume to 100 % in a few occasions and even so there was no damage.

**Comment by agoodm88** [comment] 2021-08-06 21:15
Nothing out of the ordinary happened really. I started playing a track on Spotify, turned off the bypass mode (having prev selected option as above) turned the volume up, heard a very slight distortion, noticed the sound went quiet on right hand side. Never recovered.

Speakers have been used a fair bit in the few weeks I've had it, could be coincidence but feels related.

To be clear I'm not blaming, just trying to voice my experience.

**Comment by wwmm** [comment] 2021-08-06 22:53
>To be clear I'm not blaming, just trying to voice my experience.

No problems. If people do not say it we will never know. But it seems a coincidence to me. Just processing the audio won't harm the hardware. At this moment I can only see this happening when amplifying the signal amplitude beyond what the hardware is capable of handling.

**Comment by godsic** [comment] 2021-08-09 09:11
@agoodm88 Among other things, if amplifiers in the laptop are poorly designed and (or) poorly paired to speakers, they might be prone to auto-oscillations at relatively high frequencies. Boosting those frequencies or playing with their phases, e.g., with convolver, might trigger auto-oscillations and make amplifier or speakers burn. If laptop is on warranty, I would suggest you to service it ASAP. 

It might be beneficial in the future to limit bandwidth of your processing chain to say 20-20000 Hz to avoid auto-oscillations and to avoid feeding DC component to your speakers.

**Comment by vchernin** [comment] 2021-08-13 03:16
> It might be beneficial in the future to limit bandwidth of your processing chain to say 20-20000 Hz to avoid auto-oscillations and to avoid feeding DC component to your speakers.

Would it make sense to do this by default? Perhaps if users wanted to go to higher frequencies they'd have to accept a warning/disclaimer. Or is this potential problem not common enough to warrant this?

**Comment by wwmm** [comment] 2021-08-13 03:52
>Would it make sense to do this by default?

Definitely not. First because we have no prove that this was actually the cause of the damage. And I am a little skeptical the such oscillations at the upper side of the band (20000 kHz) would have an amplitude high enough to do damage. Maybe at the lower end where the amplitude is naturally higher.

The other reason is that filters act over a frequency range. Most of the time when you try to cut 20 Hz you may cut a little than that. If it is a problem or not it will depend on how good is the system frequency response as well as the listener ears. So this kind of tradeoff has to be decided by the user.

**Comment by wwmm** [comment] 2021-08-13 04:03
It is possible but through a way different than I initially thought http://margo.student.utwente.nl/el/audio/amphelp.htm
>hi-frequency oscillation - you can't hear it, the scope shows it easily and the amp gets too hot with no signal. The Emitter voltage is not high. Sometimes a hum is heard in the speaker. This problem is much more common than you may think and may destroy the amp and/or the speakers especially the tweeters. This consumes great deal of power that will not make it out to the speakers as music. I have seen 250 watt amps putting a mere 15 watts into the speakers.

I see. It is an indirect process. The high frequency out of the audible range could make the transistors overheat and burn. I can see that being an issue. But it does not justify forcing filtering on everybody. For that to be something to be concerned you have to play audio above the audible range in the first place. What is definitely not the case for most people. And we still have no prove that this is what happened.

**Comment by wwmm** [comment] 2021-08-13 04:19
Another possible explanation https://ledgernote.com/columns/studio-recording/audio-clipping/

>If you allow your speakers to clip long enough, they can experience overheating and damage to the coils. Because the woofers vibrate to reproduce sound, the clipped off portions can cause a jarring movement that can ultimately rip the fabric of the cone or tear it away from the sides.

Clipping is something reasonably common and could also explain the distortion he reported. But filtering isn't the way to deal with this. Usually this happens when too much amplification is done to the signal. What does not seem to have been the case.

**Comment by agoodm88** [comment] 2021-08-13 09:11
Any distortion I heard was extremely slight and immediately before the speaker stopped working.  Most people would not have noticed that level of distortion in my opinion.  Volume at that point likely set somewhere around 80%.

Lenovo sent an engineer out who replaced all of the speakers in the laptop which has resolved my issue.  Hopefully understandably I am not interested in testing out if your software causes the problem to recurr.

**Comment by wwmm** [comment] 2021-08-13 14:01
Ok. As it is something we do not know the exact cause and for obvious reasons we do not want to reproduce I will close this issue.

**Closed by wwmm** 2021-08-13 14:01 UTC

**Comment by grapewheel** [comment] 2022-10-18 02:22
@agoodm88 Yes, it was indeed harmed the hardware! When I used the easy effect to listen the music through the blue tooth, It burned my blue tooth module which plugin in the board~ Linux control the hardware easily, but also danger, maybe the app let the temperature fast up and burned the hardware!

**Comment by GrabbenD** [comment] 2025-04-06 11:13
Sounds like certain Filters have the potential to damage the speakers as outlined in this guide:

https://forum.manjaro.org/t/how-to-make-linux-sound-great/146143

> _*Remember, set you Frequency to no lower than what your speakers can handle. If you can find the specs on your speakers, you will find the frequency response range, something like 175-20K or something like that. That means setting your frequency below 175 is pointless and can actually damage your speakers_

Safety Guard feature to lock such settings behind Advanced dropdown could mitigate this

**Comment by wwmm** [comment] 2025-04-06 15:00
>Sounds like certain Filters have the potential to damage the speakers as outlined in this guide:

Although I agree this is a good thing to do I have never seen a hardware damaged by this. The most likely outcome is the speakers underperforming because frequencies it can't handle are also present in the signal.

>Safety Guard feature to lock such settings behind Advanced dropdown could mitigate this

In my opinion this is one of those things users have to handle on their own. Different hardware will have difference frequency response ranges. And in some cases the manufacture may not make it easy to get this information. So having a dedicated control in EasyEffects for this may not be that effective. It may even make things worse if the user enables this without knowing the proper range.

Another point is that different filters also have different frequency responses and the user has to be aware of this. So it is best that they set this themselves using something like the filter plugin for example:

![Image](https://github.com/user-attachments/assets/6a4552b4-2dd5-42c8-bbe7-6ee57e17cd46)
