### ISSUE TITLE
Global latency not always updated

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1491] opened 2022-04-22 18:55 UTC
Recently I noticed that the latency value in the bottom bar is not always updated and `0.0 ms` is reported. This happens usually when the window is opened for the first time while a stream is reproducing. But not always, sometimes it's shown correctly. It does not happen instead when Easyeffects window is first opened and then a stream is reproduced.

Any idea why this is occurring and how to show it always updated?

**Comment by wwmm** [comment] 2022-04-22 22:48
>Any idea why this is occurring and how to show it always updated?

Maybe the value is only being updated in the window when `broadcast_pipeline_latency` is called inside `effects_base.cpp`. I would have to take a look at it. But at I haven't noticed this problem on my side yet.

Are the plugins always the same? As only the latency of the filters is shown and some of them do not add latency or do not add for all combination of parameters maybe the latency was actually zero.

**Comment by wwmm** [comment] 2022-04-23 14:40
Totally by chance I saw the bug happening now. I think the problem is that the latency value isn't saved anywhere. If the window is opened at the moment a broadcast is done it gets the value. But if it isn't the displayed value will be zero until a plugin broadcast a new latency value...

**Comment by wwmm** [comment] 2022-04-23 14:43
A possible solution would be to force a call to `broadcast_pipeline_latency` when the window is opened.

**Comment by wwmm** [comment] 2022-04-23 14:50
>A possible solution would be to force a call to broadcast_pipeline_latency when the window is opened.

Maybe not. In a way this is already done https://github.com/wwmm/easyeffects/blob/fe264ef309ab7bf7a4e840d7d509f061576c91ec/src/effects_box.cpp#L422. I wonder why the call to `get_pipeline_latency` is returning zero...

**Comment by wwmm** [comment] 2022-04-23 14:52
With the call to `get_pipeline_latency` there should be no need to save the latency value in a variable and it probably won't fix the problem. I think that its source is more subtle than I initially thought. The plugin may not be emitting the latency signal in some situations...

**Comment by wwmm** [comment] 2022-04-23 14:59
>The plugins may not be emitting the latency signal in some situations...

No. They are. In the logs I see
```
soe: limiter latency: 0.004988662 s
```
And we still have zero in the window. And to make things even more weird the a call to
```
util::warning(util::to_string(self->data->effects_base->get_pipeline_latency()));
```
inside `effects_box.cpp` returns
```
easyeffects-WARNING **: 11:56:47.601: 0.022675736
```
Could it be the string formatting the source of the problem? Strange...

**Comment by wwmm** [comment] 2022-04-23 15:05
Oh... Now I see what is happening :smile: 

The code for the string formatting is right. The problem is that the value returned by `get_pipeline_latency` is in seconds but the intention is to show in `ms`. Without multiplying the value by 1000 is is going ot be out of scale and all that is shown is zero :smile:

**Comment by wwmm** [comment] 2022-04-23 15:16
The latest code in the master branch fixes the problem I described above. But I see there is another thing that can make a wrong value to be displayed. Adding or removing plugins can make the value to go to zero again... This may have a totally different source...

**Comment by wwmm** [comment] 2022-04-23 15:22
>This may have a totally different source...

There was another place where the value also had to be multiplied by 1000. Master branch updated again. It is almost 100% fixed now. The only situation left is the one where the `limiter` latency may be ignore in the total calculation when the plugins list is changed. I do not know why yet.

**Comment by wwmm** [comment] 2022-04-23 15:27
Weird... Now I see `get_pipeline_latency` has `return total * 1000.0F;`. There should have been no need to multiply by 1000 somewhere else. I am starting to think something weird may be happening with the locale handling...

**Comment by Digitalone1** [comment] 2022-04-23 15:37
Is this happening also with the latest release? If not it's definitely something related to locale or string format. 

Try to set an empty string as default value to see if `util::to_string` is failing to convert the number.

**Comment by wwmm** [comment] 2022-04-23 15:42
>If not it's definitely something related to locale or string format.

I think an unfortunate chain of events led me to believe it was a locale problem. But what is really happening is that although the limiter emits the signal with its latency sometimes it does that before we have time to connect to this signal. That is the real reason why sometimes we have zero in the output of `get_pipeline_latency` even if the limiter has 5 ms latency. When I multiplied by 1000 on top of the other multiplication What I really was seeing was the much lower latency of the crystalizer plugin...

**Comment by wwmm** [comment] 2022-04-23 15:49
I think we will need a public getter for the latency in the plugins code. And the one inside `get_pipeline_latency` will have to iterate over the plugins to get the more recent value.

**Comment by wwmm** [comment] 2022-04-23 16:23
I have updated the master branch again. Now we use a public getter to get the most recent latency value from the plugins whenever they are needed. I think that now the problem is gone :smile:

**Closed** 2022-04-29 10:17 UTC
Labels: EasyEffects Bug
