### ISSUE TITLE
pulseaudio -k breaks pulseeffects

### ISSUE THREAD

**Issue by Thinkaboutmin** [wwmm/easyeffects#708] opened 2020-06-14 18:49 UTC
Well, the issue that I'm having is the breakage of pulseeffects whenever I kill pulseaudio with it open. Maybe that's expected, but, can't it identify that the stream stopped(or failed?) and re-fetch all the data to keep it working? As of now the only way to make it work is to kill it and then re-open it.

Journalctl log:

```
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: pulse_manager:  failed to get sink info: bluez_sink.00_14_BE_00_B2_9D.a2dp_sink
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: pulse_manager:  failed to get sink info: bluez_sink.00_14_BE_00_B2_9D.a2dp_sink
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band9-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band8-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band7-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band6-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band5-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band4-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band3-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band2-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band1-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band0-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band9-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band8-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band7-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band6-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band5-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band4-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band3-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band2-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band1-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band0-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'knee' in schema 'com.github.wwmm.pulseeffects.sinkinputs.compressor' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band9-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band8-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band7-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band6-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band5-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band4-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band3-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band2-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band1-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band0-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.rightchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band9-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band8-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band7-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band6-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band5-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band4-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band3-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band2-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band1-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:58 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'band0-type' in schema 'com.github.wwmm.pulseeffects.sinkinputs.equalizer.leftchannel' is outside of valid range
jun 14 15:24:57 Staggering-pc pulseeffects[17037]: g_settings_set_value: value for key 'knee' in schema 'com.github.wwmm.pulseeffects.sinkinputs.compressor' is outside of valid range
jun 14 15:24:56 Staggering-pc pulseeffects[17037]: pulse_manager:  failed to get sink info: bluez_sink.00_14_BE_00_B2_9D.a2dp_sink
jun 14 15:24:56 Staggering-pc pulseeffects[17037]: pulse_manager:  failed to get sink info: bluez_sink.00_14_BE_00_B2_9D.a2dp_sink
jun 14 15:24:53 Staggering-pc pulseeffects[17037]: pulse_manager:  failed to find sources
jun 14 15:24:53 Staggering-pc pulseeffects[17037]: pulse_manager:  failed to find sinks
jun 14 15:24:53 Staggering-pc pulseeffects[17037]: pulse_manager:  failed to find source outputs
jun 14 15:24:53 Staggering-pc pulseeffects[17037]: pulse_manager:  failed to find sink inputs
jun 14 15:24:53 Staggering-pc pulseeffects[17037]: pulse_manager:  failed to get sink info: bluez_sink.00_14_BE_00_B2_9D.a2dp_sink
```
The debug variable dumps the following:

```
(process:53710): pulseeffects-DEBUG: 15:23:04.161: main: locale directory: /usr/share/locale
(pulseeffects:53710): pulseeffects-DEBUG: 15:23:04.211: presets_manager: user presets directory already exists: /home/jomar/.config/PulseEffects
(pulseeffects:53710): pulseeffects-DEBUG: 15:23:04.211: presets_manager: user presets directory already exists: /home/jomar/.config/PulseEffects/input
(pulseeffects:53710): pulseeffects-DEBUG: 15:23:04.211: presets_manager: user presets directory already exists: /home/jomar/.config/PulseEffects/output
(pulseeffects:53710): pulseeffects-DEBUG: 15:23:04.211: presets_manager: user presets directory already exists: /home/jomar/.config/PulseEffects/autoload
(pulseeffects:53710): pulseeffects-DEBUG: 15:23:04.867: application:  destroyed
(pulseeffects:53710): pulseeffects-DEBUG: 15:23:04.867: presets_manager: destroyed
```

And what happens on the graphical interface after killing (pulseeffects was in background)
![PulseEffects](https://user-images.githubusercontent.com/19597109/84601186-d1e2a980-ae54-11ea-8c1c-819b20730a29.png)

The same (although the waves and other thing will be there) happens with it open.

I hope that's something that can be tickled although there's no problem if it's not doable, it may not be, really, an issue after all but rather the expected... Thanks!

My distro: Manjaro
Kernel: 5.7 (latest and greatest of it)
Pulseaudio: 13.0
Pulseeffects: 4.7.2

**Comment by wwmm** [comment] 2020-06-15 14:12
This is something that has to be improved someday. Pavucontrol is able to "restart itself" when Pulseaudio dies but PulseEffects isn't. It is doable but it will require a a clever code rewrite. The problem is that a few PulseEffects sections related to Pulseaudio are initialized only when PulseEffects starts. So we have to refactor our code in a way that these operations are distributed in functions that can be called when Pulseaudio is back online.

Let's keep this open for a while. Maybe when the time to move to GTK4 comes I will finally have the  courage to do this.

**Comment by Thinkaboutmin** [comment] 2020-06-15 16:29
Cool! I look forward for it :)

**Comment by nik-gnomic** [comment] 2020-07-20 07:06
`pulseaudio -k` can have a number of adverse effects if used on a systemd OS
pulseaudio is capable of respawning if killed, but the systemd pulseaudio.service fails
see `systemctl --user status pulseaudio.service pulseaudio.socket`
any modules loaded at system boot by 'pulseaudio-start-x11' will not be present
(module-x11-publish, module-x11-xsmp and also on KDE module-device-manager)
and sinks sources may be suspended
(see `pacmd dump`)
use command `systemctl --user restart pulseaudio` for pulseaudio to restart in unaltered state

**Comment by Thinkaboutmin** [comment] 2020-07-20 17:44
Hey @nik-gnomic that's nice to now, I wasn't aware that stopping the Pulseaudio with the -k flag would disrupt the systemd service although it doesn't change the fact that it still stops PulseEffects.

**Comment by wwmm** [comment] 2023-03-01 22:04
As there is already one for PipeWire #1447 it is better to close this issue

**Closed by wwmm** 2023-03-01 22:04 UTC
Labels: enhancement
