### ISSUE TITLE
Weird popup menu glitch when using on kde

### ISSUE THREAD

**Issue by nitanmarcel** [wwmm/easyeffects#1996] opened 2022-11-18 14:33 UTC
### EasyEffects Version

7.0.0

### What package are you using?

Flatpak (Flathub)

### Distribution

FerrenOS (Ubuntu 20.04)

### Describe the bug

When using some menus, like loading some presets, accessing the settings menu, the popup menu gets glitched out with weird artifacts that reasambles a broken display (as seen bellow)

![image](https://user-images.githubusercontent.com/41646249/202728031-e0271b35-47b7-46b0-af65-e5f6b4c761f0.png)

### Debug Log

<details><summary>Debug Log (if it helps with something)</summary><br/>

```
You have PipeWire 0.3.60 installed
This is newer or the same as PipeWire 0.3.41 required to run Easy Effects
(process:2): easyeffects-DEBUG: 16:31:50.311:   easyeffects.cpp:35      easyeffects version: 7.0.0
(process:2): easyeffects-DEBUG: 16:31:50.313:   easyeffects.cpp:45      locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 16:31:50.325:       presets_manager.cpp:49  system input presets directory: "/app/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 16:31:50.325:       presets_manager.cpp:49  system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 16:31:50.325:       presets_manager.cpp:49  system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 16:31:50.325:       presets_manager.cpp:52  system output presets directory: "/app/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 16:31:50.325:       presets_manager.cpp:52  system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 16:31:50.325:       presets_manager.cpp:52  system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 16:31:50.325:       presets_manager.cpp:194 user presets directory already exists: /home/nitanmarcel/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 16:31:50.325:       presets_manager.cpp:194 user presets directory already exists: /home/nitanmarcel/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 16:31:50.325:       presets_manager.cpp:194 user presets directory already exists: /home/nitanmarcel/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 16:31:50.325:       presets_manager.cpp:194 user presets directory already exists: /home/nitanmarcel/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 16:31:50.325:       presets_manager.cpp:194 user presets directory already exists: /home/nitanmarcel/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
(easyeffects:2): easyeffects-DEBUG: 16:31:50.671:       pipe_manager.cpp:1426   compiled with PipeWire: 0.3.41
(easyeffects:2): easyeffects-DEBUG: 16:31:50.671:       pipe_manager.cpp:1427   linked to PipeWire: 0.3.41
(easyeffects:2): easyeffects-DEBUG: 16:31:50.674:       pipe_manager.cpp:1397   core version: 0.3.60
(easyeffects:2): easyeffects-DEBUG: 16:31:50.674:       pipe_manager.cpp:1398   core name: pipewire-0
(easyeffects:2): easyeffects-DEBUG: 16:31:50.676:       pipe_manager.cpp:1311   found metadata: settings
(easyeffects:2): easyeffects-DEBUG: 16:31:50.676:       pipe_manager.cpp:1311   found metadata: default
(easyeffects:2): easyeffects-DEBUG: 16:31:50.676:       pipe_manager.cpp:1311   found metadata: route-settings
(easyeffects:2): easyeffects-DEBUG: 16:31:50.676:       pipe_manager.cpp:1166   Audio/Sink 48 alsa_output.pci-0000_05_00.6.analog-stereo with serial 49 has been added
(easyeffects:2): easyeffects-DEBUG: 16:31:50.676:       pipe_manager.cpp:1166   Audio/Source 49 alsa_input.pci-0000_05_00.6.analog-stereo with serial 50 has been added
(easyeffects:2): easyeffects-DEBUG: 16:31:50.677:       pipe_manager.cpp:1166   Audio/Sink 58 easyeffects_sink with serial 518 has been added
(easyeffects:2): easyeffects-DEBUG: 16:31:50.677:       pipe_manager.cpp:1166   Audio/Source/Virtual 64 easyeffects_source with serial 519 has been added
(easyeffects:2): easyeffects-DEBUG: 16:31:50.678:       pipe_manager.cpp:1517   easyeffects_sink node successfully retrieved with id 58 and serial 518
(easyeffects:2): easyeffects-DEBUG: 16:31:50.678:       pipe_manager.cpp:1522   easyeffects_source node successfully retrieved with id 64 and serial 519
(easyeffects:2): easyeffects-DEBUG: 16:31:50.678:       pipe_manager.cpp:899    new metadata property: 0, default.configured.audio.source, Spa:String:JSON, { "name": "alsa_input.pci-0000_05_00.6.analog-stereo" }
(easyeffects:2): easyeffects-DEBUG: 16:31:50.678:       pipe_manager.cpp:899    new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_05_00.6.analog-stereo" }
(easyeffects:2): easyeffects-DEBUG: 16:31:50.678:       pipe_manager.cpp:899    new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_05_00.6.analog-stereo" }
(easyeffects:2): easyeffects-DEBUG: 16:31:50.678:       pipe_manager.cpp:899    new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "alsa_input.pci-0000_05_00.6.analog-stereo" }
(easyeffects:2): easyeffects-DEBUG: 16:31:50.678:       pipe_manager.cpp:899    new metadata property: 0, default.video.source, Spa:String:JSON, { "name": "v4l2_input.pci-0000_05_00.4-usb-0_1_1.0" }
(easyeffects:2): easyeffects-DEBUG: 16:31:50.684:       plugin_base.cpp:289     soe: output_level successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.686:       plugin_base.cpp:289     soe: spectrum successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.693:       plugin_base.cpp:289     sie: output_level successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.695:       plugin_base.cpp:289     sie: spectrum successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.731:       lv2_wrapper.cpp:98      http://lsp-plug.in/plugins/lv2/sc_gate_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 16:31:50.762:       lv2_wrapper.cpp:98      http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 16:31:50.819:       rnnoise.cpp:261 sie: rnnoise using the standard model.
(easyeffects:2): easyeffects-DEBUG: 16:31:50.849:       lv2_wrapper.cpp:98      http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 16:31:50.852:       plugin_base.cpp:289     sie: gate successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.852:       pipe_manager.cpp:1206   alsa_input.pci-0000_05_00.6.analog-stereo port 52 is connected to ee_sie_gate port 147
(easyeffects:2): easyeffects-DEBUG: 16:31:50.853:       pipe_manager.cpp:1206   alsa_input.pci-0000_05_00.6.analog-stereo port 53 is connected to ee_sie_gate port 112
(easyeffects:2): easyeffects-DEBUG: 16:31:50.856:       plugin_base.cpp:289     sie: compressor successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.856:       pipe_manager.cpp:1206   ee_sie_gate port 138 is connected to ee_sie_compressor port 132
(easyeffects:2): easyeffects-DEBUG: 16:31:50.857:       pipe_manager.cpp:1206   ee_sie_gate port 146 is connected to ee_sie_compressor port 113
(easyeffects:2): easyeffects-DEBUG: 16:31:50.860:       plugin_base.cpp:289     sie: filter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.860:       pipe_manager.cpp:1206   ee_sie_compressor port 120 is connected to ee_sie_filter port 122
(easyeffects:2): easyeffects-DEBUG: 16:31:50.860:       pipe_manager.cpp:1206   ee_sie_compressor port 130 is connected to ee_sie_filter port 141
(easyeffects:2): easyeffects-DEBUG: 16:31:50.863:       plugin_base.cpp:289     sie: deesser successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.863:       pipe_manager.cpp:1206   ee_sie_filter port 78 is connected to ee_sie_deesser port 96
(easyeffects:2): easyeffects-DEBUG: 16:31:50.864:       pipe_manager.cpp:1206   ee_sie_filter port 79 is connected to ee_sie_deesser port 117
(easyeffects:2): easyeffects-DEBUG: 16:31:50.866:       plugin_base.cpp:289     sie: rnnoise successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.867:       pipe_manager.cpp:1206   ee_sie_deesser port 111 is connected to ee_sie_rnnoise port 136
(easyeffects:2): easyeffects-DEBUG: 16:31:50.867:       pipe_manager.cpp:1206   ee_sie_deesser port 139 is connected to ee_sie_rnnoise port 82
(easyeffects:2): easyeffects-DEBUG: 16:31:50.870:       plugin_base.cpp:289     sie: limiter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.871:       pipe_manager.cpp:1206   ee_sie_rnnoise port 119 is connected to ee_sie_limiter port 123
(easyeffects:2): easyeffects-DEBUG: 16:31:50.872:       pipe_manager.cpp:1206   ee_sie_rnnoise port 137 is connected to ee_sie_limiter port 97
(easyeffects:2): easyeffects-DEBUG: 16:31:50.879:       stream_input_effects.cpp:320    disconnecting the compressor filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:50.881:       pipe_manager.cpp:212     110 ee_sie_compressor has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:50.881:       stream_input_effects.cpp:320    disconnecting the deesser filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:50.882:       pipe_manager.cpp:212     127 ee_sie_deesser has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:50.882:       stream_input_effects.cpp:320    disconnecting the filter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:50.882:       pipe_manager.cpp:212     83 ee_sie_filter has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:50.883:       stream_input_effects.cpp:320    disconnecting the gate filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:50.884:       pipe_manager.cpp:212     81 ee_sie_gate has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:50.884:       stream_input_effects.cpp:320    disconnecting the limiter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:50.885:       pipe_manager.cpp:212     118 ee_sie_limiter has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:50.885:       stream_input_effects.cpp:320    disconnecting the rnnoise filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:50.885:       pipe_manager.cpp:212     116 ee_sie_rnnoise has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:50.890:       plugin_base.cpp:289     sie: gate successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.890:       pipe_manager.cpp:1206   alsa_input.pci-0000_05_00.6.analog-stereo port 52 is connected to ee_sie_gate port 89
(easyeffects:2): easyeffects-DEBUG: 16:31:50.890:       pipe_manager.cpp:1206   alsa_input.pci-0000_05_00.6.analog-stereo port 53 is connected to ee_sie_gate port 88
(easyeffects:2): easyeffects-DEBUG: 16:31:50.893:       plugin_base.cpp:289     sie: compressor successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.894:       pipe_manager.cpp:1206   ee_sie_gate port 137 is connected to ee_sie_compressor port 108
(easyeffects:2): easyeffects-DEBUG: 16:31:50.894:       pipe_manager.cpp:1206   ee_sie_gate port 119 is connected to ee_sie_compressor port 126
(easyeffects:2): easyeffects-DEBUG: 16:31:50.897:       plugin_base.cpp:289     sie: filter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.897:       pipe_manager.cpp:1206   ee_sie_compressor port 121 is connected to ee_sie_filter port 115
(easyeffects:2): easyeffects-DEBUG: 16:31:50.897:       pipe_manager.cpp:1206   ee_sie_compressor port 99 is connected to ee_sie_filter port 81
(easyeffects:2): easyeffects-DEBUG: 16:31:50.900:       plugin_base.cpp:289     sie: deesser successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.901:       pipe_manager.cpp:1206   ee_sie_filter port 146 is connected to ee_sie_deesser port 131
(easyeffects:2): easyeffects-DEBUG: 16:31:50.901:       pipe_manager.cpp:1206   ee_sie_filter port 138 is connected to ee_sie_deesser port 147
(easyeffects:2): easyeffects-DEBUG: 16:31:50.904:       plugin_base.cpp:289     sie: rnnoise successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.904:       pipe_manager.cpp:1206   ee_sie_deesser port 107 is connected to ee_sie_rnnoise port 122
(easyeffects:2): easyeffects-DEBUG: 16:31:50.905:       pipe_manager.cpp:1206   ee_sie_deesser port 83 is connected to ee_sie_rnnoise port 127
(easyeffects:2): easyeffects-DEBUG: 16:31:50.908:       plugin_base.cpp:289     sie: limiter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:50.908:       pipe_manager.cpp:1206   ee_sie_rnnoise port 139 is connected to ee_sie_limiter port 134
(easyeffects:2): easyeffects-DEBUG: 16:31:50.909:       pipe_manager.cpp:1206   ee_sie_rnnoise port 94 is connected to ee_sie_limiter port 96
easyeffects-INFO: 16:31:50.912:         application.cpp:49      disabling global bypass
(easyeffects:2): easyeffects-DEBUG: 16:31:50.921:       application_ui.cpp:85   Icon Theme Inspire Dark detected
(easyeffects:2): easyeffects-DEBUG: 16:31:51.260:       rnnoise_ui.cpp:377      model directory already exists: /home/nitanmarcel/.var/app/com.github.wwmm.easyeffects/config/easyeffects/rnnoise
(easyeffects:2): easyeffects-DEBUG: 16:31:51.649:       stream_input_effects.cpp:320    disconnecting the compressor filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.651:       pipe_manager.cpp:212     118 ee_sie_compressor has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.652:       stream_input_effects.cpp:320    disconnecting the deesser filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.654:       pipe_manager.cpp:212     112 ee_sie_deesser has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.655:       stream_input_effects.cpp:320    disconnecting the filter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.656:       pipe_manager.cpp:212     123 ee_sie_filter has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.656:       stream_input_effects.cpp:320    disconnecting the gate filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.657:       pipe_manager.cpp:212     140 ee_sie_gate has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.658:       stream_input_effects.cpp:320    disconnecting the limiter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.660:       pipe_manager.cpp:212     117 ee_sie_limiter has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.660:       stream_input_effects.cpp:320    disconnecting the rnnoise filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.661:       pipe_manager.cpp:212     141 ee_sie_rnnoise has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.668:       plugin_base.cpp:289     sie: gate successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.668:       pipe_manager.cpp:1206   alsa_input.pci-0000_05_00.6.analog-stereo port 52 is connected to ee_sie_gate port 132
(easyeffects:2): easyeffects-DEBUG: 16:31:51.670:       pipe_manager.cpp:1206   alsa_input.pci-0000_05_00.6.analog-stereo port 53 is connected to ee_sie_gate port 113
(easyeffects:2): easyeffects-DEBUG: 16:31:51.673:       plugin_base.cpp:289     sie: compressor successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.674:       pipe_manager.cpp:1206   ee_sie_gate port 94 is connected to ee_sie_compressor port 104
(easyeffects:2): easyeffects-DEBUG: 16:31:51.675:       pipe_manager.cpp:1206   ee_sie_gate port 139 is connected to ee_sie_compressor port 124
(easyeffects:2): easyeffects-DEBUG: 16:31:51.678:       plugin_base.cpp:289     sie: filter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.679:       pipe_manager.cpp:1206   ee_sie_compressor port 110 is connected to ee_sie_filter port 120
(easyeffects:2): easyeffects-DEBUG: 16:31:51.680:       pipe_manager.cpp:1206   ee_sie_compressor port 105 is connected to ee_sie_filter port 140
(easyeffects:2): easyeffects-DEBUG: 16:31:51.683:       plugin_base.cpp:289     sie: deesser successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.683:       pipe_manager.cpp:1206   ee_sie_filter port 119 is connected to ee_sie_deesser port 136
(easyeffects:2): easyeffects-DEBUG: 16:31:51.685:       pipe_manager.cpp:1206   ee_sie_filter port 137 is connected to ee_sie_deesser port 89
(easyeffects:2): easyeffects-DEBUG: 16:31:51.689:       plugin_base.cpp:289     sie: rnnoise successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.690:       pipe_manager.cpp:1206   ee_sie_deesser port 82 is connected to ee_sie_rnnoise port 115
(easyeffects:2): easyeffects-DEBUG: 16:31:51.692:       pipe_manager.cpp:1206   ee_sie_deesser port 123 is connected to ee_sie_rnnoise port 112
(easyeffects:2): easyeffects-DEBUG: 16:31:51.695:       plugin_base.cpp:289     sie: limiter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.695:       pipe_manager.cpp:1206   ee_sie_rnnoise port 83 is connected to ee_sie_limiter port 78
(easyeffects:2): easyeffects-DEBUG: 16:31:51.696:       pipe_manager.cpp:1206   ee_sie_rnnoise port 128 is connected to ee_sie_limiter port 131
(easyeffects:2): easyeffects-DEBUG: 16:31:51.701:       application.cpp:77      new default output device: alsa_output.pci-0000_05_00.6.analog-stereo
(easyeffects:2): easyeffects-DEBUG: 16:31:51.707:       application.cpp:85      new default input device: alsa_input.pci-0000_05_00.6.analog-stereo
(easyeffects:2): easyeffects-DEBUG: 16:31:51.708:       stream_input_effects.cpp:320    disconnecting the compressor filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.709:       pipe_manager.cpp:212     117 ee_sie_compressor has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.709:       stream_input_effects.cpp:320    disconnecting the deesser filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.710:       pipe_manager.cpp:212     88 ee_sie_deesser has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.710:       stream_input_effects.cpp:320    disconnecting the filter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.711:       pipe_manager.cpp:212     134 ee_sie_filter has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.711:       stream_input_effects.cpp:320    disconnecting the gate filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.712:       pipe_manager.cpp:212     135 ee_sie_gate has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.712:       stream_input_effects.cpp:320    disconnecting the limiter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.713:       pipe_manager.cpp:212     147 ee_sie_limiter has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.713:       stream_input_effects.cpp:320    disconnecting the rnnoise filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:31:51.713:       pipe_manager.cpp:212     81 ee_sie_rnnoise has been removed
(easyeffects:2): easyeffects-DEBUG: 16:31:51.717:       plugin_base.cpp:289     sie: gate successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.718:       pipe_manager.cpp:1206   alsa_input.pci-0000_05_00.6.analog-stereo port 52 is connected to ee_sie_gate port 114
(easyeffects:2): easyeffects-DEBUG: 16:31:51.718:       pipe_manager.cpp:1206   alsa_input.pci-0000_05_00.6.analog-stereo port 53 is connected to ee_sie_gate port 108
(easyeffects:2): easyeffects-DEBUG: 16:31:51.721:       plugin_base.cpp:289     sie: compressor successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.721:       pipe_manager.cpp:1206   ee_sie_gate port 128 is connected to ee_sie_compressor port 80
(easyeffects:2): easyeffects-DEBUG: 16:31:51.722:       pipe_manager.cpp:1206   ee_sie_gate port 83 is connected to ee_sie_compressor port 95
(easyeffects:2): easyeffects-DEBUG: 16:31:51.724:       plugin_base.cpp:289     sie: filter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.724:       pipe_manager.cpp:1206   ee_sie_compressor port 118 is connected to ee_sie_filter port 121
(easyeffects:2): easyeffects-DEBUG: 16:31:51.725:       pipe_manager.cpp:1206   ee_sie_compressor port 79 is connected to ee_sie_filter port 135
(easyeffects:2): easyeffects-DEBUG: 16:31:51.727:       plugin_base.cpp:289     sie: deesser successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.728:       pipe_manager.cpp:1206   ee_sie_filter port 139 is connected to ee_sie_deesser port 122
(easyeffects:2): easyeffects-DEBUG: 16:31:51.728:       pipe_manager.cpp:1206   ee_sie_filter port 94 is connected to ee_sie_deesser port 132
(easyeffects:2): easyeffects-DEBUG: 16:31:51.730:       plugin_base.cpp:289     sie: rnnoise successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.731:       pipe_manager.cpp:1206   ee_sie_deesser port 127 is connected to ee_sie_rnnoise port 120
(easyeffects:2): easyeffects-DEBUG: 16:31:51.731:       pipe_manager.cpp:1206   ee_sie_deesser port 134 is connected to ee_sie_rnnoise port 88
(easyeffects:2): easyeffects-DEBUG: 16:31:51.734:       plugin_base.cpp:289     sie: limiter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 16:31:51.735:       pipe_manager.cpp:1206   ee_sie_rnnoise port 123 is connected to ee_sie_limiter port 146
(easyeffects:2): easyeffects-DEBUG: 16:31:51.736:       pipe_manager.cpp:1206   ee_sie_rnnoise port 111 is connected to ee_sie_limiter port 136
(easyeffects:2): easyeffects-DEBUG: 16:31:51.741:       application.cpp:97      device alsa_card.pci-0000_05_00.6 has changed its input route to: analog-input-internal-mic
(easyeffects:2): easyeffects-DEBUG: 16:31:51.741:       application.cpp:129     device alsa_card.pci-0000_05_00.6 has changed its output route to: analog-output-speaker
(easyeffects:2): easyeffects-DEBUG: 16:32:02.109:       stream_output_effects.cpp:165   No app linked to our device wants to play. Unlinking our filters.
(easyeffects:2): easyeffects-DEBUG: 16:32:02.112:       stream_input_effects.cpp:169    No app linked to our device wants to play. Unlinking our filters.
(easyeffects:2): easyeffects-DEBUG: 16:32:02.112:       stream_input_effects.cpp:320    disconnecting the compressor filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:32:02.114:       pipe_manager.cpp:212     147 ee_sie_compressor has been removed
(easyeffects:2): easyeffects-DEBUG: 16:32:02.114:       stream_input_effects.cpp:320    disconnecting the deesser filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:32:02.116:       pipe_manager.cpp:212     113 ee_sie_deesser has been removed
(easyeffects:2): easyeffects-DEBUG: 16:32:02.116:       stream_input_effects.cpp:320    disconnecting the filter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:32:02.117:       pipe_manager.cpp:212     78 ee_sie_filter has been removed
(easyeffects:2): easyeffects-DEBUG: 16:32:02.117:       stream_input_effects.cpp:320    disconnecting the gate filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:32:02.118:       pipe_manager.cpp:212     126 ee_sie_gate has been removed
(easyeffects:2): easyeffects-DEBUG: 16:32:02.118:       stream_input_effects.cpp:320    disconnecting the limiter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:32:02.119:       pipe_manager.cpp:212     89 ee_sie_limiter has been removed
(easyeffects:2): easyeffects-DEBUG: 16:32:02.119:       stream_input_effects.cpp:320    disconnecting the rnnoise filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 16:32:02.119:       pipe_manager.cpp:212     140 ee_sie_rnnoise has been removed

```
</details>

**Comment by wwmm** [comment] 2022-11-18 14:55
This kind of problem happend at a lower level. Either in gtk4, the GPU driver or kde. It can't be fixed on our side.

**Comment by violetmage** [comment] 2023-03-02 04:45
@wwmm close this issue?

**Comment by wwmm** [comment] 2023-03-02 05:18
>close this issue?

Yes. I do not see how something like this could be caused by EasyEffects code.

**Closed by wwmm** 2023-03-02 05:18 UTC
