### ISSUE TITLE
Processing stops on window close

### ISSUE THREAD

**Issue by Taihouu** [wwmm/easyeffects#1215] opened 2021-10-16 16:35 UTC
### EasyEffects Version

6.1.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Arch Linux

### Describe the bug

Easyeffects stops processing when the window is closed. Launching it from the terminal the process stops the second the window is closed. I've tried both the AUR and Flatpak versions with the same result. I've also had the same result across EndeavourOS and Arch. 

I have it set to process all out/inputs and have _not_ set it to shutdown on window close. 

### Expected Behavior

Continuous processing.

**Comment by wwmm** [comment] 2021-10-18 17:34
>Adding easyeffects & to the WMs autostart scripts starts the GUI (how do I start it as a bg service?) at which point it does process audio, but I want it to run in the background.

What our autostart file does is executing `easyeffects --gapplication-service` in the login. If you click on easyeffects icon or run `easyeffects` in a terminal while `easyeffects --gapplication-service` is running you can close its window without loosing the effects.

**Comment by Taihouu** [comment] 2021-10-18 20:26
So I added `easyeffects --gapplication-service` to the Openbox autostart script which made no difference. It does not process until I open the GUI and when I close it processing stops. Cannot find the process with `pgrep easyeffects` when the GUI is closed, so it doesn't seem to be running at all.

**Comment by wwmm** [comment] 2021-10-18 22:10
>but perhaps it is still worth looking into as the toggle is still broken/not respected.

The problem is that it does not look like I can fix this on my side. From the applications point of view all we have to do is creating the autostart file inside `~/.config/autostart/`. All the rest is done by the desktop environment. Same thing for the dbus feature we use to make EasyEffects start as service when the user clicks on our icon in the app launcher. Each desktop environment where these things are not working will need its own kind of fix. It is out of my reach doing such a thing.

**Closed by wwmm** 2021-10-18 22:10 UTC

**Comment by quietvoid** [comment] 2022-01-03 14:13
This has started happening to me, where the running `easyeffects --gapplication-service` gets killed if I quit another instance of `easyeffects`.
Not sure what changed on my system (or the app). I run Sway so there's not even an icon to open the running service.

I might try bisecting later today.

**Comment by vchernin** [comment] 2022-01-03 18:17
> This has started happening to me, where the running `easyeffects --gapplication-service` gets killed if I quit another instance of `easyeffects`.
> 
> Not sure what changed on my system (or the app). I run Sway so there's not even an icon to open the running service.
> 
> 
> 
> I might try bisecting later today.

I'm not sure if that's the same bug, what package are you using? A Flatpak has more controlled permissions than other packages, and that can cause weird behaviour. Flathub-beta (see readme) behaves a bit better but  it still needs improvement.

> From the applications point of view all we have to do is creating the autostart file inside ~/.config/autostart/

That, or for Flatpak we ask a portal to do it for us. But that depends on a functional portal setup on the host, which depends on functional D-Bus on the host. All of which is basically out of our control.

**Comment by quietvoid** [comment] 2022-01-03 18:29
I'm using `easyeffects-git` from the AUR.
I've found multiple issues similar to this so I didn't create a new one yet.

**Comment by wwmm** [comment] 2022-01-03 21:36
>I'm using easyeffects-git from the AUR.

Strange. Although I do not use the pkgbuild from AUR(I use the one we have here in github) I am also on Arch Linux and I do not remember having seen something like this. Maybe it is better you open a new issue with some logs from your system.

**Comment by russelltg** [comment] 2023-11-24 04:53
One interesting thing I noticed is that when rofi runs easyeffects, it runs it without `--gapplication-service` flag, but if I run it with `gtk-launch` it runs with `--gapplication-service`. Looking at the code for it it seems `gtk-launch` is using dbus activation instead of just running the Exec line in the desktop file. Is it correct that the desktop file doesn't have `--gapplication-service` in the Exec line?

**Comment by wwmm** [comment] 2023-11-24 14:34
>Is it correct that the desktop file doesn't have --gapplication-service in the Exec line, or should rofi be doing dbus activation?

Yes. Rofi should be using dbus activation. If you just run `easyeffects --gapplication-service` directly EasyEffects will be launched as a background process without showing its window. The way to show its window while activating the "service mode" at the same time is using the dbus activation feature.

The `--gapplication-service` is a gtk feature that allows an ordinary app to run in the background and pretending to be a service. Somehow under the hoods gtk interacts with dbus and does all this magic.

**Comment by wwmm** [comment] 2023-11-24 14:39
More information about this in this page https://wiki.gnome.org/HowDoI/DBusApplicationLaunching
