### ISSUE TITLE
Desktop icon has a black background

### ISSUE THREAD

**Issue by Knebergish** [wwmm/easyeffects#1597] opened 2022-06-26 10:22 UTC
### EasyEffects Version

6.2.6

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 36 Kinoite

### Describe the bug

After the recent update of EasyEffects in Flatpak, the application icon began to be displayed with a black background instead of transparency. When viewing icons in Dolphin, this problem is observed only with the EasyEffects icon.
![BlackBackIco](https://user-images.githubusercontent.com/10116459/175809740-148a2206-7f38-4410-84d8-4915c9e108f9.png)

### Expected Behavior

The icon has a transparent background instead of a black fill.

**Comment by Digitalone1** [comment] 2022-06-26 10:31
@bertob can you fix it?

**Comment by wwmm** [comment] 2022-06-26 15:12
>When viewing icons in Dolphin, this problem is observed only with the EasyEffects icon.

Only in Dolphin or anywhere in KDE? Considering QT has problems with SVG files I imagine that anything using QT is showing the new icon this way.

**Comment by Knebergish** [comment] 2022-06-26 15:59
On the desktop and taskbar too.
![Desktop](https://user-images.githubusercontent.com/10116459/175822954-7e44b658-0893-4ff1-aece-bdf0bd5094e9.png) ![Taskbar](https://user-images.githubusercontent.com/10116459/175822953-52ca627b-321e-470d-9fc6-440834306240.png)

**Comment by Digitalone1** [comment] 2022-06-26 16:03
Don't know the cause of this, but we had also the same issue with the previous icon and a [commit](https://github.com/wwmm/easyeffects/commit/e179bf03b63da5626cc10b0dcdf96227775c8c51?diff=unified#diff-6e4d9fa622e521ee23cd669ece92750ad852c4bde2dadc07e8d46297e46062d8) was made to fix it. Am I right?

**Comment by Knebergish** [comment] 2022-06-26 16:07
For me the problem is reproduced with [this picture](https://github.com/wwmm/easyeffects/blob/master/data/com.github.wwmm.easyeffects.svg) - in Dolphin and Gwenview it is displayed with a black background.

**Comment by wwmm** [comment] 2022-06-26 16:08
>Am I right?

Yes. The explanation about the fix is in this comment https://github.com/wwmm/easyeffects/issues/867#issuecomment-1056077158. According to the person that found the fix
```
The issue you're seeing here is that in KDE we use the Qt SVG renderer, which supports only a subset of the SVG standard. We are trying to change this, but there is no ETA currently.

Most icons work fine, but among icons that are broken, the most common problem is that they use masking or clipping paths, both of which Qt does not support.

A workaround is to use ordinary paths instead of relying on clip paths. It's not always as clean of an approach, but the result avoids the issue in Qt applications.
```

**Comment by Knebergish** [comment] 2022-06-26 16:43
I found a [similar old problem](https://github.com/xournalpp/xournalpp/issues/3280#issuecomment-903575040) in another application, but I have too little experience with SVG to understand how to edit the image correctly.

**Comment by wwmm** [comment] 2022-06-26 16:48
>but I have too little experience with SVG to understand how to edit the image correctly.

Same thing with me. I will wait for the help of someone that actually knows this kind of stuff. Ideally QT should have better support for SVG. But considering how many years have passed since we faced this issue with QT for the first time and it is still here I have lost hope it is going to be fixed on its side...

**Comment by Digitalone1** [comment] 2022-06-26 16:52
Someone can try with [svgcleaner](https://archlinux.org/packages/community/x86_64/svgcleaner/) or [scour](https://archlinux.org/packages/extra/any/scour/) to minify the svg code and test it on QT.

**Comment by Knebergish** [comment] 2022-06-26 17:05
Seems like this version of icon works well.
![com github wwmm easyeffects2](https://user-images.githubusercontent.com/10116459/175825375-63978a00-e7e5-47fb-8a4e-29001dec92b8.svg)
In all places now icon shows correctly:
![Dolphin2](https://user-images.githubusercontent.com/10116459/175825441-ff7d87e0-888b-4ab1-9c5d-eeb0508639eb.png) ![Desktop2](https://user-images.githubusercontent.com/10116459/175825442-536f6994-a9ee-4881-8d19-ef684cce3de2.png) ![Taskbar2](https://user-images.githubusercontent.com/10116459/175825440-64f079b0-871b-4a6b-9102-d11894020a91.png)
In image I removed all "mask" and "clipPath" sections and added "fill-opacity" to "g" sections.

**Comment by Digitalone1** [comment] 2022-06-27 19:46
@Knebergish made a pull request to add the version you suggested.

**Comment by Knebergish** [comment] 2022-06-27 20:35
Thanks @Digitalone1!

**Comment by wwmm** [comment] 2022-06-27 22:45
I think we can close this issue.

**Closed by wwmm** 2022-06-27 22:45 UTC
Labels: help wanted
