### ISSUE TITLE
System Hangs when trying to open a Convolution impulse

### ISSUE THREAD

**Issue by ricardomatias** [wwmm/easyeffects#1278] opened 2021-12-03 10:11 UTC
### EasyEffects Version

6.1.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop OS 21.04

### Describe the bug

When trying to load a Convolver impulse the file open dialog shows and then the whole system hangs, I cannot exit or do anything. I'm left with the only option of hard resetting the computer.

### Expected Behavior

To load a file without freezing the whole system.

**Comment by wwmm** [comment] 2021-12-03 13:52
This is a duplicate of #1179. This is a gtk4 bug that has not been solved by its developers yet. For some reason it seems to be hitting only X11 users.

**Closed by wwmm** 2021-12-03 13:52 UTC
