### ISSUE TITLE
Unable to use more than one plugin at a time

### ISSUE THREAD

**Issue by fulminatingmoat** [wwmm/easyeffects#1325] opened 2022-01-09 08:33 UTC
### EasyEffects Version

6.2.1

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux in LXC, 5.13.19-2-pve

### Describe the bug

Unable to use more than one filter at a time, and filters do not work at all unless loopback is enabled. It looks like sie is disconnecting the filters from the pipewire graph immediately after they are connected without loopback enabled. With loopback enabled, the most recent filter selected will show up in helvum and be functional, however selecting a new filter will replace the current one instead of adding to the filter list. This applies for both input and output. 

The immediate disconnect shows on helvum as the filter appearing for a split second before disappearing. 

### Expected Behavior

Should be able to use more than one filter at a time, without loopback being required at all.

### Debug Log

<details><summary>Debug Log</summary><br/>
[easyeffects.log](https://github.com/wwmm/easyeffects/files/7834686/easyeffects.log)
</details>

### Additional Information

<details><summary>pw-dump</summary><br/>
[pw-dump.log](https://github.com/wwmm/easyeffects/files/7834687/pw-dump.log)
</details>

Running Arch Linux inside an unprivileged Proxmox Virtual Environment LXC container, with pipewire and pulse sockets bind mounted, and UID/GID mapping from host, pipewire 0.3.43, wireplumber

No DE, AwesomeWM

**Comment by wwmm** [comment] 2022-01-09 14:57
>Unable to use more than one filter at a time, and filters do not work at all unless loopback is enabled.

I don't really understand what you mean. Of which loopback are you talking about? We do not load any. I use many filters in my pipeline at the same time. So I am not sure I understand the first part too.

Run `pw-dot` in your computer so I can see how the links between filters and devices are being created. The output file can be viewed with `xdot`.

**Comment by fulminatingmoat** [comment] 2022-01-09 16:49
[pw-dot](https://user-images.githubusercontent.com/19787065/148688673-2ffb4a24-3945-4fc4-bbe1-86e98ef303a8.png)

[easyeffects config for above](https://user-images.githubusercontent.com/19787065/148688733-995f92d5-960a-4da1-a02c-3d34a0a64c4e.png) 


> Of which loopback are you talking about?

Sorry, didn't mean loopback, monitor might be more appropriate, the button on the bottom right of the 2nd picture attached. Filter gets destroyed after creation if there is nothing connected to the easyeffects souce, (video 2), turning monitor on / adding a consumer such as discord (webrtc), lets the filter stay, but as soon as that consumer exits, the filter is destroyed and isn't brought back.

> I use many filters in my pipeline at the same time.

When I go to add a filter a non-empty pipeline, the new one replaces the old one (video 1)

https://user-images.githubusercontent.com/19787065/148692029-05d12b2f-b81f-430c-914c-f76aada3414a.mp4

https://user-images.githubusercontent.com/19787065/148692032-44cc9872-4862-473a-9df2-163c89679b98.mp4

**Comment by wwmm** [comment] 2022-01-09 16:59
>adding a consumer such as discord (webrtc), lets the filter stay, but as soon as that consumer exits, the filter is destroyed and isn't brought back

Oh, I see. That is actually intended in order to save cpu power. As far as I am aware I have to unlink the filters to make sure we do not waste cpu power when nothing is actually using our virtual devices. We can consider allowing this behavior to be configured. But for the majority of the users the current behavior will have to be kept as default because is what most expect to happen. Processing silence does not make much sense. Do you intend to use these filters in helvum for something?

>When I go to add a filter a non-empty pipeline, the new one replaces the old one (video 1)

That is something I have never seen. And to make things even more odd I am also on Arch Linux. I am not sure about how this is even possible... The only restriction is adding more than one instance of the same filter.

**Comment by wwmm** [comment] 2022-01-09 17:01
I am trying to reproduce the video but somehow the pitch plugin is added instantly on my computer. And it stays there. So far the only big difference is that I do not use Helvum. But I do not see how it could be doing that. Even if the filter is removed from PipeWire its widgets should stay in our window.

**Comment by wwmm** [comment] 2022-01-09 17:03
>No DE, AwesomeWM

I wonder if something on GTK is going crazy because of that. I am on gnome.

**Comment by wwmm** [comment] 2022-01-09 17:06
>pw-dot

No pitch plugin even with its widgets in our window... Something out of the ordinary is definitely going on. I wonder what.

**Comment by fulminatingmoat** [comment] 2022-01-09 17:12
> As far as I am aware I have to unlink the filters to make sure we do not waste cpu power when nothing is actually using our virtual devices. 

Ah this makes sense, it just felt wrong on my computer because the filter doesn't return when the device is used again but that's probably related to the other issue.

> I wonder if something on GTK is going crazy because of that. I am on gnome.

This could be a GTK4/libadwaita issue, there's a secondary border around the plugin select window that is just a solid black border without picom, could be some other issues with it that are less visible

> No pitch plugin even with its widgets in our window... Something out of the ordinary is definitely going on. I wonder what.

My bad, did pw-dot without the any plugins
[easyeffects with pitch](https://user-images.githubusercontent.com/19787065/148692865-67129bb6-17f1-42d5-a176-35dd9dfdb3d5.png)

**Comment by wwmm** [comment] 2022-01-10 16:13
>My bad, did pw-dot without the any plugins

Ok, so it is not as bad as it seemed.

>This could be a GTK4/libadwaita issue, there's a secondary border around the plugin select window that is just a solid black border without picom, could be some other issues with it that are less visible

I've noticed some weird shadows or borders in the video. It is clear something odd is happening in gtk. Are you using Xorg or Wayland? Even one of the gtk developers has said that their Xorg backend needs more work. But so far I have never seen something so bizarre happening. Either on Wayland or Xorg.

I looked at your video again and I think that more than just gtk may be at fault. EasyEffects uses GSettings to handle its settings. And this may be failing when you try to add the filters. Do you have a service named `dconf-service` running in your system? Usually the "big" desktops start it automatically. Without it EasyEffects will definitely be broken.

**Comment by gekkime** [comment] 2022-05-15 12:39
Hello, commenting here because I am having the exact same issue as OP, and found a temporary solution!
I am using Arch Linux, with dwm as my window manager (also not within a full DE).

> I looked at your video again and I think that more than just gtk may be at fault. EasyEffects uses GSettings to handle its settings. And it may be failing when you try to add the filters. Do you have a service named dconf-service running in your system? Usually the "big" desktops start it automatically. Without it EasyEffects will definitely be broken.

I have dconf-service running on my system, and the temporary solution I found was to manually kill and launch it again - which causes EasyEffects to work as expected.

When I rebooted the system and launched EasyEffects again, I couldn't remove the effects that were there before, nor add any new ones - that is until I repeated the process above.

Sadly I am not sure what would fix it for good due to my lack of familiarity with dconf.

**Comment by wwmm** [comment] 2022-05-15 15:09
>If however I launch dconf-service manually (either beforehand or after killing the one started by EasyEffects), everything works as expected, I can add and remove plugins freely and they display accordingly.

Interesting. So it is related to dconf-service indeed. As I use GNOME this service is automatically initialized probably way before GNOME decides to call EasyEffects autostart file. So my guess is that autostarting this service manually would be the proper thing to do. I do not remember have ever seen this kind of topic in the gsettigns documentation. I did not even know this service would "magically" start on demand. I always assumed the desktop would somehow start it on login.

**Comment by wwmm** [comment] 2022-05-15 15:12
>I always assumed the desktop would somehow start it on login.

And as I do not remember KDE users having this problem my guess is that at least the "big desktops" somehow autostart dconf-service on login.

**Comment by wwmm** [comment] 2022-05-15 15:18
Based on the output of `systemctl --user status dconf` on my computer nowadays dconf-service is initialized by systemd as a `user` service. And in its file the type is set to `dbus`. Probably the `dbus activatable` kind. I wonder why it is not properly working when dbus starts it on demand...

**Comment by gekkime** [comment] 2022-05-16 11:11
Update, I experimented a little bit more with dconf-service.

When EasyEffects is launched, systemd launches dconf as a user service

`systemctl --user status dconf.service
● dconf.service - User preferences database
     Loaded: loaded (/usr/lib/systemd/user/dconf.service; static)
     Active: active (running) since Mon 2022-05-16 14:06:43 IDT; 4s ago
       Docs: man:dconf-service(1)
   Main PID: 73721 (dconf-service)
      Tasks: 3 (limit: 14186)
     Memory: 1.3M
        CPU: 18ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/dconf.service
             └─ 73721 /usr/lib/dconf-service`

And of course launching the actual process.

If I manually launch dconf-service through `systemctl --user start dconf.service`, EasyEffects is back to the buggy behavior.

However if I launch it through `/usr/lib/dconf-service`, which spawns the process but **doesn't**  start it as a systemd service

`systemctl --user status dconf
○ dconf.service - User preferences database
     Loaded: loaded (/usr/lib/systemd/user/dconf.service; static)
     Active: inactive (dead)
       Docs: man:dconf-service(1)

May 16 14:04:46 majchine systemd[484]: Stopping User preferences database...
May 16 14:04:46 majchine systemd[484]: Stopped User preferences database.`

then in this case, EasyEffects works as expected.

**Comment by wwmm** [comment] 2022-05-16 23:08
>then in this case, EasyEffects works as expected.

This is really weird. I do not understand how these two operations could be having different results. Both cases make calls to `/usr/lib/dconf-service`.

**Comment by wwmm** [comment] 2022-05-16 23:10
The systemd service file has these contents
```
[Unit]
Description=User preferences database
Documentation=man:dconf-service(1)

[Service]
ExecStart=/usr/lib/dconf-service
Type=dbus
BusName=ca.desrt.dconf
```
I wonder if `BusName=ca.desrt.dconf` can lead to a different behavior depending on the desktop where the service is being used.

**Comment by wwmm** [comment] 2022-10-29 14:33
As it does not seem there is much that can be done on our side I will close this issue.

**Closed by wwmm** 2022-10-29 14:33 UTC
