### ISSUE TITLE
Crash when changing spectrum points setting while having 2 or more sources playing.

### ISSUE THREAD

**Issue by tati1454** [wwmm/easyeffects#1486] opened 2022-04-19 17:45 UTC
### EasyEffects Version

6.2.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 35

### Describe the bug

When I modify the points of the spectrum while playing audio from two sources at the same time it hangs a little until it completely crashes.

### Expected Behavior

I expect no hangs or crashes when I change the points of the spectrum.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
You have PipeWire 0.3.50 installed
This is newer or the same as PipeWire 0.3.41 required to run EasyEffects
(process:2): easyeffects-DEBUG: 14:41:08.817: easyeffects version: 6.2.4
(process:2): easyeffects-DEBUG: 14:41:08.819: main: locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 14:41:08.826: presets_manager: system input presets directory: "/app/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 14:41:08.826: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 14:41:08.826: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 14:41:08.826: presets_manager: system output presets directory: "/app/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 14:41:08.826: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 14:41:08.826: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 14:41:08.826: presets_manager: user presets directory already exists: /home/tati/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 14:41:08.826: presets_manager: user presets directory already exists: /home/tati/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 14:41:08.826: presets_manager: user presets directory already exists: /home/tati/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 14:41:08.826: presets_manager: user presets directory already exists: /home/tati/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 14:41:08.826: presets_manager: user presets directory already exists: /home/tati/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
(easyeffects:2): easyeffects-DEBUG: 14:41:08.929: pipe_manager: compiled with PipeWire: 0.3.41
(easyeffects:2): easyeffects-DEBUG: 14:41:08.929: pipe_manager: linked to PipeWire: 0.3.41
(easyeffects:2): easyeffects-DEBUG: 14:41:08.931: pipe_manager: core version: 0.3.50
(easyeffects:2): easyeffects-DEBUG: 14:41:08.931: pipe_manager: core name: pipewire-0
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: found metadata: settings
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: found metadata: default
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: found metadata: route-settings
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: Audio/Sink 39 alsa_output.pci-0000_00_1f.3.analog-stereo with timestamp 1650390068933146344 was added
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: Audio/Source 40 alsa_input.pci-0000_00_1f.3.analog-stereo with timestamp 1650390068933185154 was added
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: Stream/Output/Audio 57 spotify with timestamp 1650390068933238787 was added
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: spotify port 60 is connected to alsa_output.pci-0000_00_1f.3.analog-stereo port 41
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: spotify port 58 is connected to alsa_output.pci-0000_00_1f.3.analog-stereo port 43
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: Audio/Sink 117 easyeffects_sink with timestamp 1650390068933319670 was added
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: Audio/Source/Virtual 115 easyeffects_source with timestamp 1650390068933342241 was added
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_1f.3.analog-stereo"}
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_input.pci-0000_00_1f.3.analog-stereo"}
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: new metadata property: 57, target.node, Spa:Id, 72
(easyeffects:2): easyeffects-DEBUG: 14:41:08.933: pipe_manager: new metadata property: 57, target.object, Spa:Id, 1142
(easyeffects:2): easyeffects-DEBUG: 14:41:08.934: pipe_manager: easyeffects_sink node successfully retrieved with id 117 and timestamp 1650390068933319670
(easyeffects:2): easyeffects-DEBUG: 14:41:08.934: pipe_manager: easyeffects_source node successfully retrieved with id 115 and timestamp 1650390068933342241

(easyeffects:2): easyeffects-WARNING **: 14:41:08.976: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness
(easyeffects:2): easyeffects-DEBUG: 14:41:08.976: soe: http://drobilla.net/plugins/mda/Loudness is not installed

(easyeffects:2): easyeffects-WARNING **: 14:41:08.976: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 14:41:08.976: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 14:41:08.976: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link
(easyeffects:2): easyeffects-DEBUG: 14:41:08.994: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:09.027: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:09.080: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:22.481: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:22.497: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:22.517: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:22.517: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:2): easyeffects-DEBUG: 14:41:22.554: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:22.599: soe: rnnoise using the default model
(easyeffects:2): easyeffects-DEBUG: 14:41:22.632: soe: output_level successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 14:41:22.635: soe: spectrum successfully connected to PipeWire graph

(easyeffects:2): easyeffects-WARNING **: 14:41:22.722: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness
(easyeffects:2): easyeffects-DEBUG: 14:41:22.722: sie: http://drobilla.net/plugins/mda/Loudness is not installed

(easyeffects:2): easyeffects-WARNING **: 14:41:22.722: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 14:41:22.722: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 14:41:22.722: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link
(easyeffects:2): easyeffects-DEBUG: 14:41:22.743: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:22.786: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:22.839: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:33.628: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:33.643: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:33.659: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:33.659: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:2): easyeffects-DEBUG: 14:41:33.687: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 14:41:33.724: sie: rnnoise using the default model
(easyeffects:2): easyeffects-DEBUG: 14:41:33.743: sie: output_level successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 14:41:33.745: sie: spectrum successfully connected to PipeWire graph
easyeffects-INFO: 14:41:33.796: application: disabling global bypass
(easyeffects:2): easyeffects-DEBUG: 14:41:33.800: application_ui: Icon Theme breeze-dark detected
(easyeffects:2): easyeffects-DEBUG: 14:41:34.106: app_info: cannot lookup application icon com.spotify.Client in /usr/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 14:41:34.106: app_info: cannot lookup application icon com.spotify.Client in /usr/local/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 14:41:34.106: app_info: com.spotify.Client icon name not installed in the breeze-dark icon theme in use. The application icon has been hidden.
(easyeffects:2): easyeffects-DEBUG: 14:41:36.209: new default output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(easyeffects:2): easyeffects-DEBUG: 14:41:36.211: pipe_manager: new metadata property: 57, target.node, Spa:Id, 117
(easyeffects:2): easyeffects-DEBUG: 14:41:36.211: pipe_manager: new metadata property: 57, target.object, Spa:Id, 1239
(easyeffects:2): easyeffects-DEBUG: 14:41:36.211: pipe_manager: spotify port 60 is connected to easyeffects_sink port 70
(easyeffects:2): easyeffects-DEBUG: 14:41:36.211: pipe_manager: spotify port 58 is connected to easyeffects_sink port 116
(easyeffects:2): easyeffects-DEBUG: 14:41:36.361: new default input device: alsa_input.pci-0000_00_1f.3.analog-stereo
(easyeffects:2): easyeffects-DEBUG: 14:41:36.440: app_info: cannot lookup application icon com.spotify.Client in /usr/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 14:41:36.440: app_info: cannot lookup application icon com.spotify.Client in /usr/local/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 14:41:36.440: app_info: com.spotify.Client icon name not installed in the breeze-dark icon theme in use. The application icon has been hidden.
(easyeffects:2): easyeffects-DEBUG: 14:41:36.440: application: device alsa_card.pci-0000_00_1f.3 has changed its input route to: analog-input-rear-mic
(easyeffects:2): easyeffects-DEBUG: 14:41:36.440: application: device alsa_card.pci-0000_00_1f.3 has changed its output route to: analog-output-lineout
(easyeffects:2): easyeffects-DEBUG: 14:41:36.440: app_info: cannot lookup application icon com.spotify.Client in /usr/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 14:41:36.440: app_info: cannot lookup application icon com.spotify.Client in /usr/local/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 14:41:36.440: app_info: com.spotify.Client icon name not installed in the breeze-dark icon theme in use. The application icon has been hidden.
(easyeffects:2): easyeffects-DEBUG: 14:41:36.440: app_info: cannot lookup application icon com.spotify.Client in /usr/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 14:41:36.440: app_info: cannot lookup application icon com.spotify.Client in /usr/local/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 14:41:36.440: app_info: com.spotify.Client icon name not installed in the breeze-dark icon theme in use. The application icon has been hidden.
(easyeffects:2): easyeffects-DEBUG: 14:41:46.737: soe: No app linked to our device wants to play. Unlinking our filters.
(easyeffects:2): easyeffects-DEBUG: 14:41:46.740: sie: No app linked to our device wants to play. Unlinking our filters.
(easyeffects:2): easyeffects-DEBUG: 14:42:10.622: soe: At least one app linked to our device wants to play. Linking our filters.
(easyeffects:2): easyeffects-DEBUG: 14:42:10.842: app_info: cannot lookup application icon com.spotify.Client in /usr/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 14:42:10.842: app_info: cannot lookup application icon com.spotify.Client in /usr/local/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 14:42:10.842: app_info: com.spotify.Client icon name not installed in the breeze-dark icon theme in use. The application icon has been hidden.
(easyeffects:2): easyeffects-DEBUG: 14:42:10.879: soe: output_level: new PipeWire blocksize: 2048
(easyeffects:2): easyeffects-DEBUG: 14:42:58.009: pipe_manager: Stream/Output/Audio 85 Firefox with timestamp 1650390178009564718 was added
(easyeffects:2): easyeffects-DEBUG: 14:42:58.011: pipe_manager: new metadata property: 85, target.node, Spa:Id, 117
(easyeffects:2): easyeffects-DEBUG: 14:42:58.011: pipe_manager: new metadata property: 85, target.object, Spa:Id, 1239
(easyeffects:2): easyeffects-DEBUG: 14:42:58.018: pipe_manager: Firefox port 83 is connected to easyeffects_sink port 70
(easyeffects:2): easyeffects-DEBUG: 14:42:58.018: pipe_manager: Firefox port 80 is connected to easyeffects_sink port 116
(easyeffects:2): easyeffects-DEBUG: 14:43:00.465: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:2): easyeffects-DEBUG: 14:43:02.888: app_info: Firefox disposed
(easyeffects:2): easyeffects-DEBUG: 14:43:02.889: app_info: Firefox finalized
(easyeffects:2): easyeffects-DEBUG: 14:43:02.889: app_info: data struct destroyed
(easyeffects:2): easyeffects-DEBUG: 14:43:02.889: node holder: 85, Firefox finalized
(easyeffects:2): easyeffects-DEBUG: 14:43:06.494: pipe_manager: Stream/Output/Audio 85 Firefox with timestamp 1650390186494379582 was added
(easyeffects:2): easyeffects-DEBUG: 14:43:06.499: pipe_manager: new metadata property: 85, target.node, Spa:Id, 117
(easyeffects:2): easyeffects-DEBUG: 14:43:06.499: pipe_manager: new metadata property: 85, target.object, Spa:Id, 1239
(easyeffects:2): easyeffects-DEBUG: 14:43:06.505: pipe_manager: Firefox port 80 is connected to easyeffects_sink port 70
(easyeffects:2): easyeffects-DEBUG: 14:43:06.505: pipe_manager: Firefox port 68 is connected to easyeffects_sink port 116
(easyeffects:2): easyeffects-DEBUG: 14:43:09.051: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:2): easyeffects-DEBUG: 14:43:09.052: app_info: Firefox disposed
(easyeffects:2): easyeffects-DEBUG: 14:43:09.061: app_info: Firefox finalized
(easyeffects:2): easyeffects-DEBUG: 14:43:09.061: app_info: data struct destroyed
(easyeffects:2): easyeffects-DEBUG: 14:43:09.061: node holder: 85, Firefox finalized
/usr/include/c++/11.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::reference = float&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```
</details>

**Comment by Digitalone1** [comment] 2022-04-20 16:22
I did other tests. It's happening also with one only stream and writing manually the value, but only when the spectrum is visible. 

If the spectrum is not visible (in example, having the Pipewire tab open), the value can be changed in whichever way, it does not crash.

**Comment by Digitalone1** [comment] 2022-04-20 16:43
Maybe we should copy the gsettings value before sending to `logspace`.

https://github.com/wwmm/easyeffects/blob/47e79294b9829994b23215b5dc2893eac04f79d9/src/effects_box.cpp#L104
https://github.com/wwmm/easyeffects/blob/47e79294b9829994b23215b5dc2893eac04f79d9/include/util.hpp#L52

**Comment by wwmm** [comment] 2022-04-20 16:45
And to make things worse it is one of those bugs that do not happen when running in debug mode with debug symbols =/ So far I could reproduce it only with the package I installed in my system.

**Comment by wwmm** [comment] 2022-04-20 16:55
>Maybe we should copy the gsettings value before sending to logspace.

It makes sense. Logspace receives the value by reference. Maybe when not running in debug mode + symbols there is a chance the number of points changes while the logspace function is doing its calculations.

**Comment by wwmm** [comment] 2022-04-20 16:56
But looking at the logscape code I did not see yet a reason why this should be causing a crash.

**Comment by Digitalone1** [comment] 2022-04-20 19:16
```
Assertion '__n < this->size()' failed
```

Somewhere the index used to access the vector is greater than the vector size. Something has to do with the n_point change.

**Comment by wwmm** [comment] 2022-04-21 14:28
Forcing calls to `init_spectrum_frequency_axis` to happen when the loop is idles made the crash a little harder to happen but they still happen if we change the number of points too much.

**Comment by Digitalone1** [comment] 2022-04-21 14:35
Please make also a comment specifying the number of the ticket (`1486`), so we will remember why we made this changed.

**Comment by wwmm** [comment] 2022-04-21 14:38
>Can't you try to make a copy of the value before passing to logspace?

I could but I doubt this is the problem. The logspace function does not even try to access vector elements by index. It just pushes back values.

>Please make also a comment specifying the number of the ticket

Where?

**Comment by wwmm** [comment] 2022-04-21 14:39
I will try to build a binary with debug symbols but without enabling the sanitizer. Maybe it is because of it the crash does not happen.

**Comment by wwmm** [comment] 2022-04-21 14:42
Even without the sanitizer the crash does not happen once debug symbols are enabled. This is annoying =/

**Comment by wwmm** [comment] 2022-04-21 15:01
> The distribution package builder must be using a flag that makes the bug to happen...

No. I tried `arch-meson _build` and even with the different flags a binary executed in a local folder does not crash. Even without executing `init_spectrum_frequency_axis` when the signal is idle or creating local variables for the number of points. So I guess something odd is happening when the binary is installed in the system...

**Comment by wwmm** [comment] 2022-04-21 15:52
I finally found a way to force my custom Arch Linux package to have debug symbols and somehow in this case the crash happens. This is the place where we are crashing https://github.com/wwmm/easyeffects/blob/6d34e2cbe177a5560d04bf3fd8bee46b453f0ba9/src/chart.cpp#L333. Now the question is how to avoid it.

**Comment by wwmm** [comment] 2022-04-21 16:02
>Is there a way to stop the spectrum animation when the config is open? I think it's the safest thing to do.

Maybe. But it is not going to fix the source of the problem and it could happen again somewhere else. I think I see what is going on. Depending on when `init_spectrum_frequency_axis` is called the `x` and `y` vectors of the `chart` may have different sizes. I have to make sure we only try to draw when they are equal.

**Comment by wwmm** [comment] 2022-04-21 16:12
The intention was not closing this issue LOL :smile:

**Comment by wwmm** [comment] 2022-04-21 16:13
In any case the last commit seems to have fix the crash. I will wait for more tests.

**Comment by Digitalone1** [comment] 2022-04-22 18:47
> In any case the last commit seems to have fix the crash. I will wait for more tests.

Tested and it's fixed on my system too.

Since we are talking about the spectrum, I would ask if there could be done something to add a little of right/left padding to the frequency axes where the labels are drawn in order to not show the text attached to the window border.

**Comment by wwmm** [comment] 2022-04-22 22:41
>I would ask if there could be done something to add a little of right/left padding to the frequency axes where the labels are drawn in order to not show the text attached to the window border.

There is a setter for the margin https://github.com/wwmm/easyeffects/blob/903895f999d431834f9c08cef82343f470e01c51/src/effects_box.cpp#L143. But I am setting it to zero in the spectrum because at this moment the value for the margin is applied to all sides of the whole chart. And in the spectrum it was weird to have it everywhere. There isn't a control only for the x axis. But it should not be difficulty to add one.

**Comment by wwmm** [comment] 2022-04-23 14:46
I think we can close this issue.

**Closed by wwmm** 2022-04-23 14:46 UTC
Labels: EasyEffects Bug
