### ISSUE TITLE
Gentoo Everything greyed out, failed to connect to system bus, plugins not found

### ISSUE THREAD

**Issue by nswerhun** [wwmm/easyeffects#871] opened 2021-01-09 22:02 UTC
I've just emerged pulseeffects-4.7.2-r1, with [all optional USE flags](https://packages.gentoo.org/packages/media-sound/pulseeffects). I cannot enable any of the plugins. The buttons to reorder plugins do not work. Going to the settings menu, nearly all options are greyed out. I have ensured all required dependencies are installed. I have tried resetting with `pulseeffects -r`, reemerging with various combinations of USE flags, and clearing the gstreamer cache.  What am I doing wrong? 
When I just run the application, it gives me this:
```
$ pulseeffects

(pulseeffects:8300): pulseeffects-WARNING **: 06:49:21.924: sie: rtkit: Failed to connect to system bus: Could not connect: No such file or directory

(pulseeffects:8300): pulseeffects-WARNING **: 06:49:21.989: maximizer plugin was not found!

(pulseeffects:8300): pulseeffects-WARNING **: 06:49:21.994: pitch plugin was not found!

(pulseeffects:8300): pulseeffects-WARNING **: 06:49:22.007: soe: rtkit: Failed to connect to system bus: Could not connect: No such file or directory

(pulseeffects:8300): pulseeffects-WARNING **: 06:49:22.014: pitch plugin was not found!

(pulseeffects:8300): pulseeffects-WARNING **: 06:49:22.014: webrtc plugin was not found!
```

Running `gst-inspect-1.0 | grep "lv2"` [shows tons of plugins](https://pastebin.com/raw/xtnCCmY7) installed.

`G_MESSAGES_DEBUG=pulseeffects pulseeffects` output is [here](https://pastebin.com/raw/UgHFQdae).

**Comment by wwmm** [comment] 2021-01-09 22:41
The pastebin links are not working.

>Running gst-inspect-1.0 | grep "lv2" shows tons of plugins installed.

The question is if the plugins we need are installed. The plugins show as not found in your post are not LV2 plugins. The maximizer is used through its LADSPA package. The pitch plugin requires the rubberband LADSPA plugin. And the webrtc plugins is provided by the Gstreamer library `gst-plugins-bad`. 

Most of the other plugins we use are LV2. Are you sure you installed `calf` and `linux studio plugins`?

>rtkit: Failed to connect to system bus: Could not connect: No such file or directory

It seems you do not have the rtkit package installed.

**Comment by wwmm** [comment] 2021-01-09 22:42
Any reason to use `4.7.2` instead of a newer release?

**Comment by nswerhun** [comment] 2021-01-09 23:06
>The pastebin links are not working.

My apologies, try these: 
`gst-inspect-1.0 | grep "lv2"`: https://pastebin.com/GYpmfBqZ
`G_MESSAGES_DEBUG=pulseeffects pulseeffects`: https://pastebin.com/ZMtswBqW

>And the webrtc plugins is provided by the Gstreamer library `gst-plugins-bad`
Are you sure you installed `calf` and `linux studio plugins`?

Yes
gst-plugins-bad-1.16.2
calf-0.90.3
ladspa-sdk-1.15-r1
gst-plugins-ladspa-1.16.2

>It seems you do not have the rtkit package installed.

It is installed, rtkit-0.13-r1

>Any reason to use `4.7.2` instead of a newer release?

4.7.2 is the latest (and only) version marked stable in the Gentoo repos. As such, that version was selected automatically when I installed it. The only other version available is 4.8.4, which I have tried. It has the same problem.

**Comment by wwmm** [comment] 2021-01-10 00:35
It seems `https://pastebin.com` is down at this moment here in Brazil. That is why your links "are not working". Let's see if tomorrow the site will be online again.

In the mean time kill PE `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. this will show the initialization process.

If `gst-inspect-1.0` is able to see the plugins we should be too. In case were using an older PulseEffects release before the first emerge attempt try to reset `pulseeffects -r`. Maybe something went wrong when upgrading.

**Comment by nswerhun** [comment] 2021-01-10 03:29
Here is the output for `G_MESSAGES_DEBUG=pulseeffects pulseeffects`, after first killing it:
```
(process:4325): pulseeffects-DEBUG: 15:26:33.303: main: locale directory: /usr/share/locale
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.310: presets_manager: user presets directory already
exists: /home/noah/.config/PulseEffects
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.310: presets_manager: user presets directory already
exists: /home/noah/.config/PulseEffects/input
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.310: presets_manager: user presets directory already
exists: /home/noah/.config/PulseEffects/output
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.310: presets_manager: user presets directory already
exists: /home/noah/.config/PulseEffects/autoload
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.331: application: PE version: 4.7.2
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.331: pulse_manager: context is connecting
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.331: pulse_manager: context is authorizing
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.332: pulse_manager: context is setting name
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.332: pulse_manager: context is ready
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.332: pulse_manager: connected to: /tmp/pulse-PKdhtXMmr18n/native
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.332: pulse_manager: protocol version: 33
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.332: pulse_manager: Pulseaudio version: 13.0
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.332: pulse_manager: default pulseaudio source: alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.332: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_06_00.0.analog-stereo
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.332: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.332: pulse_manager: default pulseaudio sink sampling
rate: 48000 Hz
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.332: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.332: pulse_manager:  failed to get sink info: PulseEffects_apps
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.418: soe: using output device: PulseEffects_mic
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.418: soe: using input device: alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo

(pulseeffects:4325): pulseeffects-WARNING **: 15:26:33.425: pitch plugin was not found!

(pulseeffects:4325): pulseeffects-WARNING **: 15:26:33.425: webrtc plugin was not found!
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.427: presets_manager: user presets directory already
exists: /home/noah/.config/PulseEffects
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.427: presets_manager: user presets directory already
exists: /home/noah/.config/PulseEffects/input(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.427: presets_manager: user presets directory already
exists: /home/noah/.config/PulseEffects/output
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.427: presets_manager: user presets directory already
exists: /home/noah/.config/PulseEffects/autoload
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.427: presets_manager: destroyed
pulseeffects-INFO: 15:26:33.427: application: disabling global bypass
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.427: sie: bypass is already disabled
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.427: soe: bypass is already disabled
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.669: convolver_ui: irs directory already exists: /home/noah/.config/PulseEffects/irs
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.937: sie: spectrum enabled
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:33.937: soe: spectrum enabled
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.101: sie: total latency: 0 ms
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.101: soe: total latency: 0 ms
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.109: sie: sampling rate: 48000 Hz
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: pulse_settings_ui: added sink: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: pulse_settings_ui: added sink: alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: sie: using output device: alsa_output.pci-0000_06_00.0.analog-stereo
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: pulse_settings_ui: output device changed: alsa_output.pci-0000_06_00.0.analog-stereo
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: pulse_settings_ui: added sink: alsa_output.pci-0000_06_00.0.analog-stereo
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: pulse_settings_ui: added sink: alsa_output.pci-0000_00_1f.3.iec958-stereo
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: pulse_settings_ui: added source: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2.monitor
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: pulse_settings_ui: added source: alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo.monitor
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: soe: using input device: alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: pulse_settings_ui: input device changed: alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: pulse_settings_ui: added source: alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: pulse_settings_ui: added source: alsa_output.pci-0000_06_00.0.analog-stereo.monitor
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.110: pulse_settings_ui: added source: alsa_output.pci-0000_00_1f.3.iec958-stereo.monitor
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.111: sie: NULL -> READY -> PLAYING
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.111: sie: READY -> PAUSED -> PLAYING
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.112: sie: pulsesrc latency [us]: 10000
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.112: sie: pulsesrc buffer [us]: 200000
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.112: sie: total latency: 0 ms
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.127: sie: pulsesink latency [us]: 10000
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.127: sie: pulsesink buffer [us]: 200000
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:34.127: sie: total latency: 0 ms
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:35.379: peadapter: pulseaudio block size 480 frames
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:35.379: peadapter: we will read in chunks of 512 frames
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:35.390: sie: total latency: 140 ms
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:35.393: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:35.393: sie: total latency: 140 ms
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.219: application:  destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.219: presets_manager: destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.219: soe: destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.219: soe: multiband_gate destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.219: soe: multiband_compressor destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.219: soe: webrtc destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.219: soe: NULL -> VOID_PENDING
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: soe: pitch destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: soe: deesser destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: soe: gate destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: soe: reverb destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: soe: equalizer destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: soe: filter destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: soe: compressor destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: soe: limiter destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: sie: destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: sie: delay destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: sie: autogain destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: sie: crystalizer destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.220: sie: convolver destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.221: sie: stereo_tools destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.221: sie: multiband_gate destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.221: sie: loudness destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.221: sie: multiband_compressor destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.221: sie: maximizer destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.221: sie: crossfeed destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.221: sie: exciter destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.221: sie: bass_enhancer destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.223: sie: NULL -> VOID_PENDING
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.223: sie: pitch destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.223: sie: deesser destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.223: sie: gate destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.223: sie: reverb destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.224: sie: equalizer destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.224: sie: filter destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.224: sie: compressor destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.224: sie: limiter destroyed
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.224: pulse_manager: unloading PulseEffects sinks...
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.224: pulse_manager: module 26 unloaded
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.224: pulse_manager: module 27 unloaded
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.224: pulse_manager: Context was drained
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.224: pulse_manager: disconnecting Pulseaudio context...
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.224: pulse_manager: context was terminated
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.225: pulse_manager: Pulseaudio context was disconnected
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.225: pulse_manager: unreferencing Pulseaudio context
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.225: pulse_manager: stopping pulseaudio threaded main loop
(pulseeffects:4325): pulseeffects-DEBUG: 15:26:57.225: pulse_manager: freeing Pulseaudio threaded main
loop
```
I have tried `pulseeffects -r` a few times, with no effect.

**Comment by nswerhun** [comment] 2021-01-10 04:44
Ok, thinking it was a problem with the gentoo package, I just uninstalled it, and built release v4.8.4 from source, using the tarball given on the releases page. The same problem persists. This doesn't appear to be an issue with the version or gentoo package, but rather something about my system.

**Comment by wwmm** [comment] 2021-01-10 14:24
Based on the logs the only plugins not being found are the ones with a `pulseeffects-WARNING`. Something else is going on. Can you take a screenshot of PE window showing the greyed out widgets?

**Comment by nswerhun** [comment] 2021-01-10 19:06
https://user-images.githubusercontent.com/24984195/104132680-83db4900-5344-11eb-953a-30499ea43796.mov

There is a video of what is happening. I try to click on the checkboxes to enable the plugins, it does not work. Options in the settings menu are greyed out.

**Comment by wwmm** [comment] 2021-01-10 20:59
This is really weird. Something in gtk or gsettings is broken. Considering that the greyed out plugins are bound to gsettings keys a problem in your gsetting installation seems more probable.

Is there a process named `dconf-service` running after you do a login?

**Comment by nswerhun** [comment] 2021-01-11 01:37
Both gsettings and dconf are installed, however there is no `dconf-service` to speak of.

**Comment by wwmm** [comment] 2021-01-11 02:18
>there is no dconf-service to speak of.

This can be the reason why things are so broken. Almost all of our settings are bound to gsettings keys. Which desktop are you using? Usually this service is started automatically on login.

**Comment by nswerhun** [comment] 2021-01-11 04:04
I am using my own build of dwm. I've looked at the services available on my system (openrc init system) and `dconf-service` is not one of them. Is there another way to start the daemon, not using the init system? I could put it in my `.xinitrc` or `.zprofile`.

**Comment by wwmm** [comment] 2021-01-11 14:10
In Arch Linux this is the exe path `/usr/lib/dconf-service`. Maybe it is just a matter of auto run it on login as any other exe

**Comment by nswerhun** [comment] 2021-01-11 20:40
Starting `dconf-service` made no difference.

**Comment by wwmm** [comment] 2021-01-11 21:59
>Starting dconf-service made no difference.

Are you able to use `dconf-editor` in you system?
![Screenshot from 2021-01-11 18-58-22](https://user-images.githubusercontent.com/16225172/104243214-00eae900-543f-11eb-8a49-77b1a8b2a6c8.png)
Keep PE window open while you try to change our settings in dconf-editor. You should see the widgets changing in our window. If they don't gsettings is still broken.

**Comment by nswerhun** [comment] 2021-01-12 00:59
Simply opening `dconf-editor` fixed alot of problems, somehow. I can now change input/output devices, use dark theme, and use a few of the plugins, but some of the plugins are still not working, most importantly for me, Equalizer and Crystalizer.

**Comment by nswerhun** [comment] 2021-01-12 01:04
I should add that when I start the application it now looks like this:
```
(pulseeffects:22357): pulseeffects-WARNING **: 19:03:45.950: sie: rtkit: Failed to connect to system bus: Could not connect: No such file or directory

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:45.970: compressor plugin was not found!

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:45.971: equalizer plugin was not found!

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:45.977: maximizer plugin was not found!

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:45.980: loudness plugin was not found!

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:45.992: convolver plugin was not found!

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:45.992: crystalizer plugin was not found!

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:45.994: delay plugin was not found!

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:45.994: rnnoise plugin was not found!

(pulseeffects:22357): GLib-GIO-CRITICAL **: 19:03:45.994: g_settings_bind_with_mapping: assertion 'G_IS_OBJECT (object)' failed

(pulseeffects:22357): GLib-GIO-CRITICAL **: 19:03:45.994: g_settings_bind_with_mapping: assertion 'G_IS_OBJECT (object)' failed

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:46.003: soe: rtkit: Failed to connect to system bus: Could not connect: No such file or directory

(pulseeffects:22357): pulseeffects-CRITICAL **: 19:03:46.004: pulse_manager:  failed to get source info:

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:46.005: compressor plugin was not found!

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:46.006: equalizer plugin was not found!

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:46.014: maximizer plugin was not found!

(pulseeffects:22357): pulseeffects-WARNING **: 19:03:46.014: rnnoise plugin was not found!
```

**Comment by wwmm** [comment] 2021-01-12 02:51
crystalizer is compiled with PE. If it is not workingprobably `zita-convolver` was not installed at compilation time. For the equalizer, compressor and delay plugins you will need `linux-studio-plugins` package. The maximizer is from the `zam-plugins` package

**Comment by aTosser** [comment] 2021-03-02 07:10
I am also suffering from this issue, taking note from the comments here, I looked into dconf-editor. I can indeed change settings in PE from dconf-editor so it seems that dconf is working correctly, but when I navigate to sinkinputs rnnoise > installed There is a message No schema available... ... Dconf Editor can't fine one associated with this key... etc. For my configuration maximizer, pitch, rnnoise, and webrtc are not found.

Pipewire 0.3.2.2
PE latest master.

**Comment by aTosser** [comment] 2021-03-02 10:01
I've been bashing my face against rnnoise to see what is up, and the issue is that gentoo does not search /usr/lib or /usr/local/lib for pkg-config files (.pc) and rnnoise wants to be installed by default to $prefix/lib which is not where gentoo does things for gentoo reasons. Gentoo searches /usr/lib64 only and so it requires the ./configure file to be edited with the correct libdir for gentoo and then when you make install it puts everything where it is supposed to be. This applies to rnnoise specificly but I can imagine this is why others do not work as they should. (don't quote me on this) 

In closing, this is likely a gentoo specific issue and a more elegant solution will need to be investigated.

**Comment by wwmm** [comment] 2021-03-02 16:58
>I can imagine this is why others do not work as they should. (don't quote me on this)

The maximizer and the pitch pluguins are ladspa plugins. Something else is going on in this case. Take a look at the output of `gst-inspect-1.0 | grep -i ladspa`. If you see `ladspa-ladspa-rubberband-so-rubberband-pitchshifter-stereo` and `ladspa-zamaximx2-ladspa-so-zamaximx2` it is a pulseeffects bug. If not try to clear the GStreamer cache `rm -rf ~/.cache/gstreamer-1.0/`. And if that is not enough then something is missing in the system.

**Comment by Technohacker** [comment] 2021-05-30 06:49
Something I noticed with Gentoo, the ebuild installs fine with all dependencies but `gst-inspect-1.0`, `lv2ls` and PulseEffects can't find LV2 plugins. This can happen if `/etc/profile` doesn't get sourced correctly for any reason since it loads `/etc/profile.env` which in turn defines the environment variables `$LV2_PATH` and `$LADSPA_PATH`, which point to `/usr/lib64`. Either that, or for some reason it gets overridden by a different set of variables, the path points to the home directory and `/usr/lib` instead

**Comment by wwmm** [comment] 2021-07-07 17:35
As EasyEffcts 6.0.0 takes a very different approach in may situations it will probably be better to close this issue and opening a new one if such problems are still present.

**Closed by wwmm** 2021-07-07 17:35 UTC
