### ISSUE TITLE
Random device ignoring on its reconnect

### ISSUE THREAD

**Issue by Casul51** [wwmm/easyeffects#1333] opened 2022-01-13 04:37 UTC
### EasyEffects Version

6.2.1

### What package are you using?

AUR (easyeffects-git)

### Distribution

Garuda Linux (Arch)

### Describe the bug

Sometimes when i disconnect and reconnect my bluetooth wireless headset (WI-1000XM2) Easyeffects start to ignore this device (thou device work and if bypass Easyeffects all work fine) as well "EasyEffects Source" (microphone) stop passing any sound (micro works fine).
After that - manual change of output device in prefernce start to ignore headset even if I choice it manually.

Restart of Easyeffects solves the issue.

It may be somehow related to KDE (or my install), since sometimes tray icon use muted icon as for another not active device (which actually is be muted). 

### Expected Behavior

Reconnect without need of restarting Easyeffects.

### Debug Log

Debug Log it too big :(
https://pastebin.com/MWDrinep

### Additional Information

Same issue happens on non-git version

It don't seem that it reproducible with 'safe' headset poweroff. Could reproduce with physically disconnecting bluetooth adapter. As well this happens when device lose connection on its own (big distance, etc)

It may somehow be related to KDE (or my install), since sometimes tray icon use muted icon as for another not active device (which actually is be muted). But it makes no sense since restart of Easyeffects helps.

Operating System: Garuda Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.15.11-230-tkg-pds (64-bit)
Graphics Platform: Wayland

#pipewire --version                                            
pipewire
Compiled with libpipewire 0.3.43
Linked with libpipewire 0.3.43

Everything other packages is up to date since Arch.

**Comment by wwmm** [comment] 2022-01-13 14:41
>After that - manual change of output device in prefernce start to ignore headset even if I choice it manually.

Is this the device selection menu from EasyEffects window or from another program managing audio devices?

**Comment by wwmm** [comment] 2022-01-13 15:04
Although I do not have a bluetooth headphone I have 2 sound soundcards and I think I was able to reproduce your issue. If we disable `Use Default` device in EasyEffects menu and the manually selected device is destroyed at some point there is a chance there will be no audio because in this particular combination of events the internal structure with the output device information is not being updated. So EasyEffects is trying to link to a device that does not exist anymore. That is why your log has so many lines about link failures.

But somehow on my computer I can get the audio back by manually selecting the other sound card and going back to the one that was reenabled. In your case that would be the bluetooth device. In any case we have to do something when a manually selected device is removed. I think that the only reliable action is moving to the default device when that happens. Trying to track what PipeWire is doing to manually selected devices is probably only going to give headaches.

**Comment by wwmm** [comment] 2022-01-13 15:11
>I think that the only reliable action is moving to the default device when that happens.

Maybe there is another way. I will do some tests.

**Comment by wwmm** [comment] 2022-01-13 15:42
Ihave sent some updates to the master branch. If possible test it. Things should be better now.

**Comment by Casul51** [comment] 2022-01-14 03:46
> > After that - manual change of output device in prefernce start to ignore headset even if I choice it manually.
> 
> Is this the device selection menu from EasyEffects window or from another program managing audio devices?

From EasyEffects's selection menu.

**Comment by Casul51** [comment] 2022-01-15 15:09
Well, it feels better, but after some time it does it again.

(this is 1 log, catch size limitation in pastebin)
https://pastebin.com/PbKheg4Y
https://pastebin.com/pexYU5hG

**Comment by Casul51** [comment] 2022-01-15 15:37
Restarted app, made bad reconnect, default device didn't changed from the PC's soundcard, but after turning it off and on, started to using the right, system's default device
https://pastebin.com/fLnjQJzW

**Comment by primalmotion** [comment] 2022-01-15 21:41
I have the same issue. device switching has always been finicky for me with pulse/easyeffects. Then it started to work beautifuly a few months ago. So much that I forgot about easyeffects because it was completely transparent. And now it's back to basically never switching the default device. I will try the master branch.

**Comment by wwmm** [comment] 2022-01-15 22:41
>And now it's back to basically never switching the default device

That does not seem the same thing. In this current issue the option to use the default device is disabled as far as I understand.

**Comment by primalmotion** [comment] 2022-01-15 23:17
oh. then maybe I should open another issue. I just tried the master and it does not follow the change of default devices

**Comment by Casul51** [comment] 2022-01-16 00:54
> And now it's back to basically never switching the default device.

If I understand well, my issue contains this one.

> In this current issue the option to use the default device is disabled as far as I understand.

As well as it.


So basically after 1st bad reconnect it _may_ stop thinking about headphones as default device but allow manual switching to it in EasyEffects > PipeWire > Output Device. After 2nd bad reconnect it usually don't allow to choice it at all.

**Comment by wwmm** [comment] 2022-01-16 04:50
>If I understand well, my issue contains this one.

Probably not. Default devices switching trigger completely different signals. And if these ones were failing a huge number of people would be having problems. Including myself. The bluetooth device connection/disconnection process is triggering a very specific code path.

**Comment by wwmm** [comment] 2022-01-16 05:06
>it may stop thinking about headphones as default device

That is not how it works. If you enable `Use Default Device` EasyEffects will link is last filter in the pipeline (an output level meter) to the current default device as reported by PipeWire. But sometimes PipeWire decides to set our virtual devices as default. And as it does not make sense to play audio to ourselves there may be silence in these cases. 

But in your case something different related to how PipeWire is handling bluetooth must be happening because I can not reproduce the problem with my soundcards anymore. I am doing the following tests

1. Disable `Use Default` and select the hdmi card as output instead of my onboard optical port
2. Close EasyEffects window
3. After that I turn off the hdmi card and as expected there is silence because I disabled use default and the custom device does not exist anymore.
4. Once I turn on my hdmi card I have audio again. That is what was not working before the patch.

Something more must be happening when turning on/off bluetooth devices. But unfortunately I do not have one to test at this moment.

**Closed** 2022-07-10 15:42 UTC
