### ISSUE TITLE
Switch between output devices, Turns off the effect in apps

### ISSUE THREAD

**Issue by chriztheanvill** [wwmm/easyeffects#1454] opened 2022-03-30 06:32 UTC
### EasyEffects Version

6.2.4

### What package are you using?

Fedora

### Distribution

Fedora 35

### Describe the bug

Switch between devices: Headphones and speakers, Or speaker and headphones, turns off the effect in apps.

### Expected Behavior

Switch between devices, keeps the config.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by Digitalone1** [comment] 2022-03-30 11:02
This seems a duplicate of #1393 

Do you have the latest `0.4.9` version of wireplumber?

**Comment by chriztheanvill** [comment] 2022-03-30 18:45
`sudo dnf info wireplumber

Installed Packages
Name         : wireplumber
Version      : 0.4.9
Release      : 1.fc35
Architecture : x86_64
Size         : 266 k
Source       : wireplumber-0.4.9-1.fc35.src.rpm
`

**Comment by Digitalone1** [comment] 2022-03-30 19:02
Which pipewire version?

I'm using wireplumber 0.4.9 with pipewire 0.3.49 and everything is good.

I had the same issue in the past, but the new wireplumber release fixed it.

Try to replace wireplumber with `pipewire-media-session`. If it's working, it's likely a newer wireplumber issue.

**Comment by quietvoid** [comment] 2022-04-05 14:51
There definitely seems to be a different behaviour with `wireplumber`.

Processing ("Activation" switch) per app is not persisted across `easyeffects` restarts either.
Though it works with `pipewire-media-session`.

Even when reinstalling `wireplumber`, the app state is only persisted until modified, and then the processing is always disabled.

**Comment by wwmm** [comment] 2022-04-05 15:09
>Processing ("Activation" switch) per app is not persisted across easyeffects restarts either.

I wonder if WirePlumber is still forcing streams to be moved away from our device in some situations. When the option `Process All Outputs` is enabled in EasyEffects menu it will try to move streams to our virtual devices. But this does not force the stream to stay there. Third party software and the media session manager can move it somewhere else.

That being said if `Process All Outputs` is disabled streams will be moved to our devices only if the media session manager or another tool decide to do this.

**Comment by wwmm** [comment] 2022-06-23 00:53
>Switch between devices: Headphones and speakers, Or speaker and headphones, turns off the effect in apps.

EasyEffects `6.2.6` has been release today and it is a little smarter when ti comes to handle links in situations where devices are being connected/disconnected. It may have fixed this issue.

**Comment by wwmm** [comment] 2023-07-27 14:04
I imagine we can close this issue.

**Closed by wwmm** 2023-07-27 14:04 UTC
