### ISSUE TITLE
Equalizer kills the sound on both L and R or just R

### ISSUE THREAD

**Issue by Odin000** [wwmm/easyeffects#1565] opened 2022-06-11 08:49 UTC
### EasyEffects Version

6.2.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop!_OS 22.04 LTS x86_64

### Describe the bug

Running EasyEffects with the Equalizer on, sometimes kills the sound and sometimes just the R channel.
Bypassing the equalizer solves the problem, even reactivating it after that is not a problem.
It doesn't happen too oft but the problem is there.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment] 2022-06-11 23:21
It happens to me too https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1733. I still can't reproduce the problem when I need to. It is super random :disappointed:

**Comment by wwmm** [comment] 2022-10-29 14:24
As this bug is being discussed on #1789 I will close this issue.

**Closed by wwmm** 2022-10-29 14:24 UTC
