### ISSUE TITLE
Adding the Autogain plugin mutes left channel

### ISSUE THREAD

**Issue by SBence** [wwmm/easyeffects#1024] opened 2021-07-14 00:10 UTC
Using KDE Plasma on Arch Linux with EasyEffects installed from the official repository. As soon as I add said plugin, only the right channel works, even if I turn on Bypass on the plugin or reset it. As soon as I remove it, both channels work correctly again. Couldn't reproduce the issue with other plugins.

**Comment by wwmm** [comment] 2021-07-14 00:33
Sounds like one of the plugin's ports was not linked. What is quite unexpected. If there is one plugin I use all the time is the autogain. Strange... Kill the curent instance `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`. Let's see if something unusual is shown by the logs.

While the problem is happening run `pw-dot` and attach the output file here on github. I will use xdot to see if there is really an unlinked port.

**Comment by SBence** [comment] 2021-07-14 01:09
Couldn't get the bug to trigger while in debug mode, but I could grab logs with `pw-dot` with EasyEffects run normally.
[pw.dot.log](https://github.com/wwmm/easyeffects/files/6812804/pw.dot.log)
(Had to rename the file for GitHub to allow upload.)

**Comment by wwmm** [comment] 2021-07-14 04:26
In the first file none of the plugins are linked. It could be because nothing was actually playing audio. But in the second file I can see that only the port related to the right channel was linked to our virtual sink. What explains the missing left channel. But it doesn't explain why it only happens with the autogain. All filters inherit from the same base class. So the code that creates the ports is the same. 

The code that link the filters ports is also the same for all of them... Even if you are not able to reproduce the issue while in debug mode put the results here. Maybe there is something that suggest a direction to investigate. So far I haven't seen a link failure in any of the tests I've been doing.

**Comment by wwmm** [comment] 2021-07-14 04:35
The output of `pw-dump` may also help.

**Comment by SBence** [comment] 2021-07-14 15:57
[pw-dump.log](https://github.com/wwmm/easyeffects/files/6817425/pw-dump.log) taken while playing audio with only the right channel active.
[debug.log](https://github.com/wwmm/easyeffects/files/6817430/debug.log) taken while playing audio without issue.

**Comment by wwmm** [comment] 2021-07-14 18:13
So far I did not see anything unusual in any of the files. This issue is going to be tough to fix without being able to reproduce it on my computer. The fact that the problem does not happen in debug mode suggest there may be some synchronization problem somewhere. And the changes in timings that usually comes with debug mode may be magically fixing the problem.

**Comment by zeko9381** [comment] 2021-07-14 18:21
I am having the same problem with the equalizer plugin. It works fine at first, but when a new source starts playing, only the right channel is playing.

**Comment by SBence** [comment] 2021-07-14 18:23
I've made some observations in the meantime that may or may not help:
- So far the issue only surfaced if EasyEffects was run as a service
- Almost always after a reboot
- Often but not always after a suspend
- Autogain haven't had to be added at reboot/suspend, adding it later also caused the issue to surface
    - Removing/readding isn't a fix (technically it is, but only until readding the plugin), only restarting EasyEffects is
- Adding different plugins at any time would not trigger the issue, only Autogain would

**Comment by wwmm** [comment] 2021-07-14 18:43
>I've made some observations in the meantime that may or may not help:

Not enough to cause it here. I think I will have to take a look at the code and make some changes hoping that they help somehow...

**Comment by wwmm** [comment] 2021-07-14 20:13
There is another test that can be done. Executing EasyEffects as `PIPEWIRE_DEBUG=4 easyeffects` this will show PipeWire logs instead of EasyyEffects logs. As PipeWire may print an insane amount of messages depending on the log level the idea is trying to get only what it prints when the autogain plugin is added and the left channel stops working. Maybe PipeWire prints some kind of message or warning telling why the link to this channel is failing.

**Comment by wwmm** [comment] 2021-07-14 20:15
>Maybe PipeWire prints some kind of message or warning telling why the link to this channel is failing.

Or if the link si being destroyed. I am already checking for link failures. So I am more inclined to believe that for some reason we are not even trying to do the left channel link or it is being destroyed just after being created.

**Comment by Digitalone1** [comment] 2021-07-15 06:52
Cannot reproduce on my system. Is it only a coincidence it's happening on KDE Plasma?

**Comment by wwmm** [comment] 2021-07-15 13:59
>Is it only a coincidence it's happening on KDE Plasma?

Probably. I do not see what KDE could be doing to consistently destroy always the left channel link of the same plugin.

**Comment by zeko9381** [comment] 2021-07-18 22:47
Can confirm the bug only appears when EasyEffects is running as a service.

**Comment by wwmm** [comment] 2021-07-18 23:09
>Can confirm the bug only appears when EasyEffects is running as a service.

And how easy it is to reproduce the bug? I mean how many times you had to remove and readd the autogain plugin to trigger the bug? I am running as a service at this moment, without debug enabled, and after repeating this process a few times I still could not make the bug show itself.

**Comment by wwmm** [comment] 2021-07-18 23:11
In any case is an interesting information. From the gtk point of view running as a service means mostly "keep running even if the window closes". I am not sure why this would be causing a port link to fail.

**Comment by zeko9381** [comment] 2021-07-18 23:17
I actually just use the equalizer. For me, the bug triggers when a new audio source starts playing. For example, when watching Youtube on Firefox, the first video will be fine, but every video after that will only have the right channel playing. Removing and re-adding the plugin doesn't fix the problem. For now, I just start EE and minimize it, which works fine.

**Comment by wwmm** [comment] 2021-07-19 00:42
>when watching Youtube on Firefox, the first video will be fine, but every video after that will only have the right channel playing

Between the end of the first video and the start of the second our sink probably entered the suspended state. When this happens we unlink the filters to avoid processing silence. It is a brute force approach but at this moment the PipeWire function that is supposed to pause filters does not work. I wonders why removing and readding the plugin does not restore the link...

@zeko9381 run `pw-dot` when the link is broken and attach the file here on github. I imagine that it will be similar to the one sent by the other user but who knows.

Do you have only the equalizer plugin enabled?

**Comment by SBence** [comment] 2021-07-19 15:47
> There is another test that can be done. Executing EasyEffects as `PIPEWIRE_DEBUG=4 easyeffects` this will show PipeWire logs instead of EasyyEffects logs. As PipeWire may print an insane amount of messages depending on the log level the idea is trying to get only what it prints when the autogain plugin is added and the left channel stops working. Maybe PipeWire prints some kind of message or warning telling why the link to this channel is failing.

Sorry for the late reply. I couldn't reproduce the issue when running EasyEffects this way.

**Comment by wwmm** [comment] 2021-07-19 16:40
> I couldn't reproduce the issue when running EasyEffects this way.

So even PipeWire debug mode makes the problem go away. This is sounding like a multithreading race somewhere. 

>I use Equalizer all the time and interestingly have never had any problems as long as Autogain wasn't in the chain.

And I still have no idea why. The code that creates each plugin port is the same. As well as the code that links or unlinks them. I wonder if a difference in initialization time is the key. Maybe the library libebur128 used by the autogain is taking to much time too initialize. And as this is being done in the realtime thread maybe the time slice Pipewire is allocating for this is reached and the operation does not succeed. But even if that is the case I do not see why ti would always affect the same channel.

Do you have many `client too slow` pipewire messages in your system log `sudo journalctl | grep -i "client too slow"`?

**Comment by zeko9381** [comment] 2021-07-19 17:05
Here is the `pw-dot` output:
[pw.dot.txt](https://github.com/wwmm/easyeffects/files/6842681/pw.dot.txt)

I have only the equalizer plugin enabled.
And I also have a bunch of `client to slow` messages in my system log.

**Comment by AwesomenessZ** [comment] 2021-08-04 17:26
I have this issue on both of my arch machines white running as a service. Both use kde (not sure if related) and were installed with archinstall (source of how pipewire was installed). I only have access to my old laptop at the moment but I am getting a few client too slow messages 
[too-slow.log](https://github.com/wwmm/easyeffects/files/6933202/too-slow.log) -- Plexamp is what I use for background music and autostarts as well
It only happens while running as service OR UNDER AUTOSTART in kde. Even if I manually tell kde to autostart EasyEffects (not run as a service, it opens in a window) it will have no audio in the left ear and the right will be louder than it usually is. (This is all with autogain in use only)
As others have stated closing EasyEffects or stopping the service and opening it again will fix this issue. It started happening after the rebrand.

**Comment by wwmm** [comment] 2021-08-05 17:46
>Both use kde (not sure if related)

I am starting to reconsider my opinion about this. So far I only remember KDE users reporting this bug. And I still could not see it happening on my computer.

I also do not have any idea yet about how this could even be happening =/

**Comment by Digitalone1** [comment] 2021-08-05 17:50
It's easy kde is messing with pipewire somewhere. Remember they showed the mic icon telling the user "_PulseEffects is using the mic_" which was clearly lie, something else wrong they could be doing now.

**Comment by Digitalone1** [comment] 2021-08-07 13:37
Maybe it's not KDE.

Pw links the ports, but sometimes they don't get connected, even if no issue are reported by pw and the application. It's enough only one channel don't get connected in the pipeline, even if the remaining are correctly connected, the audio is playing only on one side.

To me it's a pw issue.

**Comment by wwmm** [comment] 2021-08-07 17:52
And believe it or not I still could not see this issue happening in my system. Considering that running in debug mode "fixes" the most likely reason is that a thread racing is happening somewhere. And as I am in a machine with a Ryzen 3700x the 16 virtual cores I have available are probably masking the issue somehow.

**Comment by AwesomenessZ** [comment] 2021-08-07 18:02
My desktop has a 3600 which has  the issue though, granted it's not as good as yours but it's not like it only happens on low spec hardware

**Comment by AwesomenessZ** [comment] 2021-08-07 18:03
Has anyone tried loading a different de?
If not I can't try it later today

**Comment by wwmm** [comment] 2021-08-07 18:07
I did not have time to install another DE yet. After my last comment I tried to run EasyEffects with `taskset - c 0,1` and I still do not see it happening...

**Comment by wwmm** [comment] 2021-08-07 18:16
I am looking again at how PipeWire utilities create links and there is nothing special being done there that we do not do already https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/src/tools/pw-cli.c#L1370. I am starting to think that in some situations some links are not living for long after creation.

**Comment by Digitalone1** [comment] 2021-08-07 19:40
Making not passive links will help? Anyway this should be reported to pw devs.

**Comment by wwmm** [comment] 2021-08-07 20:24
>Making not passive links will help?

It won't help with this issue and we want to keep them passive. PipeWire does this in its `Jack` server too. Passive links do not force the graph to be active all the time. The filters do not generate data by themselves. They act on demand based on other active nodes like an audio player. So filters links should not be forcing the whole audio graph to be always active. Non passive links force that. And on top of all that there is the fact that the difference between passive and non passive is only relevant when the link exists. Our problem is that the linking is missing.

>Anyway this should be reported to pw devs.

I agree. I usually do that myself but without being able to reproduce this issue I can't help PW developers.

**Comment by AwesomenessZ** [comment] 2021-08-07 20:45
Its definitely something to do with kde.
I installed Gnome and enabled auto start as a service.
Logged out and logged into gnome. Works fine and autostarted. Logout and Login to KDE, works fine. Wth
Restarted and went into kde. Same bug.
Restarted and went into Gnome. Its fine. Then I logged out and into KDE and same bug.

**Comment by AwesomenessZ** [comment] 2021-08-07 20:55
I also seem to have "fixed" the bug by adding a 10 second delay on when kde starts EasyEffects. (so I edited the .desktop in ~/.config/autostart to have the command of `sleep 10 && easyeffects --gapplication-service`)
I noticed that gnome seemed to try to not start the service as soon as kde did, but I don't have a way to confirm this is the case.
@SBence does this fix the issue for you as well?

**Comment by wwmm** [comment] 2021-08-07 21:04
>Its definitely something to do with kde.

That is concerning. KDE and GNOME developers usually do not listen to complaints about bad behavior they introduce in their audio stack. I really hope we do not need their help to fix this.

>I also seem to have "fixed" the bug by adding a 10 second delay on when kde starts EasyEffects.

Wait... I thought that you could reproduce the issue whenever you removed the autogain/equalizer plugin and added it to the list again. Is this something that happens only after initializing the service?

**Comment by SBence** [comment] 2021-08-07 21:20
> @SBence does this fix the issue for you as well?

I'll try to test it in a few days, thanks for the suggestion.

> Wait... I thought that you could reproduce the issue whenever you removed the autogain/equalizer plugin and added it to the list again. Is this something that happens only right after initializing the service?

It's more like: if the issue is present, adding Autogain will always mute the right channel, removing it always restores it. If the issue isn't present, no amount of removing and readding Autogain will break it. So yes, it does seem like something goes wrong during service initialization / resumption after a suspend.

**Comment by AwesomenessZ** [comment] 2021-08-07 21:20
> That is concerning. KDE and GNOME developers usually do not listen to complaints about bad behavior 

Yeah if worse comes to worse, maybe just add in a delay to start if they use kde?

> I thought that you could reproduce the issue whenever you removed the autogain/equalizer plugin and added it to the list again.

Whenever I Add/remove the plugin it still only plays in the left ear until I restart all of EasyEffects (if using the service I just pkill easyeffects and open it again)

Sbence said for them:
> Autogain haven't had to be added at reboot/suspend, adding it later also caused the issue to surface

Which would follow in line with me removing and re adding autogain and still having the issue persist.
So I have no clue why this is a solution, but as soon as I removed the delay it started happening again

**Comment by wwmm** [comment] 2021-08-07 21:42
After thinking about this new information I decided to take a look at the part of our code that updates our list of node port properties. I found a mistake there that has a high chance of being related to this issue. Please test the new code through the AUR package.

**Comment by wwmm** [comment] 2021-08-07 21:55
Now that I thought I fixed the problem I am seeing it on my computer in a very bizarre way XD. The executable benerated by the pkgbuild package isn't linking any of the filters. But the one compiled manually in a folder works fine... Weird...

**Comment by wwmm** [comment] 2021-08-07 21:56
But that is a sign that now I am looking at the right direction.

**Comment by AwesomenessZ** [comment] 2021-08-07 22:00
Same happens for me lol good luck with that one

**Comment by wwmm** [comment] 2021-08-07 22:03
That is really bizarre. If I tell Meson to compile with `buildtype=release` then no link between filters is done and as a result there is no audio. But if I tell Meson to compile with `buildtype=debugoptimized` then everything works as expected. What the hell? Could it be that the compiler is removing callbacks from the final executable when doing optimizations?

**Comment by wwmm** [comment] 2021-08-07 22:06
I think I will have to reimplement the mistake in order to understand why the compiler is now going crazy.

**Comment by wwmm** [comment] 2021-08-07 22:41
Master branch updated again. Please test it.

I think I understand now what was happening. Sometimes PipeWire does things I do not expect. Like many other objects ports have many properties and there is a signal that is emitted when some of them changes. Just like there is one for when the port is created. I assumed that the signal about port changes gave us a new structure with all of its fields properly initialized wiht the old values where no change was made. It turns out that this is not what happens. The strucuture that comes with this signal has only the fields that changed initialized. The ones that did not are undefined and not set to the current port values like I assumed... Well...

What the mistake I talked about did was making any update to the ports super unlikely to be saved to our list of ports properties. Once the mistake was fixed all the information in the list was overwritten with undefined values.

**Comment by wwmm** [comment] 2021-08-07 22:45
Now I wonder if this issued is still happening after the latest changes. I hope not XD

**Comment by AwesomenessZ** [comment] 2021-08-07 22:49
Testing it now

**Comment by AwesomenessZ** [comment] 2021-08-07 22:53
It seems to be working... Now let me just spam restart and see if it hold up lol

**Comment by AwesomenessZ** [comment] 2021-08-07 23:02
Yep that seems to have solved the issue!

**Comment by wwmm** [comment] 2021-08-07 23:05
>Yep that seems to have solved the issue!

Nice! :smiley:

**Comment by wwmm** [comment] 2021-09-24 15:37
I think we can close this issue

**Closed by wwmm** 2021-09-24 15:37 UTC
