### ISSUE TITLE
After Pipewire update Easyeffects GUI won't load.

### ISSUE THREAD

**Issue by sithdaddy** [wwmm/easyeffects#2656] opened 2023-10-16 11:47 UTC
### EasyEffects Version

7.1.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Linux Mint

### Describe the bug

After updating Pipewire to the version shown in the picture bellow , the Easyeffects GUI program wont load anymore.
In the picture bellow you can see what other dependencies the Pipewire update wants to remove before doing the update.

I re-installed Easyeffects and rebooted , but it did not help.
Had to restore Timeshift backup from the day before to make Easyeffects GUI program load again.

![update removes](https://github.com/wwmm/easyeffects/assets/32434220/253d848a-97d0-4881-871c-2dc9ce374c8b)

### Expected Behavior

Applying Pipewire update and Easyeffects GUI program still working.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment] 2023-10-16 14:20
>I re-installed Easyeffects and rebooted , but it did not help.

As this PipeWire version is not causing problems to me on Arch Linux the only thing I can think of is some kind of problem specific to Flatpak is happening. What do you think @vchernin ? Did you notice anything out of the ordinary when using the Flatpak package with the latest PipeWire?

**Comment by wwmm** [comment] 2023-10-16 14:31
>In the picture bellow you can see what other dependencies the Pipewire update wants to remove before doing the update.

Maybe the problem is the update removing the packages related to `xdg-portal`. I think that without them the Flatpak package gets stuck and does not show EasyEffects window. @sithdaddy are you able to reinstall the xdg packages?

**Comment by vchernin** [comment] 2023-10-16 14:50
Why is that update removing so many packages including pipewire? A lot of those look essential to me.

**Comment by violetmage** [comment] 2023-10-16 18:09
Looking at the screenshot closely, it appears that op is running Linux Mint 22, which, underneath is based on ubuntu 22.04. IIRC, 22.04 still uses pulseaudio as the main audio server, running some sort of nested pipewire setup so that pipewire apps can function. This means that easyeffects could only interface with other apps that use pipewire on lm22. I think op tried to make pipewire the main audio server by just installing the pipewire package, but mints's packages / dependencies didn't like this and decided to get uninstalled. If that's what happened, I pronounce the system in question to be borked.

**Comment by sithdaddy** [comment] 2023-10-17 00:36
@vchernin  I thought it looked funny too when i saw the list of packages that were uninstalled. I still did the update hoping that those packages could go and they were not needed anymore.
That was not the case.

@wwmm Not sure if re-installing the XDG packages alone would help.

@violetmage Youre not too far off.  First time now that updating pipewire damaged so much.

I guess i need to hold off for a while before updating pipewire again.

**Comment by violetmage** [comment] 2023-10-17 16:50
@sithdaddy So if you are indeed using lm22 with pipewire as the main audio server, then this is a system specific issue, not an easyeffects bug. Should this be the case, please consider closing this issue as resolved.

You might get better help on the linux mint forums.

**Closed** 2023-10-18 01:00 UTC

**Comment by violetmage** [comment] 2023-10-18 16:41
@sithdaddy If you modified the pulseaudio + pipewire setup that ubuntu ships, then it is a system specific issue. Otherwise, it is a linux mint issue.

Either way, the best place to look for more help is the linux mint forums.
