### ISSUE TITLE
Preferences -> Start Service at Login is not working

### ISSUE THREAD

**Issue by Odin000** [wwmm/easyeffects#1501] opened 2022-04-28 11:48 UTC
### EasyEffects Version

6.2.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop!_OS 22.04 LTS

### Describe the bug

Start Service at Login can't be toggled, and when trying to it resets the settings under the section Service (Shutdown on Windows close goes back to toggled).

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by Digitalone1** [comment] 2022-04-30 12:00
It seems a duplicate of #1500

**Comment by Odin000** [comment] 2022-04-30 12:09
duplicate of #1500

**Closed** 2022-04-30 12:09 UTC
