### ISSUE TITLE
Sometimes only sound from one channel or no sound at all

### ISSUE THREAD

**Issue by linuxandos2** [wwmm/easyeffects#1476] opened 2022-04-11 18:13 UTC
### EasyEffects Version

6.1.5

### What package are you using?

Other (specify below)

### Distribution

Gentoo

### Describe the bug

Playing flacs with any player: intermittently sound only come from one channel left or right, sometimes no sound at all.
Ending easyeffcts solves the probblem. 

### Expected Behavior

Sound should come from both channel left and right.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

Pipewire version: 0.3.36

**Comment by wwmm** [comment] 2022-04-11 19:32
This may be related to a hard to reproduce bug I reported to the PipeWire developers https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1733. I still see it on my computer from time to time. It is still super hard to reproduce and I still have no clue about why it happens

**Comment by wwmm** [comment] 2022-04-11 19:33
In any case it may be a good idea to update EasyEffects and PipeWire. You are a few versions behind on both packages.

**Comment by linuxandos2** [comment] 2022-04-11 20:18
after unmerging gentoo package pipewire:
src/meson.build:122:0: ERROR: Dependency "libpipewire-0.3" not found, tried pkgconfig and cmake
lib in local still present

**Comment by wwmm** [comment] 2022-04-11 20:20
>need 'libpipewire-0.3' ['>=0.3.41'] found '0.3.36'.

We had to increase the requirements on the minimum PipeWire version when fixing some things.

**Comment by wwmm** [comment] 2022-04-12 14:25
>now getting : error: no match for ‘operator+ during ninja install

It is the first time I see this error. What is show in the terminal before this line is printed?

**Comment by linuxandos2** [comment] 2022-04-13 18:28
reinstalled the gentoo system.
pipewire-0.3.36  (same as before)
easyeffects-6.2.3
still same problem
will now install from git

**Comment by wwmm** [comment] 2022-04-13 19:45
>still same problem

Do you mean the one where one of the channels has no audio? It is possible. Sometimes it randomly happens to me. It seems we are hitting some kind of PipeWire bug that is super hard to reproduce. Until a solution is found what you can do in clicking twice on the global bypass button. This will force the links to be recreated. It is less annoying than having to restart the application.

That being said at least on my side it is a rare bug. This is one of the reasons why I could not fix it yet. It does not happen when I want it to happen so I can find its source =/

**Comment by linuxandos2** [comment] 2022-04-13 21:46
_Do you mean the one where one of the channels has no audio?_ **yes**
it happens as well on L or R channel and less frequently on both together.

maybe also interesting:
Before installing chromium I was not able to reproduce the problem.

At a certain moment wireplumber disappeared, don't know how???
Installed it from gentoo package:  media-video/wireplumber-0.4.9 
also chromium is installed now and running.
Cannot reproduce any more
Will test more tomorrow. Now bedtime.

**Comment by wwmm** [comment] 2022-04-14 13:58
>Before installing chromium I was not able to reproduce the problem.

Usually I see this problem while watching videos on Firefox. So it is not something specific to how Chromium handles audio stream. 

>At a certain moment wireplumber disappeared, don't know how???

As you reinstalled it is possible that the package manager is selecting the built-in media session manager by default. In the latest PipeWire version you can only have one of them installed.

**Comment by linuxandos2** [comment] 2022-04-14 16:49
Reinstalled again fresh gentoo.
you are right: the built-in media session manager is used.
Before installation of chromium.
Playing several flacs with vlc and easyeffects running no problem at all.
www-client/chromium-100.0.4896.75 installed.
on the 3rd flac: only sound from one channel.
media-video/wireplumber-0.4.9  installed.
During installatio of wireplumber new version of pipewire is pulled in: media-video/pipewire-0.3.50
disabled media session manage
enabled wireplumber
reboot
start easyeffects, chromiums and play flacs: OK no problem any more.
Probably  the built-in media session manager cannot handle multiple sources very well.

**Comment by wwmm** [comment] 2022-04-14 18:27
>Probably the built-in media session manager cannot handle multiple sources very well.

Interesting. But it does not tell me enough to actually fix the problem. Just so you have an idea there 2 types of links EasyEffects has to handle. One from the players to our virtual devices. That is done through the session manager (built-in or wireplumber)  because there are some advantages in letting it do this. But the links between filters and from filters to the soundcard/mic have to be done manually through an entirely different PipeWire API. But these actions are not entirely independent. Depending on what happens with the players we have to destroy and recreate the links between filters. Maybe under very specific circumstances PipeWire has problems when synchronizing everything. Who knows...

**Comment by linuxandos2** [comment] 2022-04-14 18:34
OK,
Anyway let me know if further testing is needed.
I have several partitions to play with.
Thanks a lot for your helpful ideas

**Comment by wwmm** [comment] 2022-04-14 19:12
>Anyway let me know if further testing is needed.

I think it will be better to report additional findings to the issue I have opened at the PipeWire's page https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1733. Although there are some small differences I think that at the end of the day it is the same problem.

**Comment by wwmm** [comment] 2022-10-29 14:26
As this kind of problem is being discussed in the issue #1789 I will close this one.

**Closed by wwmm** 2022-10-29 14:26 UTC
