### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by Peppershaker** [wwmm/easyeffects#1669] opened 2022-07-22 01:54 UTC
### EasyEffects Version

6.2.7 stable

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04

### Describe the bug

Suddenly stopped working. 

Hangs when trying to launch the GUI. 

When invoked on the CLI through Flatpak yields

`'spa_pod_is_array(pod)' failed at /app/include/spa-0.2/spa/pod/iter.h:339 spa_pod_get_array()`

### Expected Behavior

Start

### Debug Log

<details><summary>Debug Log</summary><br/>

```
You have PipeWire 0.3.48 installed
This is newer or the same as PipeWire 0.3.41 required to run EasyEffects
'spa_pod_is_array(pod)' failed at /app/include/spa-0.2/spa/pod/iter.h:339 spa_pod_get_array()
```
</details>

**Comment by wwmm** [comment] 2022-07-22 03:39
This seems to be a duplicate of #1666. The other user is also trying to use the latest flatpak package in Ubuntu 22.04.

**Closed** 2022-07-29 16:04 UTC
