### ISSUE TITLE
Pulseeffects **Flatpak** crashing on source change

### ISSUE THREAD

**Issue by Dodjob** [wwmm/easyeffects#501] opened 2019-04-28 11:05 UTC
Hello there,
- When I switch source (from VLC to youtube for example) Pulseeffects will erratically crash (90% of the time). Same apply when going forward on a track. 
-I have to manually launch it from my desktop icon in the dock.
- If I try to launch it with "pulseeffects" I get a "command not found" (I can kill it with "killall pulseeffects" though.
- Now the bad new. I wanted to make a log. and used "G_MESSAGES_DEBUG=pulseeffects flatpak run com.github.wwmm.pulseeffects" 
And as soon as I do.. it never crash -.-' never 
If I use the short version (seems to be the way to start flatpak. "flatpak run com.github.wwmm.pulseeffects" It's starting, but will exactly crash the same way as when started from the launcher. 
So I made an old school " dmesg | grep pulseeffects"
[ 2279.029058] traps: pulseeffects[23080] general protection fault ip:7f67525fac78 sp:7ffebb113d60 error:0 in libpango-1.0.so.0.4200.3[7f67525e6000+23000]
Sorry to come again with weird issues -.-'

*Ubuntu 19.04- PE 4.5.9 - Installed from "Ubuntu Software" -Flatpak*
Regards,
Hadrien

**EDIT**
After a few hours of test, I deinstalled the program from the "Software center" and installed it from the ppa. It's now working flawesly. Which means, the flatpak version is flawed, at least here.

**Comment by wwmm** [comment] 2019-04-28 14:12
It seems the problem is in the pango library. As far as I remember the only place where I interact directly with it is in the code that draws the spectrum. And this code is like it was months ago... If you disable the spectrum does the crash still happens? 

Are you facing this kind of problem @AsavarTzeth ?

**Comment by AsavarTzeth** [comment] 2019-04-29 11:42
I assume with "switch source" @Dodjob means switcing on/off all effects for one or more applications? (top menu item on the left). Then no, it never crashes.

Now as for `libpango-1.0.so.0.4200.3` it is installed under `/usr/lib` which means it is provided by the runtime. If that is somehow at fault it is out of my hands.

I do however provide `pangomm` with the application. Could there be any issue in how I package it?
- It seems very unlikely given that all I add is `--disable-documentation`
- I also cleanup `/lib/pangomm-*` (`/lib/pangomm-1.4/include` & `/lib/pangomm-1.4/proc`), but that obviously makes no difference at runtime.

Really I have no clue about this one.

**Comment by wwmm** [comment] 2019-04-29 14:10
I also have my doubts this is a problem in pangomm.

**Comment by Leeo97one** [comment] 2019-07-17 18:41
I can reproduce the issue with GNOME Music when I skip to the next track. Disabling the spectrum does not seem to help.
```
juil. 17 20:36:36 systemd-coredump[22570]: Process 22560 (pulseeffects) of user 1000 dumped core.
                                           
                                           Stack trace of thread 2:
                                           #0  0x00007f218bfb2c78 n/a (/usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.4200.3)
```
```
[leeo@leeo-arch-pc ~]$ uname -a
Linux leeo-arch-pc 5.2.0-arch2-1-ARCH #1 SMP PREEMPT Mon Jul 8 18:18:54 UTC 2019 x86_64 GNU/Linux
[leeo@leeo-arch-pc ~]$ flatpak --version
Flatpak 1.4.2
[leeo@leeo-arch-pc ~]$ flatpak info com.github.wwmm.pulseeffects

PulseEffects - Effets audio pour applications PulseAudio

          ID: com.github.wwmm.pulseeffects
         Ref: app/com.github.wwmm.pulseeffects/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.6.5
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 39,7 MB
     Runtime: org.gnome.Platform/x86_64/3.32
         Sdk: org.gnome.Sdk/x86_64/3.32

      Commit: 7e94d3ca47df4b4651cb445718cf660968fbb5c7990a638cab2ac48e0fbc2fc6
      Parent: ad2f107764a22f14a5b9bee62ff4a869b67e189b6a65a98a793a33ceaa59f59a
     Subject: pulseeffects: Update to v4.6.5 (3a175f0c)
        Date: 2019-06-24 20:32:56 +0000
```

**Comment by wwmm** [comment] 2019-07-17 19:06
Again crashing on `libpango`. Weird... I have no idea why this is happening and as far as I remember I haven't had a crash related to pango in more than 1 year. Maybe I am doing something odd that is manifesting itself only in flatpak. In case something out there has any idea this is where I use pango:

https://github.com/wwmm/pulseeffects/blob/98ec74d58cdb7bd8bf29f816b5f6aafe43eafc29/src/spectrum_ui.cpp#L161

All I do is configuring the font used by the spectrum. I do not remember having done a direct call to pango anywhere else. Unless there is a better way to configure the font this could be a bug in pango on somewhere in GTK.

**Comment by AsavarTzeth** [comment] 2019-07-17 19:39
Weird indeed. Luckily it seems safe to assume this is a rare issue.

Considering PulseEffects is one of the most popular apps on Flathub you would most likely have heard a lot more of this if it was wide spread.

**Comment by Eonfge** [comment] 2019-08-17 15:19
I've also ran into this issue. Happened to me from the start, using Fedora 30 which I was installing today.

It crashed regularly on track change (using Lollypop), even after I turned off the graph.

**Comment by wwmm** [comment] 2019-08-17 15:42
@Eonfge are you able to take a look at the core dump? It would be good to know if the crash is again related to pango.

**Comment by Eonfge** [comment] 2019-08-17 17:18
[abrt.zip](https://github.com/wwmm/pulseeffects/files/3512238/abrt.zip)

## Backtrace
> traps: pulseeffects[7609] general protection fault ip:7fc1cfecdc78 sp:7ffcb4819a20 error:0 in libpango-1.0.so.0.4200.3[7fc1cfeb9000+23000]

Not sure what causes it, the non-flatpak version runs consistently good

**Comment by Eonfge** [comment] 2019-08-17 17:22
[abrt.zip](https://github.com/wwmm/pulseeffects/files/3512241/abrt.zip)
Another log of the same occurence

**Comment by SteliosStefanatos** [comment] 2019-08-19 18:26
Experienced same issue. PulseEffects 4.6.6 (Flatpak) crashes when switching source (as described in first post) or skipping tracks (clementine media player). Ubuntu 18.04.

**Comment by wwmm** [comment] 2021-07-07 16:53
As EasyEffects 6.0.0 does not use GStreamer and moved from gtk3 to gtk4 it will probably be better to close this issue and opening a new one if such problems come back.

**Closed by wwmm** 2021-07-07 16:53 UTC
