### ISSUE TITLE
Enhance Visibility and/or Simplify Functionality of Band Off and Mute in Equalizer

### ISSUE THREAD

**Issue by iciclejj** [wwmm/easyeffects#2836] opened 2024-01-01 14:45 UTC
Hi,

I've been working with the Equalizer effect in EasyEffects and noticed that there are currently two methods for disabling a band: setting the filter type to `Off` and using the `Mute` toggle.

I have two issues with this:

1. **Redundancy**: There might be reasons to have both `Mute` and `Off` that I'm not aware of, but to me it seems redundant to have both these options.

2. **Visual Clarity**: Currently, setting a band filter to `Off` grays out the band and locks the `Gain` slider. Meanwhile, if you `Mute` a band, you will have no visual indicators of it being muted unless you click the cogwheel above the band you muted. This becomes very difficult to manage if you're for example muting multiple bands in a 32-band equalizer setup. 

Suggested Changes:

1. Keep only the `Mute` toggle. It seems to have more usefulness than the `Off` filter type, considering it retains the underlying filter type in place. 

2. Make the `Mute` toggle have a similar or equivalent visual indicator as `Off` currently has.\
\
Not sure exactly what the best approach would be, but I suggest doing this regardless of whether the `Off` filter stays or not.

I'm willing to implement the changes myself, just wanted to check if any of them seem desirable. 

If I'm missing any reasoning behind the current design, then please let me know :)

**Comment by wwmm** [comment] 2024-01-01 16:41
That is not a good idea. Our equalizer window is just a wrapper for the equalizer from `Linux Studio Plugins` and just like other parametric equalizers it has separate controls to turn the band off and to mute it. Nowadays EasyEffects has the ability to also show the native plugin window. Removing the mute control from our custom gtk window won't remove the control from the native plugin window. So as far as consistency goes it will be a mess.

CPU usage has also to be taken into account. As I am not familiar with LSP's code I do not know what the plugin is doing inside. Maybe the mute is just playing silence while still doing audio processing while the "off" is actually saving cpu cycles. We shouldn't just assume they operate in an equal way because this may not be the case. IF the mute is processing silence users on weak processors will feel the weight of all the 32 bands even if most of them are not intended to process something.

If the change is done upstream by the Linux Studio Plugins developer I will obviously do the same here. Although I prefer to have the the mute button as a quick way to see the change caused by the band instead of selecting a different mode in the band type it is not a big deal to me to have only one. But it only makes sense to do it in our custom gtk window if the plugin native window also does it. But changing its native window is outside of my reach.

As the work should not start on our side for now let's close this issue.

**Closed by wwmm** 2024-01-01 16:41 UTC

**Comment by iciclejj** [comment] 2024-01-03 10:55
I see, thanks for the clarification. I guess I agree that it doesn't seem like a good idea to start removing any features in this case.

But what about implementing a Mute (and probably also Solo) indicator that's visible in the main equalizer UI without clicking into the band settings, similar to the LSP's own UI? Maybe even just an "advanced view" toggle to show all the settings upfront (type, mode, slope, solo, mute) without needing to click into the band menu (again, similar to LSP GUI).

**Comment by wwmm** [comment] 2024-01-03 14:49
>But what about implementing a Mute (and probably also Solo) indicator that's visible in the main equalizer UI without clicking into the band settings, similar to the LSP's own UI? Maybe even just an "advanced view" toggle to show all the settings upfront (type, mode, slope, solo, mute) without needing to click into the band menu (again, similar to LSP GUI).

I think it is fine to do it. Ideally without adding more  widgets to take the scarce space we have in the window. But I am not sure it will be possible this way. If the only way is through the addition of more widgets the easiest thing to do is probably putting a third row of GtkLabel below the labels for the quality and the frequency that are always visible in the equalizer window. Then depending on the mute and solo button states the letters `M` and `S` could be showed or hidden.
