### ISSUE TITLE
The harmonics bar can excede the window

### ISSUE THREAD

**Issue by EmmanuelMess** [wwmm/easyeffects#1867] opened 2022-10-02 16:22 UTC
### EasyEffects Version

6.3.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 20.04

### Describe the bug

![Captura de pantalla de 2022-10-02 13-21-54](https://user-images.githubusercontent.com/10991116/193464916-6f5e113d-2025-41d6-bec8-33eb5576c738.png)

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment] 2022-10-02 17:20
Duplicate of #1441. This is a gtk4 bug. As it was discussed in the other issue it has to be fixed on their side.

**Closed by wwmm** 2022-10-02 17:20 UTC
