### ISSUE TITLE
Mali400: not enough memory for GPU operations

### ISSUE THREAD

**Issue by Cyborgscode** [wwmm/easyeffects#1979] opened 2022-11-12 13:21 UTC
### EasyEffects Version

6.3.0

### What package are you using?

Fedora

### Distribution

Fedora 38 aka RAWHIDE AARCH64 

### Describe the bug

Device: Pinephone
GPU: Mali400
Bugzilla report: https://bugzilla.redhat.com/show_bug.cgi?id=2142263

easyeffects fails to start up, due to oom in gpu memory:

[pine@fedorapine ~]$ easyeffects
DRM_IOCTL_MODE_CREATE_DUMB failed: Nicht genügend Hauptspeicher verfügbar
DRM_IOCTL_MODE_CREATE_DUMB failed: Nicht genügend Hauptspeicher verfügbar
Speicherzugriffsfehler (Speicherabzug geschrieben)
(not enough memory) 

I assume it refers to the gpu memory, as 5 GB of main memory are available ;)

HWACCEL Support in form of libav was made available, but didn't help here. No idea if easyeffects can utilize it.

### Expected Behavior

hard to say.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment] 2022-11-12 14:18
>easyeffects fails to start up, due to oom in gpu memory

That is weird. Here on my `RAdeon RX 5700 XT` EasyEffects is using less than `40 MB` of gpu memory. My guess is that `gtk4` is not playing nice with your gpu driver. EasyEFfects does not do direct gpu memory allocation. Gtk4 is the one handling lower level operations.

**Comment by violetmage** [comment] 2023-03-02 04:40
@Cyborgscode I don't think that this is an EasyEffects issue. It could be a hardware driver issue, or gtk4 issue; I couldn't really say for sure.

Also, @wwmm I'm drooling, sitting here with a bunch of binary blobs and a 1060 coil-whining away

**Comment by wwmm** [comment] 2023-03-02 05:17
Whatever it is the cause I doubt it is on our side. It is definitely at a lower level in the software stack. If it is gtk4 or the driver I do not know. Let's close this issue.

**Closed by wwmm** 2023-03-02 05:17 UTC
