### ISSUE TITLE
Cannot set a frequency value on filter

### ISSUE THREAD

**Issue by arouene** [wwmm/easyeffects#3246] opened 2024-07-11 10:03 UTC
### EasyEffects Version

7.1.7

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 40

### Describe the bug

I cannot set a value on the frequency for the Filter plugin. Each time I try to set a value it reset to "10 Hz", sometimes when I reset the Filter, the frequency goes down by it-self ??!

https://github.com/wwmm/easyeffects/assets/20049990/715b6e4f-12d3-4a00-92e1-537451c302fb

### Expected Behavior

Be able to set "3000 Hz" in the frequency

**Comment by wwmm** [comment] 2024-07-11 14:39
This looks similar to #3214. And just like there I can´t reproduce the bug. It is fine here on my computer. Somehow the user on the other issue fixed the issue installing through a different kind of package  (Flatpak). But the source of the bug is still unknown. Most likely some change in one of the gtk4 libraries because I can't remember any change in EasyEffects in the last months that could cause something like this.

**Comment by arouene** [comment] 2024-07-11 16:32
Yes seems similar enough, so I installed the RPM version instead of the Flatpak one, and ... it's "fixed", I cannot reproduce.
For information the RPM is a version 7.1.6.

Thank you !

**Comment by wwmm** [comment] 2024-07-11 16:56
> Yes seems similar enough, so I installed the RPM version instead of the Flatpak one, and ... it's "fixed", I cannot reproduce. For information the RPM is a version 7.1.6.
> 
> Thank you !

This is so weird. In the other issue using Flatpak was the solution. Here it is the other way around... Well... For now let's close this issue :smile:

**Closed by wwmm** 2024-07-11 16:56 UTC
