### ISSUE TITLE
Spectrum laggy when playing at 44.1 kHz

### ISSUE THREAD

**Issue by tati1454** [wwmm/easyeffects#1261] opened 2021-11-19 14:22 UTC
### EasyEffects Version

6.1.2

### What package are you using?

Fedora

### Distribution

Fedora 35

### Describe the bug

When I play youtube videos or music through chromium at 48 kHz the spectrum moves nice, but when I play music from the spotify app at 44.1 kHz the spectrum starts getting laggy.

### Expected Behavior

I expect the spectrum to have a nice FPS

### Debug Log

<details><summary>Debug Log</summary><br/>
(process:7752): easyeffects-DEBUG: 11:19:12.507: main: locale directory: /usr/share/locale
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.604: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.604: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.604: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.604: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.604: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.604: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/input
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.604: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/output
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.604: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/autoload/input
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.604: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/autoload/output
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.625: application: easyeffects version: 6.1.2
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.626: pipe_manager: compiled with pipewire: 0.3.34
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.626: pipe_manager: linked to pipewire: 0.3.40
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.629: pipe_manager: core version: 0.3.40
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.629: pipe_manager: core name: pipewire-0
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.629: pipe_manager: found metadata: settings
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.632: pipe_manager: found metadata: default
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.632: pipe_manager: found metadata: route-settings
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.632: pipe_manager: Audio/Sink 41 alsa_output.pci-0000_00_1f.3.analog-stereo was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.632: pipe_manager: Audio/Source 42 alsa_input.pci-0000_00_1f.3.analog-stereo was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.632: pipe_manager: Audio/Sink 43 alsa_output.platform-snd_aloop.0.analog-stereo was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.632: pipe_manager: Audio/Source 44 alsa_input.platform-snd_aloop.0.analog-stereo was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.632: pipe_manager: Stream/Output/Audio 113 spotify was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.632: pipe_manager: spotify port 114 is connected to alsa_output.pci-0000_00_1f.3.analog-stereo port 45
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.633: pipe_manager: spotify port 115 is connected to alsa_output.pci-0000_00_1f.3.analog-stereo port 47
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.633: pipe_manager: Audio/Sink 103 easyeffects_sink was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.633: pipe_manager: Audio/Source/Virtual 98 easyeffects_source was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.634: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_00_1f.3.analog-stereo" }
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.634: pipe_manager: new metadata property: 0, default.configured.audio.source, Spa:String:JSON, { "name": "alsa_input.pci-0000_00_1f.3.analog-stereo" }
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.634: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_00_1f.3.analog-stereo" }
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.634: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "alsa_input.pci-0000_00_1f.3.analog-stereo" }
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.634: pipe_manager: new metadata property: 113, target.node, Spa:Id, 60
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.695: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.729: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.777: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.845: lv2_wrapper: http://lsp-plug.in/plugins/lv2/limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.861: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.876: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.876: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.901: lv2_wrapper: http://lsp-plug.in/plugins/lv2/mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.956: pipe_manager: Filter pe_soe_output_level, id = 94, was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.958: soe: output_level successfully connected to pipewire graph
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.959: pipe_manager: Filter pe_soe_spectrum, id = 81, was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.961: soe: spectrum successfully connected to pipewire graph
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.962: pipe_manager: Filter pe_soe_equalizer, id = 76, was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:12.964: soe: equalizer successfully connected to pipewire graph
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.018: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.051: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.098: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.166: lv2_wrapper: http://lsp-plug.in/plugins/lv2/limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.182: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.198: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.198: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.223: lv2_wrapper: http://lsp-plug.in/plugins/lv2/mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.276: pipe_manager: Filter pe_sie_output_level, id = 63, was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.278: sie: output_level successfully connected to pipewire graph
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.279: pipe_manager: Filter pe_sie_spectrum, id = 116, was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.281: sie: spectrum successfully connected to pipewire graph
easyeffects-INFO: 11:19:13.293: application: disabling global bypass
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.309: application_ui: Icon Theme breeze-dark detected
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.535: new default output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.536: pipe_manager: new metadata property: 113, target.node, Spa:Id, 103
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.536: pipe_manager: spotify port 114 is connected to easyeffects_sink port 102
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.536: pipe_manager: spotify port 115 is connected to easyeffects_sink port 100
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.545: new default input device: alsa_input.pci-0000_00_1f.3.analog-stereo
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.559: application: device alsa_card.pci-0000_00_1f.3 has changed its input route to: analog-input-rear-mic
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.559: application: device alsa_card.pci-0000_00_1f.3 has changed its output route to: analog-output-lineout
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.559: application: device alsa_card.platform-snd_aloop.0 has changed its input route to: analog-input
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.559: application: input autoloading: the target node name does not match the input device name
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.559: application: device alsa_card.platform-snd_aloop.0 has changed its output route to: analog-output
(easyeffects:7752): easyeffects-DEBUG: 11:19:13.559: application: output autoloading: the target node name does not match the output device name
(easyeffects:7752): easyeffects-DEBUG: 11:19:27.406: soe: output_level: new PipeWire blocksize: 8192
(easyeffects:7752): easyeffects-DEBUG: 11:19:53.335: pipe_manager: Stream/Output/Audio 120 Chromium (Freeworld) was added
(easyeffects:7752): easyeffects-DEBUG: 11:19:53.335: pipe_manager: new metadata property: 120, target.node, Spa:Id, 103
(easyeffects:7752): easyeffects-DEBUG: 11:19:53.346: pipe_manager: Chromium (Freeworld) port 109 is connected to easyeffects_sink port 102
(easyeffects:7752): easyeffects-DEBUG: 11:19:53.346: pipe_manager: Chromium (Freeworld) port 92 is connected to easyeffects_sink port 100
(easyeffects:7752): easyeffects-DEBUG: 11:19:53.618: soe: output_level: new PipeWire blocksize: 1024
(easyeffects:7752): easyeffects-DEBUG: 11:20:09.699: pipe_manager: Stream/Output/Audio spotify was removed
(easyeffects:7752): easyeffects-DEBUG: 11:20:09.705: pipe_manager: Stream/Output/Audio Chromium (Freeworld) was removed

</details>

**Comment by wwmm** [comment] 2021-11-19 14:33
Duplicate of #1001. A solution for that still has to be found.

**Closed by wwmm** 2021-11-19 14:33 UTC
