### ISSUE TITLE
Feature: Sort equalizer bands by frequency, and/or manually reorder?

### ISSUE THREAD

**Issue by nyanpasu64** [wwmm/easyeffects#1733] opened 2022-08-06 22:04 UTC
### EasyEffects Version

6.2.8

### What package are you using?

Flatpak (Flathub)

### Distribution

Void Linux

### Describe the bug

When adjusting a complex equalization preset, I often like to create fine-tuned bands at specific frequencies and widths, rather than purely adjusting the amplitude of preset bands. As a result, over time I often end up with bands out of frequency order, making it hard to see at a glance whether low or high frequencies are brought up or down.

### Expected Behavior

Ideally there would be a button to sort bands in frequency order (after adding bands), and perhaps even a way to move undesired bands to the end of the list (either setting the frequency to 20 KHz then sorting, or drag-and-drop bands to reorder them) so you can decrease the band count.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment] 2022-08-06 22:16
This will require some serious refactoring in the equalizer window code. For performance reasons I already intended to actually use a listview container instead of a GtkBox. But I have no idea when I will be able to focus on this. With a listview handling the bands sorting may become possible. Doing this with a GtkBox holding the band widgets will be a pain.

**Comment by nyanpasu64** [comment] 2022-08-06 22:21
Is it possible to sort the underlying data structure holding bands (as if you exported to JSON and sorted the bands there), then rebuild the UI from the sorted bands (as if you loaded the preset from disk)?

I looked into sorting the JSON presets by hand, but it seemed like a nontrivial amount of work I'd have to write a JSON-parsing program for, rather than quickly sorting by hand in a text editor (the JSON contains band0, band1, then band10 through band19, _then_ band2 and so on, plus you duplicate bands for left and right channels). I may get around to it at some point, I hope, but I'm not super well versed on JSON libraries.

**Comment by Digitalone1** [comment] 2022-08-07 08:24
We have an APO format import feature. Could you do it in APO format? Its syntax is not too hard to write.

Maybe from the documentation is seems hard:

https://sourceforge.net/p/equalizerapo/wiki/Configuration%20reference/

But if you download an APO preset and look inside it, the format is pretty straightforward.

https://sourceforge.net/projects/peace-equalizer-apo-extension/files/Configurations%20%28presets%29/

**Comment by wwmm** [comment] 2022-08-07 14:15
>plus you duplicate bands for left and right channels).

It isn't really duplicated. We use an equalizer that is capable of applying different settings for each channel. But unless you enable the `split channels` mode you only have to worry about what it is in the left channel. When `split channels` is disabled EE will map the values from the left channel to the right channel internally.

I think that the workaround suggested by @Digitalone1 will be simpler to do but in case you want to edit the json files directly you will have to rename the bands section accordingly. For example after iterating through the bands and finding which one has the smallest frequency rename the band section name to `band0`. Once you find the next smallest frequency rename its band section to `band1` and so on. As EE code is right now it creates the widgets in the band index order.

**Comment by polarathene** [comment] 2022-08-27 23:33
As a new user, I did find the current UX for this a bit frustrating. I had been tweaking the bands, and later decided I would like to remove a band, but I couldn't find a way to delete a specific one, only decrement from the right..

So a quick fix, I'd just move the band I didn't want to the end maybe (_not that this would be intuitive since I would have thought the bands were always sorted by frequency_), but that wasn't possible via UI either.

**Comment by wwmm** [comment] 2022-08-27 23:59
>but I couldn't find a way to delete a specific one

That is something that should be possible to do. But we definitely have to be careful.  under the hoods we use the equalizer from Linux Studio Plugins. This equalizer has a fixed number of bands and each of then has its own string id for each parameter. When you "create a band" what is actually happening is that we bind the widgets to a given key in our gsettings database. And the same is done from the plugin to the database. When deleting bands in the middle we have to somehow keep track of what is going on so we do not bind multiple widgets to the same band. Doable... But a little tricky to handle this.

**Comment by bhack** [comment] 2022-10-04 13:06
Also autoeq imported files are not sorted by freq so It is a little bit counterintuitive to adapt a bit high or low frequencies searching for the right column.

**Comment by Digitalone1** [comment] 2022-10-04 13:11
> Also autoeq imported files are not sorted by freq so It is a little bit counterintuitive to adapt a bit high or low frequencies searching for the right column.

Autoeq? As far as I know we have only import for APO and GraphicEq.

Anyway, can't you just sort the config file (APO or GraphicEq)? LSP equalizer is bound to gsettings key, so it's difficult from code side to sort the bands.

**Comment by bhack** [comment] 2022-10-04 13:16
> Autoeq? As far as I know we have only import for APO and GraphicEq.

Yes If you see they are not sorted:
https://github.com/jaakkopasanen/AutoEq/tree/master/results

I think that we can sort it at https://github.com/wwmm/easyeffects/blob/782ffe0078e357591d2d713e218e4516a213aa2b/src/equalizer_ui.cpp#L303

**Comment by Digitalone1** [comment] 2022-10-04 13:35
It's hard to sort them there because we scan the file line by line.

It's easier if you edit the file manually.

**Comment by bhack** [comment] 2022-10-04 14:18
> It's hard to sort them there because we scan the file line by line.

I don't understand what is the problem... You need only to add the operator to your `APO_band` struct:

```c++
#include <iostream>
#include <numbers>
#include <vector>

using namespace std;

struct APO_Band {
  std::string type;
  float freq = 1000.0F;
  float gain = 0.0F;
  float quality = (1.0F / std::numbers::sqrt2_v<float>);
    bool operator<(const APO_Band& a) const
    {
        return freq < a.freq;
    }
};


int main() {
    std::vector<struct APO_Band> bands;
    sort( bands.begin(), bands.end());

}
```

**Comment by Digitalone1** [comment] 2022-10-04 14:43
Nice. Since we try to adhere to C++20, maybe it's better to overload `<=>`

Then add the sort after the empty check.

```c++
  eq_file.close();

  if (bands.empty()) {
    return false;
  }

  std::sort(bands.begin(), bands.end());
```

**Comment by nyanpasu64** [comment] 2022-10-04 14:50
I suppose I'd use a stable sort to keep different filter types and Q values with the same corner/center frequency in their original order.

**Comment by Digitalone1** [comment] 2022-10-04 14:57
An example (if I intended it right):

```c++
bool operator<=>(const APO_Band& a) const {
  if (freq < a.freq) {
    return -1
  }

  if (freq > a.freq) {
    return 1;
  }

  return 0;
}
```

**Comment by bhack** [comment] 2022-10-04 15:34
In c++20 you can also just use this without changing the struct:

```c++ 
std::ranges::sort(bands, {}, &APO_Band::freq);
```

**Comment by Digitalone1** [comment] 2022-10-04 16:10
Okay, can you test it and make the pull request?

Just be careful to place the sort after the empty check.

**Comment by bhack** [comment] 2022-10-04 16:31
> Okay, can you test it and make the pull request?

I would like but you don't have a clear CONTRIBUTING.md to setup the dev environment. It will be probably require more time to figure out how to setup the dev-env that this single line.

**Comment by vchernin** [comment] 2022-10-04 16:45
> I would like but you don't have a clear CONTRIBUTING.md to setup the dev environment. It will be probably require more time to figure out how to setup the dev-env that this single line.

It could be more clearly indicated, but [this wiki page](https://github.com/wwmm/easyeffects/wiki/Installation-from-Source) has all the instructions to build EasyEffects. I recommend gnome builder from flathub for the most straightforward experience.

**Comment by wwmm** [comment] 2022-10-04 16:59
>I would like but you don't have a clear CONTRIBUTING.md to setup the dev environment.

Usually what I do once inside the source code folder is

1. glib-compile-schemas data/schemas/
2. meson _build
3. cd _build
4. ninja
5. cd src
6. source ../../util/environmental_variables.sh
7. If everything went well `./easyeffects` should show EasyEffects.

**Comment by bhack** [comment] 2022-10-04 17:03
Does `glib-compile-schemas` install all the dependencies?

**Comment by wwmm** [comment] 2022-10-04 17:05
>Does glib-compile-schemas install all the dependencies?

No. It doesn't install any dependency. We use `GSettings` for our database and it needs its xml schemas to eb compiled to a binary file. Usually this is done in a system folder by the package management tool. But as I run in a custom folder while developing I have to do this myself. As well as set some environmental variables. What is done by `environmental_variables.sh`

**Comment by bhack** [comment] 2022-10-04 17:07
Isn't better to just add a `Dockerfile` and eventually a `.devcontainer` in the repository? It will make the contribution supereasy..

**Comment by Digitalone1** [comment] 2022-10-04 17:07
For compiling dependencies, take a look at the [PKGBUILD](https://github.com/wwmm/easyeffects/blob/master/PKGBUILD).

`'meson' 'itstool' 'appstream-glib' 'git'`

**Comment by wwmm** [comment] 2022-10-04 17:08
>Isn't better to just add a Dockerfile and eventually a .devcontainer in the repository? It will make the contribution supereasy..

Assuming someone is willing to do this and making sure it works. As I do not use Docker I do not have any idea about how to do it. And I also do not have the time this is probably going to require to be put in place and maintained.

**Comment by vchernin** [comment] 2022-10-04 17:25
I really don’t see a point of a docker container setup when in terms of practical usability Flatpak is probably easier, since Flatpak is ultimately just a container/sandbox under the hood like docker except focused on gui apps. The whole point is to be able to build with as little manual hassle with dependencies and build system commands as possible like with gnome builder, so I think that is best for new contributors. 

But if someone wants a dev container file if they prefer docker/podman I don’t see why not.

**Comment by bhack** [comment] 2022-10-04 17:28
> I don’t really see a point of a docker container setup when in terms of practical usability Flatpak is probably easier (and already maintained here), since Flatpak is ultimately just a container/sandbox under the hood like docker except focused on gui apps. The whole point is to be able to build with as little manual hassle with dependencies and build system commands as possible like with gnome builder, so I think that is best for new contributors.

The main difference is that you need to compile all the dependencies instead to have it OS pre-installed  "-dev" (like in Dockerfile).
So for occasional PRs it is a quite heavy overhead.

What we need to do with the flathub Gtkbuild after compilation to run it?

**Comment by vchernin** [comment] 2022-10-04 17:35
> So for occasional PRs it is a quite heavy overhead.

Yeah that is true, although it is at least alleviated with a local build cache. Buildstream (used for flatpak runtimes) has a concept of a cache that can be shared so you don’t need to build for hours. But that doesn’t exist for flatpak builder unfortunately.

> What we need to do with the flathub Gtkbuild after compilation to run it?

Flathub gtk build? If you mean to build EasyEffects you must first ensure the plugins are installed, then build, then run.
```
flatpak install flathub org.freedesktop.LinuxAudio.Plugins.LSP//22.08 org.freedesktop.LinuxAudio.Plugins.ZamPlugins//22.08 org.freedesktop.LinuxAudio.Plugins.MDA//22.08 -y
flatpak-builder build-dir --user --install util/flatpak/com.github.wwmm.easyeffects.Devel.json --force-clean --ccache
flatpak run com.github.wwmm.easyeffects.Devel
```

**Comment by bhack** [comment] 2022-10-04 17:40
It seems something is missing:
`lv2_wrapper.cpp:63	Could not find the plugin: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr`

**Comment by wwmm** [comment] 2022-10-04 17:55
:It seems something is missing: lv2_wrapper.cpp:63 Could not find the plugin: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr

The equalizer needs the `Linux Studio Plugins` package. At least on Arch Linux it is named `lsp-plugins`.

**Comment by bhack** [comment] 2022-10-04 18:02
I'am running the master prepared `flatpack`:

` flatpak run com.github.wwmm.easyeffects.Devel`

**Comment by bhack** [comment] 2022-10-04 18:17
> The equalizer needs the Linux Studio Plugins package. At least on Arch Linux it is named lsp-plugins.

Yes it was installed with @Digitalone1 command:
`flatpak install flathub org.freedesktop.LinuxAudio.Plugins.LSP//22.08 org.freedesktop.LinuxAudio.Plugins.ZamPlugins//22.08 org.freedesktop.LinuxAudio.Plugins.MDA//22.08 -y`

But I have:
`flatpak run com.github.wwmm.easyeffects.Devel`
` lv2_wrapper.cpp:63 Could not find the plugin: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr`

**Comment by bhack** [comment] 2022-10-04 18:42
Stable `flatpak run com.github.wwmm.easyeffects` instead it is working correctly.

**Comment by vchernin** [comment] 2022-10-04 19:04
Following the instructions I do not see that warning. Is your local repo on the latest commit in master?

**Comment by bhack** [comment] 2022-10-04 19:05
> Following the instructions I listed above I do not see that warning. Is your local repo on the latest commit in master?

Yes e9763f2cfcc47b46b2249773155cc7fb60919304

**Comment by vchernin** [comment] 2022-10-04 19:07
I am unsure how that could not work… did the flatpak-builder command give any warnings? What distro, flatpak and flatpak-builder do you have?

**Comment by vchernin** [comment] 2022-10-04 19:09
One idea, what does does

`flatpak list | grep easyeffects`
and
`flatpak list | grep LSP`
output?

**Comment by bhack** [comment] 2022-10-04 19:11
I see that the metadata is very different:

`flatpak info -m com.github.wwmm.easyeffects`

`flatpak info -m com.github.wwmm.easyeffects.Devel`

**Comment by bhack** [comment] 2022-10-04 19:15
Are you sure that the Gtk builder build is generating the complete/correct metadata?

**Comment by bhack** [comment] 2022-10-04 19:23
> flatpak list | grep easyeffects
and
flatpak list | grep LSP
output?

`LSP	org.freedesktop.LinuxAudio.Plugins.LSP	1.2.3	22.08	flathub	user`

`Devel	com.github.wwmm.easyeffects.Devel		master	devel-origin	user`

**Comment by bhack** [comment] 2022-10-04 19:31
@vchernin Confirmed the metadata is not complete with Gtk builder...
I've manually patched the metadata:

```
[Extension org.freedesktop.LinuxAudio.Plugins]
directory=extensions/Plugins
no-autodownload=true
subdirectories=true
add-ld-path=lib
merge-dirs=lv2
version=21.08

[Extension org.freedesktop.LinuxAudio.Plugins.LSP]
directory=extensions/Plugins/LSP
subdirectories=true
add-ld-path=lib
merge-dirs=lv2
version=21.08

[Extension org.freedesktop.LinuxAudio.Plugins.MDA]
directory=extensions/Plugins/MDA
subdirectories=true
add-ld-path=lib
merge-dirs=lv2
version=21.08

[Extension org.freedesktop.LinuxAudio.Plugins.ZamPlugins]
directory=extensions/Plugins/ZamPlugins
subdirectories=true
add-ld-path=lib
merge-dirs=lv2
version=21.08

[Extension com.github.wwmm.easyeffects.Locale]
directory=share/runtime/locale
autodelete=true
locale-subset=true

[Extension com.github.wwmm.easyeffects.Debug]
directory=lib/debug
autodelete=true
no-autodownload=true
```

**Comment by vchernin** [comment] 2022-10-04 19:35
Which parts did you patch? 
this is what I see for a build on the latest master:

```
[Application]
name=com.github.wwmm.easyeffects.Devel
runtime=org.gnome.Platform/x86_64/43
sdk=org.gnome.Sdk/x86_64/43
command=easyeffects

[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=xdg-run/pipewire-0:ro;

[Environment]
LV2_PATH=/app/lib/lv2:/app/extensions/Plugins/lv2

[Extension org.freedesktop.LinuxAudio.Plugins]
directory=extensions/Plugins
no-autodownload=true
subdirectories=true
add-ld-path=lib
merge-dirs=lv2
version=22.08

[Extension org.freedesktop.LinuxAudio.Plugins.LSP]
directory=extensions/Plugins/LSP
subdirectories=true
add-ld-path=lib
merge-dirs=lv2
version=22.08

[Extension org.freedesktop.LinuxAudio.Plugins.MDA]
directory=extensions/Plugins/MDA
subdirectories=true
add-ld-path=lib
merge-dirs=lv2
version=22.08

[Extension org.freedesktop.LinuxAudio.Plugins.ZamPlugins]
directory=extensions/Plugins/ZamPlugins
subdirectories=true
add-ld-path=lib
merge-dirs=lv2
version=22.08

[Extension com.github.wwmm.easyeffects.Devel.Locale]
directory=share/runtime/locale
autodelete=true
locale-subset=true

[Extension com.github.wwmm.easyeffects.Devel.Debug]
directory=lib/debug
autodelete=true
no-autodownload=true

[Build]
built-extensions=com.github.wwmm.easyeffects.Devel.Locale;com.github.wwmm.easyeffects.Devel.Debug
```

**Comment by bhack** [comment] 2022-10-04 19:36
The gtk builder generated is only

```
[Application]
name=com.github.wwmm.easyeffects.Devel
runtime=org.gnome.Platform/x86_64/43
sdk=org.gnome.Sdk/x86_64/43
command=easyeffects

[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=xdg-run/pipewire-0:ro;

[Environment]
LV2_PATH=/app/lib/lv2:/app/extensions/Plugins/lv2
```

**Comment by vchernin** [comment] 2022-10-04 19:38
What is gtk builder? do you mean gnome builder? if so there is a known issue where it does not use the flatpak plugin extensions properly.

**Comment by bhack** [comment] 2022-10-04 19:40
Yes I meant gnome builder

**Comment by bhack** [comment] 2022-10-04 19:44
>  if so there is a known issue where it does not use the flatpak plugin extensions properly.

We need to document it or this info will be lost.

**Comment by vchernin** [comment] 2022-10-04 19:46
it is documented here: https://github.com/wwmm/easyeffects/wiki/Installation-from-Source#gnome-builder

**Comment by bhack** [comment] 2022-10-04 19:56
Yes but it is really not clear the effect and that instead it is required to execute other manual commands to prepare and install the dev flatpack package...

**Comment by vchernin** [comment] 2022-10-04 20:03
I have edited it to hopefully be clearer on the issue, please feel free to edit it or give suggestions if it can be clarified further.

**Comment by bhack** [comment] 2022-10-04 20:04
Thanks

**Comment by bhack** [comment] 2022-10-04 21:03
Please note that we could have some minor usability issues after https://github.com/wwmm/easyeffects/pull/1872:

Sorting could go to impact the UI in the case of a reduction to a subset of N filters as suggested in Autoeq executed in the Easyeffect UI:

E.g.
https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/1MORE%20Triple%20Driver%20Over%20Ear#parametric-eqs

**Comment by Digitalone1** [comment] 2022-10-04 21:12
I didn't get it fully. Are you saying that moving many bands is taking much time? Did you test it?

**Comment by bhack** [comment] 2022-10-04 21:21
No I meant that if you cut the number of filters from the UI, in the autoeq case, it need to work in the original unsorted order.

But instead after the PR I suppose we cut filters in the UI in the sorted orders right?

**Comment by Digitalone1** [comment] 2022-10-04 21:29
Okay, I didn't understand. 

If you reduce the bands, the last one in the UI is unset.

**Comment by Digitalone1** [comment] 2022-10-04 21:33
And, I think we need another change.

Since we have a maximum of 32 bands, the sort algorithm may do an extra unneeded work if the extracted bands from the config file are more than 32.

We should check if the size is greater than 32. If true, resize to 32, than sort.

I will do it when have time. Please do not close this issue.

**Comment by bhack** [comment] 2022-10-04 21:53
> If you reduce the bands, the last one in the UI is unset.

Yes this is ok for manual filters but it could go to lower the usability with Autoeq imported ones.

**Comment by Digitalone1** [comment] 2022-10-04 22:25
> Yes this is ok for manual filters but it could go to lower the usability with the Autoeq imported ones.

So I suppose it was better to keep them in the original order.

**Comment by bhack** [comment] 2022-10-04 22:37
> So I suppose it was better to keep them in the original order.

It is a particular case as e.g. with autoeq you could have an indication like this for Parametric EQ:
> You can use filters 1-5 or 1-10. 
But generally you will do this once and more probably for very constrained device.

We need to figure out what solution is better by an usability point of view as we could also choice to import an user limited number of filters and sort.

**Comment by nyanpasu64** [comment] 2022-10-04 22:51
Regardless of whether you sort when importing filters (I think it's unnecessary if we have a manual sort button, plus sometimes you don't want to sort as described here), I want a way to sort frequency bands in the editor itself, both for imported filters and those entered by hand. Perhaps we should sort 0 dB or muted filter bands after ones which produce a sound (this could be toggled by a checkbox, unless it's too confusing for users and we need to pick either on or off).

Either way, it would be nice to be able to drag and drop individual filter bands, so I can take a specific filter and move it into place before tuning it. Though this isn't strictly *necessary*, since if we only have sorting but not dragging, you could set a frequency and nonzero dB value to a disabled band after the enabled bands, them sort the bands (less intuitive but works).

**Comment by bhack** [comment] 2022-10-04 22:55
> Either way, it would be nice to be able to drag and drop individual filter bands, so I can take a specific filter and move it into place before tuning it. Though this isn't strictly necessary, since if we only have sorting but not dragging, you could set a frequency and nonzero dB value to a disabled band after the enabled bands, them sort the bands (less intuitive but works).

Probably it is easier to disable/deselect filters before executing the sort.

**Comment by Digitalone1** [comment] 2022-10-04 23:03
Maybe it's better to revert all and write a sort method for the whole plugin to be used only when needed.

The first thing that comes to my mind. Define a struct for single band, make a vector, copy all values, sorts
 and apply.

Of a self-made sort which swaps bands where needed (make a temporary copy in a struct, then rewrite the keys). 

In either cases we could exclude the disabled bands. Dragging is difficult to do. Take in consideration that equalizer controls are bound to gsettings keys.

**Comment by wwmm** [comment] 2022-10-05 00:02
I think that while the equalizer bands are handled as they are now we should not try to implement sorting on them. This should wait until the bands are handled through a listview. The performance of the current approach is really bad. Implementing sorting now just to have to do it in a completely different way in the future is wasting efforts.

>Take in consideration that equalizer controls are bound to gsettings keys.

And there is this and the fact that the mapping has to go to the Linux Studio Plugins equalizer ports too. Sorting is not going to be so easy to do right.

**Comment by Digitalone1** [comment] 2022-10-05 06:01
I though about this and come up with the following idea.

We miss the ability to sort the gsettings keys. So we should find a workaround to sort them through a different structure.

* Therefore define an EqualizerBand structure containing all the controls of the LSP Equalizer Bands (with default value same as the relative gsettings keys);
* Define in the Equalizer class an array 32 of the above structure;
* Bind the values of the above array to gsettings keys, so it's synced with the current used LSP Equalizer settings;
* Add a button in the EqualizerUI to sort the bands which callback the stable_sort function on the array of EqualizerBand;
* We could overload <=> to define a custom order based on Filter type and Frequency value (stable_sort will sort on  it).

@wwmm do you think it's a good solution? It's independent from the listview feature because the listview will be used to move bands manually, but the user could still sort all the bands automatically with one click (considering also that, having 20+ bands not sorted, moving them manually for sorting is overkill).

**Comment by wwmm** [comment] 2022-10-05 12:58
>do you think it's a good solution?

I am skeptical about how viable and bug free this approach is really going to be. If I understood what you want you intend to bind widgets to a fixed helper structure and the GSettings database keys to another helper structure while a glue code acts as the man in the middle making sure that each signal goes to where it should go. As the mapping has to be bidirectional the chances of breaking things that are working seem a little high.

**Comment by wwmm** [comment] 2022-10-05 13:00
>It's independent from the listview feature because the listview will be used to move bands manually,

Not necessarily. The ListView could have automatic sorting too.

**Comment by Digitalone1** [comment] 2022-10-05 13:10
> I am skeptical about how viable and bug free this approach is really going to be. If I understood what you want you intend to bind widgets to a fixed helper structure and the GSettings database keys to another helper structure while a glue code acts as the man in the middle making sure that each signal goes to where it should go. As the mapping has to be bidirectional the chances of breaking things that are working seem a little high.

No, only the array of bands to the gsettings key. Is that possible? If we bind lv2 ports to widgets, I assume we could be able to bind gsettings key to values in an array (bidirectional).

> Not necessarily. The ListView could have automatic sorting too.

Well, that would be the ideal solution. A listview sorting on a pre-defined order. The sorting should not be really automatic. I mean, only when the user click the sorting button.

**Comment by wwmm** [comment] 2022-10-05 13:20
>No, only the array of bands to the gsettings key. Is that possible? If we bind lv2 ports to widgets, I assume we could be able to bind gsettings key to values in an array (bidirectional).

It is but it would have the same limitation. Remember that the our bindings to the lv2 ports are not bidirectional. In other words if the ports are update by the plugin or something else the changes are not propagated to the database. As things are right now information goes only from GSettings to the lv2 ports and not the other way around.

But in the widgets things are bidirectional. If we change them the database has to be updated and if the database changes because a preset was loaded the widgets have to see that.

>Well, that would be the ideal solution. A listview sorting on a pre-defined order. The sorting should not be really automatic. I mean, only when the user click the sorting button.

Sure. But a manual sorting that acts independently of what the ListView is doing does not seem a good idea. Remember that the ListView is free to change the widgets bindings as it desires. Ideally we should let the sort to it.

**Comment by wwmm** [comment] 2022-10-05 13:24
>But a manual sorting that acts independently of what the ListView is doing does not seem a good idea

It is probably possible to trigger the sorting with a button. But it is probably better to let the ListView do it instead of using an external code.

**Comment by wwmm** [comment] 2022-10-05 13:42
>So this is not the ideal solution because the user may not want to sort the bands. I mean we need something to sort them only after clicking a button.

Although I never tried I imagine there is a way to manually tell the ListView when it should do the sorting. It would be weird if gtk only allows this to happen automatically. I really hope this is not the case.

My point is that as the ListView is free to create and destroy widgets when it thinks it should the sorting should be it's responsibility. Independently of whether it's triggered automatically or manually.

**Comment by Digitalone1** [comment] 2022-10-05 14:09
But the listview is only changing the widget order or also the values of gsettings key?

This is important because if I sort the bands and then save the preset, I expect to get it sorted also in the preset (which means it's sorted in gsettings also). And at the next load, I get the bands already sorted.

If the listview only changes the widget order, but every widget is still bound to the previous keys, it's not what we expect. We need something to sort the gsettings key. In other words, if band0 > band1, I expect band0 in gsettings to assume band 1 values and band1 in gsettings to assume previous band 0 values.

**Comment by wwmm** [comment] 2022-10-05 15:02
>But the listview is only changing the widget order or also the values of gsettings key?

As far as I remember the input model is not modified when the ListView does the sorting. So in order to do what you want the model given as input to the ListView would have to be manually sorted. What in turn would trigger an automatic ListView update where the widgets would be moved to the correct order.

In any case as this is still better than custom auxiliary structures because the sorting would happen in the ListView model data. The property bindings would still be handled by the ListView factory callbacks. We won't collide with the widget management done by the ListView.

**Comment by wwmm** [comment] 2022-12-30 15:39
I have updated our master branch with `Sort Bands` button in our equalizer. As things are right now the sorting is temporary. The user will have to click on this button whenever he wants to see the bands sorted by frequency.

**Comment by wwmm** [comment] 2023-03-19 15:22
With the last changes done by @Digitalone1 I think we can finally close this issue.

**Closed by wwmm** 2023-03-19 15:22 UTC
Labels: enhancement
