### ISSUE TITLE
Some issues and thoughts on EasyEffects

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#999] opened 2021-07-07 17:07 UTC
Congratulations @wwmm. Great work.

I'm testing the new version and it's a big improvement. I'd like to list some little issues and observations.

- [x] There are some issues with locale just like in PE versions previous to 4.8.3. In Italian localization some decimals are with point, others with comma.
- [x] Equalizer bands are not centered and they stretch the main window width. Should be centered (just like in crystalizer) and wrapped in a frame so they can be slided horizontally without stretching the window.
- [x] Bass Enhancer credit does not start with uppercase: "using" rather than Using.
- [x] Icon notification in output level meter exceeding 0 db should be put at right, avoiding level numbers to be moved when the icon is shown. 
- [x]  The new version spawns all the plugins nodes in Pipewire graph. This is not a big issue right now, but maybe in the future this could be worked around to found a method to spawn only the used plugins. You can see this in Helvum (see screenshot). This could be tricky in the future if an utility like pavucontrol is made for Pipewire (too many nodes to handle for the user). I like the way how carla-rack jack host works, having plugins inside and not showing them individually, but I know this is the cost of using pipewire filters and getting rid of gstreamer.

<details>
<summary> Helvum screenshot </summary>

![Schermata del 2021-07-07 12-46-46](https://user-images.githubusercontent.com/25790525/124800103-8ca88280-df55-11eb-9baf-0c35e898e81e.png)

</details>

**Comment by wwmm** [comment] 2021-07-07 17:30
>There are some issues with locale just like in PE versions previous to 4.8.3. In Italian localization some decimals are with point, others with comma.

I admit I did not do many localization tests. Maybe the fact gtkmm4 is handling them in a different way is related to this increase in inconsistency

>Equalizer bands are not centered and they stretch the main window width. Should be centered (just like in crystalizer) and wrapped in a frame so they can be slided horizontally without stretching the window.

Someone talked about that in the gtk4 port issue. But I decided to let this for the next releases so I can think about this more carefully. Different from past releases now the top container has the scrollwidget insted of every plugin having its own. What was an overkill. But now I have to see if a "scrollwidget inside a scrollwidget" is something that is going to work well.

>Bass Enhancer credit does not start with uppercase: "using" rather than Using.

Thanks. I updated the branch now.

>The new version spawns all the plugins nodes in Pipewire graph. This is not a big issue right now, but maybe in the future this could be worked around to found a method to spawn only the used plugins. You can see this in Helvum (see screenshot). This could be tricky in the future if an utility like pavucontrol is made for Pipewire (too many nodes to handle for the user). I like the way how carla-rack jack host works, having plugins inside and not showing them individually, but I know this is the cost of using pipewire filters and getting rid of gstreamer.

Yes. It is bad. I've noticed that from the beginning. The problem is that reloading the filters on the fly would complicate the approach considerably. Maybe an easy way to improve this will come to me in the future. But at the same time I think it will be unavoidable for tools like Pavucontrol to implement some kind of blocklist. It really does not make sense in their context to show tons of filters for the user without providing a way to actually use them. Most people will want to see only sinks and sources and no filter. So even if there is only 1 being shown people will complain.

**Comment by wwmm** [comment] 2021-07-07 17:30
>Congratulations @wwmm. Great work.

Thanks! :-)

**Comment by Mlocik97** [comment] 2021-07-07 19:55
I still somehow find "EasyEffects" name not fit for this project... I was more thinking about "AudaEffects" or "SoundTweaker" Or something else,...

**Comment by Mlocik97** [comment] 2021-07-08 16:19
Btw. about presets in Wiki, today is year 2021, I think, presets for old PE <= 3 can be deleted, because they are from 2017, they are already 4 years old, and wiki is starting to be too noise.

**Comment by wwmm** [comment] 2021-07-08 17:01
>Btw. about presets in Wiki, today is year 2021, I think, presets for old PE <= 3 can be deleted, because they are from 2017, they are already 4 years old, and wiki is starting to be too noise.

Yes. The wiki has been in need of a major update for a long time. The problem is that I will always choose to use my free time working in the code because I think that writing the wiki or the manual is boring. So the situation got in this bad state.

Some years ago I changed the wiki write permission to public hoping that its development would magically become more dynamic as anyone would be able to update it. But that clearly did not happen. I wonder if there is better way to collaboratively handle this situation.

**Comment by wwmm** [comment] 2021-07-08 17:03
I also wonder how many users actually know about this wiki. In its first years it seemed to me that some people never did not even knew about its existence.

**Comment by wwmm** [comment] 2021-07-09 17:00
>Equalizer bands are not centered and they stretch the main window width. Should be centered (just like in crystalizer) and wrapped in a frame so they can be slided horizontally without stretching the window.

I updated the master branch with some improvements  in the equalizer interface. It should be fine now. But let me know what you think.

**Comment by wwmm** [comment] 2021-07-10 00:31
>The new version spawns all the plugins nodes in Pipewire graph. This is not a big issue right now, but maybe in the future this could be worked around to found a method to spawn only the used plugins. You can see this in Helvum (see screenshot). This could be tricky in the future if an utility like pavucontrol is made for Pipewire (too many nodes to handle for the user). I like the way how carla-rack jack host works, having plugins inside and not showing them individually, but I know this is the cost of using pipewire filters and getting rid of gstreamer.

I did a quick attempt today to improve this and it was a total failure. Lots of bugs were introduced when I tried to coonect/disaconnect the plugins from PipeWire ondemand. I am not sure what went wrong. I probably have to synchronize something somewhere. But it is clear that it is not going to be trivial to follow that path =/

**Comment by Digitalone1** [comment] 2021-07-10 09:17
> I updated the master branch with some improvements in the equalizer interface. It should be fine now. But let me know what you think.

It's OK now.

**Comment by damdam-kr** [comment] 2021-07-11 05:16
Hi. Pulseeffects used to have presets for equalizers. I cannot find that in easyeffects equalizer.

**Comment by wwmm** [comment] 2021-07-11 13:58
>Hi. Pulseeffects used to have presets for equalizers. I cannot find that in easyeffects equalizer.

For now they are not available. While reimplementing the equalizer interface they felt a little out of place. Those presets are meant for a 10 bands graphical equalizer but what we have is a 32 bands parametric equalizer. I think that at some point we will have to consider the integration of a simple 10 bands equalizer. Then it will make sense to have those presets.

**Comment by Digitalone1** [comment] 2021-07-12 07:32
> For now they are not available. While I was reimplementing the equalizer interface they felt a little out of place. Those presets are meant for a 10 bands graphical equalizer but what we have is a 32 bands parametric equalizer. I think that at some point we will have to consider the integration of a simple 10 bands equalizer. Then it will make sense to have those presets.

I don't think they are so much out of place, just select 10 bands and apply them. I thought you didn't add them because they were gstreamer presets.

If you want to integrate a new plugin because of different number of bands, consider to add the LSP Multiband Compressor 8x which is so much better than the existing Calf version used by EE.

**Comment by wwmm** [comment] 2021-07-12 15:08
>I don't think they are so much out of place, just select 10 bands and apply them. I thought you didn't add them because they were gstreamer presets.

I had this feeling because I probably would have to create a menu only for them. And they can only be used when the equalizer is working with 10 bands... Or maybe I was just tired and I didn't want to write more code... Maybe I will change my mind in the future. But for now I would like to keep the equalizer interface a little cleaner.

 >If you want to integrate a new plugin because of different number of bands, consider to add the LSP Multiband Compressor 8x which is so much better than the existing Calf MC version used by EE.

I have been thinking about that. Specially after reading an issue in the Calf page where they discuss problems in the crossover used by Calf multiband plugins. But the LSP multiband plugins have so much more parameters that I decided to let this for another moment. There is a fair amount of work involved. And the multiband compressor interface will have to be its design reconsidered when moving to the LSP plugins.

**Comment by Digitalone1** [comment] 2021-07-13 09:38
> I have been thinking about that. Specially after reading an issue in the Calf page where they discuss problems in the crossover used by Calf multiband plugins. But the LSP multiband plugins have so much more parameters that I decided to let this for another moment. There is a fair amount of work involved. And the multiband compressor interface will have to be its design reconsidered when moving to the LSP plugins.

Thanks to Pipewire and Carla I can test all lv2 plugins and comparing LSP and Calf MB Compressors at same settings I can hear that LSP is extremely superior in audio quality.

I think Linux community through EE deserves this Multiband Compressor. Gate and Limiter can stay to Calf, but MC should be switched to LSP. Already in the past you switched the Singleband Compressor from Calf to LSP. I could work on implementing it in the future when I have time. Any suggestions on how to design the GUI for GTK4? No Glade?

**Comment by wwmm** [comment] 2021-07-13 14:36
>Any suggestions on how to design the GUI for GTK4? No Glade?

Yes. No Glade. While doing the port I had to write more than 15000 lines of xml by hand. After a while it becomes a matter of copy and paste but until I got used to this new procedure it was annoying. And after all this work even if Glade is ported to gtk4 I won't use it anymore. Unless it becomes officially supported by the gtk developers. As long as it stays as a third party project this kind of situation may happen again in the future.

**Comment by Msouza91** [comment] 2021-07-14 16:41
> I had this feeling because I probably would have to create a menu only for them. And they can only be used when the equalizer is working with 10 bands... Or maybe I was just tired and I didn't want to write more code... I can change my mind in the future. But for now I would like to keep the equalizer interface a little cleaner.

Just sharing my 2 cents... I'm on Fedora and we are on PE 5.0.4 yet, loved the fact that I could use this function, but now I hope the update of the package takes a bit longer while you work this out since APO profiles are important to me because I use EQ profiles from AutoEQ to correct the output from my earphones and I can't listen to them without the correction anymore since I have ZSN Pro Xs and they are too boomy without it. I found the import UI simple enough to understand and it worked with the profile I have.

**Comment by wwmm** [comment] 2021-07-14 17:39
>since APO profiles are important to me because I use EQ profiles from AutoEQ to correct the output from my earphones and I can't listen to them without the correction anymore since I have ZSN Pro Xs and they are too boomy without it. I found the import UI simple enough to understand and it worked with the profile I have.

Hi @Msouza91! You can still import APO presets. That feature has even been improved recently #1003. What is not available are the built-in presets for musical genres like `rock, pop, classic, etc`.

**Comment by Digitalone1** [comment] 2021-07-15 06:57
Another little issue.

- [ ] Icon notification in output level meter exceeding 0 db should be put at right, avoiding level numbers to be moved when the icon is shown.

**Comment by wwmm** [comment] 2021-07-15 14:14
>Icon notification in output level meter exceeding 0 db should be put at right, avoiding level numbers to be moved when the icon is shown.

I did some tests with the warning icon at the right side and depending on the window width it forces the /players/plugins toggle buttons to be moved. What is just as annoying as moving the level labels =/

Ideally space for the icon should be reserved somehow without having to show it. But I do not know if this is possible.

**Comment by Digitalone1** [comment] 2021-07-15 17:11
> I did some tests with the warning icon at the right side and depending on the window width it forces the players/plugins toggle buttons to be moved. What is as annoying as moving the level labels =/
> 
> Ideally space for the icon should be reserved somehow without having to show it. But I do not know if this is possible.

A workaround could be always show the icon, but make it transparent when the levels are below 0 db. I'd like to test, but without glade I don't even know where to start. It's there a documentation for GTK4 GUI?

**Comment by wwmm** [comment] 2021-07-15 21:53
> Isn't there a documentation for GTK4 GUI?

I have been using two sites
```
https://devdocs.io/gtk~4.0/
https://developer.gnome.org/gtk4/4.0/
```
But they may be outdated

>or maybe easier, a different icon when levels are below 0. An image meaning something is OK.

It would work. But it feels a little redundant considering that the level meters are there all the time too.

**Comment by wwmm** [comment] 2021-07-15 22:19
I am looking at LSP multiband compressor parameters 
```
/usr/lib/lv2/lsp-plugins.lv2/mb_compressor_stereo.ttl 
https://lsp-plug.in/?page=manuals&section=mb_compressor_stereo
```
and there is even more than I initially thought. Each band band has its own sidechain. This makes it obviously even more powerful but also makes it tougher to integrate. I am not sure when I will have time to try to use it but it is clear that this is a task that it is going to take a while to be finished.

**Comment by Mlocik97** [comment] 2021-07-15 22:20
Mainly I think, it better to solve it the way it will "reserve" place for warning icon, instead putting there another "invisible" icon that just takes more KB.

**Comment by Digitalone1** [comment] 2021-07-15 22:29
> I am looking at LSP multiband compressor parameters
> 
> ```
> /usr/lib/lv2/lsp-plugins.lv2/mb_compressor_stereo.ttl 
> https://lsp-plug.in/?page=manuals&section=mb_compressor_stereo
> ```
> 
> and there is even more than I initially thought. Each band has its own sidechain. This makes it obviously even more powerful but also makes it tougher to integrate. I don't know when I will have time to try to use it but it is clear that this is a task that it is going to take a while to be finished.

I'm using it in Carla. The difficulty is that it has more parameters, but can be configured like the calf mbc. The quality is very high. I had an idea on how to implement it, but the fact that I can't use glade is big limitation.

**Comment by wwmm** [comment] 2021-07-15 22:34
>but can be configured like the calf mbc

From a usability point of view the difference is small. But under the hood everything is different. The parameters names are different so the gsettings bindings will have to change. And as it has more parameters the gsettigns schema has to grow accordingly. The classes handling he multiband compressor presets will also have to grow, etc. The graphical interface is just part of the work. It can be done. But as I am getting to the end of my vacations it may take some time until I start to look at this.

**Comment by Digitalone1** [comment] 2021-07-16 06:09
https://devdocs.io/gtk~4.0/ch39s04

The solution is opacity CSS property. The icon is always shown. Default CSS opacity property is set to 0 and when output level is above 0 db, the same property is switched to 1.

**Comment by Mlocik97** [comment] 2021-07-16 06:41
You can use CSS? "Display: none;"

Dňa pi, 16. júl 2021, 8:09 Giusy Digital ***@***.***>
napísal(a):

**Comment by Mlocik97** [comment] 2021-07-16 06:46
You can use CSS? "Display: none;"

**Comment by Mlocik97** [comment] 2021-07-16 06:47
Gmail mobile + Github = expose my authentification token. Are You fucking kidding me?

**Comment by Digitalone1** [comment] 2021-07-16 06:51
> You can use CSS? "Display: none;"

No, you can't, but it's the same happening now, not showing the icon when levels are below 0 and the space is not reserved. With opacity property the icon is always there and the space is reserved.

**Comment by Mlocik97** [comment] 2021-07-16 06:59
oh right... so You don't have something like this:

```html
<div>
    <icon />
</div>

<style>
    div {
        height: 50px;
        width: 50px;
    }
    icon {
        display: none;
    }
</style>
```

in GTK way. I though You can use GtkContainer (that would replace behaviour of my div in example) like in GTK3?

**Comment by Mlocik97** [comment] 2021-07-16 10:35
![Screenshot_archlinux_2021-07-16_12:34:44](https://user-images.githubusercontent.com/34808350/125935056-5f490bf9-a079-4b38-b229-c6f100bbd1ac.png)

I installed EasyEffects on Manjaro, but it generated over 100 "LSP" icons...

**Comment by Digitalone1** [comment] 2021-07-16 10:58
That's an issue related to LSP package, not EE.

**Comment by Digitalone1** [comment] 2021-07-16 11:01
> oh right... so You don't have something like this:

It's generally not a good idea to specify a fixed width in applications because what's good for your system may not be the same on other systems with different configurations, icon and GTK themes. So the opacity solution should be better.

**Comment by wwmm** [comment] 2021-07-16 14:15
Master branch updated with the opacity property solution.

>A suggestion to resolve the locale issue is to move the locale methods in utils, like a made in the legacy branch.

I am not so sure this is the proper solution anymore. GTKMM4 https://developer.gnome.org/gtkmm-tutorial/unstable/gtkmm-tutorial.html docs says
```
gtkmm-4.0 is used in combination with glibmm-2.68, which sets the global locale for your program. The older glibmm-2.4 does not do that, and gtkmm-3.0 does it only to some extent. What this means is briefly that if your gtkmm-3.0 program contains a call to std::locale::global(std::locale("")), you can probably remove it. If you don't want glibmm or gtkmm to set the global locale for you, you should add a call to Glib::set_init_to_users_preferred_locale(false) before any call to Glib::init() or Gtk::Application::create(). 
```
Setting locale manually feels like fighting against the toolkit. In which places is the locale wrong?

**Comment by wwmm** [comment] 2021-07-16 14:22
The only places where I see the wrong locale in my computer are in the sliders values. But in this case I know the reason. Differently from spinbuttons the sliders do not seem to have a way to set custom formatting. I think that in the past we handled this by using additional labels to show the sliders values. But if possible I would like to find a way to fix this without having to add tons of labels just to fix the locale. It has to be possible somehow.

**Comment by wwmm** [comment] 2021-07-16 14:25
At this moment I have a mixed locale in my system
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
The application language is in english but numbers are in brazilian portuguese. As far as I can see the spinbuttons locale is fine.

**Comment by wwmm** [comment] 2021-07-16 14:34
>Differently from spinbuttons the sliders do not seem to have a way to set custom formatting.

Maybe they have https://devdocs.io/gtk~4.0/gtkscale#GtkScaleFormatValueFunc. It is so different from how it is handled by the spinbuttons that I did not notice it at the time. I will see how hard is to use this.

**Comment by Digitalone1** [comment] 2021-07-16 14:35
> The only places where I see the wrong locale in my computer are in the sliders values. But in this case I know the reason. Differently from spinbuttons the sliders do not seem to have a way to set custom formatting. I think that in the past we handled this by using additional labels to show the sliders values. But if possible I would like to find a way to fix this without having to add tons of labels just to fix the locale. It has to be possible somehow.

Well this seems more a GTK4 issue. Anyway different widget have wrong locale on my system, please test with `LC_ALL=it_IT.UTF8 easyeffects`

I.e. the ratio for gate and compressor is wrong, but in mbc is OK.

**Comment by wwmm** [comment] 2021-07-16 14:44
```
** (process:8696): WARNING **: 11:37:59.019: Can't set the global locale to the user's preferred locale.
   locale::facet::_S_create_c_locale name not valid
   The environment variable LANG may be wrong.


(process:8696): Gtk-WARNING **: 11:37:59.020: Locale not supported by C library.
	Using the fallback 'C' locale.
```
I was about to edit my locale to enable Italian when I realized that I also see the ratio parameter with the wrong value in Portuguese. I forgot to add a call to `prepare_spinbutton(ratio, "");` in both plugins. Master branch updated again. IT should be fine now.

**Comment by wwmm** [comment] 2021-07-16 14:47
The main purpose of `prepare_spinbutton` is to add unit beside the numbers. I may have forgotten to call it for widgets where the value has no unit.

**Comment by Digitalone1** [comment] 2021-07-16 15:05
I'm giving a quick look. It's also wrong in gate reduction and limiter oversampling (but this is an integer, the decimal shouldn't be shown).

**Comment by Digitalone1** [comment] 2021-07-16 15:13
Give a look also at `level_to_localized_string`, if the locale is needed to be set there. And there seem to be an unused method `level_to_localized_string_showpos` which was useful to show the plus sign on labels in the equalizer if I remember correctly.

I see also `float_to_localized_string` in effects base UI. Don't even remember this, maybe used for APO functions? Unfortunately I can't check the code on my system now, maybe in the next days in an attempt to port the lsp mbc.

**Comment by wwmm** [comment] 2021-07-16 15:14
>It's also wrong in gate reduction and limiter oversampling (but this is an integer, the decimal shouldn't be shown).

That is right. And in the gate reduction there should be a unit too. I have sent a new update to the master branch fixing this.

**Comment by Digitalone1** [comment] 2021-07-16 15:23
Seeing now some issues hare and there.

The followings are not centered properly. 

![Schermata del 2021-07-16 17-15-31](https://user-images.githubusercontent.com/25790525/125970838-19484faf-4f20-4980-8257-3c62f43ee431.png)

![Schermata del 2021-07-16 17-16-06](https://user-images.githubusercontent.com/25790525/125970854-6e50aad6-ba0f-46aa-9c0a-82a6ff6db71a.png)

Also, compressor attach and release should be aligned at the top or centered vertically.

Then Detection selector shuld not be expanded horizontally, like the Link one.

![Schermata del 2021-07-16 17-18-22](https://user-images.githubusercontent.com/25790525/125971033-1717a323-d2ae-491f-b01d-50554190404c.png)

**Comment by wwmm** [comment] 2021-07-16 15:24
>Give a look also at level_to_localized_string, if the locale is needed to be set there.

There is no need for manually setting the locale. When doing the custom formatting and setting the processed string to the widget gtkmm or glibmm is the one applying the locale. That is why I said we would be fighting against the toolkit if we try to set them on our own. 

>And there seem to be an unused method level_to_localized_string_showpos which was useful to show the plus sign on labels in the equalizer if I remember correctly.

It is being used by the global level meters that were being displaced by the saturation icon. I am not sure if it is worth the effort of using them in the equalizer.

>I see also float_to_localized_string in effects base UI. Don't even remember this, maybe used for APO functions? Unfortunately I can't check the code on my system now, maybe in the next days in an attempt to port the lsp mbc.

At this moment `float_to_localized_string` is being used to set the latency value displayed for each audio app entry in the players tab. I think we can keep it as it is.

**Comment by wwmm** [comment] 2021-07-16 15:27
>The followings are not centered properly.

I've notice it. And I really tried to center that thing. Nothing I tried worked. I still do not know why.

>Also, compressor attach and release should be aligned at the top or centered vertically.
>Also, compressor attach and release should be aligned at the top or centered vertically.

That should be easy to fix. I hope...

**Comment by Digitalone1** [comment] 2021-07-16 15:31
> I've noticed it. And I really tried to center that thing. Nothing I tried worked. I still do not know why.

Try to remove the uniform width to the box, so every cell can get it's own width.

**Comment by Digitalone1** [comment] 2021-07-16 15:32
These also are not properly centered.

![Schermata del 2021-07-16 17-27-38](https://user-images.githubusercontent.com/25790525/125972357-3ab2020f-222b-4e0e-838f-827ffd3affe5.png)

**Comment by wwmm** [comment] 2021-07-16 15:41
>These also are not properly centered.

This one was easy to fix.

>Also, compressor attach and release should be aligned at the top or centered vertically.

The grids holding these ones already have `<property name="valign">center</property>`. But it seems to be ignored.

**Comment by wwmm** [comment] 2021-07-16 15:42
>Try to remove the uniform width to the box, so every cell can get it's own width.

By box do you mean the stack?

**Comment by wwmm** [comment] 2021-07-16 16:37
It is better now
![Screenshot from 2021-07-16 13-34-00](https://user-images.githubusercontent.com/16225172/125980234-7dfbcf08-31de-4951-8e4a-a1ff3458fc67.png)

The problem was related to the homogeneous size but not where I was expecting it to be. The labels `Time` and `Threshold` were stretching to fill the column. But as that additional size was empty it was very subtle to notice that this was the source of the problem. The thing was centered when you considered the "invisible space".

**Comment by wwmm** [comment] 2021-07-16 16:56
Sliders locale should be fixed now
![Screenshot from 2021-07-16 13-52-15](https://user-images.githubusercontent.com/16225172/125982629-74c8747f-af7a-441f-8f38-9ac2fca27ea3.png)
Setting the formatting function was enough
```
scale->set_format_value_func([=](double value) {
    std::ostringstream str;

    str.precision(scale->get_digits());

    str << std::fixed << scale->get_adjustment()->get_value() << " " << unit;

    return str.str();
  });
```
But it makes me wonder why gtk4 is not doing it by itself. It is not like I am doing anything special in this function.

**Comment by Digitalone1** [comment] 2021-07-16 19:00
> > Try to remove the uniform width to the box, so every cell can get it's own width.
> 
> By box do you mean the stack?

No, I mean the grid containing the spinboxes and the labels. Maybe you can resolve toggling the homogenous property so every row does not have the same width.

**Comment by wwmm** [comment] 2021-09-24 15:38
I think we can close this issue.

**Closed by wwmm** 2021-09-24 15:38 UTC
