### ISSUE TITLE
No sound after returning from TTY

### ISSUE THREAD

**Issue by jazz-it** [wwmm/easyeffects#2146] opened 2023-03-01 19:45 UTC
### EasyEffects Version

7.0.0

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro KDE Plasma

### Describe the bug

My setup use HDMI connection from my nVidia GPU to my AVR then a) another HDMI connection to my monitor and b) my passive speakers. Set an Equalizer effect for your audio output. When playing some music with such setup, go to TTY, then shortly resume your session from TTY and the sound will be gone. However, when you go to Pipewire > Test Signal and produce the test signal, you will hear it from your speakers, but the music will be muted, even the player still produces the song. Then go to the Output tab and remove the "Enable" checkbox from your player and suddenly the sound will be back again.

### Expected Behavior

I expected the sound to come back again after coming back from TTY with the effects enabled. Now I need to re-login in order to recover my sound. What causes this and is there a fix/workaround?

**Comment by wwmm** [comment] 2023-03-01 22:03
This is the same as #1447, #708 and #1376. So we can close this issue and probably some of the ones I mentioned. The problem is PipeWire dying when switching to another tty. PipeWire can restart itself after dying but doing the same in EasyEffects ondemand depending on whether or not the sound server died is not an easy thing to do. Pavucontrol does it but things are a lot simpler there.

**Closed by wwmm** 2023-03-01 22:03 UTC
