### ISSUE TITLE
Use an external tool for translation?

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#1321] opened 2022-01-07 05:57 UTC
A seperate service for updating translations might make them more manageable. I thought of using [weblate](https://weblate.org) (open source naturally) but there are others too.

The main benefit would be better accessability, translators can just use a website instead of having to know how commits and pull requests work.

Yes keeping it all as normal contributions might be simpler from a setup perspective, but I think making them more accessible is worth it. Most larger projects do seem to usually use a seperate service.

Importantly, the format of the translations themselves is still the same old po files. So if you want, you should still be able to use the non-weblate way.

Note technically at least weblate's default hosted option only allows up to 15 languages and up to 1000 strings. But EE would almost certainly qualify for the "libre" plan, being an open source project, and that plan has up to 60 languages and up to 10000 strings. I doubt we'd want to host our own weblate instance just for translations though.

Any thoughts or opinions?

Useful links:
https://docs.weblate.org/en/weblate-4.10.1/admin/continuous.html#continuous-translation
https://docs.weblate.org/en/weblate-4.10.1/admin/continuous.html#push-changes
https://docs.weblate.org/en/weblate-4.10.1/devel/integration.html

**Comment by wwmm** [comment] 2022-01-07 13:01
I do not remember where but a discussion about something like this was done before. I still have the feeling these services will be one more thing I will have to manage somehow. I doubt it will be a one time operation that will allow us to keep doing things as we do without conflicts. 

In the past there were cases where the translator just opened an issue with the translation file attached and I did the rest. So knowing git isn't really necessary.

**Comment by vchernin** [comment] 2022-01-07 20:34
> I still have the feeling these services will be one more thing I will have to manage somehow. I doubt it will be a one time operation that will allow us to keep doing things as we do without conflicts.

To some extent this will probably always be true, which is the main argument instead this. It is an unavoidable layer of complexity, and I don't want to burden you with more things to manage :) I will offer to help admin it, if this is a thing that happens.

> without conflicts.

There is support for just directly [pushing translation changes when they're made](https://docs.weblate.org/en/weblate-4.10.1/admin/continuous.html#push-changes). Although in my opinion third party services should not have push access, instead it can just generate PRs.

It also possible that weblate updates itself [everytime a push in github](https://docs.weblate.org/en/weblate-4.10.1/admin/continuous.html#github-setup) is made. So what's in weblate should always reflect what's actually in master.

Beyond that I don't exactly know how avoidable conflicts are. One user doing translations manually and one using weblate [could cause conflicts](https://docs.weblate.org/en/weblate-4.10.1/admin/continuous.html#avoiding-merge-conflicts) though, as weblate has no ability to track ordinary PRs.

> In the past there were cases where the translator just opened an issue with the translation file attached and I did the rest. So knowing git isn't really necessary.

True. One possible difference though, is users might find a web interface easier to make the translations. Then again there's probably a way to use weblate just as an alternative to Poedit.

**Comment by wwmm** [comment] 2022-01-08 14:33
>instead it can just generate PRs.

I agree. Generating pull request is better.

>It is also possible that weblate updates itself everytime a push in github is made. So what's in weblate should always reflect what's actually in master.

Ok. 

>One user doing translations manually and one using weblate could cause conflicts though, as weblate has no ability to track ordinary PRs.

Two different people updating the same translation file at the same time can be a problem as things are right now too. I think that with weblate limited to pull requests instead of direct write access this will be manageable.

If there is a way to use weblate without forbidding people of using the current approach I think there is no problem in trying it. What do you think @Digitalone1? After all you have been the most active translator.

**Comment by Digitalone1** [comment] 2022-01-08 23:07
No issues to me. Never used weblate, but I can try to make an account on it.

**Comment by vchernin** [comment] 2022-01-08 23:33
Ok sounds good, @wwmm should I create the weblate project and invite you once you have an account? Or would you like to? [The sign up URL is here](https://hosted.weblate.org/accounts/register/).

In any case, I think you should be the one with highest permission levels (even if weblate is only making PRs). Maybe @Digitalone1 should also be an admin if they'd like to be (they can review translations, etc)?

**Comment by wwmm** [comment] 2022-01-09 15:25
I created an account there. I am looking at how to create the project. THe first screen was
```
Please check in advance whether your project is eligible for gratis project hosting on this site.

-     Translated content has to be released under a license approved by OSI or recognized as libre by FSF.
-     All the source code has to be publicly available in a supported version control system.
-     Translations have to be in the same repository as the source code, or under the same project/organization as the source code repository.
-     Using Weblate has been approved by the upstream project.
-     Mention you use Weblate for translations in the README. It’ll attract new translators and also help Weblate to be free for more projects.
-     The project has had active development for at least three months.
-     You will have 14 days to set up your project.
-     Please request project approval once you finish the setup.
-     Unapproved projects will be removed.
-     There is no guarantee of service availability, nor quality for free service plan.

```
The only thing missing is the README note but that obviously would only be done once we actually start to use it.

**Comment by wwmm** [comment] 2022-01-09 15:43
I had to create a "translation component"(whatever it is this) in order for it to let me apply for the libre plan. But it still wants moroe things to let me apply
![Screenshot from 2022-01-09 12-40-51](https://user-images.githubusercontent.com/16225172/148689459-944f7511-3626-4482-b690-24fca120fc77.png)
I have never thought about license for the translations. I always assumed they would be included in the one from the project. I am not sure about what weblate wants here.

**Comment by vchernin** [comment] 2022-01-09 19:27
Hmm.. from reading you should be able to select a "translation license" [within the project configuration page](https://docs.weblate.org/en/latest/admin/projects.html#translation-license). It just needs to be done explicitly it seems.

**Comment by wwmm** [comment] 2022-01-10 04:21
Now we wait. Let's see what they do
![Screenshot from 2022-01-10 01-19-02](https://user-images.githubusercontent.com/16225172/148718138-261d206a-42c6-49f4-8cc7-55699049b423.png)

**Comment by wwmm** [comment] 2022-01-10 04:27
@vchernin and @Digitalone1 if you make an account in weblate let me know your user name so I can add both of you to the project.

**Comment by wwmm** [comment] 2022-01-10 04:28
>if you make an account in weblate let me know your user name so I can add both of you to the project.

If you want. Of course.

**Comment by vchernin** [comment] 2022-01-10 04:28
My username is @vchernin as usual

**Comment by Digitalone1** [comment] 2022-01-11 10:08
Mine is @Digitalone1

**Comment by wwmm** [comment] 2022-01-14 14:59
Weblate has accepted the request for the free plan. Now we have to configure it properly.

**Comment by vchernin** [comment] 2022-01-15 07:00
Well the recent PR (manually pushed?) does seem correct, although I am not sure what went wrong that locked it earlier.

Have you configued things like https://docs.weblate.org/en/weblate-4.10.1/admin/continuous.html#github-setup? I think that one is entirely on the github side.

Another thing, you might want to enable "Push on commit" under version control settings. So it actually makes the PRs automatically. 

Since weblate only commits (and subsequently pushes) the gathered translations after 24 hours, it shouldn't be pushing for each change. That 24 hours could be increased too.

**Comment by Digitalone1** [comment] 2022-01-15 11:30
Unfortunately I only noticed now that with new version the plugin names in the plugins stack are not translated anymore. Something has to be changed in the translation template. 

But, please, commit the last changes before the template regeneration, I completed the Italian translation.

**Comment by wwmm** [comment] 2022-01-15 15:26
>although I am not sure what went wrong that locked it earlier.

I think I did something that confused weblate. When I accepted the pull request I decided to use the github option that squashed the commits. Weblate probably was not smart enough to understand that the files were still equal. I will do another test without squashing.

>Unfortunately I only noticed now that with new version the plugin names in the plugins stack are not translated anymore.

Now I see I forgot to add `plugin_name.hpp` to `POTFILES.in`

>But, please, commit the last changes before the template regeneration, I completed the Italian translation.

Ok.

**Comment by wwmm** [comment] 2022-01-15 15:31
>I will do another test without squashing.

Now there was no conflict. So I have to remember weblate does not understand squashes done by github. It is not a big deal. Weblate offers ways to reduce the number of commits if this becomes an issue.

**Comment by wwmm** [comment] 2022-01-15 15:32
>you might want to enable "Push on commit" under version control settings

I enabled it now that things seems to be ok.

**Comment by wwmm** [comment] 2022-01-15 15:42
>Now I see I forgot to add plugin_name.hpp to POTFILES.in

That is not the only problem. Something else is also wrong.

**Comment by Digitalone1** [comment] 2022-01-15 15:43
> > Now I see I forgot to add plugin_name.hpp to POTFILES.in
> 
> That is not the only problem. Something else is also wrong.

What? I see plugins names in the template.

**Comment by wwmm** [comment] 2022-01-15 15:46
>What? I see plugins names in the template.

I am not sure. For some reason I still do not see the plugin names translations. I now wonder if things like `_("Equalizer")` work in a header file.

**Comment by Digitalone1** [comment] 2022-01-15 15:48
Which language? Did you compile after updating the translation?

**Comment by wwmm** [comment] 2022-01-15 15:52
>Which language?

`pt_BR.UTF-8`. I haven't updated it in many months. But I think that words like `Equalizer` and `Compressor` were already translated a long time ago.

>Did you compile after updating the translation?

Yes. I installed EE in a local folder and I have also reinstalled it in the system through the AUR pkgbuild.

**Comment by wwmm** [comment] 2022-01-15 15:54
>I now wonder if things like _("Equalizer") work in a header file.

That can not be the problem. It has always been defined in a header.

**Comment by Digitalone1** [comment] 2022-01-15 15:58
If the base strings were removed, the translations got removed too. They should be reinserted. Fortunately we can check one of the old [commit](https://github.com/wwmm/easyeffects/tree/7f88daa66886a5bd5e7a83b2e9af5370a090febc/po) and retrieve the previous [translations](https://github.com/wwmm/easyeffects/blob/7f88daa66886a5bd5e7a83b2e9af5370a090febc/po/pt_BR.po#L2601).

**Comment by wwmm** [comment] 2022-01-15 16:02
>If the base strings were removed, the translations got removed too. 

I see. So in Italian things are working now? If it is only pt_BR.UTF-8 that is broken it is not a big deal. I can translate these words again.

**Comment by Digitalone1** [comment] 2022-01-15 16:07
It's for all languages unfortunately. It will only work after the translations are readded and pushed to main branch.

**Comment by wwmm** [comment] 2022-01-15 16:09
That is weird. Why can't the base strings just be readded?

**Comment by wwmm** [comment] 2022-01-15 16:10
The current po file has
```
#: include/plugin_name.hpp:91
msgid "Equalizer"
msgstr "Equalizador"
```
IT feels like it should be working.

**Comment by Digitalone1** [comment] 2022-01-15 16:15
Not for all, some strings have the `fuzzy` tag (see [here](https://github.com/wwmm/easyeffects/blob/5c65fd9ac60e000616315bd8c07c8a297534da48/po/pt_BR.po#L3026)), it means they have to be verified from poedit (or weblate app) before to be used. Once verified, tag is removed.

**Comment by wwmm** [comment] 2022-01-15 16:28
Ok, I think now I understand. In gtkmm the translations were associated to the file `effects_base_ui.hpp` that does not exist anymore
```
#: include/effects_base_ui.hpp:145
msgid "Equalizer"
msgstr "Equalizador"
```
and the translation system was not smart enough to keep reuse the translation. Is that it?

**Comment by wwmm** [comment] 2022-01-15 16:31
But thinking about it again it does not make much sense...

**Comment by Digitalone1** [comment] 2022-01-15 16:37
After that header was removed, the template `.pot` file removed the strings related to the plugin names, but locale `.po` files kept them as they was commented, so still in the text, but not parsed by the compiler.

When the correct header was added, some of the translations have been retrieved automatically, but others don't and some are flagged as `fuzzy`.

**Comment by wwmm** [comment] 2022-01-15 17:25
>When the correct header was added, some of the translations have been retrieved automatically, but others don't and some are flagged as fuzzy.

Ok But shouldn't the example I showed about about the `Equalizer` in `pt_BR.UTF-8` be working? It isn't marked as fuzzy and `msgstr` is not empty. It is almost like gtk is ignoring the translation.

**Comment by Digitalone1** [comment] 2022-01-15 17:30
It should work. I will add Italian translations and check on my system when have time. Will let you know if I can reproduce.

**Comment by wwmm** [comment] 2022-01-15 17:37
I've just noticed something really strange. I added the following print
```
util::warning(_("Equalizer"));
```
inside `plugins_menu.cpp` and it is translated without any problems. I did not even had to change the translation template or the language file for that. It just worked. It makes no sense...

**Comment by Digitalone1** [comment] 2022-01-15 17:47
Yes, it's weird. When the main branch will be updated (it's every 24 hours, right? I see a user is working on it now, could be done later), I'd like to fetch it on my repo and test on my system.

**Comment by wwmm** [comment] 2022-01-15 17:50
>it's every 24 hours, right?

Yes. The automatic pull request creation should happen every 24 hours assuming I did everything right. But it can also be done manually if necessary.

**Comment by wwmm** [comment] 2022-01-15 18:16
I think I have finally figured out what is going on. The following test may or may not work depending on when the variable is created
```
std::string test = _("Equalizer");

util::warning(test);
```

If the variable is created inside a constructor or something else that is only called once whatever it is that gtk has to do about translations is done the translation works. But if the variable is defined in a way that it behaves like a `global` translations do not work. For example if we define it inside a header or inside a cpp in a similar way as we do the `log_tag` variables.

I think that depending on the variable scope it may be instantiated way before gtk prepares whatever it has to do. In gtkmm that map was a member variable so by the time it was instantiated gtk probably had done its thing.

**Comment by Digitalone1** [comment] 2022-01-15 18:17
You're right @wwmm, it's not working to me either. :(

**Comment by wwmm** [comment] 2022-01-15 18:50
@Digitalone1 I was able to fix the issue. The map with the plugin names is now initialized in the `Data` structure.  Holy moly... I was not expecting this kind of subtlety in glib translation support...

**Comment by Digitalone1** [comment] 2022-01-15 18:57
@wwmm Nice.

**Comment by wwmm** [comment] 2022-02-03 14:24
We can close this.

**Closed by wwmm** 2022-02-03 14:24 UTC
Labels: enhancement
