### ISSUE TITLE
EassyEffects Blocks System Wide Mouse and Keyboard Events

### ISSUE THREAD

**Issue by piedpipr** [wwmm/easyeffects#1502] opened 2022-04-30 11:46 UTC
### EasyEffects Version

6.2.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop!_OS 22.04 LTS

### Describe the bug

EasyEffects is blocking the system wide mouse and keyboard events when I click open any menu in EasyEffects. For example from the plugin tab if If I click on Convolver >> Impulses it will blocks all keyboard or mouse events system wide as long as the Impulses selection menu/prompt is open. As long as I click or use keyboard staying focused on EasyEffects it works within EasyEffects window even when the menu is open but not the other way around. This lack of functionality becomes a hassle whenever I want to load a saved preset or Impulse Response file from the system file manager. When the file picker/manager opens up if EasyEffects window is not maximized or tiled to a side beforehand most of the times it gets behind the system file manager window as a result neither I can select preset not I can click on the EasyEffects window, resulting in total loss of control of the Window Manager/UI or system as a whole. Turning off the device manually is only option that remains.

### Expected Behavior

EasyEffect will not block mouse or keyboard events for the system or scope the events within itself in the hope of the next click/event by the user only rather it will register each events purely on the basis of window focusing.

### Debug Log

<details><summary>Debug Log</summary><br/>

```

```
</details>

**Comment by Digitalone1** [comment] 2022-04-30 11:57
I can't reproduce this issue on my system. So it should be something related to Flatpak or PopOS. Or Xorg if you are not using Wayland.

**Comment by piedpipr** [comment] 2022-04-30 12:12
@Digitalone1 I guess so too. Previous version of my PopOS installation had the same issue when PipeWire was not officially supported then. This latest fresh install having the exact same problem. Maybe some PopOS users can confirm, but it's definitely there to my speculation. No I do to use Wayland.

**Comment by wwmm** [comment] 2022-04-30 14:18
This has the same source as #1182. It is one of the gtk4 bugs that only happens in some systems. Mostly on Xorg but Wayland is not 100% free of them.

As it is something that has to be fixed in gtk and we already have similar issues I will close this one.

**Closed by wwmm** 2022-04-30 14:18 UTC
