### ISSUE TITLE
Flatpak App: Changing Priority Type, Niceness and Priority Has No Effect

### ISSUE THREAD

**Issue by thomas-profitt** [wwmm/easyeffects#445] opened 2019-02-23 03:52 UTC
Tested with pulseeffects **4.5.0** on Fedora 29 (where the Flatpak app is still the only compatible binary available).

To reproduce:
- Run pulseeffects, enabled for one or all outputs, while playing music, with Priority Type set to None,
- Check priority and niceness for all pulseeffects processes and see that they're default,
- Set Priority Type to Niceness or Priority,
- Close pulseeffects' GUI, and pkill remaining processes,
- Start pulseeffects under the same conditions as before,
- Check priority and niceness again to see that neither has changed.

![screenshot from 2019-02-22 22-06-27](https://user-images.githubusercontent.com/13843293/53281451-8452a280-3720-11e9-8f07-4713bc55f408.png)
(Screenshot shows pulseeffects running with Real Time set and Priority 4)

**Comment by wwmm** [comment] 2019-02-23 04:07
Try to do this test in debug mode `G_MESSAGES_DEBUG=pulseeffects flatpak run com.github.wwmm.pulseeffects`. This way we will see what is happening.

Is this suppposed to be working in the flatpak package @AsavarTzeth ?

**Comment by thomas-profitt** [comment] 2019-02-23 04:10
```
(pulseeffects:2): pulseeffects-DEBUG: 22:08:39.122: sie: NULL -> READY -> PLAYING
(pulseeffects:2): pulseeffects-DEBUG: 22:08:39.122: sie: READY -> PAUSED -> PLAYING

(pulseeffects:2): pulseeffects-WARNING **: 22:08:39.123: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.Failed: No such file or directory

(pulseeffects:2): pulseeffects-WARNING **: 22:08:39.123: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.Failed: No such file or directory

(pulseeffects:2): pulseeffects-WARNING **: 22:08:39.126: sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.Failed: No such file or directory
(pulseeffects:2): pulseeffects-DEBUG: 22:08:39.126: sie: pulsesrc latency [us]: 100000
(pulseeffects:2): pulseeffects-DEBUG: 22:08:39.126: sie: pulsesrc buffer [us]: 500000
```

Ah!

**Comment by wwmm** [comment] 2019-02-23 04:16
It is the first time I see this error. It may be specific to the flatpak package. With the native package on Arch Linux I get sometimes an error like `device or resource busy` that comes and goes totally at random. It seems related to how fast GStreamer is creating or destroying threads. But `no such file or directory` is new...

**Comment by thomas-profitt** [comment] 2019-02-23 04:21
I'm not familiar with how Flatpak apps access stuff, but I read the documentation [here](http://docs.flatpak.org/en/latest/sandbox-permissions.html#d-bus-access) and tried running it with `--socket=system-bus` and `--socket=session-bus`, which had no effect.

**Comment by thomas-profitt** [comment] 2019-02-23 04:51
I tried building from source on Fedora 29, to confirm or deny that this is a problem unique to the Flatpak app, but `gstreamer-plugins-bad-1.0` isn't available (only `gstreamer-plugins-bad-0.10`), and no `gstreamer-fft` is available, and I don't know how I can get the libs and drop them somewhere pkgconfig will find.

**Comment by AsavarTzeth** [comment] 2019-02-23 14:18
I honestly have no idea if RealtimeKit is supposed to work. I just looked up what RealtimeKit was and what DBus it offered, then granted access to that service from the sandbox.

Whether that dbus access is enough or not, I don't know. One would think it is, since that dbus service is running as a privileged user on the host. In any case, that is about all I can do.

- `--socket=system-bus` is redundant (and overkill) since I already grant `--system-talk-name=org.freedesktop.RealtimeKit1` by default (which might be questionable by some).
- `--socket=session-bus` does nothing because RealtimeKit is only using the system bus.

**Debugging**

When you debug this it is important to check if your `rtkit-daemon.service` is active and running. That is the service that provides the RealtimeKit DBus API. It does not need to be enabled, just make sure it runs when PulseEffects is.

```
user@host ~> systemctl status rtkit-daemon
● rtkit-daemon.service - RealtimeKit Scheduling Policy Service
   Loaded: loaded (/usr/lib/systemd/system/rtkit-daemon.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2019-02-23 14:20:03 CET; 4min 36s ago
 Main PID: 428 (rtkit-daemon)
    Tasks: 3 (limit: 4915)
   Memory: 1.3M
   CGroup: /system.slice/rtkit-daemon.service
           └─428 /usr/lib/rtkit-daemon
```

The error `sie: rtkit: GDBus.Error:org.freedesktop.DBus.Error.Failed: No such file or directory` seems to indicate it is not. That or it is DBus activated and not fast starting fast enough. Anyhow it will not matter, 

**Reproducing**

When I start PulseEffects I get this output:

```
user@host ~> journalctl -b -fu rtkit-daemon
feb 23 14:36:59 rtkit-daemon[1153]: Supervising 0 threads of 0 processes of 0 users.
feb 23 14:36:59 rtkit-daemon[1153]: Failed to look up client: No such file or directory
feb 23 14:36:59 rtkit-daemon[1153]: Supervising 0 threads of 0 processes of 1 users.
```
Not sure why does not work. It may very well be intentional and part of the sandboxing. You would have to ask a Flatpak developer or anyone with deeper knowledge of the underlying Linux technologies.

For comparison, here is the `rtkit-daemon` journal output, when using the `PKGBUILD` from the AUR. Here everything works.

```
user@host ~> sudo systemctl restart rtkit-daemon
user@host ~> journalctl -b -fu rtkit-daemon
...
feb 23 14:56:41 rtkit-daemon[1773]: Supervising 6 threads of 1 processes of 1 users.
feb 23 14:56:41 rtkit-daemon[1773]: Successfully made thread 2052 of process 1999 (/usr/bin/pulseeffects) owned by '1000' RT at priority 4.
...
feb 23 14:57:27 rtkit-daemon[1773]: Successfully made thread 2100 of process 1999 (/usr/bin/pulseeffects) owned by '1000' RT at priority 5.
feb 23 14:57:27 rtkit-daemon[1773]: Supervising 7 threads of 1 processes of 1 users.
```

**Comment by AsavarTzeth** [comment] 2019-02-23 14:26
On a related note. Have you looked into [Pipewire](https://pipewire.org/) yet? It might solve this problem since among other things it is designed with low latency and containers (like flatpak) in mind.

Of course I have no idea if it is usable yet with all the GStreamer components you need, or not.

**Comment by wwmm** [comment] 2019-02-23 14:33
Besides `org.freedesktop.RealtimeKit1` we also access `org.freedesktop.DBus.Properties`. Is access to this last one also enabled in the package?

I think Pipewire is still too young and at least to me it seems that their focus is on the video side for now. It is not clear how they intend to deal with apps like PulseEffects. Until they offer the same functionality Pulseaudio has we can't support it.

**Comment by AsavarTzeth** [comment] 2019-02-23 14:47
I see, I thought the idea of Pipewire was that its a transport mechanism that does not really care if it is video or audio. Seems strange that there would be that more focus on video, but what do I know; nothing really.

I did consider if `org.freedesktop.DBus.Properties` might be the culprit. Admittedly I have not allowed access to this. But, the thing is if it was the cause `--socket=session-bus` would have worked, since it allows everything.

**Comment by wwmm** [comment] 2019-02-23 14:52
I see. I have no other idea...

Pipewire was born to do with video what Pulseaudio does for sound apps. That is why they have their focus on the video side

**Comment by thomas-profitt** [comment] 2019-02-23 14:57
I can confirm that before starting pulseeffects, the rtkit-daemon service is active and that the process is running.

When pulseeffects starts, with no outputs enabled, journalctl shows no output for the rtkit-daemon unit. 

When I open VLC and start playing music, and the VLC output is enabled in pulseeffects, I see the same output in journalctl as you describe:
```
Feb 23 08:55:59 snowy rtkit-daemon[837]: Supervising 0 threads of 0 processes of 0 users.
Feb 23 08:55:59 snowy rtkit-daemon[837]: Supervising 0 threads of 0 processes of 0 users.
Feb 23 08:55:59 snowy rtkit-daemon[837]: Failed to look up client: No such file or directory
Feb 23 08:55:59 snowy rtkit-daemon[837]: Failed to look up client: No such file or directory
Feb 23 08:55:59 snowy rtkit-daemon[837]: Supervising 0 threads of 0 processes of 1 users.
Feb 23 08:55:59 snowy rtkit-daemon[837]: Failed to look up client: No such file or directory
Feb 23 08:56:00 snowy rtkit-daemon[837]: Supervising 0 threads of 0 processes of 1 users.
Feb 23 08:56:00 snowy rtkit-daemon[837]: Supervising 0 threads of 0 processes of 1 users.
Feb 23 08:56:00 snowy rtkit-daemon[837]: Failed to look up client: No such file or directory
Feb 23 08:56:00 snowy rtkit-daemon[837]: Failed to look up client: No such file or directory
Feb 23 08:56:00 snowy rtkit-daemon[837]: Supervising 0 threads of 0 processes of 1 users.
Feb 23 08:56:00 snowy rtkit-daemon[837]: Failed to look up client: No such file or directory
Feb 23 08:56:00 snowy rtkit-daemon[837]: Supervising 0 threads of 0 processes of 1 users.
Feb 23 08:56:00 snowy rtkit-daemon[837]: Supervising 0 threads of 0 processes of 1 users.
Feb 23 08:56:00 snowy rtkit-daemon[837]: Failed to look up client: No such file or directory
Feb 23 08:56:00 snowy rtkit-daemon[837]: Failed to look up client: No such file or directory
Feb 23 08:56:00 snowy rtkit-daemon[837]: Supervising 0 threads of 0 processes of 1 users.
Feb 23 08:56:00 snowy rtkit-daemon[837]: Failed to look up client: No such file or directory
```

**Comment by AsavarTzeth** [comment] 2019-02-23 16:02
Given some time, I figured out how to do a clean trace of the `rtkit-daemon` process where I am trying to figure out what file it claims to not exist. I truncated it somewhat (marked by **...**), because there was lots of redundant (I think) information.

Now I am in no way qualified to parse this, but one may be able to find a hint at least. Perhaps someone else will find this useful.

```
user@host ~> pgrep -a rtkit-daemon
2338 /usr/lib/rtkit-daemon
```

Flatpak (sandboxed):

```
user@host ~> env LC_MESSAGES=C sudo strace -p2338 -e trace=file
strace: Process 2338 attached
openat(AT_FDCWD, "//7588/task/7590/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//8901/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//8901/task/11/stat", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//7588/task/7590/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//8901/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//8901/task/14/stat", O_RDONLY) = -1 ENOENT (No such file or directory)
...
```

AUR `PKGBUILD` (not sandboxed):

```
user@host ~> env LC_MESSAGES=C sudo strace -p2338 -e trace=file
strace: Process 2338 attached
...
stat("//9153", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
readlink("//9153/exe", "/usr/bin/pulseeffects", 127) = 21
openat(AT_FDCWD, "//9153/task/9168/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//9153/task/9167/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//9153/task/9165/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//9153/task/9166/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//9153/task/9164/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//9153/task/9163/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//7588/task/7590/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//9153/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//9153/task/9169/stat", O_RDONLY) = 7
stat("//9153", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
openat(AT_FDCWD, "//9153/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//9153/task/9169/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//9153/task/9169/stat", O_RDONLY) = 7
openat(AT_FDCWD, "//9153/stat", O_RDONLY) = 7
stat("//9153", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
readlink("//9153/exe", "/usr/bin/pulseeffects", 127) = 21
```

The one thing I detect is that it never does not make the **readlink()** call with Flatpak. I also see "/usr/bin/pulseeffects", which makes me think.

**Comment by thomas-profitt** [comment] 2019-02-24 00:09
I tried running it with `--filesystem=host`, and with `--filesystem=host --filesystem=/proc`, and with all other very permissive permissions documented in `man flatpak build-finish`, with no change in output.

I'm surprised that `--filesystem=/proc` (which I've learned isn't included in `--filesystem=host`) didn't have any effect: the issue really looks like rtkit on the host is failing to interface with pulseeffects via procfs, and you'd think that if /proc in the container is /proc on the host, it'd work just fine as if it were running on the host.

I still don't know anything about how this sandboxing works, but maybe processes have different PIDs in the sandbox vs on the host, such that PID 11 in the sandbox (it seems like a low number!) isn't PID 11 on the host?

**Comment by thomas-profitt** [comment] 2019-02-24 00:14
I'm fairly familiar with running software in Docker containers, and so I know that the containers (which use (many of) the same kernel functionalities as Flatpak, I'm sure) will have their own process namespace (is that the right term?) such that it may see "node index.js" as PID 1 while on my host, the same process is 12855, e.g.:
```
> docker-compose exec name-of-node-container ps aux                                                                                                                                                                                                       ~/software/hostname-containers
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.9 928396 78116 ?        Ssl  Feb21   1:25 node index.js
root        29  0.0  0.0  36640  2808 pts/0    Rs+  00:11   0:00 ps aux
> ps aux | grep 'node index.js'                                                                                                                                                                                                                     ~/software/hostname-containers
root     12855  0.0  0.9 928396 78380 ?        Ssl  Feb20   1:25 node index.js
tom      17193  0.0  0.0  14428  1012 pts/0    S+   18:11   0:00 grep node index.js
```

I bet this is where the disconnect is.

**Comment by thomas-profitt** [comment] 2019-02-24 00:32
I've learned from [this Issue of another project that ships a flatpak](https://github.com/flathub/com.visualstudio.code.oss/issues/5) that the PID namespacing Flatpak uses is provided by a project called bubblewrap/bwrap, but I'm not yet sure if it's possible to disable PID namespacing so that there's no difference between host and container PIDs, but I'm willing to bet that's what we need to do.

**Comment by AsavarTzeth** [comment] 2019-02-24 09:37
Thank you so much. I was quite sure it was a namespace issue, but not as confident about which type. In any case, I was tired at that point and bound to miss something (obvious or not).

Anyhow, [pid_namespaces(7)](http://man7.org/linux/man-pages/man7/pid_namespaces.7.html) is what we are looking for.

A quick search of the web and I also re-discovered some old blog posts:
- https://blogs.gnome.org/alexl/2017/01/18/the-flatpak-security-model-part-1-the-basics/
- https://blogs.gnome.org/mclasen/2018/07/02/flatpak-in-detail-part-3/

**Particularly noteworthy is a section from the second link:**

> **Processes**
>
> One namespace that is used by flatpak is the pid namespace, which hides processes outside the sandbox from the sandboxed app.  If you run ps inside the sandbox, you’ll see something like this:
> 
> $ ps
> PID TTY TIME CMD
> 1 ? 00:00:00 bwrap
> 2 ? 00:00:00 sh
> 3 ? 00:00:00 ps
> 
> One thing you’ll notice is that the app itself (the sh process, in this case) ends up with a PID of 2. Just something to keep in mind when getting your app ready for running in a sandbox: PIDs can’t be used to identify the app to the rest of the system anymore. This has caused minor problems, e.g with the _NET_WM_PID property that some window managers look at to decide about window decorations.

**Further Debugging**

Just to be sure I verified this.

```
user@host ~> flatpak run --command=sh com.github.wwmm.pulseeffects//stable
[📦 com.github.wwmm.pulseeffects ~]$ ps axo pid,nice,rtprio,comm
  PID  NI RTPRIO COMMAND
    1   0      - bwrap
    3   0      - sh
    4   0      - ps
```

```
[user@host ~]$ pgrep -a sh
7082 bash
7362 sh
[user@host ~]$ sudo renice -19 -p 7362
7362 (process ID) old priority 0, new priority -19
```

```
[📦 com.github.wwmm.pulseeffects ~]$ ps axo pid,nice,rtprio,comm
  PID  NI RTPRIO COMMAND
    1   0      - bwrap
    3 -19      - sh
    5 -19      - ps
```

```
[user@host ~]$ sudo chrt -f -p 10 7362
```

```
[📦 com.github.wwmm.pulseeffects ~]$ ps axo pid,nice,rtprio,comm
  PID  NI RTPRIO COMMAND
    1   0      - bwrap
    3   -     10 sh
    6   -     10 ps
```

Another thing I checked is what process `rtkit-daemon` identified incorrectly. It seems to be the `xdg-dbus-proxy` that sits between the sandboxed app and the host.
```

...
[user@host ~]$ sudo strace -p1087 -e trace=file
...
openat(AT_FDCWD, "//7357/task/21/stat", O_RDONLY) = -1 ENOENT (No such file or directory)
^Cstrace: Process 1087 detached
user@host ~> cat /proc/7357/stat
7357 (xdg-dbus-proxy) S 7356 7349 3691 34818 7450 4194560 351 32 0 0 4 5 0 0 20 0 2 0 640508 160747520 1231 18446744073709551615 94391985790976 94391985823557 140728106201792 0 0 0 0 4096 0 0 0 0 17 3 0 0 0 0 0 94391985838376 94391985840148 94392004177920 140728106207789 140728106207814 140728106207814 140728106209248 0
```

I think the real issue here is that `rtkit-daemon` was never designed with sandboxes (namespaces) in mind. Although it is interesting to note that Pipewire also seems to support RealtimeKit. In that case I assume Pipewire sits between and is able to translate the PIDs before it sends it to `rtkit-daemon`.

I do believe this is the intended (future?) solution. Breaking the sandbox at this level is not possible, nor would it be considered acceptable.

Once more, I know nothing about the state of Pipewire, but I still have to ask. Is it, at least theoretically, feasible to use Pipewire for communication with RealtimeKit, and only that. Or is it a private API?

I found this [documentation page](https://pipewire.github.io/pipewire/rtkit_8c.html) if it helps.

Even if it's currently not, I am interested about the future.  If it is possible, could we perhaps try it in a feature branch or something? If you need me to do the testing, I am all yours.

**Comment by wwmm** [comment] 2019-02-24 14:29
I will do some tests here with this api and if it works I will create a `pipewire` branch. I think we could have pipewire as an optional compile time dependency. With a few preprocessor if/def we could switch from direct rtkit access to access through pipewire.

**Comment by wwmm** [comment] 2019-02-24 14:40
I talk directly to rtkit because although Pulseaudio uses rtkit it does not offer an api for clients. The current situation is do this yourself. I hope that this Pipewire api isn't meant only for its internal purposes.

**Comment by wwmm** [comment] 2019-02-24 14:43
I am looking at Pipewire rtkit source code https://github.com/PipeWire/pipewire/blob/master/src/modules/module-rtkit.c and it feels like a copy and paste of the Pulseaudio functions. I did not see yet any sign of translation between the sandbox... Not a good sign... It feels like it is mean to be used by Pipewire... But I will try anyway

**Comment by wwmm** [comment] 2019-02-24 15:05
Well this is disappointing... I can't even try them =/ The header with those functions prototypes exists only in the documentation. The Arch pkg does not have it and Pipewire repository also doesn't! All the functions are defined in a Pipewire module that doesn't seem meant for the public.

**Comment by wwmm** [comment] 2019-02-24 15:26
Contents of `/etc/pipewire/pipewire.conf`:
```
#load-module libpipewire-module-protocol-dbus
load-module libpipewire-module-rtkit
load-module libpipewire-module-protocol-native
load-module libpipewire-module-suspend-on-idle
#load-module libpipewire-module-spa-monitor alsa/libspa-alsa alsa-monitor alsa
load-module libpipewire-module-spa-monitor v4l2/libspa-v4l2 v4l2-monitor v4l2
#load-module libpipewire-module-spa-monitor bluez5/libspa-bluez5 bluez5-monitor bluez5
#load-module libpipewire-module-spa-node videotestsrc/libspa-videotestsrc videotestsrc videotestsrc Spa:POD:Object:Props:patternType=Spa:POD:Object:Props:patternType:snow
load-module libpipewire-module-autolink
#load-module libpipewire-module-mixer
load-module libpipewire-module-client-node
load-module libpipewire-module-flatpak
#load-module libpipewire-module-audio-dsp
#load-module libpipewire-module-link-factory
#load-module libpipewire-module-jack
```
I think that Pipewire handles the realtime priority of its own process/thread and maybe of the thread used by the client connection to it too. If that is the case Pipewire will not solve our problem. As it can be seen here https://github.com/wwmm/pulseeffects/blob/d4052b3dd242be266929282815c13c848323816b/src/pipeline_base.cpp#L43 I ask GStreamer to notify me when it creates a new thread and then I use rtkit to change this thread priority. This has no relation with the Pulseaudio client connection thread or any other thread I create in other places. We need to change the priority of internal GStreamer threads it creates for audio processing. I honestly hope I am wrong but it doesn't seem like Pipewire handles this

**Comment by wwmm** [comment] 2019-02-24 15:28
In case it helps someone reading all this discussion this is the GStreamer tutorial about this https://gstreamer.freedesktop.org/documentation/application-development/advanced/threads.html

**Comment by AsavarTzeth** [comment] 2019-06-24 08:51
Today I randomly stumbled upon this very interesting new portal interface: https://github.com/flatpak/xdg-desktop-portal/commit/db3858c87c2bb50456760a82a41345315226ed66

To me this interface is potentially very similar to what we want, except we want to communicate with the RealtimeKit daemon, not the Feral Interactive GameMode daemon. It even handles the pid conversion.

Perhaps someone could write a `org.freedesktop.portal.RealtimeKit` portal inspired by this one? It would probably be a good idea to ask if it would be accepted first.

**Comment by AsavarTzeth** [comment] 2019-07-22 19:24
I just opened a new portal request issue and lined it to this issue. Hopefully someone will notice it and add a portal/D-Bus interface that takes care of the pid namespace translation and asks the user for permission.

**Comment by wwmm** [comment] 2021-07-07 16:55
As EasyEffects 6.0.0 does not use GStreamer and moved to native PipeWire filters we do not have to handle priorities ourselves anymore. Pipewire will do that under the hoods. We can close this issue.

**Closed by wwmm** 2021-07-07 16:55 UTC
Labels: help wanted
