### ISSUE TITLE
EQ Serialization/Visualization UI issue with Q

### ISSUE THREAD

**Issue by bhack** [wwmm/easyeffects#1884] opened 2022-10-10 23:47 UTC
### EasyEffects Version

6.3.0/master

### What package are you using?

Flatpak (Flathub)

### Distribution

Linux

### Describe the bug

![immagine](https://user-images.githubusercontent.com/1710528/194968243-115806a9-9e02-4cad-8c0f-5acf0f611583.png)

Q has a value of 4.0. It is set but it is not visible. If I change it forth and back it is visualized again. But when it is saved or reloaded it is not visible in the main EQ UI (but still visible in the setting and reappear after a slightly move).

I suppose it is applied correctly but this UI issue could create some doubt in users.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by bhack** [comment] 2022-10-12 21:36
It happens only with Q `4.0`

**Comment by Digitalone1** [comment] 2022-10-13 17:40
Cannot reproduce on my system.

![image](https://user-images.githubusercontent.com/25790525/195667516-af33b454-ace5-4e85-bd17-2f1a1217362f.png)


Can you test on latest master (even on Flatpak if you can)?

**Comment by bhack** [comment] 2022-10-13 17:50
I think that we have removed the nightly info from the Readme/Wiki...

**Comment by vchernin** [comment] 2022-10-13 17:51
There is no longer a nightly flatpak on flathub-beta, but there is a [flatpak bundle here](https://github.com/wwmm/easyeffects#ci-artifacts).

**Comment by bhack** [comment] 2022-10-13 17:59
Ok I can reproduce with nightly, please try to import an APO profile with a Q 4.0... [E.g. this one](https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/harman_over-ear_2018/HIFIMAN%20Edition%20XS/HIFIMAN%20Edition%20XS%20ParametricEQ.txt)

**Comment by Digitalone1** [comment] 2022-10-13 18:24
It's correctly applying to me.

![image](https://user-images.githubusercontent.com/25790525/195676400-5057f205-310b-4590-b00f-ea3b8d1f9b98.png)

**Comment by bhack** [comment] 2022-10-13 19:22
On my side - Easy Effects (Devel)

![immagine](https://user-images.githubusercontent.com/1710528/195690451-73d44770-71f0-42e8-a4d3-b5323bd82c28.png)

**Comment by bhack** [comment] 2022-10-13 20:37
Is this related to a memory issue? As we cannot produce the same output with the same version.

**Comment by wwmm** [comment] 2022-10-13 20:37
>It's correctly applying to me.

Same thing on my computer. The `Q`value is visible on all bands. @bhack did you do something after loading the APO preset or just loading it should show the bug?

**Comment by wwmm** [comment] 2022-10-13 20:39
>Is this related to a memory issue? As we cannot produce the same output with the same version.

I think more bands as well as more frequencies and quality values should be affected in this case.

**Comment by wwmm** [comment] 2022-10-13 20:41
After closing and opening EasyEffects window after loading the preset I see the bug. Strange...

**Comment by bhack** [comment] 2022-10-13 20:42
I just load the APO preset. If I change it to 3.99 and I close and open again Easyeffects i found 3.99. If I close it with 4.00 I don't find Q on load.
If I move from 4,00 and back to 4.00 it appears. But when I close it and open again Easyeffects it is lost (but it is always set in the gear sub-menu)

**Comment by bhack** [comment] 2022-10-13 20:45
> After closing and opening EasyEffects window after loading the preset I see the bug. Strange...

It seems to me a classical memory issue (probably using uninitiated vars?)

**Comment by wwmm** [comment] 2022-10-13 20:49
And it seems to only happen when the quality is set to `4`. IT is probably related to the fact that this is the value set as default in GTK's xml for each band. But I am not sure about why GTK is doing what it is doing yet. The value will be used by the equalizer. For some reason GTK does not seem to have the quality spinbutton properly set by the time the label has to be updated.

**Comment by wwmm** [comment] 2022-10-13 20:52
>It seems to me a classical memory issue (probably using uninitialized vars?)

All bands are initialized in the same way through GTK property bindings.

**Comment by bhack** [comment] 2022-10-13 21:01
> In our spinbutton xml we had <property name="value">4</property> as the default quality spinbutton value.

Is this rendered or is it rendered only when we add a new band?

**Comment by Digitalone1** [comment] 2022-10-13 21:23
> I have updated our master branch with a workaround for the problem. It was just GTK trying to be "too smart". In our spinbutton xml we had `<property name="value">4</property>` as the default quality spinbutton value. It seems to me that when the window was reloaded and the database connection was done GTK saw that the spinbutton already had the `4.0` value and instead of propagating the signal that would eventually update the label it decided to "optimize things" and not sending the signal as the value was already in the spinbutton.

Okay, but shouldn't this be reproducible with the spinbutton "default value" for the value property (which I suppose is 0 when it's not specified)?

**Comment by wwmm** [comment] 2022-10-13 22:37
>Is this rendered or is it rendered only when we add a new band?

The widgets for each band are constructed when they GTK when they are added.

>Okay, but shouldn't this be reproducible with the spinbutton "default value" for the value property (which I suppose is 0 when it's not specified)?

I did not think about that. I did a test now and GTK is doing the same shit when the quality is set to zero... This is annoying... I wonder why GTK is checking the values in the spinbutton. By default a spinbutton uses double and comparing doubles is usually tricky. I would imagine it would be easier for them to just forward the signal...

**Comment by bhack** [comment] 2022-10-13 22:51
Do you see where the signal is conditional filtered?
https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkspinbutton.c

**Comment by wwmm** [comment] 2022-10-13 22:54
>Do you see where the signal is conditional filtered?
>https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkspinbutton.c

The values showed by the spinbutton are controlled through a `GtkAdjustment` object. This is probably the object responsible for the decision about whether or not the `value-changed` signal will be emitted after the connection of the `value` property to the gsettings database key.

**Comment by wwmm** [comment] 2022-10-13 22:55
>The values showed by the spinbutton are controlled through a GtkAdjustment object. 

Although I was talking about "spinbutton" before the value property that was being set was in the `GtkAdjustment` that is nested to the spinbutton in the xml.

**Comment by wwmm** [comment] 2022-10-13 23:01
When we load the window we connect the `GtkAdjustment` value property to the corresponding quality property in the GSettings database
```
g_settings_bind(settings, tags::equalizer::band_q[index].data(), gtk_spin_button_get_adjustment(self->band_quality),
                  "value", G_SETTINGS_BIND_DEFAULT);
```
`G_SETTINGS_BIND_DEFAULT` means that the binding is bidirectional and the corresponding signal from GSettings to the GTK widget should be emitted once after the connection to make sure the objects are synchronized. This is clearly happening when the value is not equal to the default value set in the spinbutton by the GtkAdjustment. The problem seems to come from the fact that the Adjustment is refusing to emit the `value-changed` signal when it sees that the value is already there. It makes some sense depending on how you look at it. But it is not what we want here because the label text property is bound to what is happening to the GtkAdjustment value property. If the value is not updated the text won't be too.

**Comment by wwmm** [comment] 2022-10-13 23:06
In any case I wonder why the close that updates the label isn't being updated with the spinbutton default value. This is how the binding is done in the xml file
```
       <child>
            <object class="GtkLabel" id="band_quality_label">
                <property name="width-chars">8</property>
                <property name="label">Q</property>

                <binding name="label">
                    <closure type="gchararray" function="set_band_quality_label">
                        <lookup name="value">band_quality</lookup>
                    </closure>
                </binding>

                <style>
                    <class name="dim-label" />
                </style>
            </object>
        </child>
```
`<lookup name="value">band_quality</lookup>` should be updating the label independently of whether or not we binding the spinbutton to gsettings. I think that GTK is calling `set_band_quality_label` too soon.

**Comment by wwmm** [comment] 2022-10-13 23:14
I have updated the master branch again after removing a nullptr check inside `set_band_quality_label` that is not really needed. I Things seem fine now. The nullptr check was probably forcing the signal to be ignored because GTK is trying to update the label way before the object we were checking for was ready. As we do not need it in this particular callback I think it is fine not doing the check.

**Comment by bhack** [comment] 2022-10-13 23:49
Ok it is working... I don't know what is the default effect as we don't have a default anymore

**Comment by bhack** [comment] 2022-10-19 17:03
As we don't have a default anymore in the xml can we close this or do you want to investigate more?

**Comment by wwmm** [comment] 2022-10-19 22:14
>As we don't have a default anymore in the xml can we close this or do you want to investigate more?

I think we can close this issue.

**Closed by wwmm** 2022-10-19 22:14 UTC
