### ISSUE TITLE
Calf filters are broken

### ISSUE THREAD

**Issue by DanMan** [wwmm/easyeffects#1933] opened 2022-11-02 21:53 UTC
### EasyEffects Version

7.0.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 36

### Describe the bug

It doesn't do anything.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
lilv_lib_open(): error: Failed to open library /app/lib/lv2/calf.lv2/calf.so (/usr/lib/x86_64-linux-gnu/libjack.so.0: undefined symbol: pw_thread_fill_attr)

(easyeffects:2): easyeffects-WARNING **: 22:51:34.395: 	lv2_wrapper.cpp:225	failed to instantiate http://calf.sourceforge.net/plugins/BassEnhancer
```
</details>

**Comment by wwmm** [comment] 2022-11-03 00:33
@vchernin was there any change in the `calf` package used by the Flatpak build?

**Comment by vchernin** [comment] 2022-11-03 06:57
`calf` hasn't been updated in years, taking a guess lilv/calf or some other software depends on `pw_thread_fill_attr` which was only introduced in https://github.com/PipeWire/pipewire/commit/0b96b87331e398b8e49ff57cd2440e9a34c90333#diff-0ecc850ee1f3d7ed53a06924247ec88c4fbb69f2431d6b7a069e60ff6b70b078 in pipewire 0.3.51. While I will try update and test it later today when I have time, but it wouldn't be ideal to update it since ubuntu 22.04 users will be using 0.3.48 forever. However, maybe it will happen to work anyhow.

**Comment by vladzur** [comment] 2022-11-03 12:53
Same issue here, any Calf plugin works using Pop!_OS 22.04
```
pipewire
Compiled with libpipewire 0.3.59
Linked with libpipewire 0.3.59
```

**Comment by wwmm** [comment] 2022-11-03 14:07
>taking a guess lilv/the plugin or some other software depends on pw_thread_fill_attr 

This would be really strange. `Lilv` and `calf` do not make direct calls to PipeWire functions. And even if they wanted they would not be able to call `pw_thread_fill_attr`. This is a private PipeWire function that only PipeWire can use.

**Comment by sm3rek** [comment] 2022-11-03 19:30
Noticed the same on Linux mint 21. I'm using the flatpak version and pipewire 0.3.41

**Comment by vchernin** [comment] 2022-11-04 06:55
I managed to fix this for my machine after updating libpipewire for the build. However I still need to test the effects on ubuntu 22.04/older pipewire so I haven't merged it quite yet. https://github.com/flathub/com.github.wwmm.easyeffects/pull/165

**Comment by vchernin** [comment] 2022-11-04 17:20
Unfortunately libpipewire 0.3.57 with daemon 0.3.48 seems broken on ubuntu 22.04... I could not get libpipewire 0.3.51 to work for some reason.

```
vincent@ubuntu2204:~$ G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects//test
You have PipeWire 0.3.48 installed
This is newer or the same as PipeWire 0.3.41 required to run Easy Effects
(process:2): easyeffects-DEBUG: 10:15:14.001: 	easyeffects.cpp:35	easyeffects version: 7.0.0
(process:2): easyeffects-DEBUG: 10:15:14.002: 	easyeffects.cpp:45	locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 10:15:14.013: 	presets_manager.cpp:49	system input presets directory: "/app/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 10:15:14.013: 	presets_manager.cpp:49	system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 10:15:14.013: 	presets_manager.cpp:49	system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 10:15:14.013: 	presets_manager.cpp:52	system output presets directory: "/app/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 10:15:14.013: 	presets_manager.cpp:52	system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 10:15:14.013: 	presets_manager.cpp:52	system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 10:15:14.013: 	presets_manager.cpp:194	user presets directory already exists: /home/vincent/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 10:15:14.013: 	presets_manager.cpp:194	user presets directory already exists: /home/vincent/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 10:15:14.013: 	presets_manager.cpp:194	user presets directory already exists: /home/vincent/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 10:15:14.013: 	presets_manager.cpp:194	user presets directory already exists: /home/vincent/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 10:15:14.013: 	presets_manager.cpp:194	user presets directory already exists: /home/vincent/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
(easyeffects:2): easyeffects-DEBUG: 10:15:14.231: 	pipe_manager.cpp:1426	compiled with PipeWire: 0.3.57
(easyeffects:2): easyeffects-DEBUG: 10:15:14.231: 	pipe_manager.cpp:1427	linked to PipeWire: 0.3.57
(easyeffects:2): easyeffects-DEBUG: 10:15:14.247: 	pipe_manager.cpp:1397	core version: 0.3.48
(easyeffects:2): easyeffects-DEBUG: 10:15:14.247: 	pipe_manager.cpp:1398	core name: pipewire-0
(easyeffects:2): easyeffects-DEBUG: 10:15:14.248: 	pipe_manager.cpp:1311	found metadata: settings
(easyeffects:2): easyeffects-DEBUG: 10:15:14.248: 	pipe_manager.cpp:1166	Audio/Sink 43 easyeffects_sink with serial 46 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.248: 	pipe_manager.cpp:1166	Audio/Source/Virtual 44 easyeffects_source with serial 47 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.248: 	pipe_manager.cpp:1166	Audio/Sink 112 easyeffects_sink with serial 160 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Sink 54 easyeffects_sink with serial 64 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Source/Virtual 113 easyeffects_source with serial 161 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Sink 112 easyeffects_sink with serial 160 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Sink 112 easyeffects_sink with serial 160 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Source/Virtual 55 easyeffects_source with serial 65 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Source/Virtual 113 easyeffects_source with serial 161 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Source/Virtual 113 easyeffects_source with serial 161 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Sink 76 easyeffects_sink with serial 121 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Source/Virtual 84 easyeffects_source with serial 122 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Sink 99 easyeffects_sink with serial 143 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Source/Virtual 98 easyeffects_source with serial 144 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Sink 112 easyeffects_sink with serial 160 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.249: 	pipe_manager.cpp:1166	Audio/Source/Virtual 113 easyeffects_source with serial 161 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.248: 	pipe_manager.cpp:1166	Audio/Sink 112 easyeffects_sink with serial 160 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.250: 	pipe_manager.cpp:1166	Audio/Source/Virtual 113 easyeffects_source with serial 161 has been added
(easyeffects:2): easyeffects-DEBUG: 10:15:14.255: 	pipe_manager.cpp:1517	easyeffects_sink node successfully retrieved with id 43 and serial 46
(easyeffects:2): easyeffects-DEBUG: 10:15:14.255: 	pipe_manager.cpp:1522	easyeffects_source node successfully retrieved with id 44 and serial 47
(easyeffects:2): easyeffects-DEBUG: 10:15:14.266: 	plugin_base.cpp:289	soe: output_level successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 10:15:14.269: 	output_level.cpp:37	soe: output_level: PipeWire blocksize: 1024
(easyeffects:2): easyeffects-DEBUG: 10:15:14.269: 	output_level.cpp:38	soe: output_level: PipeWire sampling rate: 48000
(easyeffects:2): easyeffects-DEBUG: 10:15:14.300: 	plugin_base.cpp:289	soe: spectrum successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 10:15:14.300: 	stream_output_effects.cpp:182	No output device set. Aborting the link

```

@wwmm any ideas? This seems to be a bug as pipewire should be somewhat forwards and backwards compatible according to https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1515. 

The last resort would just to be to tell ubuntu 22.04 users they need to update their pipewire daemon version... but I still don't know what changed in the 7.0.0 update that requires new libpipewire in the first place.

**Comment by wwmm** [comment] 2022-11-04 19:19
>any ideas? This seems to be a bug somewhere as pipewire
 I have no idea. Considering we do not even have access to the function where the crash happens it can only be a PipeWire bug.

>but I still don't know what changed in the 7.0.0 update that requires new libpipewire in the first place

I can't think of any change on our side that could justify this crash. Our LV2 wrapper is still like it was many months ago. And we do not call that PipeWire function. It is weird...

**Comment by wwmm** [comment] 2022-11-04 19:21
>lilv_lib_open(): error: Failed to open library /app/lib/lv2/calf.lv2/calf.so (/usr/lib/x86_64-linux-gnu/libjack.so.0: undefined symbol: pw_thread_fill_attr)

As PipeWire is supposed to be compatible with Jack clients my guess is that `Calf` is trying to initialize something from `Jack`. But for whatever reason the part of PipeWire that provides this compatibility has changed in a way that Jack clients/plugins are not expecting.

**Comment by vchernin** [comment] 2022-11-10 21:28
It seems to be a runtime dependency change that causes this specific regression, so https://github.com/wwmm/easyeffects/pull/1966 is the temporary fix.

**Closed** 2022-11-10 22:18 UTC
