### ISSUE TITLE
In the Equaliser input a value 

### ISSUE THREAD

**Issue by servimo** [wwmm/easyeffects#1383] opened 2022-02-03 15:48 UTC
In the equaliser have the possibility to input values, without the need to scroll with the mouse.

**Comment by wwmm** [comment] 2022-02-03 16:03
Do you mean having a spinbutton there so that the band gain can be set without having to necessarily use the scales?

**Comment by servimo** [comment] 2022-02-03 16:15
![easyeffects](https://user-images.githubusercontent.com/10197145/152382052-4f55c125-76e9-441b-b656-8cc95bd9574b.png)
I mean in the numbers marked you can click on them and insert the value you want. I see this in others applications.

**Comment by Digitalone1** [comment] 2022-02-03 17:38
Something like [this](https://doc.qt.io/archives/4.6/designer-quick-start.html).

Very difficult to implement in GTK. I've seen it in some KDE widgets, but I think it's not a specific Qt widget, maybe a spinbutton combined with a slider where the value is bound between both objects.

The problem is that GTK spinbutton is very large, not so easy to stick inside the plugin UI footer without messing the already existing layout.

**Comment by wwmm** [comment] 2022-02-03 18:48
>maybe a spinbutton combined with a slider where the value is bound between both objects.

That is probably what is done in most if not all of these cases.

>The problem is that GTK spinbutton is very large

I think it is possible to hide the `up/down` buttons that are usually inside the spinbutton. But it may still be too large without applying a css class on it.

**Comment by servimo** [comment] 2022-02-04 02:37
With clicks or the scrolling of the mouse you can go up and down by 0,10, but if you click in the button in the scrolling bar it didn't act like clicking or scrolling, appears decimal values other than by 0,10.
With the box with a input you can go quickly to a pre determined value.

**Comment by Digitalone1** [comment] 2022-02-10 08:26
This is very difficult to implement and will complicate things out. Every spinbox has two level of adjustment. With up/down arrow you can adjust by 0,01 and with pagup/pagdown on the numeric keypad you can adjust by 0,10. Use them for now to be more accurate on setting values.

Honestly, I don't think this will be ever implemented. In the current state the interface is already complex. No need to make it more complex adding more widgets to bind to other existing widgets. Considering also that in the default state gtk spinboxes are too large and we need workarounds to make them smaller.

**Comment by wwmm** [comment] 2022-02-13 04:23
For curiosity I decided to see how ugly it could get without customization
![Screenshot from 2022-02-13 01-20-18](https://user-images.githubusercontent.com/16225172/153738476-9394f07b-94c3-4a6d-9bc2-438e5a5b0b36.png)
As expected it is ugly. It was simple to implement. Just `15 lines` of xml code. But the default GtkSpinButton look is not good in this position.

**Comment by wwmm** [comment] 2022-02-13 04:55
One way would be to use a flat `GtkEntry`. But the problem is that we won't have the number validation that comes for free with a GtkSpinButton... And we would still need to force the number to be aligned with the scale...

**Comment by Digitalone1** [comment] 2022-02-13 08:54
Is there no easy way to remove the +/- buttons?

**Comment by bhack** [comment] 2022-02-13 10:39
> Besides the fact this would make inkscape a dependency it is using gtkmm3. So it is not possible to use it anyway.

It was not to use as is or to create a new dependency. It was just to have a reference custom GTK widget if we like its design.

**Comment by wwmm** [comment] 2022-02-13 16:08
A different approach that can be fully implemented changing only the xml file would be to add a GtkSpinButton to the band menu. The question is if this will make users confused. At least it would only be visible when opening the band menu.

**Comment by bhack** [comment] 2022-02-13 16:22
The only think that i find useful in the inkscape custom Scale Is the precison mode with + Alt.

**Comment by wwmm** [comment] 2023-08-02 16:16
After looking how the native ui handles this problem I decided to add to each band menu a spinbutton that allows the gain to be set. It is the easiest thing to do and is similar to what the native ui does.
![Screenshot from 2023-08-02 13-07-40](https://github.com/wwmm/easyeffects/assets/16225172/d143d489-62c6-43d0-bfb6-589bbc87a66f)
We can close this issue.

**Closed by wwmm** 2023-08-02 16:16 UTC
Labels: enhancement
