### ISSUE TITLE
EasyEffects systemd service instance is exited when quitting another instance

### ISSUE THREAD

**Issue by quietvoid** [wwmm/easyeffects#1310] opened 2022-01-03 22:25 UTC
### EasyEffects Version

6.2.0
easyeffects-git 6.1.5.r268.g7f88daa6-1

### What package are you using?

AUR (easyeffects-git)

### Distribution

Arch Linux

### Describe the bug

Similar to #1215, except I'm not using Flatpak.
Running Sway 1.6.1.

When I have `easyeffects` running in the background, and I launch another `easyeffects` instance (for the GUI), both are exited when I close the new one.
Closing with Ctrl+Q.

I tried building from the AUR `easyeffects-git` package as well as the PKGBUILD from the git, both end up with the same result.

As far as I'm aware, this is a regression because it used to work correctly.

### Expected Behavior

The instance running as a service should keep running, but it's exiting cleanly instead.
Since the service is set to restart on failure, it's never restarted.

### Debug Log

<details><summary>Debug Log</summary><br/>

For this log, I started the systemd service, another instance and waited a couple seconds before closing it.

```
Jan 03 17:14:14.718487 user systemd[1211]: Started easyeffects daemon.
Jan 03 17:14:14.728953 user easyeffects[79124]: easyeffects version: 6.2.0
Jan 03 17:14:14.728959 user easyeffects[79124]: main: locale directory: /usr/share/locale
Jan 03 17:14:14.731287 user easyeffects[79124]: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
Jan 03 17:14:14.731291 user easyeffects[79124]: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
Jan 03 17:14:14.731293 user easyeffects[79124]: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
Jan 03 17:14:14.731295 user easyeffects[79124]: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
Jan 03 17:14:14.731302 user easyeffects[79124]: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/
Jan 03 17:14:14.731305 user easyeffects[79124]: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/input
Jan 03 17:14:14.731308 user easyeffects[79124]: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/output
Jan 03 17:14:14.731311 user easyeffects[79124]: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/autoload/input
Jan 03 17:14:14.731314 user easyeffects[79124]: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/autoload/output
Jan 03 17:14:14.760072 user easyeffects[79124]: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Jan 03 17:14:14.775336 user easyeffects[79124]: pipe_manager: compiled with PipeWire: 0.3.42
Jan 03 17:14:14.775341 user easyeffects[79124]: pipe_manager: linked to PipeWire: 0.3.42
Jan 03 17:14:14.778251 user easyeffects[79124]: pipe_manager: core version: 0.3.42
Jan 03 17:14:14.778257 user easyeffects[79124]: pipe_manager: core name: pipewire-0
Jan 03 17:14:14.778288 user easyeffects[79124]: pipe_manager: found metadata: settings
Jan 03 17:14:14.778294 user easyeffects[79124]: pipe_manager: found metadata: default
Jan 03 17:14:14.778300 user easyeffects[79124]: pipe_manager: found metadata: route-settings
Jan 03 17:14:14.778343 user easyeffects[79124]: pipe_manager: Audio/Sink 46 alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo with timestamp 1641248054778326287 was added
Jan 03 17:14:14.778353 user easyeffects[79124]: pipe_manager: Audio/Source 47 alsa_input.pci-0000_0d_00.4.analog-stereo with timestamp 1641248054778346457 was added
Jan 03 17:14:14.778404 user easyeffects[79124]: pipe_manager: Stream/Output/Audio 118 spotify with timestamp 1641248054778394418 was added
Jan 03 17:14:14.778420 user easyeffects[79124]: pipe_manager: Stream/Output/Audio 127 spotify with timestamp 1641248054778413468 was added
Jan 03 17:14:14.778438 user easyeffects[79124]: pipe_manager: Stream/Output/Audio 117 spotify with timestamp 1641248054778432738 was added
Jan 03 17:14:14.778449 user easyeffects[79124]: pipe_manager: Stream/Output/Audio 109 spotify with timestamp 1641248054778442938 was added
Jan 03 17:14:14.778461 user easyeffects[79124]: pipe_manager: spotify port 114 is connected to alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo port 48
Jan 03 17:14:14.778468 user easyeffects[79124]: pipe_manager: spotify port 116 is connected to alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo port 50
Jan 03 17:14:14.778479 user easyeffects[79124]: pipe_manager: spotify port 128 is connected to alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo port 48
Jan 03 17:14:14.778487 user easyeffects[79124]: pipe_manager: spotify port 129 is connected to alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo port 50
Jan 03 17:14:14.778497 user easyeffects[79124]: pipe_manager: spotify port 110 is connected to alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo port 48
Jan 03 17:14:14.778503 user easyeffects[79124]: pipe_manager: spotify port 111 is connected to alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo port 50
Jan 03 17:14:14.778515 user easyeffects[79124]: pipe_manager: spotify port 100 is connected to alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo port 48
Jan 03 17:14:14.778520 user easyeffects[79124]: pipe_manager: spotify port 104 is connected to alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo port 50
Jan 03 17:14:14.778533 user easyeffects[79124]: pipe_manager: Audio/Sink 59 easyeffects_sink with timestamp 1641248054778528319 was added
Jan 03 17:14:14.778543 user easyeffects[79124]: pipe_manager: Audio/Source/Virtual 64 easyeffects_source with timestamp 1641248054778538489 was added
Jan 03 17:14:14.778859 user easyeffects[79124]: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo" }
Jan 03 17:14:14.778866 user easyeffects[79124]: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo" }
Jan 03 17:14:14.778877 user easyeffects[79124]: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "alsa_input.pci-0000_0d_00.4.analog-stereo" }
Jan 03 17:14:14.779325 user easyeffects[79124]: 'spa_pod_is_array(pod)' failed at /usr/include/spa-0.2/spa/pod/iter.h:339 spa_pod_get_array()
Jan 03 17:14:14.779623 user easyeffects[79124]: pipe_manager: easyeffects_sink node successfully retrieved with id 59 and timestamp 1641248054778528319
Jan 03 17:14:14.779630 user easyeffects[79124]: pipe_manager: easyeffects_source node successfully retrieved with id 64 and timestamp 1641248054778538489
Jan 03 17:14:14.784232 user easyeffects[79124]: pipe_manager: spotify port 114 is connected to easyeffects_sink port 84
Jan 03 17:14:14.784243 user easyeffects[79124]: pipe_manager: spotify port 116 is connected to easyeffects_sink port 95
Jan 03 17:14:14.784942 user easyeffects[79124]: pipe_manager: spotify port 128 is connected to easyeffects_sink port 84
Jan 03 17:14:14.784952 user easyeffects[79124]: pipe_manager: spotify port 129 is connected to easyeffects_sink port 95
Jan 03 17:14:14.785624 user easyeffects[79124]: pipe_manager: spotify port 110 is connected to easyeffects_sink port 84
Jan 03 17:14:14.785632 user easyeffects[79124]: pipe_manager: spotify port 111 is connected to easyeffects_sink port 95
Jan 03 17:14:14.786393 user easyeffects[79124]: pipe_manager: spotify port 100 is connected to easyeffects_sink port 84
Jan 03 17:14:14.786402 user easyeffects[79124]: pipe_manager: spotify port 104 is connected to easyeffects_sink port 95
Jan 03 17:14:14.797645 user easyeffects[79124]: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness
Jan 03 17:14:14.797650 user easyeffects[79124]: soe: http://drobilla.net/plugins/mda/Loudness is not installed
Jan 03 17:14:14.797666 user easyeffects[79124]: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness
Jan 03 17:14:14.797673 user easyeffects[79124]: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output
Jan 03 17:14:14.797679 user easyeffects[79124]: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link
Jan 03 17:14:14.806692 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:14.824355 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:14.851499 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:14.890275 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:14.898736 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:14.906684 user easyeffects[79124]: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
Jan 03 17:14:14.906688 user easyeffects[79124]: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:14.920497 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:14.939272 user easyeffects[79124]: soe: rnnoise using the default model
Jan 03 17:14:14.949434 user easyeffects[79124]: pipe_manager: Filter ee_soe_output_level, id = 130, was added
Jan 03 17:14:14.950327 user easyeffects[79124]: soe: output_level successfully connected to PipeWire graph
Jan 03 17:14:14.950806 user easyeffects[79124]: pipe_manager: Filter ee_soe_spectrum, id = 97, was added
Jan 03 17:14:14.951717 user easyeffects[79124]: soe: spectrum successfully connected to PipeWire graph
Jan 03 17:14:14.952242 user easyeffects[79124]: pipe_manager: Filter ee_soe_equalizer, id = 71, was added
Jan 03 17:14:14.953157 user easyeffects[79124]: soe: equalizer successfully connected to PipeWire graph
Jan 03 17:14:14.971595 user easyeffects[79124]: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness
Jan 03 17:14:14.971600 user easyeffects[79124]: sie: http://drobilla.net/plugins/mda/Loudness is not installed
Jan 03 17:14:14.971610 user easyeffects[79124]: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness
Jan 03 17:14:14.971618 user easyeffects[79124]: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output
Jan 03 17:14:14.971624 user easyeffects[79124]: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link
Jan 03 17:14:14.980620 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:14.997664 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:15.024151 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:15.062678 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:15.071098 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:15.079060 user easyeffects[79124]: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:15.079065 user easyeffects[79124]: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
Jan 03 17:14:15.093132 user easyeffects[79124]: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
Jan 03 17:14:15.111942 user easyeffects[79124]: sie: rnnoise using the default model
Jan 03 17:14:15.119280 user easyeffects[79124]: soe: equalizer latency: 0.128000 s
Jan 03 17:14:15.119416 user easyeffects[79124]: soe: output_level: new PipeWire blocksize: 8192
Jan 03 17:14:15.121040 user easyeffects[79124]: pipe_manager: Filter ee_sie_output_level, id = 108, was added
Jan 03 17:14:15.121937 user easyeffects[79124]: sie: output_level successfully connected to PipeWire graph
Jan 03 17:14:15.122345 user easyeffects[79124]: pipe_manager: Filter ee_sie_spectrum, id = 86, was added
Jan 03 17:14:15.123279 user easyeffects[79124]: sie: spectrum successfully connected to PipeWire graph
Jan 03 17:14:15.164262 user easyeffects[79124]: pipe_manager: Filter ee_sie_rnnoise, id = 140, was added
Jan 03 17:14:15.165144 user easyeffects[79124]: sie: rnnoise successfully connected to PipeWire graph
Jan 03 17:14:15.175893 user easyeffects[79124]: application: disabling global bypass
Jan 03 17:14:15.177805 user easyeffects[79124]: new default output device: alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo
Jan 03 17:14:15.177974 user easyeffects[79124]: presets_manager: autoloading preset HD58X Oratory1990 Harman for device alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo
Jan 03 17:14:15.178913 user easyeffects[79124]: presets_manager: loaded preset: /home/user/.config/easyeffects/output/HD58X Oratory1990 Harman.json
Jan 03 17:14:15.182637 user easyeffects[79124]: new default input device: alsa_input.pci-0000_0d_00.4.analog-stereo
Jan 03 17:14:15.185873 user easyeffects[79124]: application: device alsa_card.usb-JDS_Labs_JDS_Labs_Atom_DAC-00 has changed its output route to: iec958-stereo-output
Jan 03 17:14:15.185905 user easyeffects[79124]: presets_manager: autoloading preset HD58X Oratory1990 Harman for device alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo
Jan 03 17:14:15.186621 user easyeffects[79124]: presets_manager: loaded preset: /home/user/.config/easyeffects/output/HD58X Oratory1990 Harman.json
Jan 03 17:14:15.186643 user easyeffects[79124]: application: device alsa_card.pci-0000_0d_00.4 has changed its input route to: analog-input-rear-mic
Jan 03 17:14:17.481852 user easyeffects[79124]: application_ui: Icon Theme Adwaita detected
Jan 03 17:14:17.585980 user easyeffects[79124]: rnnoise_box: model directory already exists: /home/user/.config/easyeffects/rnnoise
Jan 03 17:14:22.834873 user easyeffects[79124]: presets_manager: destroyed
Jan 03 17:14:22.835081 user easyeffects[79124]: sie: destroyed
Jan 03 17:14:22.835098 user easyeffects[79124]: effects_base: destroyed
Jan 03 17:14:22.835107 user easyeffects[79124]: sie: stereo_tools destroyed
Jan 03 17:14:22.836642 user easyeffects[79124]: sie: reverb destroyed
Jan 03 17:14:22.838188 user easyeffects[79124]: sie: pitch destroyed
Jan 03 17:14:22.838210 user easyeffects[79124]: sie: multiband_gate destroyed
Jan 03 17:14:22.839812 user easyeffects[79124]: sie: multiband_compressor destroyed
Jan 03 17:14:22.841379 user easyeffects[79124]: sie: maximizer destroyed
Jan 03 17:14:22.842204 user easyeffects[79124]: sie: loudness destroyed
Jan 03 17:14:22.843062 user easyeffects[79124]: sie: limiter destroyed
Jan 03 17:14:22.843966 user easyeffects[79124]: sie: gate destroyed
Jan 03 17:14:22.844805 user easyeffects[79124]: sie: filter destroyed
Jan 03 17:14:22.845630 user easyeffects[79124]: sie: exciter destroyed
Jan 03 17:14:22.846495 user easyeffects[79124]: sie: equalizer destroyed
Jan 03 17:14:22.848350 user easyeffects[79124]: sie: echo_canceller destroyed
Jan 03 17:14:22.848365 user easyeffects[79124]: sie: delay destroyed
Jan 03 17:14:22.849220 user easyeffects[79124]: sie: deesser destroyed
Jan 03 17:14:22.850040 user easyeffects[79124]: sie: crystalizer destroyed
Jan 03 17:14:22.850059 user easyeffects[79124]: sie: crossfeed destroyed
Jan 03 17:14:22.850072 user easyeffects[79124]: sie: convolver destroyed
Jan 03 17:14:22.850084 user easyeffects[79124]: sie: compressor destroyed
Jan 03 17:14:22.850994 user easyeffects[79124]: sie: bass_loudness destroyed
Jan 03 17:14:22.851798 user easyeffects[79124]: sie: bass_enhancer destroyed
Jan 03 17:14:22.852671 user easyeffects[79124]: sie: autogain destroyed
Jan 03 17:14:22.853141 user easyeffects[79124]: sie: spectrum destroyed
Jan 03 17:14:22.853406 user easyeffects[79124]: sie: output_level destroyed
Jan 03 17:14:22.856355 user easyeffects[79124]: soe: destroyed
Jan 03 17:14:22.856374 user easyeffects[79124]: effects_base: destroyed
Jan 03 17:14:22.856382 user easyeffects[79124]: soe: stereo_tools destroyed
Jan 03 17:14:22.857480 user easyeffects[79124]: soe: rnnoise destroyed
Jan 03 17:14:22.857502 user easyeffects[79124]: soe: reverb destroyed
Jan 03 17:14:22.858370 user easyeffects[79124]: soe: pitch destroyed
Jan 03 17:14:22.858385 user easyeffects[79124]: soe: multiband_gate destroyed
Jan 03 17:14:22.859272 user easyeffects[79124]: soe: multiband_compressor destroyed
Jan 03 17:14:22.860536 user easyeffects[79124]: soe: maximizer destroyed
Jan 03 17:14:22.861341 user easyeffects[79124]: soe: loudness destroyed
Jan 03 17:14:22.862187 user easyeffects[79124]: soe: limiter destroyed
Jan 03 17:14:22.863077 user easyeffects[79124]: soe: gate destroyed
Jan 03 17:14:22.863921 user easyeffects[79124]: soe: filter destroyed
Jan 03 17:14:22.864761 user easyeffects[79124]: soe: exciter destroyed
Jan 03 17:14:22.865596 user easyeffects[79124]: soe: echo_canceller destroyed
Jan 03 17:14:22.865611 user easyeffects[79124]: soe: delay destroyed
Jan 03 17:14:22.866493 user easyeffects[79124]: soe: deesser destroyed
Jan 03 17:14:22.867312 user easyeffects[79124]: soe: crystalizer destroyed
Jan 03 17:14:22.867338 user easyeffects[79124]: soe: crossfeed destroyed
Jan 03 17:14:22.867348 user easyeffects[79124]: soe: convolver destroyed
Jan 03 17:14:22.867361 user easyeffects[79124]: soe: compressor destroyed
Jan 03 17:14:22.868265 user easyeffects[79124]: soe: bass_loudness destroyed
Jan 03 17:14:22.869088 user easyeffects[79124]: soe: bass_enhancer destroyed
Jan 03 17:14:22.869933 user easyeffects[79124]: soe: autogain destroyed
Jan 03 17:14:22.870351 user easyeffects[79124]: soe: spectrum destroyed
Jan 03 17:14:22.870675 user easyeffects[79124]: soe: output_level destroyed
Jan 03 17:14:22.870693 user easyeffects[79124]: pipe_manager: Destroying PipeWire registry...
Jan 03 17:14:22.870695 user easyeffects[79124]: pipe_manager: Disconnecting PipeWire core...
Jan 03 17:14:22.871027 user easyeffects[79124]: pipe_manager: Audio/Sink alsa_output.usb-JDS_Labs_JDS_Labs_Atom_DAC-00.iec958-stereo was removed
Jan 03 17:14:22.871031 user easyeffects[79124]: pipe_manager: Audio/Source alsa_input.pci-0000_0d_00.4.analog-stereo was removed
Jan 03 17:14:22.871038 user easyeffects[79124]: pipe_manager: Stream/Output/Audio spotify was removed
Jan 03 17:14:22.871042 user easyeffects[79124]: pipe_manager: Stream/Output/Audio spotify was removed
Jan 03 17:14:22.871045 user easyeffects[79124]: pipe_manager: Stream/Output/Audio spotify was removed
Jan 03 17:14:22.871048 user easyeffects[79124]: pipe_manager: Stream/Output/Audio spotify was removed
Jan 03 17:14:22.871056 user easyeffects[79124]: pipe_manager: Audio/Sink easyeffects_sink was removed
Jan 03 17:14:22.871058 user easyeffects[79124]: pipe_manager: Audio/Source/Virtual easyeffects_source was removed
Jan 03 17:14:22.887879 user easyeffects[79124]: pipe_manager: Stopping PipeWire's loop...
Jan 03 17:14:22.887948 user easyeffects[79124]: pipe_manager: Destroying PipeWire's context...
Jan 03 17:14:22.888206 user easyeffects[79124]: pipe_manager: Destroying PipeWire's loop...
Jan 03 17:14:22.888238 user easyeffects[79124]: application: shutting down...
Jan 03 17:14:22.888362 user easyeffects[79124]: Exitting the main function with status: 0
```
</details>

<details><summary>Second instance debug log</summary><br/>

```
(process:79133): easyeffects-DEBUG: 17:14:17.459: easyeffects version: 6.2.0
(process:79133): easyeffects-DEBUG: 17:14:17.460: main: locale directory: /usr/share/locale
(easyeffects:79133): easyeffects-DEBUG: 17:14:17.462: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:79133): easyeffects-DEBUG: 17:14:17.462: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:79133): easyeffects-DEBUG: 17:14:17.462: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:79133): easyeffects-DEBUG: 17:14:17.462: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:79133): easyeffects-DEBUG: 17:14:17.462: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/
(easyeffects:79133): easyeffects-DEBUG: 17:14:17.462: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/input
(easyeffects:79133): easyeffects-DEBUG: 17:14:17.462: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/output
(easyeffects:79133): easyeffects-DEBUG: 17:14:17.462: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/autoload/input
(easyeffects:79133): easyeffects-DEBUG: 17:14:17.462: presets_manager: user presets directory already exists: /home/user/.config/easyeffects/autoload/output
(easyeffects:79133): easyeffects-DEBUG: 17:14:17.593: Exitting the main function with status: 1
```
</details>

### Additional Information

My systemd service starts at boot (and login)
I debugged with this service file:
```
[Unit]
Description=easyeffects daemon
PartOf=graphical-session.target
After=graphical-session.target

[Service]
Environment="G_MESSAGES_DEBUG=easyeffects"
ExecStart=/usr/bin/easyeffects --gapplication-service
Restart=on-failure

[Install]
WantedBy=graphical-session.target
```

Also, the exit log from the 2nd instance is printed right at launch.
But the PID that exits is indeed the newly launched program, not the running service.

Will look into bisecting a bit later.

**Comment by quietvoid** [comment] 2022-01-03 22:47
Tried on e13f757d5ac69eae9b02fbee44bb1837b9a3ca06 and I'm not able to reproduce the issue.
Time to bisect I guess.

**Comment by wwmm** [comment] 2022-01-03 22:47
Could it be that `Shutdow on Window Close` is enabled on your installation? This is the behavior I would expect when this setting is enabled.

**Comment by quietvoid** [comment] 2022-01-03 22:48
No, it's disabled.

**Comment by wwmm** [comment] 2022-01-03 22:57
There is something odd in your installation. I have been using the master branch everyday for  a few weeks and I do not have in my logs the errors I see in yours
```
Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

'spa_pod_is_array(pod)' failed at /usr/include/spa-0.2/spa/pod/iter.h:339 spa_pod_get_array()
```
I have never seen any of them. One of the first things I did in the master branch was using `adw_style_manager_set_color_scheme` like suggested by the warning message. This is already there. THe PipeWire error is something I also have never seen.

**Comment by wwmm** [comment] 2022-01-03 23:04
>I debugged with this service file:

What happens if you run `/usr/bin/easyeffects --gapplication-service` by hand in a terminal and start `easyeffects` on another? One obvious difference between our Arch Linux installations is that I do not use systemd to start EasyEffects.

**Comment by quietvoid** [comment] 2022-01-03 23:10
> One of the first things I did in the master branch was using adw_style_manager_set_color_scheme like suggested by the warning message

I had a stray settings.ini with `gtk-application-prefer-dark-theme` in my gtk4 configs.
Removing it also removed the warning, but not the `spa_pod_is_array` error.

> What happens if you run /usr/bin/easyeffects --gapplication-service by hand in a terminal and start easyeffects on another?

The same behaviour happens.

**Comment by quietvoid** [comment] 2022-01-03 23:15
One notable difference is that the second instance on 6.1.5 outputs this on quit:
```
(easyeffects:99330): easyeffects-DEBUG: 18:14:31.505: application:  destroyed
(easyeffects:99330): easyeffects-DEBUG: 18:14:31.505: presets_manager: destroyed
```

Seemingly the master version exits with an error instead.

**Comment by quietvoid** [comment] 2022-01-03 23:30
I'm a bit confused that I landed on 7bf78accaa9570e0fe17280f9f51ac46dc3cdb4f as first bad commit, since it's before the 6.1.5 tag.
Gonna try again but maybe that helps you a bit.

**Comment by wwmm** [comment] 2022-01-03 23:36
>since it's before the 6.1.5 tag.

I had an `libadwaita` branch where work was being done for some time. `6.1.5` was released as a bugfix release while I was removing gtkmm from our code.

It seems to me that the only version of EasyEffects behaving properly on your system are the ones based on gtkmm. Now that we use gtk4 directly something that is different on your system may be triggering some kind of gtk4 bug. It is looking like one of those odd situations where gtk misbehaves outside of GNOME =/

**Comment by wwmm** [comment] 2022-01-03 23:42
When EasyEfects receives the command line option to start as a service we do https://github.com/wwmm/easyeffects/blob/7f88daa66886a5bd5e7a83b2e9af5370a090febc/src/application.cpp#L237. Under normal circunstances that reference should be kept even if there are no windows associated to the application. This is how it keeps running in the background. For some reason on your system gtk does not seem to be creating this additional reference and the application closes. I wonder why...

**Comment by wwmm** [comment] 2022-01-03 23:45
It is a known thing that gtk4 and sway have some incompatibilities. But I do not see how the desktop could be having such a side effect on gtk.

**Comment by quietvoid** [comment] 2022-01-04 00:11
So I ended up on the same commit on the second bisect.

However I did test on X11 + AwesomeWM and the issue is present depending on how I close the window.
If I use the decorator/app close button, the service is still running.

However if I Ctrl+Q, it is exited.

**Comment by wwmm** [comment] 2022-01-04 00:16
>However if I Ctrl+Q, it is exited.

That is the expected behavior. `Gtrl+Q` makes the application exit and `Ctrl+W` only closes the window allowing the service to keep running. Based on what you described things seems to work as intended in `X11 + AwesomeWM`. It seems we really have one more incompatibility between gtk4 and sway. The question is why this is happening only now that we are using gtk4 directly without gtkmm as the man in the middle.

**Comment by quietvoid** [comment] 2022-01-04 00:18
I can indeed get the correct behaviour by using the app close button even on Sway.
I was not aware of Ctrl+W, but that also works.

So not sure if there's still an issue here.

**Comment by wwmm** [comment] 2022-01-04 00:20
Oh! I see. This is a new behavior we did not have before. If you were testing with `Ctrl+Q` then everything makes sense. As EasyEffects is an application that can stay running in the background I had to make a distinction between only closing the window and quitting the whole application.

**Comment by quietvoid** [comment] 2022-01-04 00:23
Oh well, I guess I learned about Ctrl+W after all of this.
Would close the issue, unless you want to modify the behaviour to take into consideration a running service.

**Comment by wwmm** [comment] 2022-01-04 00:25
I think we can close this.

**Closed by wwmm** 2022-01-04 00:25 UTC

**Comment by crisap94** [comment] 2022-01-04 15:38
I'm having the same problem, I don't think Ctrl+W is the solution, I mean If the option exists "Shutdown on window close", thereafter if I click the Window X button It shouldn't disable it, the app does not get killed but the service seems not to apply the configuration until I re-open the app.

**Comment by wwmm** [comment] 2022-01-04 16:18
>I mean If the option exists "Shutdown on window close", thereafter if I click the Window X button It shouldn't disable it

That option was added to cover a very specific corner case and for many times I considered removing it. Some people want the service to be finished when they close the window. Independently of how they are closing the window. What is not possible under normal circumstances when EasyEffects is started as a service. That option exists only to allow that.

The only difference in the next release is that the meaning of `Ctrl+Q` has changed. It is now meant to finish the application instead of "closing its window". For people that use `Ctrl+W` or click on the "close button" things are still the same. Two different options to close the window without killing the service.
