### ISSUE TITLE
AutoGain distortion and Dropouts after closing interface...

### ISSUE THREAD

**Issue by BayouGuru67** [wwmm/easyeffects#2364] opened 2023-05-20 18:50 UTC
### EasyEffects Version

7.0.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Kubuntu 22.04.2 LTS (fully-updated)

### Describe the bug

If I close the GUI interface the audio will drop out briefly while using my computer.  Not under heavy loads, just opening a webpage or document will cause it.  If I do not close the GUI, it does not seem to have this problem.

AutoGain could use a bit more work, as it is still a little broken compared to the quality of it's operation back in the PulseEffects days, and it is horribly distorting the first quarter second or so of every new audio source played.  Shouldn't it be looking ahead a bit?  Mind you, this is an improvement over 7.0.3 which had a tendency to play a bit of loud, distorted historical audio on the front side of each new audio source played.

### Expected Behavior

I expect the audio not to drop out when I open a document or web page.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

I am only running AutoGain to a target of -15 db and using the Limiter to minimize the volume changes from the various videos, etc. and keep a firm lid on the levels.   If I run regular Compression, the dropout problem happens a bit more often.  If I run Multi-band Compression, it happens even more frequently.  While the latest update seems to have largely fixed the problem of noise (briefly distorted audio) when starting new audio sources, the dropouts that have come with it are very annoying. It does not seem to be a matter of CPU usage, as the usage is plenty low, usually hovering around 2% on my 6-core AMD system.

**Comment by wwmm** [comment] 2023-05-20 21:31
>If I close the GUI interface the audio will drop out briefly while using my computer. Not under heavy loads, just opening a webpage or document will cause it. If I do not close the GUI, it does not seem to have this problem.

I use this plugin all the time and I have never seen something like this happening. Are you able to record this? "Distortion" can have many different forms. Try to get some logs follow the third step of this section https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs#basic-logs. You can make it run without showing the window by passing the option `--gappliccation-service`.

>AutoGain could use a bit more work, as it is still a little broken compared to the quality of it's operation back in the PulseEffects days, and it is horribly distorting the first quarter second or so of every new audio source played. 

That is very debatable. It isn't broken and has more features and better code now than it ever had in PulseEffects. And considering that all it does it adjust volume levels it is not very likely it is doing what we usually mean by distortion.

> While the latest update seems to have largely fixed the problem of noise (briefly distorted audio) when starting new audio sources,

That sounds like something related to PipeWire's dynamic latency switching that can happen when a new stream is started and requests a lower latency than the currently being used. Our last release has no change in this direction. A PipeWire upgrade is more likely to be related.

>the dropouts that have come with it are very annoying.

Dropout?? Something unusual is happening in your computer. No doubt. But the autogain is probably not the cause. Something else is going on. If possible try to take a print of `pw-top` output while these issues are happening.

**Comment by wwmm** [comment] 2023-05-24 13:36
Ok! Good to know a pipewire updated helped. We can close this issue then.

**Closed by wwmm** 2023-05-24 13:36 UTC
