### ISSUE TITLE
Top menus block all other Ubuntu interaction 

### ISSUE THREAD

**Issue by robotard** [wwmm/easyeffects#1255] opened 2021-11-18 07:19 UTC
Ubuntu 21.10, Pipewire 0.3.32, EasyEffects 6.1.4

Upon clicking top bar menu options such as presets or settings, you cannot interact with anything else running on Ubuntu until you click the top menu again...

This even blocks the import dialog to choose the preset file you wish to import (on that note, I've upgraded from PulseEffects, and the open file screen isn't showing ~/.config to find my old PulseEffects/output presets, and ubuntu is set to show all files)

**Comment by vchernin** [comment] 2021-11-18 07:28
This sounds like https://github.com/wwmm/easyeffects/issues/1182.

Ubuntu 21.10 defaults to Wayland which avoids this problem. Do you have Nvidia graphics or are you using Kubuntu or something?

**Comment by wwmm** [comment] 2021-11-18 13:29
It is definitely the same thing. I have already reported some of these menu issues to the gtk4 developers. But I have no idea if they are looking into it.

**Comment by robotard** [comment] 2021-11-18 20:56
Can confirm NVidia here, but this is booting into X11 currently as am triing to fix one thing at a time... 

Reeeeeallly want Wayland working well for both audio and video though... Seem to keep getting some weird audio blips that I can only tell seem to correlate with a gnome session restart straight after? No log out, just audio drops half a second... Very occassionally I get a huuuuge static response (directly through to my amp) that bumps the volume to 1000%. Doesnt stop until I change audio output then back... Terrifying!

**Comment by wwmm** [comment] 2021-12-18 15:24
Closing this issue as the problem is already being tracked somewhere else.

**Closed by wwmm** 2021-12-18 15:24 UTC
