### ISSUE TITLE
Sporadic delay in starting audio. 

### ISSUE THREAD

**Issue by haonanq666** [wwmm/easyeffects#906] opened 2021-02-28 09:58 UTC
I have noticed that on the latest version of pulseeffects, pipewire, and pipewire-pulse available in the arch repositories, sometimes audio will lag behind by upwards of 2 seconds. I have not been able to find a way to consistently reproduce the bug, but watching a few videos on youtube and starting and stopping randomly likely will cause this. 

After opening pulseeffects, sometimes audio appears up to 2 seconds after pressing "play" on the video on youtube (sometimes a few hundred milliseconds, the delay is inconsistent). The audio will lag behind the video by up to 2 seconds, and will continue to play for an equivalent duration after pressing "stop". 

This is different from #898 because pulseeffects still plays the audio (without crashing). The only other abnormal behavior is when I switch to a new page, in the time that the new video loads, the audio is choppy, like if you hold the spacebar on a youtube video. 

After killing pulseeffects, running only pipewire-pulse, there is no noticeable lag starting and stopping audio nor is there the choppy sound when loading a new page. I have not changed any default configurations (latency, buffer, etc.). Also, these issues were not encountered on the previous version of pulseeffects (which used pulseaudio). Also, this misbehavior is temporarily fixed if I pause the video long enough for ``pipe_manager`` to remove the current stream and a new stream is started when I resume. 

Apologies for not giving a more detailed description, I am not an audio professional. I would be happy to provide further debugging, but please ask for it in the simplest of terms.

**Comment by wwmm** [comment] 2021-02-28 14:29
What is the output of `pw-top` when PulseEffects and your audio applications are running? This is sounding like one of the issues caused by PipeWire dynamic latency update. It may also help to see some logs. After getting the pw-top output kill PulseEffects `pulseeffects -q` and restart it in de bug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`.

**Comment by haonanq666** [comment] 2021-02-28 22:38
``pw-top`` while audio and pulseeffects are running (and when I noticed the delay and chopping occurring):
```
S   ID  QUANT   RATE    WAIT    BUSY   W/Q   B/Q  ERR  NAME                                                   

!   28      0      0   0.0  s   0.0  s  0.00  0.00    0  Dummy-Driver
!   33      0      0   0.0  s   0.0  s  0.00  0.00    0  Midi-Bridge
!   39      0      0   0.0  s   0.0  s  0.00  0.00    0  alsa_output.pci-0000_04_00.1.pro-output-3
    40   1024  48000 390.5  s  34.4  s  0.02  0.00    0  alsa_output.usb-bestechnic_HUAWEI_USB-C_HEADSET_0296
    86      0      0  48.7  s  25.4  s  0.00  0.00    0   + pulseeffects_sink
    88   1024  48000  67.7  s  35.8  s  0.00  0.00    0   + Chromium
   111      1     20 107.3  s  32.9  s  0.01  0.00    0   + pulseeffects_soe
    97      1     20  80.3  s  34.3  s  0.00  0.00    0   + pulseeffects_soe
!   41      0      0   0.0  s   0.0  s  0.00  0.00    0  alsa_input.usb-bestechnic_HUAWEI_USB-C_HEADSET_0296A
!   42      0      0   0.0  s   0.0  s  0.00  0.00    0  alsa_output.pci-0000_04_00.6.analog-surround-40
!   43      0      0   0.0  s   0.0  s  0.00  0.00    0  alsa_input.pci-0000_04_00.6.analog-stereo
!   89      0      0   0.0  s   0.0  s  0.00  0.00    0  pulseeffects_source
```
The debug output:
```
(process:42022): pulseeffects-DEBUG: 17:22:48.805: main: locale directory: /usr/share/locale
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.032: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.032: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.032: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.032: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.032: presets_manager: user presets directory already exists: /home/dddf/.config/PulseEffects
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.032: presets_manager: user presets directory already exists: /home/dddf/.config/PulseEffects/input
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.032: presets_manager: user presets directory already exists: /home/dddf/.config/PulseEffects/output
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.032: presets_manager: user presets directory already exists: /home/dddf/.config/PulseEffects/autoload
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.040: application: PE version: 5.0.0
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.040: pipe_manager: compiled with pipewire: 0.3.20
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.040: pipe_manager: linked to pipewire: 0.3.22
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.043: pipe_manager: core version: 0.3.22
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.044: pipe_manager: core name: pipewire-0
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.044: pipe_manager: found metadata: default
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.044: pipe_manager: found metadata: route-settings
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.044: pipe_manager: Audio/Sink 39 alsa_output.pci-0000_04_00.1.pro-output-3 was added
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.044: pipe_manager: Audio/Sink 40 alsa_output.usb-bestechnic_HUAWEI_USB-C_HEADSET_0296A100000000000000000000000-00.iec958-stereo was added
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.044: pipe_manager: Audio/Source 41 alsa_input.usb-bestechnic_HUAWEI_USB-C_HEADSET_0296A100000000000000000000000-00.analog-stereo was added
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.044: pipe_manager: Audio/Sink 42 alsa_output.pci-0000_04_00.6.analog-surround-40 was added
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.044: pipe_manager: Audio/Source 43 alsa_input.pci-0000_04_00.6.analog-stereo was added
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.044: pipe_manager: Audio/Sink 86 pulseeffects_sink was added
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.044: pipe_manager: Audio/Duplex 89 pulseeffects_source was added
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.044: pipe_manager: connected to the core
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.045: pipe_manager: new metadata property: 0, default.audio.sink, Spa:Id, 40
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.045: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:Id, 40
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.045: pipe_manager: new metadata property: 0, default.configured.audio.source, Spa:Id, 41
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.045: pipe_manager: new metadata property: 0, default.audio.source, Spa:Id, 41
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.061: soe: using input device: 86
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.061: soe: using output device: 40
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.065: soe: limiter is enabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.068: soe: compressor is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.070: soe: filter is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.108: soe: equalizer is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.110: soe: reverb is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.111: soe: bass_enhancer is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.112: soe: exciter is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.113: soe: crossfeed is already disabled

(pulseeffects:42022): pulseeffects-WARNING **: 17:22:49.114: maximizer plugin was not found!
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.117: soe: multiband_compressor is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.118: soe: loudness is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.120: soe: gate is already disabled

(pulseeffects:42022): pulseeffects-WARNING **: 17:22:49.120: pitch plugin was not found!
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.123: soe: multiband_gate is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.124: soe: deesser is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.126: soe: stereo_tools is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.128: soe: convolver is enabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.130: soe: crystalizer is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.131: soe: autogain is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.133: soe: delay is already disabled

(pulseeffects:42022): pulseeffects-WARNING **: 17:22:49.133: rnnoise plugin was not found!
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.140: sie: using input device: 41
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.140: sie: using output device: 89
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.140: sie: limiter is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.141: sie: compressor is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.141: sie: filter is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.146: sie: equalizer is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.146: sie: reverb is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.147: sie: gate is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.148: sie: deesser is already disabled

(pulseeffects:42022): pulseeffects-WARNING **: 17:22:49.148: pitch plugin was not found!
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.153: sie: webrtc is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.153: sie: multiband_compressor is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.154: sie: multiband_gate is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.154: sie: stereo_tools is already disabled

(pulseeffects:42022): pulseeffects-WARNING **: 17:22:49.154: maximizer plugin was not found!

(pulseeffects:42022): pulseeffects-WARNING **: 17:22:49.154: rnnoise plugin was not found!
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.156: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.156: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.156: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.156: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.156: presets_manager: user presets directory already exists: /home/dddf/.config/PulseEffects
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.156: presets_manager: user presets directory already exists: /home/dddf/.config/PulseEffects/input
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.156: presets_manager: user presets directory already exists: /home/dddf/.config/PulseEffects/output
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.156: presets_manager: user presets directory already exists: /home/dddf/.config/PulseEffects/autoload
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.156: presets_manager: destroyed
pulseeffects-INFO: 17:22:49.156: application: disabling global bypass
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.156: soe: bypass is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.156: sie: bypass is already disabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.481: convolver_ui: irs directory already exists: /home/dddf/.config/PulseEffects/irs
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.491: rnnoise_ui: model directory already exists: /home/dddf/.config/PulseEffects/rnnoise
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.840: rnnoise_ui: model directory already exists: /home/dddf/.config/PulseEffects/rnnoise
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.875: sie: spectrum enabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.876: soe: spectrum enabled
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.879: soe: using output device: 40
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.879: sie: webrtc probe is using input device: 40
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.879: pipe_settings_ui: selected output device changed: alsa_output.usb-bestechnic_HUAWEI_USB-C_HEADSET_0296A100000000000000000000000-00.iec958-stereo
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.879: sie: using input device: 41
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:49.879: pipe_settings_ui: selected input device changed: alsa_input.usb-bestechnic_HUAWEI_USB-C_HEADSET_0296A100000000000000000000000-00.analog-stereo
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:50.585: new default sink: alsa_output.usb-bestechnic_HUAWEI_USB-C_HEADSET_0296A100000000000000000000000-00.iec958-stereo
(pulseeffects:42022): pulseeffects-DEBUG: 17:22:50.586: new default source: alsa_input.usb-bestechnic_HUAWEI_USB-C_HEADSET_0296A100000000000000000000000-00.analog-stereo
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.277: pipe_manager: Stream/Output/Audio 97 Chromium was added
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.278: pipe_manager: new metadata property: 97, target.node, Spa:Id, 86
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.279: pipe_manager: Chromium port 93 is connected to pulseeffects_sink port 94
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.279: pipe_manager: Chromium port 100 is connected to pulseeffects_sink port 92
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.325: soe: sampling rate: 48000 Hz
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.349: peadapter: input block size 996 frames
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.349: peadapter: we will read in chunks of 512 frames
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.350: convolver: irs file: /home/dddf/.config/PulseEffects/irs/Dolby ATMOS ((128K MP3)) 1.Default.irs
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.350: convolver: irs rate: 44100 Hz
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.350: convolver: irs channels: 2
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.350: convolver: irs frames: 10368
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.350: convolver: resampling irs to 48000 Hz
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.351: soe: total latency: 30 ms
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.356: soe: NULL -> READY -> PLAYING
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.360: soe: READY -> PAUSED -> PLAYING
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.364: soe: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.364: soe: total latency: 30 ms
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.383: convolver: irs frames after resampling 11285
(pulseeffects:42022): pulseeffects-DEBUG: 17:23:31.383: convolver: autogain factor: 0.693024
(pulseeffects:42022): pulseeffects-DEBUG: 17:26:42.789: pipe_manager: Stream/Output/Audio Chromium was removed
(pulseeffects:42022): pulseeffects-DEBUG: 17:26:48.303: soe: No app wants to play audio. We will stop our pipeline.
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.560: pipe_manager: Stream/Output/Audio 88 Chromium was added
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.560: pipe_manager: new metadata property: 88, target.node, Spa:Id, 86
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.563: pipe_manager: Chromium port 102 is connected to pulseeffects_sink port 94
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.563: pipe_manager: Chromium port 91 is connected to pulseeffects_sink port 92
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.594: soe: sampling rate: 48000 Hz
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.620: peadapter: input block size 996 frames
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.620: peadapter: we will read in chunks of 512 frames
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.620: convolver: irs file: /home/dddf/.config/PulseEffects/irs/Dolby ATMOS ((128K MP3)) 1.Default.irs
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.620: convolver: irs rate: 44100 Hz
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.620: convolver: irs channels: 2
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.620: convolver: irs frames: 10368
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.620: convolver: resampling irs to 48000 Hz
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.620: soe: total latency: 30 ms
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.625: soe: NULL -> READY -> PLAYING
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.629: soe: READY -> PAUSED -> PLAYING
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.633: soe: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.633: soe: total latency: 30 ms
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.643: convolver: irs frames after resampling 11285
(pulseeffects:42022): pulseeffects-DEBUG: 17:30:16.643: convolver: autogain factor: 0.693024
```
(note: I removed some GTK warnings regarding the icons I'm using; I'm fairly certain they are irrelevant).

**Comment by haonanq666** [comment] 2021-03-02 02:29
Oh, and @wwmm do you have a good resource on how to configure the

> PipeWire dynamic latency update
 
The arch wiki pages (and any other webpage) doesn't really have good documentation on how to fiddle with PipeWire.

**Comment by wwmm** [comment] 2021-03-02 16:12
So far I did not see anything unusual in your logs. And the latency showed by `pw-top` is not big enough for a 2 seconds delay. `1024/48000 =  0.021` seconds. Is there any difference if you set `realtime` priority in our settings menu?

>do you have a good resource on how to configure the...

Take a look at this page https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Configuration. It is not complete but I am not aware of a better page.

**Comment by haonanq666** [comment] 2021-03-03 06:08
The latency is upwards of 2 seconds, sometimes only few hundred milliseconds. I was able to get a really long latency (even after setting ``real time`` to 1, the debug messages confirmed that this change was successful ``soe: rtkit: changed GstPipeWireSrc:source thread real-time priority value to 1``), and here is the pw-top output for it:
```
S   ID  QUANT   RATE    WAIT    BUSY   W/Q   B/Q  ERR  NAME                                                   

!   28      0      0   0.0  s   0.0  s  0.00  0.00    0  Dummy-Driver
!   33      0      0   0.0  s   0.0  s  0.00  0.00    0  Midi-Bridge
!   39      0      0   0.0  s   0.0  s  0.00  0.00    0  alsa_output.pci-0000_04_00.1.pro-output-3
!   42      0      0   0.0  s   0.0  s  0.00  0.00    0  alsa_output.pci-0000_04_00.6.analog-surround-40
!   43      0      0   0.0  s   0.0  s  0.00  0.00    0  alsa_input.pci-0000_04_00.6.analog-stereo
!  128      0      0   0.0  s   0.0  s  0.00  0.00    0  pulseeffects_sink
!   88      0      0   0.0  s   0.0  s  0.00  0.00    0  pulseeffects_source
    50   1024  48000 272.2  s  26.3  s  0.01  0.00   11  alsa_output.usb-bestechnic_HUAWEI_USB-C_HEADSET_0296
    94      1     20  37.2  s  21.7  s  0.00  0.00   11   + pulseeffects_soe
   179      0      0  62.0  s  25.8  s  0.00  0.00   11   + pulseeffects_sink
   111   1024  48000  59.3  s  25.4  s  0.00  0.00   11   + Chromium
   106      1     20  31.0  s  21.9  s  0.00  0.00   11   + pulseeffects_soe
   172      1     20  37.2  s  35.5  s  0.00  0.00   11   + pulseeffects_soe
!   51      0      0   0.0  s   0.0  s  0.00  0.00    0  alsa_input.usb-bestechnic_HUAWEI_USB-C_HEADSET_0296A
!   41      0      0   0.0  s   0.0  s  0.00  0.00    0  pulseeffects_soe
!   98      0      0   0.0  s   0.0  s  0.00  0.00    0  pulseeffects_source
``` 
I used [this video](https://www.youtube.com/watch?v=TjAa0wOe5k4). It starts off in sync, but if I keep refreshing the page, the latency becomes higher each time. The pw-top output was taken when the audio lagged behind by at least 2 seconds. The video has beeps once every second, and I could visually see two cycles went by before any beep was heard. After pausing the video, two extra beeps were heard before the audio stopped. The debug messages showed the same things it showed above. 

I could also reproduce this bug using a music player app. After pressing "next song" many times, the latency snowballs to more than 2 seconds. This is easy to see as the music player shows that the new song plays for 2 seconds before the audio from the last song stops and the start of the new song is played. The music player is based on Electron and Vue, and ``pipe_manager`` seems to recognize it as Chromium. 

I have tried using Elisa (``pipe_manager`` recognized the stream as Elisa) to play a local file, and also observed abnormal behavior. Pressing pause causes choppy audio (the audio plays for 2 seconds after pressing pause). There is a lag after pressing play. When running Elisa, I noticed these errors popped up:
```
(pulseeffects:68421): pulseeffects-WARNING **: 00:58:22.826: pipe_manager: Remote error on id:51

(pulseeffects:68421): pulseeffects-WARNING **: 00:58:22.826: pipe_manager: Remote error message:enum params id:2 (Spa:Enum:ParamId:Props) failed
```
I do not know why, whether it is relevant, nor did I find a way to consistently reproduce it. 

I have a wild uneducated guess that it is because ``pipe_manager`` mishandles the audio stream. I have aggressively paused/started a single video (on chromium) when audio was in sync, and it stayed in sync. Also, after ``pipe_manager`` removes the stream and adds it again, the audio is back in sync. It seems that when interacting directly with ``pipe_manager``, such as when loading a new page on chromium, or pausing on a native music app, does the stuttering and lag kick in.

**Comment by wwmm** [comment] 2021-03-03 14:48
>I used this video. It starts off in sync, but if I keep refreshing the page, the latency becomes higher each time

It seems this issue will be one of those that is hard to solve. So far refreshing the page in Firefox changes nothing in my desktop.  It is still synchronized. This may be a hardware dependent bug. I will try to test in my laptop too.

>I have a wild uneducated guess that it is because pipe_manager mishandles the audio stream

pipe_manager does not handle audio player streams in the way you are think. In this case the player itself is destroying and creating streams. When this happens PipeWire notifies every client that asked to be notified about these events. That is what pipe_manager is doing in this case. Just printing events sent by PipeWire.

What is happening to you is probably a bad interaction between Pipewire's plugins for GStreamer, pipewiresrc and pipewiresink, and the PipeWire server itself. But I am not sure why yet...

**Comment by wwmm** [comment] 2021-03-03 14:55
So far refreshing the audio sync test in Firefox has no problems in my laptop too. Issue  #898 happens for reasons that are still unknown. But no delay.

**Comment by AbsurdlySuspicious** [comment] 2021-07-03 08:36
I've been able to reproduce exactly this under high cpu load. One particular thing I noticed is that when I press pause in deadbeef, it disappears from application list in PE, debug logs say its stream is removed, but "buffered" several seconds of audio still play and spectrum widget reacts to it. It keeps playing until this dangling buffer ends or until activity timeout stops the pipeline, whichever happens first. I'll post pw-top output next time I encounter this

**Comment by AbsurdlySuspicious** [comment] 2021-09-02 00:36
Regarding v5: I've checked pw-top several times when this happened and it was no different compared to moments when there's no delay. I believe dynamic latency have nothing to do with this

Regarding v6: I haven't encountered this issue yet even under high load. Transition to pw-filters should have solved this

**Comment by wwmm** [comment] 2021-09-02 00:51
>Regarding v6: I haven't encountered this issue yet even under high load. Transition to pw-filters should have solved this

Interesting. Considering that EasyEffects is the currently supported app for PipeWire I will close this. Debugging the v5 releases won't be productive because of the move from GStreamer to PipeWire filters. The approach is too different.

**Closed by wwmm** 2021-09-02 00:51 UTC
