### ISSUE TITLE
[Feature Request] Compact mode for UI

### ISSUE THREAD

**Issue by Mlocik97** [wwmm/easyeffects#774] opened 2020-09-03 13:18 UTC
As I can see, 720px height is minimum resolution for today's systems. So for Window we have about 700px of free space. I tested with different themes, what will be minimum height, after squashing at minimum size. With Ambiance theme, I get 653px Height of viewport, the same I get with Radiance theme. but with Adwaita theme, I get 686px Height. So it's nearly not fitting to display with 720p resolution.

So yes, You are right, there is no space.

But...

I think, we can be able to squash elements in interface, if we somehow reorder items, or change size of these elements, such as buttons. I know too dense UI is not "pretty", but we propably can create **compact mode for UI.**. And automatically active it for displays with small resolutions.

_Originally posted by @Mlocik97 in https://github.com/wwmm/pulseeffects/issues/724#issuecomment-686483920_

**Comment by Mlocik97** [comment] 2020-09-03 13:30
I don't know much about GTK, but my second idea is to create liquid interface, or use relative values to set sizes, instead absolute. (So it will not take exactly 40px on all resolutions, but 2% of display size)

**Comment by wwmm** [comment] 2020-09-03 14:03
Too much effort for too little gain. It is not that it is hard to do in gtk. It would be a pain in qt too. The problem is you can't just change create another interface files in glade( in qt it would be qt designer) you have to bound them to c++ classes. If we use the same c++ class for each kind of interface we have to ensure that they have exactly the same amount of widgets and each of them must have the same name in each interface. And the c++ classes would have to be recreated on the fly to do this change. The other way would be to have one c++ class for each interface kind. But now we have doubled the total amount of interface code that has to be maintained...

And on top of this there is the difficulty of making such alternative interface. In order to reduce a button size you have to reduce it's label font. This may be bad. The only way this interface could be smaller would be using lots of tabs. What makes things more complex to develop and use.

**Comment by ernestask** [comment] 2020-09-13 10:38
Maybe you might be interested in knowing about https://gitlab.gnome.org/GNOME/libhandy.

**Comment by paper42** [comment] 2021-03-21 17:41
There is libadwaita (libhandy for GTK4) which allows building adaptive applications.

**Comment by wwmm** [comment] 2021-03-21 19:41
The idea behind these libraries is good. But they are not mature enough. And writing interfaces in plain C is too painful. Specially the amount of interface that we have. If one day a mature, reliable integration of such libraries in GTKMM4 is available they would be an option to consider.

**Comment by Mlocik97** [comment] 2021-03-21 19:45
hmm, so now I understand why everyone use Electron instead GTK or QT...

**Comment by wwmm** [comment] 2021-03-21 20:39
>is it really that much problem to do little responsivity/adaption and add Compact mode for UI in GTK?

As far as I know in standard QT or GTK we have to hide/show the widgets ourselves. As well as reloading or loading a new interface if that is more appropriated. It is a manual process.

>I understand why everyone use Electron instead GTK or QT

This is probably more related to the use of javascript and on how easy is to make a multiplatform app. I doubt any framework will be able to alternate from standard to compact mode in complex applications without some serious amount of work from the programmers. Same thing on Android. Different interfaces for portrait and landscape orientations do not come for free. You have to code considering that. And in some cases you have to write one interface for each orientation.

What complicates these things is that there is no point in a compact mode that hides from the user widgets that have to be used no matter what. The application will be useless. This is something that toolkit does not have how to know for itself.

>I'm starting to not like GTK, I wanted to learn it, but well, I will propably still use Electron instead.

There is always a compromise when choosing a graphical toolkit. If you want to run your applications in other operational systems GTK I do not recommend GTK. QT still is the better option if the programmer is comfortable with C++. I think electron is more for people that want to write multiplatform applications in javascript. I doubt you have the same performance and flexibility QT can offer when writing the application.

**Comment by wwmm** [comment] 2021-03-21 20:47
On the other hand if I can support only Linux I prefer GTK. Being able to put widgets in menus (popover) is very convenient in some situations. Personally I think that supporting translations in GTK is very simple. And you have the ecosystem that comes with it. Like the gsettings framework I use in the presets systems. In my opinion the alternative offered by QT does not come even close.

GTK also offers for free a service mode so we can close the window and keeping the app running in the background. Not having to writing dbus code to create a service made my life a lot easier.

As I said there is always a tradeoff.

**Comment by wwmm** [comment] 2021-07-10 04:33
I think the interface is as compact as it can get. Time to close this.

**Closed by wwmm** 2021-07-10 04:33 UTC
