### ISSUE TITLE
Pop!_OS Flatpak EasyEffects no audio after 5 minutes in Dota/CS2

### ISSUE THREAD

**Issue by Ivanmt22** [wwmm/easyeffects#3249] opened 2024-07-12 02:05 UTC
### EasyEffects Version

7.1.7

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop!_OS 22.04 LTS

### Describe the bug

I'm using EasyEffects **only** for my microphone (Mainly Noise Reduction & Bass Enhancer) for discord on Pop!_OS, installed through the Pop_Store, I have no need for EasyEffects for my outputs, just inputs. Everytime I boot up CS2 or Dota, those games specifically; I lose audio after 5 minutes. I then go into audio settings (which in both games they're set to default) I change it to "Easy Effects Sink" I get audio again, but only for another 5 minutes. After that, I'm unable to get audio again; even after switching to literally every single other output I have. The only way to get audio again, is to restart, which after a few minutes loses me audio, rinse and repeat. My best guess is because CS and Dota both have the ability to change audio output, that's somehow affecting things. I've also checked my outputs when it happens and nothing changes. 

### Expected Behavior

For audio to consistently be active in CS and Dota using EasyEffects. 

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

Steam isn't flatpak, .deb package.

**Comment by wwmm** [comment] 2024-07-12 03:10
Did you disable `Process All Output Streams` in EasyEffects preferences window? If you do not do this EE will move streams to its virtual output device. Once you disable this option your playback streams will be entirely manager by WirePlumber. If things still do not work right at this point the issue is on WirePlumber/PipeWire side.

**Comment by violetmage** [comment] 2024-07-12 03:15
I think in this case the log output from easyeffects would be very helpful.

[Instructions for getting easyeffects logs](https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs#basic-logs)

**Comment by Ivanmt22** [comment] 2024-07-12 04:29
> Did you disable `Process All Output Streams` in EasyEffects preferences window?

As far as I'm aware, I did. I also forced which output and input to use and it still gave me hassle. For the time being, I've switched to NoiseTorch as I only needed input. If I ever need an equalizer I'll redownload EasyEffects. Thanks for the suggestion guys.

**Comment by wwmm** [comment] 2024-07-12 05:08
> > Did you disable `Process All Output Streams` in EasyEffects preferences window?
> 
> As far as I'm aware, I did. I also forced which output and input to use and it still gave me hassle. For the time being, I've switched to NoiseTorch as I only needed input. If I ever need an equalizer I'll redownload EasyEffects. Thanks for the suggestion guys.

One possibility is that the PipeWire version in your repositories is too old to to be used with EasyEffects.  Ubuntu/Debian takes too long to update PipeWire. And the situation is probably worse in the LTS. Most of the problems I usually see Ubuntu users having are fixed by installing a newer PipeWire version through a PPA and rebooting.

As I can't reproduce the issue at least on Proton games and you moved to NoiseTorch this issue can be closed.

**Closed by wwmm** 2024-07-12 05:08 UTC
