### ISSUE TITLE
Settings dialog box not closing

### ISSUE THREAD

**Issue by alexbramford** [wwmm/easyeffects#1293] opened 2021-12-15 03:22 UTC
### EasyEffects Version

6.1.5-1.fc35

### What package are you using?

Fedora

### Distribution

Fedora release 35 (Thirty Five)

### Describe the bug

easyeffects "Settings" window cannot be closed after making changes to any of the settings.
"Settings" window remains visible over every other application.
Window elements are not responding: minimize, resize, close, double-click window header
Only way to reset is to restart easyeffects

### Expected Behavior

easyeffects "Settings" window should close when clicking on another pat of the easyeffects GUI.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
08:51:22 tma7 ~/temp/pipewire/libpipewire-module-raop-sink> killall easyeffects; sudo journalctl --vacuum-time=1seconds; sleep 5; IREPLUMBER_DEBUG=4 PIPEWIRE_DEBUG=5 systemctl --user restart pipewire.service pipewire-pulse.service wireplumber.service; G_MESSAGES_DEBUG=easyeffects GST_DEBUG=4 easyeffects &
Vacuuming done, freed 0B of archived journals from /run/log/journal.
Vacuuming done, freed 0B of archived journals from /var/log/journal.
Vacuuming done, freed 0B of archived journals from /var/log/journal/83f6a0c81ac74621a02f8df1f5024a79.
[1]+  Terminated              G_MESSAGES_DEBUG=easyeffects GST_DEBUG=4 easyeffects
Warning: The unit file, source configuration file or drop-ins of pipewire.service changed on disk. Run 'systemctl --user daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of pipewire-pulse.service changed on disk. Run 'systemctl --user daemon-reload' to reload units.
[1] 24467
08:51:29 tma7 ~/temp/pipewire/libpipewire-module-raop-sink> (process:24467): easyeffects-DEBUG: 20:51:29.928: main: locale directory: /usr/share/locale
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.084: presets_manager: system input presets directory: "/etc/easyeffects/input";
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.084: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input";
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.084: presets_manager: system input presets directory: "/home/alexb/.config/kdedefaults/easyeffects/input";
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.084: presets_manager: system input presets directory: "/usr/share/kde-settings/kde-profile/default/xdg/easyeffects/input";
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.084: presets_manager: system output presets directory: "/etc/easyeffects/output";
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.084: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output";
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.084: presets_manager: system output presets directory: "/home/alexb/.config/kdedefaults/easyeffects/output";
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.084: presets_manager: system output presets directory: "/usr/share/kde-settings/kde-profile/default/xdg/easyeffects/output";
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.085: presets_manager: user presets directory already exists: /home/alexb/.config/easyeffects/
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.085: presets_manager: user presets directory already exists: /home/alexb/.config/easyeffects/input
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.085: presets_manager: user presets directory already exists: /home/alexb/.config/easyeffects/output
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.085: presets_manager: user presets directory already exists: /home/alexb/.config/easyeffects/autoload/input
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.085: presets_manager: user presets directory already exists: /home/alexb/.config/easyeffects/autoload/output

(easyeffects:24467): Gtk-WARNING **: 20:51:30.099: Unknown key gtk-button-images in /home/alexb/.config/gtk-4.0/settings.ini

(easyeffects:24467): Gtk-WARNING **: 20:51:30.100: Unknown key gtk-menu-images in /home/alexb/.config/gtk-4.0/settings.ini

(easyeffects:24467): Gtk-WARNING **: 20:51:30.100: Unknown key gtk-toolbar-style in /home/alexb/.config/gtk-4.0/settings.ini
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.117: application: easyeffects version: 6.1.5
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.118: pipe_manager: compiled with PipeWire: 0.3.40
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.118: pipe_manager: linked to PipeWire: 0.3.41
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.120: pipe_manager: core version: 0.3.41
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.120: pipe_manager: core name: pipewire-0
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.120: pipe_manager: found metadata: settings
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.120: pipe_manager: Audio/Sink 36 192.168.1.109-moode-audio with timestamp 1639536690120964304 was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.121: pipe_manager: found metadata: default
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.121: pipe_manager: found metadata: route-settings
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.121: pipe_manager: Audio/Sink 45 easyeffects_sink with timestamp 1639536690121072732 was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.121: pipe_manager: Audio/Source/Virtual 46 easyeffects_source with timestamp 1639536690121102000 was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.122: pipe_manager: easyeffects_sink node successfully retrieved with id 45 and timestamp 1639536690121072732
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.122: pipe_manager: easyeffects_source node successfully retrieved with id 46 and timestamp 1639536690121102000
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.210: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "node-raop-sink-test-agb" }
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.223: pipe_manager: Audio/Sink 52 alsa_output.pci-0000_00_1f.3.analog-stereo with timestamp 1639536690223721601 was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.223: pipe_manager: Audio/Source 53 alsa_input.pci-0000_00_1f.3.analog-stereo with timestamp 1639536690223773160 was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.229: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "192.168.1.109-moode-audio" }
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.229: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "192.168.1.109-moode-audio" }
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.237: pipe_manager: new metadata property: 0, default.video.source, Spa:String:JSON, { "name": "v4l2_input.pci-0000_00_14.0-usb-0_7_1.0" }
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.245: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_00_1f.3.analog-stereo" }
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.245: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "alsa_input.pci-0000_00_1f.3.analog-stereo" }
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.278: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.312: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.362: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.437: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.454: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.471: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.471: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.498: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.556: pipe_manager: Filter ee_soe_output_level, id = 72, was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.557: soe: output_level successfully connected to PipeWire graph
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.558: pipe_manager: Filter ee_soe_spectrum, id = 77, was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.560: soe: spectrum successfully connected to PipeWire graph
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.561: pipe_manager: Filter ee_soe_equalizer, id = 82, was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.563: soe: equalizer successfully connected to PipeWire graph
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.566: pipe_manager: Filter ee_soe_exciter, id = 89, was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.568: soe: exciter successfully connected to PipeWire graph
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.621: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.655: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.704: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.774: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.791: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.810: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.810: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.839: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.899: pipe_manager: Filter ee_sie_output_level, id = 108, was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.901: sie: output_level successfully connected to PipeWire graph
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.903: pipe_manager: Filter ee_sie_spectrum, id = 113, was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.905: sie: spectrum successfully connected to PipeWire graph
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.906: pipe_manager: Filter ee_sie_equalizer, id = 118, was added
(easyeffects:24467): easyeffects-DEBUG: 20:51:30.908: sie: equalizer successfully connected to PipeWire graph
easyeffects-INFO: 20:51:30.996: application: disabling global bypass
(easyeffects:24467): easyeffects-DEBUG: 20:51:31.037: soe: output_level: new PipeWire blocksize: 2048
(easyeffects:24467): easyeffects-DEBUG: 20:51:31.038: sie: output_level: new PipeWire blocksize: 2048
(easyeffects:24467): easyeffects-DEBUG: 20:51:31.049: application_ui: Icon Theme breeze-dark detected
(easyeffects:24467): easyeffects-DEBUG: 20:51:31.645: application: device alsa_card.pci-0000_00_1f.3 has changed its input route to: analog-input-internal-mic
(easyeffects:24467): easyeffects-DEBUG: 20:51:31.645: application: device alsa_card.pci-0000_00_1f.3 has changed its output route to: analog-output-speaker
(easyeffects:24467): easyeffects-DEBUG: 20:51:31.645: application: output autoloading: the target node name does not match the output device name
(easyeffects:24467): easyeffects-DEBUG: 20:51:31.645: new default output device: 192.168.1.109-moode-audio
(easyeffects:24467): easyeffects-DEBUG: 20:51:31.645: new default output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(easyeffects:24467): easyeffects-DEBUG: 20:51:31.646: new default input device: alsa_input.pci-0000_00_1f.3.analog-stereo
```
</details>

### Additional Information

**Operating System**
```
cat /etc/redhat-release 

Fedora release 35 (Thirty Five)
```

**Desktop Environment:**

```
EasyEffects: 6.1.5

KDE Desktop
plasmashell 5.23.3

rhythmbox 3.4.4

moooeaudio: 7.6.0 2021-11-20
shairport-sync --version: 3.3.8-OpenSSL-Avahi-ALSA-stdout-soxr-metadata-mqtt-dbus-sysconfdir:/etc
Raspberry Pi: Raspbian GNU/Linux 10 (buster)

```

**Kernel**
```
`Kernel: x86_64 Linux 5.15.6-200.fc35.x86_64`
```

**Pipewire version**
```
pipewire --version

Compiled with libpipewire 0.3.41
Linked with libpipewire 0.3.41
```

**Startup steps**
```
killall easyeffects; \
sudo journalctl --vacuum-time=1seconds; \
sleep 5; \
IREPLUMBER_DEBUG=4 PIPEWIRE_DEBUG=5 systemctl --user restart pipewire.service   pipewire-pulse.service  wireplumber.service; \
G_MESSAGES_DEBUG=easyeffects GST_DEBUG=4 easyeffects &

```

**Logging:**
[G_MESSAGES_DEBUG=easyeffects.txt](https://github.com/wwmm/easyeffects/files/7716267/G_MESSAGES_DEBUG.easyeffects.txt)

**Screenshots**

**Showing easyeffects "Settings" dialog not closed, visible over Rhythmbox**

![issue-easyeffects-settings-not-closing](https://user-images.githubusercontent.com/3232097/146115681-0589caad-0f76-4809-a407-5dada92b2bc4.png)

**Showing easyeffects "Settings" dialog not closed, visible over Tilix**

![issue-easyeffects-settings-not-closing-over-tilix](https://user-images.githubusercontent.com/3232097/146115905-07539db3-d046-4fa3-9704-e3cdebc89d02.png)

**Comment by vchernin** [comment] 2021-12-15 03:26
Do you have Nvidia graphics? Are you running on X11? `echo $XDG_SESSION_TYPE`

Fedora KDE runs in Wayland by default unless you're on Nvidia, where it runs in X11. There are a few reports of similar sounding X11 specific bugs.

**Comment by alexbramford** [comment] 2021-12-15 03:30
I'm still running X11 instead of Wayland at present.

```
echo $XDG_SESSION_TYPE
x11
```

**Comment by alexbramford** [comment] 2021-12-15 03:34
Not running Nvidia graphics (AFAICT)

```
lspci -v

00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02) (prog-if 00 [VGA controller])
	Subsystem: Hewlett-Packard Company Device 8339
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at b0000000 (64-bit, non-prefetchable) [size=16M]
	Memory at a0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 5000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
```

**Comment by vchernin** [comment] 2021-12-15 03:57
Sounds like a duplicate of https://github.com/wwmm/easyeffects/issues/1182 if it only occurs on X11.

**Comment by alexbramford** [comment] 2021-12-15 04:46
Repeating the test under Wayland:

- The "Settings" dialog **does not** vanish when one clicks in any other part of the **easyeffects** application
- The "Settings" dialog **does vanish** when one clicks on any **other application**

**Comment by vchernin** [comment] 2021-12-15 05:19
> The "Settings" dialog does not vanish when one clicks in any other part of the easyeffects application

It does vanish for me on GNOME Wayland. So I assume this is some kind of GTK4 or KWin bug, slightly different from #1182 since it's better than on X11.

Note the settings window is being redone in the next EasyEffects update. In 6.2.0 you need to use the close button to close the preferences window, you can't close it by clicking elsewhere in the EasyEffects window. But at least on GNOME Wayland you can click other windows just fine (but the preferences dialog is kept open).

![image](https://user-images.githubusercontent.com/38842733/146127880-653849c2-12e0-4db9-9524-90270f291dca.png)

**Comment by wwmm** [comment] 2021-12-15 14:38
Even if this issue is slightly different it is better to track all these cases in the issues we already have. @alexbramford make a comment on #1182 telling that on kde even on wayland the problem still happens.

**Closed by wwmm** 2021-12-15 14:38 UTC
