### ISSUE TITLE
I don't hear Audio from Pulseeffects if I set my system to sleeping mode and turn it back again

### ISSUE THREAD

**Issue by Toadfield** [wwmm/easyeffects#789] opened 2020-09-20 14:56 UTC
If I set my system to sleeping mode and turn it back,then I don't hear audio from Pulseefects,and I have to close it to hear audio.

**Comment by wwmm** [comment] 2020-09-21 14:37
In the past some people reported problems similar problems. Honestly I have no idea about the cause. The last time I forced my desktop to sleep everything was fine when resuming activities. So it seems to be some kind of hardware dependent problem. And even if that is the case I am not sure if the issue happens in Pulseaudio or GStreamer.

**Comment by Toadfield** [comment] 2020-09-21 15:33
Until that problem can't be solved,I can't use it really,because now I can't hear sound at all if I start it.

**Comment by polygonalenippel** [comment] 2020-10-07 06:51
@Toadfield I have the same issue. It's really annoying.

Stopping all audio sources and doing a combination of the following seems to help

* Restart pulse, usually with `systemctl --user restart pulseaudio.service`. This will mess up some programs which do not expect it.
* Restart PulseEffects (multiple times if necessary)
* Restart the audio source program

But of course this is not how it is supposed to be.

Do you happen to have a portable DAC/amp? i.e. one that 'turns off' when USB power is cut off?

**Comment by Toadfield** [comment] 2020-10-07 13:36
Thanks for the tips,but I won't do that,I will wait until the developer of this project fixes this.
I don't have an DAC/amp,I have my headphones connect via aux directly to my soundboard that's build into my mainboard,and I have my Microphone connected with a phantom power supply to my soundboard.

**Comment by wwmm** [comment] 2020-10-07 13:46
I did another test in my desktop using the Gnome menu function that puts the system to sleep. then I hit one of the keyboards keys to make the system turn on. Audio was resumed automatically.

The test was done with the onboard card. Whatever is the cause of this issue in the affected people computers it is something I am unable to reproduced in my Gnome desktop.

**Comment by sundbp** [comment] 2020-11-27 09:34
I'm also using Gnome desktop (current manjaro with PulseEffects 4.8.2). If my desktop goes to sleep audio is broken on wake up. To get back to working I need to do:
- kill pulseeffects via `pulseeffects -q`
- restart processes that had audio hooked up via pulseeffects

I am using an external USB DAC (Soncoz LA-QXD1).

I'd be willing to provide logs and perform experiments to make it work as I love the product but it's not practical for me to use as it stands. Let me know if and how I can help @wwmm !

**Comment by wwmm** [comment] 2020-11-27 15:06
Hi @sundbp 

Unfortunately I don't know even what to suggest to you. I still cannot reproduce this issue both on my laptop and on my desktop. Somehow after a resume the audio comes back on its own.

So far I only see one possible cause. In some setups Pulseaudio is dying when the machine suspends. This is not a problem for Pulseaudio because it is able to restart itself. But PulseEffects is not able to restart itself after Pulseaudio dies. When this happens we have to restart PulseEffects manually. The question is if the Pulseaudio process is dying in your machine when you suspend.

**Comment by wwmm** [comment] 2020-11-27 15:34
Does Pavucontrol shows PulseEffects devices in the tab `Output Devices` after suspending? If it doesn't Pulseaudio died.

**Comment by sundbp** [comment] 2020-11-27 16:27
Hm. in my explicit testing now I can't actually trigger the issue. Suspend/resume works fine. Same goes for unplugging DAC and plugging it back in.. I thought that may be the culprit (the DAC sometimes drops USB connection on EM noise), but it is not, at least not by just yanking the cable. 

However, it seems to happen every time overnight or if I leave my desk for a few hours and it goes into suspend mode itself.

Not what I expected!

**Comment by wwmm** [comment] 2020-11-27 19:23
>it seems to happen every time overnight

This in a case I can't test I as do not let my desktop or my laptop suspended. But I wonder how time could be a factor here.

**Comment by sundbp** [comment] 2020-11-27 21:05
Likewise - it is indeed very curious. I fully expected an explicitly triggered sleep/resume to behave the same way as overnight timeout based sleep/resume - and if not that then figured pulling the DAC USB cable at random should cover the other eventuality of it being related to some bad state caused by the DAC. Both of those working flawlessly hadn't occurred to me..

I'll leave pavucontrol and pulseffects up overnight today and see what things look like in the morning. Note that the phenomena doesn't require any actual audio to be played - in the typical case my desktop just stands idle for whatever my suspend time is in the evening and goes to sleep, then in the morning when I wake it up it's in a bad state. I'll figure out tomorrow morning if pulseaudio dies - and try to look at the relevant logs at the time of wakeup to see if anything interesting shows up.

**Comment by sundbp** [comment] 2020-11-29 09:20
I can confirm that pulseaudio does restart in my overnight sleep/resume case. I see the START time of the process being when the desktop is resumed. And hence no PulseEffects in the Output Devices, and pulseeffects is "frozen" - the Spectrum in GUI is caught "mid-move" :) 

This is what I see in syslog:
```
Nov 29 09:09:37 monster pulseaudio[271492]: 32 events suppressed
Nov 29 09:09:37 monster pulseaudio[271492]: q overrun, queuing locally
Nov 29 09:09:37 monster pulseaudio[271492]: q overrun, queuing locally
Nov 29 09:09:37 monster pulseaudio[271492]: q overrun, queuing locally
Nov 29 09:09:37 monster pulseaudio[271492]: q overrun, queuing locally
Nov 29 09:09:37 monster pulseaudio[271492]: q overrun, queuing locally
Nov 29 09:09:37 monster pulseaudio[271492]: q overrun, queuing locally
Nov 29 09:09:37 monster pulseaudio[271492]: q overrun, queuing locally
Nov 29 09:09:37 monster pulseaudio[271492]: q overrun, queuing locally
Nov 29 09:09:37 monster pulseaudio[271492]: q overrun, queuing locally
Nov 29 09:09:37 monster pulseaudio[271492]: q overrun, queuing locally
Nov 29 09:09:37 monster pulseaudio[271492]: q overrun, queuing locally
Nov 29 09:09:38 monster pulseaudio[271492]: protocol error, kicking client
Nov 29 09:09:40 monster pulseaudio[271492]: Assertion 'pa_frame_aligned(length, &s->sample_spec)' failed at ../pulseaudio/src/pulsecore/sink.c:1233, function pa_sink_render(). Aborting.
Nov 29 09:09:40 monster audit[271492]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=4 pid=271492 comm="null-sink" exe="/usr/bin/pulseaudio" sig=6 res=1
Nov 29 09:09:42 monster systemd-coredump[314624]: Process 271492 (pulseaudio) of user 1000 dumped core.
Nov 29 09:09:43 monster systemd[3398]: pulseaudio.service: Main process exited, code=killed, status=6/ABRT
Nov 29 09:09:43 monster systemd[3398]: pulseaudio.service: Failed with result 'signal'.
Nov 29 09:09:43 monster systemd[3398]: pulseaudio.service: Scheduled restart job, restart counter is at 9.
Nov 29 09:09:43 monster pulseaudio[314640]: Stale PID file, overwriting.
Nov 29 09:09:43 monster pulseaudio[314640]: Failed to find a working profile.
Nov 29 09:09:43 monster pulseaudio[314640]: Failed to load module "module-alsa-card" (argument: "device_id="0" name="pci-0000_22_00.4" card_name="alsa_card.pci-0000_22_00.4" namereg_fail=false tsched=no fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes avoid_resampling=yes card_properties="module-udev-detect.discovered=1""): initialization failed.
Nov 29 09:09:49 monster pulseaudio[314640]: ALSA woke us up to write new data to the device, but there was actually nothing to write.
Nov 29 09:09:49 monster pulseaudio[314640]: Most likely this is a bug in the ALSA driver 'snd_hda_intel'. Please report this issue to the ALSA developers.
Nov 29 09:09:49 monster pulseaudio[314640]: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
```

I'll see how it looks after a clean reboot and a few other variations like that. I'll see what I can report back.

**Comment by wwmm** [comment] 2020-11-29 14:42
I suggest you report that to the Pulseaudio developers https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues.

I hope that one day I find a way to implement auto restart in PulseEffects when Pulseaudio dies. But the amount of code refactoring for that is way above the one I would like. Maybe when the time to move to GTK4 comes I will have the inspiration for that.

**Comment by sundbp** [comment] 2020-11-30 09:18
@wwmm Looking through more log-files it looks like it's this that is going on for me as well: https://bugs.archlinux.org/task/68126

So not alone in seeing this. Thanks for helping me find the right path to explore!

**Comment by wwmm** [comment] 2021-07-07 17:45
As EasyEffects now uses native PipeWire filters instead of GStreamer it will be better to close this issue and opening a new one if this kind of problem still happens.

**Closed by wwmm** 2021-07-07 17:45 UTC
