### ISSUE TITLE
Subwoofer not working after switching to easyeffects

### ISSUE THREAD

**Issue by susonthapa** [wwmm/easyeffects#1041] opened 2021-07-23 06:42 UTC
The sound is only comming from the speaker but not the subwoofer. If I kill `easyeffects` then the sound comes from the subwoofer as well.
I had this issue previously https://github.com/wwmm/easyeffects/issues/953 and  it was fixed after I set the downmixing in `/etc/pulsewire/client.conf`. 

However after the latest update (switching from **Pulseeffects** to **Easyeffects**), the subwoofer is not working. This time I believe it might be `easyeffects` issue as other apps are working fine. Any help would be appreciated. Also I took the screenshot of the `Pipewire` tab and as you can see `easyeffects` is not using `pipewire-pulse` API. I don't know much about that but it's just something I noticed.

![image](https://user-images.githubusercontent.com/33973551/126745968-f622526a-2513-4d45-83e0-ee725d9b6bac.png)

**Comment by wwmm** [comment] 2021-07-23 14:25
>easyeffects is not using pipewire-pulse API

That is not the problem. EasyEffects uses native PipeWire filters to implement its plugins. There are many advantages but also some difficulties in the new approach. Pipewire's media session does not handle links between filters. So I have to link each channel manually. And as our filters have only 2 channels they are being linked only to the left and right channels of your sound card.

I will open an issue at PipeWire's page about this. I do not think that doing the upmixing on our side is the best solution. THe server is in a much better position to do that right.

**Comment by wwmm** [comment] 2021-07-23 15:15
Link to the issue I have opened https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1447

**Comment by Digitalone1** [comment] 2022-05-30 17:01
Can be closed as a duplicate of #1126.

A possible workaround is reported in https://github.com/wwmm/easyeffects/issues/1126#issuecomment-1141315558

**Closed** 2022-05-30 22:49 UTC
Labels: EasyEffects Bug
