### ISSUE TITLE
easyeffects swapping stereo channels

### ISSUE THREAD

**Issue by ayushhroyy** [wwmm/easyeffects#1302] opened 2021-12-23 10:05 UTC
### EasyEffects Version

6.1.5

### What package are you using?

Arch Official (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Hello, I have been using pulseeffects-legacy from aur for some time and i switched to pipewire yesterday, when i installed and opened easy effects it switched my stereo mapping (I use analog output 4.0 and i had to manually map the stereos as they werent correct by default from /usr/share/alsa-card-profile/mixer/profile-sets/default.conf, iMac 16,2) it turns off my right speaker completely and the gnome settings audio test, it plays the front-left as front-right and rear-left as front-right. and when i click the rear speakers, gnome-control-center crashes. i tried changing the speaker mapping and output channels throught /etc/pulse/daemon.conf but it doesnt work and shows my channels in easyeffects as 2. please inform me if i should look into some logs or is it a minor error I'm doing

![image](https://user-images.githubusercontent.com/77523847/147224250-a27fa579-2b2e-425f-a54e-73d55fb9cdef.png)

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment] 2021-12-23 14:37
Kill EasyEfects `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can see some logs. But I think I will need more details about your custom device configuration. I also use Arch Linux but I use my card on stereo mode and its optical port. Gnome control center audio test plays the front left and the front right where they should be. The "swapped channels" may be related to how PipeWire is exposing your card `4.0 profile`.

**Comment by wwmm** [comment] 2021-12-23 14:43
Have in mind that we have some limitations when it comes to surround profiles. See #1216 and https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1447. In PipeWire we use its native filters instead of GStreamer like it is done in the legacy branch. Native PipeWire filters are better that the old approach but if the user uses a surround profile we are the ones responsible for handling the upmixing from stereo filters to surround output devices. The problem is that doing upmixing is hard and we have no implementation for that now. Try to do some tests in stereo mode to see if that works better.

**Comment by wwmm** [comment] 2021-12-23 14:45
>Try to do some tests in stereo mode to see if that works better.

If the upmixing to surround is indeed the problem you can try to do what PipeWire's developer suggests at https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1447. Load a loopback device that will make the upmixing from stereo to surround and tell EasyEffects to use it as the output device.

**Comment by ayushhroyy** [comment] 2021-12-24 16:28
These are my logs with G_MESSAGES_DEBUG=easyeffects easyeffects


(process:56399): easyeffects-DEBUG: 21:57:26.274: main: locale directory: /usr/share/locale
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.146: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.146: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.146: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.146: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.146: presets_manager: user presets directory already exists: /home/ayush/.config/easyeffects/
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.204: presets_manager: user presets directory already exists: /home/ayush/.config/easyeffects/input
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.204: presets_manager: user presets directory already exists: /home/ayush/.config/easyeffects/output
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.205: presets_manager: user presets directory already exists: /home/ayush/.config/easyeffects/autoload/input
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.205: presets_manager: user presets directory already exists: /home/ayush/.config/easyeffects/autoload/output
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.540: application: easyeffects version: 6.1.5
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.561: pipe_manager: compiled with PipeWire: 0.3.40
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.561: pipe_manager: linked to PipeWire: 0.3.42
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.584: pipe_manager: core version: 0.3.42
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.584: pipe_manager: core name: pipewire-0
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.584: pipe_manager: found metadata: settings
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.588: pipe_manager: found metadata: default
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.588: pipe_manager: found metadata: route-settings
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.595: pipe_manager: Audio/Sink 44 alsa_output.pci-0000_00_03.0.hdmi-stereo-extra2 with timestamp 1640363247588837111 was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.595: pipe_manager: Audio/Sink 45 alsa_output.pci-0000_00_1b.0.analog-surround-40 with timestamp 1640363247595742187 was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.595: pipe_manager: Audio/Source 46 alsa_input.pci-0000_00_1b.0.analog-stereo with timestamp 1640363247595828029 was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.595: pipe_manager: Stream/Output/Audio 149 spotify with timestamp 1640363247595933946 was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.595: pipe_manager: spotify port 167 is connected to alsa_output.pci-0000_00_1b.0.analog-surround-40 port 51
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.595: pipe_manager: spotify port 156 is connected to alsa_output.pci-0000_00_1b.0.analog-surround-40 port 53
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.595: pipe_manager: spotify port 154 is connected to alsa_output.pci-0000_00_1b.0.analog-surround-40 port 55
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.596: pipe_manager: spotify port 155 is connected to alsa_output.pci-0000_00_1b.0.analog-surround-40 port 57
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.596: pipe_manager: Audio/Sink 152 easyeffects_sink with timestamp 1640363247596036691 was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.596: pipe_manager: Audio/Source/Virtual 153 easyeffects_source with timestamp 1640363247596123992 was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.596: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_00_1b.0.analog-surround-40" }
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.596: pipe_manager: new metadata property: 0, default.configured.audio.source, Spa:String:JSON, { "name": "alsa_input.pci-0000_00_1b.0.analog-stereo" }
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.596: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_00_1b.0.analog-surround-40" }
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.596: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "alsa_input.pci-0000_00_1b.0.analog-stereo" }
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.596: pipe_manager: new metadata property: 0, default.video.source, Spa:String:JSON, { "name": "v4l2_input.pci-0000_00_14.0-usb-0_7_1.0" }
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.597: pipe_manager: easyeffects_sink node successfully retrieved with id 152 and timestamp 1640363247596036691
(easyeffects:56399): easyeffects-DEBUG: 21:57:27.597: pipe_manager: easyeffects_source node successfully retrieved with id 153 and timestamp 1640363247596123992

(easyeffects:56399): easyeffects-WARNING **: 21:57:28.855: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness
(easyeffects:56399): easyeffects-DEBUG: 21:57:28.855: soe: http://drobilla.net/plugins/mda/Loudness is not installed

(easyeffects:56399): easyeffects-WARNING **: 21:57:28.855: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:56399): easyeffects-WARNING **: 21:57:28.855: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:56399): easyeffects-WARNING **: 21:57:28.855: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link
(easyeffects:56399): easyeffects-DEBUG: 21:57:28.888: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:28.943: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.011: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.111: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.141: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.165: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.165: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.207: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.371: pipe_manager: Filter ee_soe_output_level, id = 129, was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.373: soe: output_level successfully connected to PipeWire graph
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.374: pipe_manager: Filter ee_soe_spectrum, id = 128, was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.376: soe: spectrum successfully connected to PipeWire graph
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.377: pipe_manager: Filter ee_soe_equalizer, id = 88, was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.379: soe: equalizer successfully connected to PipeWire graph
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.391: pipe_manager: Filter ee_soe_exciter, id = 71, was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.393: soe: exciter successfully connected to PipeWire graph
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.395: pipe_manager: Filter ee_soe_autogain, id = 75, was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.397: soe: autogain successfully connected to PipeWire graph
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.401: pipe_manager: Filter ee_soe_limiter, id = 97, was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.402: soe: limiter successfully connected to PipeWire graph

(easyeffects:56399): easyeffects-WARNING **: 21:57:29.455: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.455: sie: http://drobilla.net/plugins/mda/Loudness is not installed

(easyeffects:56399): easyeffects-WARNING **: 21:57:29.455: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:56399): easyeffects-WARNING **: 21:57:29.455: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:56399): easyeffects-WARNING **: 21:57:29.455: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.474: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.512: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.567: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.644: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.662: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.678: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.678: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.708: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:56399): easyeffects-DEBUG: 21:57:29.768: pipe_manager: Filter ee_sie_output_level, id = 79, was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:30.027: sie: output_level successfully connected to PipeWire graph
(easyeffects:56399): easyeffects-DEBUG: 21:57:30.028: pipe_manager: Filter ee_sie_spectrum, id = 78, was added
(easyeffects:56399): easyeffects-DEBUG: 21:57:30.030: sie: spectrum successfully connected to PipeWire graph

(easyeffects:56399): easyeffects-WARNING **: 21:57:30.030: sie:  link from node 46 to node 78 failed
(easyeffects:56399): easyeffects-DEBUG: 21:57:30.046: soe: limiter latency: 0.010125 s
(easyeffects:56399): easyeffects-DEBUG: 21:57:30.048: soe: output_level: new PipeWire blocksize: 8192
easyeffects-INFO: 21:57:30.083: application: disabling global bypass
(easyeffects:56399): easyeffects-DEBUG: 21:57:30.192: application_ui: Icon Theme Papirus detected
(easyeffects:56399): easyeffects-DEBUG: 21:57:31.828: new default output device: alsa_output.pci-0000_00_1b.0.analog-surround-40
(easyeffects:56399): easyeffects-DEBUG: 21:57:31.828: pipe_manager: new metadata property: 149, target.node, Spa:Id, 152
(easyeffects:56399): easyeffects-DEBUG: 21:57:31.835: pipe_manager: spotify port 155 is connected to easyeffects_sink port 176
(easyeffects:56399): easyeffects-DEBUG: 21:57:31.835: pipe_manager: spotify port 154 is connected to easyeffects_sink port 175
(easyeffects:56399): easyeffects-DEBUG: 21:57:31.856: new default input device: alsa_input.pci-0000_00_1b.0.analog-stereo
(easyeffects:56399): easyeffects-DEBUG: 21:57:31.867: application: device alsa_card.pci-0000_00_03.0 has changed its output route to: hdmi-output-2
(easyeffects:56399): easyeffects-DEBUG: 21:57:31.867: application: output autoloading: the target node name does not match the output device name
(easyeffects:56399): easyeffects-DEBUG: 21:57:31.867: application: device alsa_card.pci-0000_00_1b.0 has changed its input route to: analog-input-internal-mic
(easyeffects:56399): easyeffects-DEBUG: 21:57:31.867: application: device alsa_card.pci-0000_00_1b.0 has changed its output route to: analog-output-speaker
(easyeffects:56399): easyeffects-DEBUG: 21:57:31.867: soe: pipeline latency: 10.125000 ms

(easyeffects:56399): Gsk-CRITICAL **: 21:57:32.317: gsk_radial_gradient_node_new: assertion 'color_stops[i].offset >= color_stops[i - 1].offset' failed

(easyeffects:56399): Gsk-CRITICAL **: 21:57:32.317: gsk_render_node_ref: assertion 'GSK_IS_RENDER_NODE (node)' failed

(easyeffects:56399): Gsk-CRITICAL **: 21:57:32.317: gsk_render_node_unref: assertion 'GSK_IS_RENDER_NODE (node)' failed

**Comment by ayushhroyy** [comment] 2021-12-24 16:34
As you mentioned, i tried the solutions with stereo mode and they didn't work please note that when i turn off the easyeffects knob for an app, it works as expected through the channels (shown below)
![image](https://user-images.githubusercontent.com/77523847/147364873-bcde8cbc-1239-49ef-a5a5-d9774b2c3fa8.png)

**Comment by wwmm** [comment] 2021-12-24 17:21
If the channels are swapped even when the device is in stereo mode instead of `analog-surround-40` PipeWire is giving the us the wrong channel mapping for your device. I do not see much I could do from my side. PipeWire sets tags on the channels lie `FL` and `FR` for front-left and front-right. And we use thins information to know to which device channels we have to link our `FL` and `FR`. On my 2 sound card this works and as this is the first report I receive about swapped channels I imagine this approach is working for many other people too. The only thing I can thing now is that PipeWire may be giving the wrong channel mapping for your device.

The fact that it works when effects are disabled does not mean much because links from audio streams to devices are made in a very different way than links from filters to devices. For filters the process uses lower level functions and the channel tag has to be correct.

**Comment by wwmm** [comment] 2021-12-24 17:24
What is in the file generated by `pw-dump > pw_dump.txt` on your computer?

**Comment by ayushhroyy** [comment] 2021-12-25 05:16
[pw_dump.txt](https://github.com/wwmm/easyeffects/files/7775492/pw_dump.txt)

**Comment by ayushhroyy** [comment] 2021-12-25 05:25
I guess the issue is with easyeffects or my pipewire config, i use the pipewire-pulse aur package as pulseeffects-legacy is working correctly with the effects and it depends on pulseaudio. Since i switched to pipewire, I only had to edit [Mapping analog-surround-40] in /usr/share/alsa-card-profile/mixer/profile-sets/default.conf and I feel like i am missing some steps also, 
this was my original channel-map
[front-left,front-right,rear-left,rear-right]

which i changed to 
[rear-left,front-left,rear-right,front-right]

and it worked properly.

**Comment by ayushhroyy** [comment] 2021-12-25 07:05
is it normal for RL and RR to disappear with the effects on?
![Screenshot from 2021-12-25 12-33-49](https://user-images.githubusercontent.com/77523847/147379516-24fd2ebf-f8e3-4474-a90e-c8fd4aa5c843.png)
![Screenshot from 2021-12-25 12-33-56](https://user-images.githubusercontent.com/77523847/147379517-71e252de-5ffb-43c3-a120-04d45a257dae.png)
![Screenshot from 2021-12-25 12-34-13](https://user-images.githubusercontent.com/77523847/147379519-cb4b3506-b9ea-48a2-9c34-1afe17c553c9.png)

**Comment by ayushhroyy** [comment] 2021-12-25 08:39
[update] I am following this issue as it is similar to mine [https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1417]

**Comment by wwmm** [comment] 2021-12-25 14:16
>rear-left,front-left,rear-right,front-right]

That explains the strange line `13548` in `pw-dump` file `"audio.position": "RL,FL,RR,FR",`. I wonder what happens if you try EasyEffects without the custom mapping. Does it play  `FL` and `FR` where they should be while the other applications play to wrong places? 

>is it normal for RL and RR to disappear with the effects on?

That is the issue about surround upmixing I was talking about before. The only disadvantage of using PipeWire filters is that we do not get surround upmixing for free.As EasyEffects is a stereo application we only have `FL` and `FR` outputs. The loopback device approach explained by PipeWire's author at https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1447 may help you to create a virtual output device that will do that upmixing for EasyEffects.

**Comment by wwmm** [comment] 2021-12-25 14:18
In any case your Helvum output shows that our `output level` filter is linked to the `FL` and `FR` channels of your sound card. So these stereo audio should be going to the right channels. If they aren't it is a PipeWire bug.

**Comment by ayushhroyy** [comment] 2021-12-25 15:01
> That explains the strange line `13548` in `pw-dump` file `"audio.position": "RL,FL,RR,FR",`. I wonder what happens if you try EasyEffects without the custom mapping. 

I have tried that one, it plays through the wrong channels even with the effects off, the custom mapping atleast fixed pipewire playback it's as if pipewire ignores the custom mapping whenever easyeffects is running

**Comment by ayushhroyy** [comment] 2021-12-25 15:03
> In any case your Helvum output shows that our `output level` filter is linked to the `FL` and `FR` channels of your sound card. So these stereo audio should be going to the right channels. If they aren't it is a PipeWire bug.

i guess that's it, i will try to fix the issue with live usbs and will switch back to pulseaudio and pulseeffects-legacy for now, thanks for your help, if i achieve to fix it, I will let you know and quote this thread i'll be closing this issue now, good day.

**Comment by ayushhroyy** [comment] 2022-05-12 21:52
Greetings,
After working on and off for the issue and switching to pulseaudio, It has started being latent now with bluetooth devices and the pipewire issue is still prominent

I was followed [this](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1447) issue and made these changes(line 232-236) to pipewire.conf file in ~/.config/pipewire/pipewire.conf 
[pipewireconf.txt](https://github.com/wwmm/easyeffects/files/8682761/pipewireconf.txt) doesnt seem to make a difference
 The behavious is the same, opening easyeffects and applying effects still switches to 2 outputs either on the right or left.
 
 This is my pwdump fil
[pw_dump.txt](https://github.com/wwmm/easyeffects/files/8682776/pw_dump.txt)
e

**Comment by wwmm** [comment] 2022-05-12 21:58
@ayushhroyy  it will be more interesting to see the output of `pw-dot` when the channels are swapped. Its output file can be viewed with `xdot`

**Comment by ayushhroyy** [comment] 2022-05-14 09:29
[pw with easyeffects off.zip](https://github.com/wwmm/easyeffects/files/8692641/pw.with.easyeffects.off.zip)


[pw with easy effects ON.zip](https://github.com/wwmm/easyeffects/files/8692642/pw.with.easy.effects.ON.zip)



in the second file with easyeffects ON, it is utilitising the FL and FR channels instead of using analog audio 4.0

**Comment by ayushhroyy** [comment] 2022-05-14 12:49
copy of 
[issue 1216](https://github.com/wwmm/easyeffects/issues/1216)
and
[issue 1142](https://github.com/wwmm/easyeffects/issues/1142)

**Comment by wwmm** [comment] 2022-05-14 15:43
>it is utilitising the FL and FR channels instead of using analog audio 4.0

I see. You have a surround device. Unfortunately we have no solution for this case yet. Doing upmixing/downmixing ourselves is a pain. Like Pulseaudio, PipeWire does it automatically when handling streams links. But as its filters have to be linked manually (the media session manager does not support filters) no upmixing/downmixing is done when EasyEffects links its filters to the cound card.

For now I think you will have to load a loopback device configured in a way that the upmixing is done. That is what PipeWire's developer suggested in the past. You can then make EasyEffects use this loopback device as output device.

**Comment by wwmm** [comment] 2022-05-14 15:43
In any case as we already have an issue about the surround situation I think we can close this one.

**Closed by wwmm** 2022-05-14 15:43 UTC

**Comment by ayushhroyy** [comment] 2022-05-15 12:25
The two channels it uses FL and FR, is there any way make those say RR and RL ?

**Comment by wwmm** [comment] 2022-05-15 15:01
>The two channels it uses FL and FR, is there any way make those say RR and RL ?

Not from the EasyEffects side. When a manual link is done we match the filter port with the target device port with the same tag. For example our filters have a `FL` and `FR` tag for each channel port. As EasyEffects code is right now it will link these ports to the ones in the target device that PipeWire marked as `FL` and `FR`. And in the cases where the device has no channel tag the matching is done based on the port index. An example is the `Pro Audio` profile. In this mode the sound card ports do not have channel tags.

I think there is a Pipewire configuration file that allows you to change the card mapping between channel and tags. The problem is that you will brake any app linked directly to it instead of through EasyEffects. They would play to the wrong channels.

I think that writing a PipeWire configuration script that loads a loopback device with the correcting mapping and setting this device as EasyEffects output is the safest workaround you could do. This way anything talking directly to your soundcard would see the correct mapping.
