### ISSUE TITLE
Only FL and FR speakers works with easyeffects.

### ISSUE THREAD

**Issue by MarcinW87** [wwmm/easyeffects#1142] opened 2021-09-10 18:32 UTC
Hi. I have kind of strange issue. My default setup is 5.1. When easyeffects is disabled all speakers works fine, but situation changes dramatically when it is enabled. Only front left and front right is working. 

<a href=https://pastebin.com/e3LMhUhg>pw-dot</a> with easyeffects
<a href=https://pastebin.com/7Nqaaqyc>pw-dot</a> without easyeffects

I'm using pipewire 0.3.34

**Comment by Digitalone1** [comment] 2021-09-10 19:26
This is a known issue, Easyeffects is a stereo application and at the moment the output pipeline is linking only the front ports, so only FR and FL are working. 

There was an attempt to resolve this problem making an upmix, but it's not working anymore for unknown reasons and Pipewire is not giving us an easy solution to resolve this issue.

**Comment by wwmm** [comment] 2021-09-10 19:38
It is like Digitalone1 said. This used to work in the past when we used GStreamer because like Pulseaudio PipeWire does upmixing/downmixing automatically when streams are linked to devices. But for many reasons it is better to do what we do with filters instead of streams. But the downside is that we will have to handle upmixing/downmixing ourselves.

THere is something Pipewire's developer suggested to do that you may try yourself in PipeWire's configuration https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1447#note_1006488. If you create a virtual device with 2 inputs and the outpus matching your surround configuration you can make EasyEffects use it as output. Until I find a way to handle the upmixing/downmixing it is probably the only way.

**Comment by Digitalone1** [comment] 2022-05-30 17:00
Can be closed as a duplicate of #1126 

A possible workaround is reported in https://github.com/wwmm/easyeffects/issues/1126#issuecomment-1141315558

**Closed** 2022-05-30 22:49 UTC
