### ISSUE TITLE
Dark theme not working after switching from pulseeffects to easyeffects, used to work fine before (Arch Linux)

### ISSUE THREAD

**Issue by magicgoose** [wwmm/easyeffects#1007] opened 2021-07-10 20:20 UTC
Importing any impulse (from .wav file) doesn't do anything, and as a result, the effect is unusable.
Some other problems are:
* Dark theme doesn't work (even if I enable checkbox "use dark theme" in easyeffects) -- used to work just fine in pulseeffects
* Presets from pulseeffects are gone

Thankfully, everything goes back to normal if I uninstall easyeffects and install pulseeffects, so that works as a temporary workaround.

Checked on Arch Linux, KDE, kernel is linux-zen, all packages up to date.
Please let me know if I can assist in troubleshooting this in any way.

**Comment by wwmm** [comment] 2021-07-10 20:26
Kill the current instance `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`. I also use Arch Linux and the convolver works here. But I am using the pkgbuild in our sources to build the package I did not try the repository package yet.

**Comment by wwmm** [comment] 2021-07-10 20:30
>Dark theme doesn't work (even if I enable checkbox "use dark theme" in easyeffects) -- used to work just fine in pulseeffects

No problems switching to the dark theme here. Strange...

>Presets from pulseeffects are gone

That was unavoidable. Some changes had to be made and as result the old presets are not compatible. It is still possible to edit the files and make them work but it is not a fun process. It may be easier to just open the preset file in a text editor to view the values and inserting them in the window to create a new one.

Hopefully someone will figure out how to write a script to convert them. I did not have time to try this yet.

**Comment by wwmm** [comment] 2021-07-10 20:31
>Thankfully, everything goes back to normal if I uninstall easyeffects and install pulseeffects, so that works as a temporary workaround.

It should work. EasyEffects saves its settings in a different path.

**Comment by wwmm** [comment] 2021-07-10 20:36
I installed the repository package to see what happened and so far no problems with the convover. Importing a wav worked as well as switching to the dark theme. Could it be that the fact I am on GNOME has some influence on this? Strange...

**Comment by magicgoose** [comment] 2021-07-10 23:00
> That was unavoidable. Some changes had to be made and as result the old presets are not compatible. It is still possible to edit the files and make them work but it is not a fun process. It may be easier to just open the preset file in a text editor to view the values and inserting them in the window manually to create a new one.

Oh then it's alright. I only had a few, easy to re-create.



> Kill the current instance `easyeffects -q`

When I kill it, I get this terminal output (note SIGSEGV at the end), is this concerning?
```
(easyeffects:4401): Gtk-WARNING **: 23:51:40.613: Unknown key gtk-button-images in /home/user/.config/gtk-4.0/settings.ini

(easyeffects:4401): Gtk-WARNING **: 23:51:40.613: Unknown key gtk-menu-images in /home/user/.config/gtk-4.0/settings.ini

(easyeffects:4401): Gtk-WARNING **: 23:51:40.613: Unknown key gtk-toolbar-style in /home/user/.config/gtk-4.0/settings.ini

(easyeffects:4401): easyeffects-WARNING **: 23:51:40.782: lv2_wrapper: Could not find the plugin: urn:zamaudio:ZaMaximX2

(easyeffects:4401): easyeffects-WARNING **: 23:51:40.966: lv2_wrapper: Could not find the plugin: urn:zamaudio:ZaMaximX2
fish: Job 1, 'easyeffects -q' terminated by signal SIGSEGV (Address boundary error)
```

Also, I don't know why, but after another reboot, convolver works (can't reproduce the original issue anymore).

The only problem that still stands is the lack of dark theme, the bulk of the window contents has bright background, despite dark theme being used in KDE, and also despite the dark theme setting in easyeffects.

![Screenshot_20210710_235815](https://user-images.githubusercontent.com/1442206/125178231-c1793b80-e1da-11eb-8359-39c026a9f4dd.png)

I guess it could be because of KDE, yes...

**Comment by wwmm** [comment] 2021-07-10 23:11
>When I kill it, I get this terminal output (note SIGSEGV at the end), is this concerning?

Usually that does not happen. So yes. It is concerning. I wonder if it is somehow related to the message `lv2_wrapper: Could not find the plugin: urn:zamaudio:ZaMaximX2`. The maximizer plugin is optional but I did not do tests yet with some optional dependecies removed from my system. I have all of them installed.

**Comment by wwmm** [comment] 2021-07-10 23:13
BAsed on what I see in the second question in our FAQ dark themes used to need special settings in kde https://github.com/wwmm/easyeffects/wiki/FAQ. Could it be that this old settings only works with gtk3 and not with gtk4? I do not know...

**Comment by wwmm** [comment] 2021-07-10 23:25
I did some tests and we can have segmentation faults when optional dependencies are not installed. I will try to fix this.

**Comment by magicgoose** [comment] 2021-07-10 23:30
Cool, thank you!

> Based on what I see in the second question in our FAQ dark themes used to need special settings in kde https://github.com/wwmm/easyeffects/wiki/FAQ. Could it be that this old setting procedure only works with gtk3 and not with gtk4? I do not know...

I checked and the setting is already there. So apparently it doesn't work with gtk4 (yet).

**Comment by wwmm** [comment] 2021-07-11 00:16
I released now a new version `6.0.2` that fixes crashes caused by not installed optional dependencies. But that dark theme issue is probably something that KDE folks will have to take a look at. So I will close this issue.

**Closed by wwmm** 2021-07-11 00:16 UTC

**Comment by primalmotion** [comment] 2021-07-11 17:19
I'm having the same problem under SwayWM. Dark mode does nothing

**Comment by wwmm** [comment] 2021-07-11 18:49
>I'm having the same problem under SwayWM. Dark mode does nothing

I think it may take some time until people start to support gtk4 themes. What that theme switch does in EasyEffects or PulseEffects is just asking gtk to use a dark theme. All the details are handled by gtk.

**Comment by danger89** [comment] 2021-09-09 20:10
Same problem under Linux Mint (XFCE), using the flatpack version.

**Comment by ardishco-the-great** [comment] 2022-07-20 18:28
Same problem on BSPWM, using the regular arch repository package.

**Comment by ardishco-the-great** [comment] 2022-07-20 18:42
I cannot change it to dark mode or anything or the sort, not even changing gtk colours helped.

I will read the FAQ for answes, though.

**Comment by vchernin** [comment] 2022-07-20 18:43
Have you tried the built in EasyEffects dark mode setting? It is within the EasyEffects preferences window.

**Comment by ardishco-the-great** [comment] 2022-07-20 18:46
I have tried it, but it does not change anything at all.

**Comment by vchernin** [comment] 2022-07-20 18:50
Can you please try to collect some logs while change the EasyEffects setting? See [the wiki](https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs).

**Comment by ardishco-the-great** [comment] 2022-07-20 19:24
nothing appears on the log after changing to dark mode however something did catch my eye in the logs at startup: 

`Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.`

**Comment by wwmm** [comment] 2022-07-20 22:30
>Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

If I remember well what this really means is that somewhere you have a configuration file using a deprecated setting. Maybe `~/.config/gtk-4.0/settings.ini`?

**Comment by ardishco-the-great** [comment] 2022-07-20 22:37
I changed the theme since I last wrote here to try to fix the issue btw, that line in the log is not there anymore but here is what that file looks like

`[Settings]
gtk-application-prefer-dark-theme=1
gtk-cursor-theme-name=Breeze
gtk-cursor-theme-size=24
gtk-decoration-layout=:minimize,maximize,close
gtk-enable-animations=true
gtk-font-name=Noto Sans,  10
gtk-icon-theme-name=pixelitos
gtk-primary-button-warps-slider=false
gtk-theme-name=Adwaita-dark`

**Comment by wwmm** [comment] 2022-07-20 22:45
>here is what that file looks like

Here on GNOME I have only one line in this file and it has nothing to do with the switch between dark themes
```
[Settings]
gtk-hint-font-metrics=1
```

Which `gtk4` and `libadwaita` versions do you have installed?

**Comment by ardishco-the-great** [comment] 2022-07-20 22:49
The latest, I update my system every week and reinstalled both of those while trying to troubleshoot anyway.

Maybe GNOME does all that stuff on its own. GNOME loves using gtk for their apps...but I will try deleting everything and putting only that one in.

**Comment by wwmm** [comment] 2022-07-20 23:11
>Maybe GNOME does all that stuff on its own.

I am not sure. When using gtk on other desktops some amount of customization in `~/.config/gtk-4.0/settings.ini` has always been necessary. But with libadwaita handling the switching between theme variants I am not sure if the other desktops are required to offer some kind of support.

**Comment by ardishco-the-great** [comment] 2022-07-21 20:43
I finally found time to do it and no, deleting stuff in the settings did not help...

**Comment by ardishco-the-great** [comment] 2022-07-28 09:02
I fixed it. I lost my sanity over it for 3 days straight but I fucking did it.

adding this to ~/.config/gtk-4.0/gtk.css applies some colours

```
@define-color accent_color @green_4;
@define-color accent_bg_color @green_4;
@define-color window_bg_color #2f343f;
@define-color window_fg_color white;
@define-color headerbar_bg_color #3B4252;
@define-color headerbar_fg_color white;
@define-color popover_bg_color #434C5E;
@define-color popover_fg_color white;
@define-color view_bg_color #2f343f;
@define-color view_fg_color white;
@define-color card_bg_color rgba(255, 255, 255, 0.08);
@define-color card_fg_color white;
```

and adding
`GTK_THEME=$GTK_THEME_NAME easyeffects `to /etc/profiles (to apply your theme to all your gtk apps) or  ~/.profile (to apply to your user). If I remember correctly adding it to my launch options also fixes it, although I haven't tried it myself yet.

**Comment by vchernin** [comment] 2022-07-28 15:27
That defintely is not how it’s supposed to work, I assume wrong settings somewhere like in `~/.config/gtk-4.0` were what broke it in the first place.

**Comment by sibwaze** [comment] 2023-10-10 17:35
> and adding `GTK_THEME=$GTK_THEME_NAME easyeffects `to /etc/profiles (to apply your theme to all your gtk apps) or ~/.profile (to apply to your user). If I remember correctly adding it to my launch options also fixes it, although I haven't tried it myself yet.

sorry, but that's fucking stupid idea, never do that again
