### ISSUE TITLE
auto loading and/or configuration of presets stopped working for Bluetooth devices

### ISSUE THREAD

**Issue by jtl5770** [wwmm/easyeffects#1784] opened 2022-08-28 14:38 UTC
### EasyEffects Version

6.2.8

### What package are you using?

Fedora

### Distribution

Fedora 36

### Describe the bug

I used to be able to have different presets load automatically depending on the current output device. E.g. I use this to load a "LaptopSpeaker" preset with equalization whenever I use the Laptop Speakers directly, and for any of my Bluetooth headphones I use a "Flat" profile that essentially does nothing.

This used to work like a charm.

But nowadays, whenever I try to save a preset for a Bluetooth device, it looks like this:

![Screenshot from 2022-08-28 16-04-54](https://user-images.githubusercontent.com/24967370/187078975-fe518a78-6d68-40b4-bf8f-497762a65b2f.png)

Note the missing or empty "profile" line - this used to be filled out with the bluetooth profile in use.
Since this information is somehow no longer being recorder, also the autoloading of the profile no longer works.

I tried this with a fully updated Fedora 36 install and even with a new, fresh test user - the result is what you see in the screenshot. Note it works perfectly for non-bluetooth devices, here it is even able to differentiate between using the laptop speaker or plugging a cable headphone in the 3.5mm jack.

![image](https://user-images.githubusercontent.com/24967370/187079267-d96a3969-b480-4048-8781-5f7ab769bcf4.png)

The weird thing is: I have another Laptop with also Fedora 36 on it where it simply works. The profile line is filled in, and auto loading works. But I am completely out of any idea why this could behave differently (as written above I even tried it on a freshly created user to avoid any strange configuration that may still be somewhere around in my home directory.

I don't know how to investigate that further or what the reason could be in the first place.

### Expected Behavior

preset / device connections should be saved with the profile being filled in for bluetooth devices and preset auto loading should work.

**Comment by wwmm** [comment] 2022-08-28 14:57
It is always a bluetooth device... Unbelievable...

>The weird thing is: I have another Laptop with also Fedora 36 on it where it simply works. 

PipeWire is probably setting the device address in a different way in the hardware where it does not work. It is a long story https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2409... In the past PipeWire used unique id numbers for devices and we could rely on them to match nodes, devices and profiles. But since when PipeWire started to reuse id numbers the profile autoloading became a nightmare. We are supposed to match devices based on their names because the name usually has some kind of unique id buried in it. The problem is getting this id so we can parse the name... On pci sound cards PipeWire does one thing. On usb devices it saved somewhere else. And not so long ago I found out that depending on the bluetooth version different things may happen https://github.com/wwmm/easyeffects/issues/1717. It is a complete nightmare...

My guess is that your device address is being saved in a different property we do not know about yet. The output of `pw-dump` should show it.

**Comment by jtl5770** [comment] 2022-08-28 17:46
I attached the result of pw-dump...
[output.txt](https://github.com/wwmm/easyeffects/files/9440178/output.txt)

**Comment by wwmm** [comment] 2022-08-28 19:42
The fix for #1717 should solve your case too. I forgot it did not make into the `6.2.8` release. Are you able to get a package that builds from our master branch? Another option would be to get an Flatpak artifact from a recent commit https://github.com/wwmm/easyeffects/actions/workflows/CI.yaml. The next release is close but there are still some minor changes I would like to do before releasing it.

**Comment by jtl5770** [comment] 2022-08-29 14:15
I think I'll wait for a new flatpak appearing on flathub then (or a new fedora package, whatever comes earlier).
Thanks for helping me in clarifying the situation

**Comment by wwmm** [comment] 2022-10-29 14:20
I think we can close this issue. The bug should be fixed.

**Closed by wwmm** 2022-10-29 14:20 UTC
