### ISSUE TITLE
(UI/UX) Suggestion - Change "Shutdown on Window Closing" to "Run in Background"

### ISSUE THREAD

**Issue by violetmage** [wwmm/easyeffects#2140] opened 2023-02-27 21:10 UTC
In the settings menu, the option is labled "Shutdown on window closing".

However, it may be advantageous to use a more common phrase, like, "Run in background"

I think that while it is not as accurate an explanation for what is happening "under the hood", the phraseology is more commonly understood by non-technical users; additionally, it may be easier to find good translations.

**Comment by wwmm** [comment] 2023-02-27 22:11
>However, it may be advantageous to use a more common phrase, like, "Run in background"

I think we considered this at the time. But the problem is that it is not what the function does. Imagine you started easyeffects without giving it the necessary command line options to make it pretend to be a service. There is not way to force service mode once started. You may abort the service mode. That is what  `Shutdown on window closing` does. But you can only run as a service if EE process is killed and restarted as `easyeffects --gapplication-service`. A `run in background` option would be totally useless.

**Comment by wwmm** [comment] 2023-02-27 22:17
>A run in background option would be totally useless.

By this I meant without somehow managing automatic process restart. What I do not know how to do at this moment.

**Comment by violetmage** [comment] 2023-02-27 23:07
You are right, however I wanted to consider how a non-technical user might interpret these phrases. I think that it is not intuitive to say that, when enabled, "Shutdown on window close" exits the application when the window is closed, and when not enabled allows the application to run without a graphical window.

Having had to explain this to a new linux desktop user, it seems to me that "Run in background" is more readily understood than "run without a window", even if it is not exactly consisted with the way it is implemented here.

**Comment by violetmage** [comment] 2023-02-27 23:12
Maybe we could make `--gapplication-service` the default, and if "run in background" is not checked, tell the service to quit whenever the window is closed.

Then we could keep the current behavior as an option, something like `--no-gapplication-service`

**Comment by wwmm** [comment] 2023-02-28 00:21
> it seems to me that "Run in background" is more readily understood than "run without a window"

I am almost sure that at the time the option was called `Run in background` there were people complaining that the name was misleading and that the app was not running in the background "as intended".

>Maybe we could make --gapplication-service the default, and if "run in background" is not checked, tell the service to quit whenever the window is closed.

As far as I know it is not possible. `--gapplication-service` isn't an EasyEffects option. It is a gtk feature that is parsed deep within gtk. We can't make it default. It has to be given as a command line option.  The only reason why EasyEffects starts in service mode when clicking on its launcher icon is that we provide some dbus files that tell the desktops how to launch with this option as argument.

**Comment by wwmm** [comment] 2023-02-28 00:30
>and if "run in background" is not checked, tell the service to quit whenever the window is closed.

There is another reason why this would not work that way. There isn't really a service. `--gapplication-service` just tells gtk to not let the app to exit when there is no window shown. EasyEffects is an ordinary gui app like any other. THis gtk feature is only allowing its window to be hidden.

Sometimes I think about having a true service. But the amount of work necessary for that is so huge that I always give up...

**Closed** 2023-08-04 21:42 UTC
