### ISSUE TITLE
libgtk-4.so.1: undefined symbol: pango_layout_line_get_length

### ISSUE THREAD

**Issue by AgostinoA** [wwmm/easyeffects#1651] opened 2022-07-15 14:37 UTC
### EasyEffects Version

6.2.6-3

### What package are you using?

Other (specify below)

### Distribution

Debian SID

### Describe the bug

Guys, You have any idea of ​​this call, why gives an error, even if the call results in the library with nm -D

### Debug Log

libgtk-4.so.1: undefined symbol: pango_layout_line_get_length

**Comment by wwmm** [comment] 2022-07-16 14:30
>libgtk-4.so.1: undefined symbol: pango_layout_line_get_length

I never saw this error on my computers. But the first thing I would try would be reinstalling the `pango` package. It is one of the gtk dependencies.

But if that does not solve the problem it may be necessary to rebuild the package. @hosiet you may be interested on this.

**Comment by hosiet** [comment] 2022-07-27 16:28
I cannot reproduce this issue either. Could you provide the detailed procedure on exactly what happened (e.g., error in stderr, and/or crash when opening the app)? Is there any screenshot available? Did you fully upgraded your Debian Sid system (via `sudo apt update ; sudo apt full-upgrade`, and the upgrade finishes successfully)? Can you try the current version easyeeffects/6.2.7-1 and see whether this issue still exist?

**Comment by wwmm** [comment] 2022-10-29 14:21
As fixing this is out of our reach I will close this issue.

**Closed by wwmm** 2022-10-29 14:21 UTC

**Comment by AgostinoA** [comment] 2022-11-12 17:45
I had solved some time ago sorry, just realized now due to 1000's of issues commitments.
I simply did overload on the library (libgtk-4.so.1) downloaded from fedora repository. It is the problem solved.
I was able to create portable easyeffects.
